## *Jeu de données IRVE*
-------------------
# Analyse des relations entre champs (intégrité des données)
------------------------------
## Contexte
- clarification du rôle des modèles de données dans les jeux de données (cf mise à jour récente des [guides data.gouv](https://guides.etalab.gouv.fr/qualite/documenter-les-donnees/))
- intégration d'une propriété "relationship" dans les schémas de données ([issue TableSchema](https://github.com/frictionlessdata/specs/issues/803) en cours de validation)
- création d'outils de contrôle des relations entre champs des jeux de données tabulaires (cf usage ci-dessous)

## Objectifs
- valider sur un cas réel l'utilisation d'un modèle de données en complément d'un schéma de données
- identifier les apports que pourraient avoir les contrôles de validation des relations entre champs

## Résultats
- les principaux résultats sont regroupés sur un [tableau de bord](https://nbviewer.org/github/loco-philippe/Environmental-Sensing/blob/main/python/Validation/irve/Analyse/IRVE_indicateurs.ipynb) 
- la formalisation d'un modèle de données facilite la compréhension des données et des relations entre champs
- l'outil de contrôle permet d'améliorer significativement la qualité des données par l'identification d'incohérences de relations
- l'identification des incohérences permet de trouver des stratégies de réduction des écarts (dans l'exemple ci-dessous, on passe 36% d'écart à 3,8 %)  
- l'analyse des données permet de (re)construire le modèle de données qui minimise les incohérences
- les incohérences détectées sur le jeu de données IRVE restent faibles (inférieures à 5 % des point de charge documentés - voir chapitre 4)

## Suite à donner
- Mettre à jour, valider et publier le modèle de données IRVE
- Définir les contrôles supplémentaires à intégrer pour toutes nouvelles données ainsi que pour le jeu complet
- Mettre en oeuvre les outils de contrôle

## Evolutions possibles 
- Ajouter dans les guides d'Etalab un guide pour les modèles de données 
- Intégrer dans les schémas de données la propriété "relationship" en cours de validation,
- Définir un indicateur qui mesure l'écart (existant / attendu) des relations entre champs

## Sommaire
*(liens actifs sur jupyter Notebook ou Nbviewer)*
- [1 - modèle de données](#1---modèle-de-données)
- [2 - Initialisation](#2---Initialisation)
- [3 - Séparation des pdc itinerance et hors itinerance](#3---Séparation-des-pdc-itinerance-et-hors-itinerance)
- [4 - Bilan initial intégrité](#4---Bilan-initial-intégrité)
- [5 - Séparation doublons pdc - date de maj](#5---Séparation-doublons-pdc---date-de-maj)
- [6 - Séparation doublons station - date de maj](#6---Séparation-doublons-station---date-de-maj)
- [7 - Synthèse](#7---Synthèse)
- [8 - Exemples d'erreurs résiduelles](#8---Exemples-d\'erreurs-résiduelles)

Ce Notebook peut être consulté sur [nbviewer](http://nbviewer.org/github/loco-philippe/Environmental-Sensing/tree/main/python/Validation/irve/Analyse)

données utilisées : https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/    
fichier : "*consolidation-etalab-schema-irve-statique-v-2.2.0-2024xxxx.csv*"

-----------------------
# 1 - modèle de données

Le modèle de données proposé ci-dessous est construit sur la base du schéma de données mis à disposition et du contenu du jeu de données.    
Il est à consolider en fonction de l'expertise des concepteurs et réutilisateurs (voir [guide méthodologique](https://github.com/loco-philippe/Environmental-Sensing/blob/main/property_relationship/FR_methodology.ipynb)).

*Notation:*
- *M : Mandatory - documentation obligatoire*
- *PK : Primary Key - identifiant unique de l'entité*
- *Root : champ fictif associé à une ligne du tableau*

In [2]:
from base64 import b64encode
from IPython.display import Image, display
with open('IRVE_modele.txt', 'r', encoding="utf-8") as f:
    modele = f.read()
display(Image(url="https://mermaid.ink/img/" + b64encode(modele.encode("ascii")).decode("ascii")))

------
# 2 - Initialisation
## initialisation logicielle

In [3]:
from datetime import datetime
import json
from tab_dataset import Cdataset
import pandas as pd
import ntv_pandas as npd
import pathlib

def analyse_integrite(data, schema, affiche=True, indic=True):
    '''analyse les relations du DataFrame 'data' définies dans le schéma 'schema'.
    Le nombre de ligne en erreur par relation (dict) est retourné et optionnellement affiché (paramètre 'affiche=True') . 
    Les lignes en erreur sont optionnellement ajoutées (paramètre 'indic=True') à 'data' sous forme de champs booléens par relation.
    '''
    dic_errors = Cdataset(data).check_relationship(schema)
    dic_count = {name: len(errors) for name, errors in dic_errors.items()}
    if affiche:
        for name, total in dic_count.items():
            print('{:<50} {:>5}'.format(name, total))
    if indic:
        data['ok'] = True
        for name, errors in dic_errors.items():
            data[name] = True
            data.loc[errors, name] = False
            data['ok'] = data['ok'] & data[name] 
    return dic_count

def add_nbre_pdc(data, affiche=True):
    '''ajoute un champ avec le nombre de pdc calculés et le compare au champ 'nbre_pdc'
    Le nombre d'écarts est affiché optionnellement (paramètre 'affiche=True').
    '''
    data['nb_pdc_calc'] = data.groupby('id_station_itinerance')['index'].transform('count')
    nbre_pdc = data['nbre_pdc'].astype('int')
    data['nbre_pdc_ok'] = data['nb_pdc_calc'] == nbre_pdc
    data['calc-nbre'] = data['nb_pdc_calc'] - nbre_pdc
    if affiche:
        ecart_nbre = len(data) - data['nbre_pdc_ok'].sum()
        print('{:<20} {:>5}'.format('nbre_pdc_ko', ecart_nbre))
        print(round(ecart_nbre / len(data) * 100), ' %')

## initialisation des données
- lecture du fichier issu de l'api 190 000 lignes (120 000 fin 2024)

In [4]:
dates = ['2023-03-03', '2023-04-17', '2023-05-02', '2023-05-24', '2023-06-17', '2023-07-04', '2023-07-23', '2023-08-08',
         '2023-09-06', '2023-09-19', '2023-10-04', '2023-10-21', '2023-10-31', '2023-11-23', '2023-12-14', '2023-12-29',
         '2024-01-15', '2024-02-07', '2024-02-28', '2024-03-27', '2024-04-24', '2024-05-19', '2024-06-05', '2024-08-02',
         '2024-10-24', '2024-11-27', '2025-01-03', '2025-10-04', '2025-11-18']
date= dates[-1]
log = {'date_irve': date, 
    'file': 'consolidation-etalab-schema-irve-statique-v-2.3.1-'+date[:4]+date[5:7]+date[8:]+'.csv', # après 2024-02-06
    'chemin': str(pathlib.Path(npd.__file__).parent.parent.parent/"Environmental-Sensing"/"python"/"Validation"/"irve"/"Analyse")
      }
irve = pd.read_csv(log['chemin'] + '/' + log['file'], sep=',', low_memory=False, dtype='object')
log['len_irve'] = len(irve)
print('nombre de lignes : ', log['len_irve'])

nombre de lignes :  190917

## schéma de données
Le schéma de données restreint à la propriété 'relationship' et construit à partir du modèle de données est le suivants :

In [5]:
# complément à inclure dans le schéma de données
schema = {
    'relationships': [
         # relation unicité des pdl
         {"fields": ["id_pdc_itinerance", "index"],                    "link" : "coupled" },   
         # relations inter entités
         {"fields": ["id_station_itinerance", "contact_operateur"],    "link" : "derived" },
         {"fields": ["id_station_itinerance", "nom_enseigne"],         "link" : "derived" },
         {"fields": ["id_station_itinerance", "coordonneesXY"],        "link" : "derived" },
         {"fields": ["id_pdc_itinerance", "id_station_itinerance"],    "link" : "derived" },
         # relations intra entité - station
         {"fields": ["id_station_itinerance", "nom_station"],          "link" : "derived" },
         {"fields": ["id_station_itinerance", "implantation_station"], "link" : "derived" },
         #{"fields": ["id_station_itinerance", "date_maj"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "nbre_pdc"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "condition_acces"],      "link" : "derived" },
         {"fields": ["id_station_itinerance", "horaires"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "station_deux_roues"],   "link" : "derived" },
         # relations intra entité - localisation
         {"fields": ["coordonneesXY", "adresse_station"],              "link" : "derived" }
    ]
}
# liste des champs liés à un controle (relations) et obligatoires (mandatory)
relations = ['index', 'contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 
             'nom_station', 'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 
             'id_pdc_itinerance', 'date_maj', 'last_modified']
mandatory = ['contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 'nom_station',
             'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 'id_pdc_itinerance', 
             'puissance_nominale', 'prise_type_ef', 'prise_type_2', 'prise_type_combo_ccs', 'prise_type_chademo', 
             'prise_type_autre', 'paiement_acte', 'paiement_autre', 'reservation',  'accessibilite_pmr', 'restriction_gabarit', 
             'date_maj', 'last_modified']
controles = ['index - id_pdc_itinerance', 'contact_operateur - id_station_itinerance', 'nom_enseigne - id_station_itinerance',
             'coordonneesXY - id_station_itinerance', 'id_station_itinerance - id_pdc_itinerance',
             'nom_station - id_station_itinerance', 'implantation_station - id_station_itinerance',
             'nbre_pdc - id_station_itinerance', 'condition_acces - id_station_itinerance', 'horaires - id_station_itinerance',
             'station_deux_roues - id_station_itinerance', 'adresse_station - coordonneesXY']

-----------------------
## 3 - Séparation des pdc itinerance et hors itinerance
- 0.2 % des points de recharge sont hors itinerance (1 % en 2024)

In [6]:
# séparation des données
data = irve
data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']] = data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']].astype('string')
#data[['last_modified','date_maj']] = data[['last_modified','date_maj']].astype('datetime64')
data['non_concerne'] = data['id_station_itinerance'].str.contains('oncern') | data['id_pdc_itinerance'].str.contains('oncern')

non_concerne = data[data['non_concerne']].reset_index()['index']
itinerance = data[~data['non_concerne']].reset_index()
itinerance_init = itinerance.loc[:, relations]
log['pdc_hors_itinerance'] = len(non_concerne)
log['pdc_en_itinerance'] = len(itinerance)
print('nombre de pdc hors itinerance : ', log['pdc_hors_itinerance'], 'soit : ', len(non_concerne)/(len(non_concerne)+len(itinerance)))
print('nombre de pdc en itinerance   : ', log['pdc_en_itinerance'])

nombre de pdc hors itinerance :  295 soit :  0.0015451740808833157
nombre de pdc en itinerance   :  190622

In [7]:
# arborescence des champs et nombre de valeurs différentes
print(itinerance_init.npd.analysis().tree())

-1: root-derived (190622)
   0 : index (0 - 190622)
   1 : contact_operateur (190389 - 233)
   2 : nom_enseigne (184432 - 6190)
   3 : coordonneesXY (147909 - 42713)
   4 : adresse_station (149357 - 41265)
   5 : id_station_itineranc (120036 - 70586)
   6 : nom_station (149916 - 40706)
   7 : implantation_station (190617 - 5)
   8 : nbre_pdc (190531 - 91)
   9 : condition_acces (190618 - 4)
   10: horaires (189495 - 1127)
   11: station_deux_roues (190615 - 7)
   12: id_pdc_itinerance (54370 - 136252)
   13: date_maj (189667 - 955)
   14: last_modified (190001 - 621)

-----------------------
## 4 - Bilan initial intégrité
- 59 % des lignes présentent un défaut d'intégrité (moins de 20% en 2024)

In [8]:
# séparation données bonnes (itinerance_ok_1) et données résiduelles (itinerance_1)
res = analyse_integrite(itinerance_init, schema)
itinerance_ok_1 = itinerance_init.loc[itinerance_init.ok, relations].reset_index(drop=True)
itinerance_1 = itinerance_init.loc[~itinerance_init.ok, relations].reset_index(drop=True)
itinerance_init = itinerance_init.loc[:, relations]
log['init_ok'] = len(itinerance_ok_1)
log['init_ko'] = len(itinerance_1)
print("\nnombre d'enregistrements sans erreurs : ", log['init_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['init_ko'])
print("taux d'erreur : ", round(log['init_ko'] / log['pdc_en_itinerance'] * 100), ' %')

index - id_pdc_itinerance                          105815
contact_operateur - id_station_itinerance          20762
nom_enseigne - id_station_itinerance               20895
coordonneesXY - id_station_itinerance              38954
id_station_itinerance - id_pdc_itinerance          60666
nom_station - id_station_itinerance                 7394
implantation_station - id_station_itinerance       16670
nbre_pdc - id_station_itinerance                   11805
condition_acces - id_station_itinerance             6242
horaires - id_station_itinerance                    7374
station_deux_roues - id_station_itinerance         51004
adresse_station - coordonneesXY                    12942

nombre d'enregistrements sans erreurs :  79088
nombre d'enregistrements avec au moins une erreur :  111534
taux d'erreur :  59  %

-----------------------
## 5 - Séparation doublons pdc - date de maj
- 50 % des pdc en erreur sont liées aux doublons de pdc (40 % fin 2024)
- la suppression des doublons permet de réduire de 94% le nombre de lignes erronnées (50 % fin 2024)

In [9]:
# séparation doublons pdc (doublons_pdc) et données résiduelles (itinerance_2)
itinerance_1['doublons_pdc'] = itinerance_1.sort_values(by=['date_maj', 'last_modified']).duplicated('id_pdc_itinerance', keep='last')

doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)['index']
#doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_2 = itinerance_1[~itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_1 = itinerance_1.loc[:, relations]
log['doublons_pdc'] = len(doublons_pdc)
log['sans_doublons_pdc'] = len(itinerance_2)
print('nombre de doublons pdc : ', log['doublons_pdc'], ' soit ', round(log['doublons_pdc']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_pdc'], ' soit ', round(log['sans_doublons_pdc']/log['init_ko'] * 100), ' %')

nombre de doublons pdc :  54370  soit  49  %
nombre de pdc sans doublon   :  57164  soit  51  %

In [10]:
# séparation données bonnes (itinerance_ok_3) et données résiduelles (itinerance_3)
res = analyse_integrite(itinerance_2, schema)
itinerance_ok_3 = itinerance_2.loc[itinerance_2.ok, relations].reset_index(drop=True)
itinerance_3 = itinerance_2.loc[~itinerance_2.ok, relations].reset_index(drop=True)
itinerance_2 = itinerance_2.loc[:, relations]
log['etape3_ok'] = len(itinerance_ok_3)
log['etape3_ko'] = len(itinerance_3)
print("\nnombre d'enregistrements sans erreurs : ", log['etape3_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape3_ko'])

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance           1031
nom_enseigne - id_station_itinerance                1251
coordonneesXY - id_station_itinerance               2068
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 1019
implantation_station - id_station_itinerance        1971
nbre_pdc - id_station_itinerance                    1936
condition_acces - id_station_itinerance              141
horaires - id_station_itinerance                     944
station_deux_roues - id_station_itinerance          1980
adresse_station - coordonneesXY                     3445

nombre d'enregistrements sans erreurs :  50330
nombre d'enregistrements avec au moins une erreur :  6834

-----------------------
## 6 - Séparation doublons station - date de maj
- la suppression des anciens pdc permet de réduire de 13 % supplémentaire le nombre de lignes erronnées
- les dernières erreurs correspondent à des stations associées à 43 opérateurs et sont liées à des causes multiples

In [11]:
# séparation doublons stations (doublons_stat_maj) et données résiduelles (itinerance_4)
itinerance_3['stat_maj'] = itinerance_3.id_station_itinerance + itinerance_3.date_maj
stat_maj_unique = itinerance_3.sort_values(by='stat_maj').drop_duplicates('id_station_itinerance', keep='last')
itinerance_3['last_stat_maj'] = itinerance_3['stat_maj'].isin(stat_maj_unique['stat_maj'])

doublons_stat_maj = itinerance_3[~itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)['index']
itinerance_4 = itinerance_3[itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)
itinerance_3 = itinerance_3.loc[:, relations]
log['doublons_station'] = len(doublons_stat_maj)
log['sans_doublons_station'] = len(itinerance_4)
print('nombre de doublons stations : ', log['doublons_station'], ' soit ', 
      round(log['doublons_station']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_station'])

nombre de doublons stations :  900  soit  1  %
nombre de pdc sans doublon   :  5934

In [12]:
# séparation données bonnes (itinerance_ok_5) et données résiduelles (itinerance_5 / itinerance_5_full)
res = analyse_integrite(itinerance_4, schema)
itinerance_ok_5 = itinerance_4.loc[itinerance_4.ok, relations].reset_index(drop=True)
itinerance_5_full = itinerance_4.loc[~itinerance_4.ok].reset_index(drop=True)
itinerance_5 = itinerance_5_full.loc[:, relations]
#itinerance_4 = itinerance_4.loc[:, relations]
log['etape5_ok'] = len(itinerance_ok_5)
log['etape5_ko'] = len(itinerance_5)
print("\nnombre d'enregistrements sans erreurs : ", log['etape5_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape5_ko'], ' soit ', 
      round(log['etape5_ko']/log['etape3_ko'] * 100), ' %')

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              2
nom_enseigne - id_station_itinerance                  44
coordonneesXY - id_station_itinerance                558
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  814
implantation_station - id_station_itinerance         687
nbre_pdc - id_station_itinerance                     586
condition_acces - id_station_itinerance               41
horaires - id_station_itinerance                      78
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     3021

nombre d'enregistrements sans erreurs :  1171
nombre d'enregistrements avec au moins une erreur :  4763  soit  70  %

In [13]:
# structure des données présentant une erreur et nombre de valeurs
print(itinerance_5.npd.analysis().tree())

-1: root-derived (4763)
   0 : index (0 - 4763)
   1 : contact_operateur (4693 - 70)
   2 : nom_enseigne (4385 - 378)
   3 : coordonneesXY (3806 - 957)
   4 : adresse_station (3251 - 1512)
   5 : id_station_itineranc (2755 - 2008)
      11: station_deux_roues (2003 - 5)
      13: date_maj (1846 - 162)
   6 : nom_station (3318 - 1445)
   7 : implantation_station (4758 - 5)
   8 : nbre_pdc (4730 - 33)
   9 : condition_acces (4761 - 2)
   10: horaires (4664 - 99)
   12: id_pdc_itinerance (0 - 4763)
   14: last_modified (4648 - 115)

In [14]:
# nb maxi d'erreurs
itinerance_4['somme'] = 0
for name in res.keys():
    itinerance_4['somme'] += 1 - itinerance_4[name]
erreurs = max(itinerance_4['somme'])
maxi = itinerance_4[itinerance_4.somme >= erreurs]
print("nombre d'enregistrements avec ", erreurs, " erreurs : ", len(maxi))

nombre d'enregistrements avec  4  erreurs :  35

In [15]:
# principaux opérateurs contributeur de défauts
operateurs = list(itinerance_5.drop_duplicates('contact_operateur')['contact_operateur'])
erreurs_op = [len(itinerance_5.loc[itinerance_5.contact_operateur == operateur]) for operateur in operateurs]
err_op_5, oper_5 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:5]))
err_op_10, oper_10 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:10]))

print(len(err_op_5), ' opérateurs représentent : ', round(sum(err_op_5) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_5, oper_5):
    print(err, op)

5  opérateurs représentent :  59  % des écarts

943 support@alizecharge.fr
930 sav@izivia.com
399 a.buffler@bouygues-es.com
321 fastcharge.exploitation@mobilize.com
200 support@service.emob.eniplenitude.com

In [16]:
print(len(err_op_10), ' opérateurs représentent : ', round(sum(err_op_10) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_10, oper_10):
    print(err, op)

10  opérateurs représentent :  74  % des écarts

943 support@alizecharge.fr
930 sav@izivia.com
399 a.buffler@bouygues-es.com
321 fastcharge.exploitation@mobilize.com
200 support@service.emob.eniplenitude.com
191 supervision-ev.france@totalenergies.com
152 cpo@citeos.com
138 support@dream-energy.fr
122 contact@mobilygreen.fr
110 customerservice@shellrecharge.com

-----------------------
## 7 - Synthèse

### fichiers
Génération des fichiers intégrant les défauts d'intégrité :
- fichier csv des lignes résiduelles à traiter (IRVE_itinerance_residuel)
- fichier csv des données itinerance avec indicateur des données à corriger ou à ignorer (IRVE_itinerance_complet)
- fichier csv des données itinerance valides (IRVE_itinerance_valide)
- fichier csv des doublons (IRVE_itinerance_doublons)

In [17]:
# consolidation des données
itinerance['doublons_stat_maj'] = itinerance['index'].isin(doublons_stat_maj)
itinerance['doublons_pdc'] = itinerance['index'].isin(doublons_pdc)
itinerance['lignes_a_corriger'] = itinerance['index'].isin(itinerance_5['index'])
itinerance['doublons_a_supprimer'] = itinerance['doublons_stat_maj'] | itinerance['doublons_pdc']
itinerance['lignes_ko'] = itinerance['doublons_a_supprimer'] | itinerance['lignes_a_corriger']
print('total des lignes à corriger : ', itinerance['lignes_a_corriger'].sum())
itinerance_doublons = itinerance[itinerance['doublons_a_supprimer']].reset_index(drop=True)
print('total des doublons à supprimer : ', len(itinerance_doublons))
itinerance_ok = itinerance[~itinerance['lignes_ko']].reset_index(drop=True)
print('nombre de pdc avec controles ok : ', len(itinerance_ok))

total des lignes à corriger :  4763
total des doublons à supprimer :  55270
nombre de pdc avec controles ok :  130589

In [18]:
# génération des fichiers
extension = log['date_irve'] +'.csv'
itinerance_5_full.to_csv('IRVE_itinerance_residuel' + extension)
itinerance.to_csv('IRVE_itinerance_complet' + extension)
itinerance_ok.to_csv('IRVE_itinerance_valide' + extension)
itinerance_doublons.to_csv('IRVE_itinerance_doublons' + extension)
log['IRVE_itinerance_residuel' + extension] = len(itinerance_5_full)
log['IRVE_itinerance_complet' + extension] = len(itinerance)
log['IRVE_itinerance_valide' + extension] = len(itinerance_ok)
log['IRVE_itinerance_valide_stat' + extension] = len(itinerance_ok.drop_duplicates('id_station_itinerance', keep='last'))
log['IRVE_itinerance_doublons' + extension] = len(itinerance_doublons)

In [19]:
l_prefix = list(pd.read_csv(log['chemin'] + '/' + 'Operations_Recharge_16-07-2024.csv', sep=';', low_memory=False, dtype='object')['Identifiant'])
l_prefix[0]

'FR073'

In [22]:
for op in oper_5:
    print('IRVE_itinerance_residuel' + '_' + op + '_' + extension)
    itinerance_5_full.loc[itinerance_5_full.contact_operateur == op].to_csv('IRVE_itinerance_residuel' + '_' + op + '_' + extension)

IRVE_itinerance_residuel_support@alizecharge.fr_2025-11-18.csv
IRVE_itinerance_residuel_sav@izivia.com_2025-11-18.csv
IRVE_itinerance_residuel_a.buffler@bouygues-es.com_2025-11-18.csv
IRVE_itinerance_residuel_fastcharge.exploitation@mobilize.com_2025-11-18.csv
IRVE_itinerance_residuel_support@service.emob.eniplenitude.com_2025-11-18.csv

### vérification de l'intégrité

In [23]:
# vérification de l'absence d'erreurs
res = analyse_integrite(itinerance_ok.loc[:, relations], schema, affiche=False)
log['bilan_erreurs'] = sum(res.values())
log['date'] = datetime.now().isoformat()
print('bilan intégrité :')
print('    erreurs : ', log['bilan_erreurs'])

bilan intégrité :
    erreurs :  0

In [24]:
# structure des données bonnes
#print(Cdataset(itinerance_ok.loc[:, mandatory]).tree())
print(itinerance_ok.loc[:, mandatory].npd.analysis().tree())

-1: root-derived (130589)
   4 : id_station_itineranc (73238 - 57351)
      0 : contact_operateur (57135 - 216)
      1 : nom_enseigne (51519 - 5832)
      2 : coordonneesXY (24581 - 32770)
         3 : adresse_station (928 - 31842)
      5 : nom_station (23900 - 33451)
      6 : implantation_station (57346 - 5)
      7 : nbre_pdc (57264 - 87)
      8 : condition_acces (57347 - 4)
      9 : horaires (56354 - 997)
      10: station_deux_roues (57344 - 7)
      22: restriction_gabarit (57209 - 142)
   11: id_pdc_itinerance (0 - 130589)
   12: puissance_nominale (130373 - 216)
   13: prise_type_ef (130581 - 8)
   14: prise_type_2 (130581 - 8)
   15: prise_type_combo_ccs (130581 - 8)
   16: prise_type_chademo (130582 - 7)
   17: prise_type_autre (130582 - 7)
   18: paiement_acte (130581 - 8)
   19: paiement_autre (130580 - 9)
   20: reservation (130582 - 7)
   21: accessibilite_pmr (130583 - 6)
   23: date_maj (129769 - 820)
   24: last_modified (130099 - 490)

### Indicateurs

In [25]:
# génération des indicateurs liés aux règles
regles = ['Pdc non unique', 'Station multi-operateurs', 'Station multi-enseignes', 'Station multi-localisations', 
          'Pdc multi-stations', 'station avec plusieurs noms', 'station multi-implantations', 
          'nombre de pdc par station incoherent', 'station multi-acces', 'station multi-horaires', 
          'acces deux-roues incoherent', 'localisation multi-adresses']
principal = [16, 17, 18, 19, 20]
secondaire = [21, 22, 23, 24, 25, 26, 27]
irve = itinerance_5_full # residuel
total = len(irve)
indic = {}

irve['principal'] = True
for ind in principal:
    irve['principal'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] = True
for ind in secondaire:
    irve['secondaire'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] |= (~irve['principal'] & ~irve['secondaire'])
irve['verif'] = irve['principal'] & irve['secondaire']
indic['principal pdc'] = int(total - irve['principal'].sum())
indic['secondaire pdc'] = int(total - irve['secondaire'].sum())

irve_p = irve[~irve['principal']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
irve_s = irve[~irve['secondaire']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
indic['principal stat'] = len(irve_p)
indic['secondaire stat'] = len(irve_s)

In [26]:
# ajout des principaux opérateurs contributeur de défauts
indic['operateurs'] = list(oper_5)
indic['erreurs_operateurs'] = list(err_op_5)

In [27]:
# ajout de l'indicateur d'écart entre nombre de pdc calculés et saisis
add_nbre_pdc(irve, affiche=True)
indic['nb_pdc_calc-nbre_pdc'] = int(irve['calc-nbre'].sum())

nbre_pdc_ko           1970
41  %

In [28]:
# indicateur d'écart entre nombre de pdc calculés et saisis sur les données sans doublon
itinerance_sans_doublons = itinerance[~itinerance['doublons_a_supprimer']].reset_index(drop=True)
add_nbre_pdc(itinerance_sans_doublons, affiche=True)

nbre_pdc_ko          41280
30  %

In [29]:
len(itinerance_4)

5934

In [30]:
# stockage des indicateurs
log |= indic
log_file = log['chemin'] + '/' + 'logfile.txt'
#with open('logfile.txt', 'a', encoding="utf-8") as f:
with open(log_file, 'a', encoding="utf-8") as f:
    f.write(json.dumps(log) + '\n')

In [31]:
itinerance_5_full.columns[16:28]

Index(['index - id_pdc_itinerance',
       'contact_operateur - id_station_itinerance',
       'nom_enseigne - id_station_itinerance',
       'coordonneesXY - id_station_itinerance',
       'id_station_itinerance - id_pdc_itinerance',
       'nom_station - id_station_itinerance',
       'implantation_station - id_station_itinerance',
       'nbre_pdc - id_station_itinerance',
       'condition_acces - id_station_itinerance',
       'horaires - id_station_itinerance',
       'station_deux_roues - id_station_itinerance',
       'adresse_station - coordonneesXY'],
      dtype='object')

-----------------------
## 8 - Exemples d'erreurs résiduelles 

### Erreurs multiples 
- exemple avec le nombre maximal d'erreurs (4) (35 pdc)
- exemple station 'FRS35P35093001B1' avec 25 pdc : coordonnées XY, nom_station, implantation station, condition accès)

In [32]:
maxi.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
340,22648,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534911,2025-04-23,2025-10-30T21:38:38.412000+00:00
341,22649,support@dream-energy.fr,ENZO HOTEL FROUARD,"[6.150969, 48.742738]",15 rue Ferdinand Braun - Ostwald 67540,FRDREP90106270,OSTWALD - STRASBOURG LA VIGIE,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534912,2025-04-23,2025-10-30T21:38:38.412000+00:00
342,22650,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534913,2025-04-23,2025-10-30T21:38:38.412000+00:00
343,22651,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534921,2025-04-23,2025-10-30T21:38:38.412000+00:00
344,22652,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534922,2025-04-23,2025-10-30T21:38:38.412000+00:00
1550,96015,support@mobilize-ps.fr,BODEMER BAYEUX,"[-0.700226002831211, 49.27084281571326]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,BODEMER Bayeux,Parking privé à usage public,1,Accès libre,24/7,False,FRMBZESMYCQ1,2024-06-03,2025-10-28T15:28:31.144000+00:00
1551,96016,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[-0.700259, 49.270901]","\t16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,\t\tScauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",False,FRMBZESMYQC1,2024-06-03,2025-10-28T15:28:31.144000+00:00
1576,96287,supervision-ev.france@totalenergies.com,MEL,"[3.036602, 50.647916]","Avenue Vauban, 59130 Lambersart",FRMELPRES5911202,LAMBERSART - Avenue Vauban,Voirie,4,Accès libre,24/7,FALSE,FRMELERES591300721,2025-10-09,2025-10-09T16:16:08.920000+00:00
1587,96311,supervision-ev.france@totalenergies.com,MEL,"[3.179727, 50.712572]","11 Rue Léo Lagrange, 59150 Wattrelos",FRMELPRES5911202,WATTRELOS - 11 Rue Léo Lagrange,Voirie,4,Accès libre,24/7,FALSE,FRMELERES591500521,2025-10-09,2025-10-09T16:16:08.920000+00:00
1593,96321,supervision-ev.france@totalenergies.com,MEL,"[3.154113, 50.679396]","Avenue des 2 Moulins, 59170 Croix",FRMELPRES5911202,CROIX - Avenue des 2 Moulins,Voirie,4,Accès libre,24/7,FALSE,FRMELERES591700521,2025-10-09,2025-10-09T16:16:08.920000+00:00
1612,96363,supervision-ev.france@totalenergies.com,MEL,"[3.134137, 50.710864]","230 Rue de Tourcoing, 59420 Mouvaux",FRMELPRES5911202,MOUVAUX - 230 Rue de Tourcoing,Voirie,4,Accès libre,24/7,FALSE,FRMELERES594200421,2025-10-09,2025-10-09T16:16:08.920000+00:00
1619,96376,supervision-ev.france@totalenergies.com,MEL,"[3.08578, 50.665872]","2 - 6 Rue Charles Gounod, 59700 Marcq-en-Barœul",FRMELPRES5911202,MARCQ-EN-BARŒUL - 2 - 6 Rue Charles Gounod,Voirie,4,Accès libre,24/7,FALSE,FRMELERES597000721,2025-10-09,2025-10-09T16:16:08.920000+00:00
3420,141514,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930011,2024-09-18,2025-08-14T09:54:19.251000+00:00
3421,141515,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930012,2024-09-18,2025-08-14T09:54:19.251000+00:00
3422,141520,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,False,FRS35E350930041,2024-09-18,2025-08-14T09:54:19.251000+00:00
3423,141521,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,False,FRS35E3509300410,2024-09-18,2025-08-14T09:54:19.251000+00:00
3424,141522,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,False,FRS35E3509300411,2024-09-18,2025-08-14T09:54:19.251000+00:00
3425,141523,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,False,FRS35E3509300412,2024-09-18,2025-08-14T09:54:19.251000+00:00
3426,141524,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,False,FRS35E3509300413,2024-09-18,2025-08-14T09:54:19.251000+00:00
3427,141525,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,False,FRS35E3509300414,2024-09-18,2025-08-14T09:54:19.251000+00:00
3428,141526,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,False,FRS35E3509300415,2024-09-18,2025-08-14T09:54:19.251000+00:00
3429,141527,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,False,FRS35E3509300416,2024-09-18,2025-08-14T09:54:19.251000+00:00
3430,141528,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,False,FRS35E3509300417,2024-09-18,2025-08-14T09:54:19.251000+00:00
3431,141529,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,False,FRS35E3509300418,2024-09-18,2025-08-14T09:54:19.251000+00:00
3432,141530,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,False,FRS35E3509300419,2024-09-18,2025-08-14T09:54:19.251000+00:00
3433,141531,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,False,FRS35E350930042,2024-09-18,2025-08-14T09:54:19.251000+00:00
3434,141532,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,False,FRS35E3509300420,2024-09-18,2025-08-14T09:54:19.251000+00:00
3435,141533,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,False,FRS35E3509300421,2024-09-18,2025-08-14T09:54:19.251000+00:00
3436,141534,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,False,FRS35E350930043,2024-09-18,2025-08-14T09:54:19.251000+00:00
3437,141535,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,False,FRS35E350930044,2024-09-18,2025-08-14T09:54:19.251000+00:00
3438,141536,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,False,FRS35E350930045,2024-09-18,2025-08-14T09:54:19.251000+00:00
3439,141537,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,False,FRS35E350930046,2024-09-18,2025-08-14T09:54:19.251000+00:00
3440,141538,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,False,FRS35E350930047,2024-09-18,2025-08-14T09:54:19.251000+00:00
3441,141539,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,False,FRS35E350930048,2024-09-18,2025-08-14T09:54:19.251000+00:00
3442,141540,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,False,FRS35E350930049,2024-09-18,2025-08-14T09:54:19.251000+00:00

In [79]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRS35P35093001B1', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3420,141514,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930011,2024-09-18,2025-08-14T09:54:19.251000+00:00
3421,141515,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930012,2024-09-18,2025-08-14T09:54:19.251000+00:00
3422,141520,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,False,FRS35E350930041,2024-09-18,2025-08-14T09:54:19.251000+00:00
3423,141521,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,False,FRS35E3509300410,2024-09-18,2025-08-14T09:54:19.251000+00:00
3424,141522,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,False,FRS35E3509300411,2024-09-18,2025-08-14T09:54:19.251000+00:00
3425,141523,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,False,FRS35E3509300412,2024-09-18,2025-08-14T09:54:19.251000+00:00
3426,141524,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,False,FRS35E3509300413,2024-09-18,2025-08-14T09:54:19.251000+00:00
3427,141525,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,False,FRS35E3509300414,2024-09-18,2025-08-14T09:54:19.251000+00:00
3428,141526,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,False,FRS35E3509300415,2024-09-18,2025-08-14T09:54:19.251000+00:00
3429,141527,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,False,FRS35E3509300416,2024-09-18,2025-08-14T09:54:19.251000+00:00
3430,141528,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,False,FRS35E3509300417,2024-09-18,2025-08-14T09:54:19.251000+00:00
3431,141529,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,False,FRS35E3509300418,2024-09-18,2025-08-14T09:54:19.251000+00:00
3432,141530,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,False,FRS35E3509300419,2024-09-18,2025-08-14T09:54:19.251000+00:00
3433,141531,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,False,FRS35E350930042,2024-09-18,2025-08-14T09:54:19.251000+00:00
3434,141532,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,False,FRS35E3509300420,2024-09-18,2025-08-14T09:54:19.251000+00:00
3435,141533,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,False,FRS35E3509300421,2024-09-18,2025-08-14T09:54:19.251000+00:00
3436,141534,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,False,FRS35E350930043,2024-09-18,2025-08-14T09:54:19.251000+00:00
3437,141535,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,False,FRS35E350930044,2024-09-18,2025-08-14T09:54:19.251000+00:00
3438,141536,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,False,FRS35E350930045,2024-09-18,2025-08-14T09:54:19.251000+00:00
3439,141537,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,False,FRS35E350930046,2024-09-18,2025-08-14T09:54:19.251000+00:00
3440,141538,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,False,FRS35E350930047,2024-09-18,2025-08-14T09:54:19.251000+00:00
3441,141539,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,False,FRS35E350930048,2024-09-18,2025-08-14T09:54:19.251000+00:00
3442,141540,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,False,FRS35E350930049,2024-09-18,2025-08-14T09:54:19.251000+00:00

### Repartition des defauts par operateur
Répartition pour les 10 opérateurs présentant le plus de défauts

In [34]:
print('PdC avec une incohérence : ')
for operateur in oper_10:
    print('\n', sum(itinerance_5.contact_operateur == operateur))
    print('Répartition des incohérences ', operateur, ' :')
    for cont in controles:
        #print(cont, sum((itinerance_4['contact_operateur'] == 'supervision-ev.france@totalenergies.com') & ~(itinerance_4[cont])))
        print('{:<50} {:>5}'.format(cont, sum((itinerance_4['contact_operateur'] == operateur) & ~(itinerance_4[cont]))))

PdC avec une incohérence :

 943
Répartition des incohérences  support@alizecharge.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                  29
coordonneesXY - id_station_itinerance                198
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  385
implantation_station - id_station_itinerance          12
nbre_pdc - id_station_itinerance                     299
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      641

 930
Répartition des incohérences  sav@izivia.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      930

 399
Répartition des incohérences  a.buffler@bouygues-es.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    4
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      395

 321
Répartition des incohérences  fastcharge.exploitation@mobilize.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance         321
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 200
Répartition des incohérences  support@service.emob.eniplenitude.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance         200
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 191
Répartition des incohérences  supervision-ev.france@totalenergies.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                 65
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   65
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                      43
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                      10
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      123

 152
Répartition des incohérences  cpo@citeos.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      152

 138
Répartition des incohérences  support@dream-energy.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   5
coordonneesXY - id_station_itinerance                  4
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    5
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                     136
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                       35

 122
Répartition des incohérences  contact@mobilygreen.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  122
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 110
Répartition des incohérences  customerservice@shellrecharge.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance         110
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

### Defauts operateur ALIZECHARGE
Les défauts identifiés concernent des stations utilisant un même identifiant. Par exemple, la station 'FRADPP91479018' contient 82 points de recharge avec plusieurs adresses et un nombre de points de rechage variable. Cet exemple concerne des stations implantées sur plusieurs étages d'un parking (on devrait donc a minima identifier une station par étage).

In [35]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'support@alizecharge.fr', relations][50:200]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
103,3627,support@alizecharge.fr,ADP Groupe,"[2.362554,48.728787]","2 Rue des Transporteurs, 94390 Paray-Vieille-...",FRADPE91479018,ORY EP - Parking P3 SILO - Niveau 3,Parking public,14,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901824,2025-11-14,2025-11-14T06:56:38.070000+00:00
104,3628,support@alizecharge.fr,ADP Groupe,"[2.362554,48.728787]","2 Rue des Transporteurs, 94390 Paray-Vieille-...",FRADPE91479018,ORY EP - Parking P3 SILO - Niveau 3,Parking public,14,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901825,2025-11-14,2025-11-14T06:56:38.070000+00:00
105,3629,support@alizecharge.fr,ADP Groupe,"[2.362554,48.728787]","2 Rue des Transporteurs, 94390 Paray-Vieille-...",FRADPE91479018,ORY EP - Parking P3 SILO - Niveau 3,Parking public,14,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901826,2025-11-14,2025-11-14T06:56:38.070000+00:00
106,3630,support@alizecharge.fr,ADP Groupe,"[2.362554,48.728787]","2 Rue des Transporteurs, 94390 Paray-Vieille-...",FRADPE91479018,ORY EP - Parking P3 SILO - Niveau 3,Parking public,14,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901827,2025-11-14,2025-11-14T06:56:38.070000+00:00
107,3631,support@alizecharge.fr,ADP Groupe,"[2.362554,48.728787]","2 Rue des Transporteurs, 94390 Paray-Vieille-...",FRADPE91479018,ORY EP - Parking P3 SILO - Niveau 3,Parking public,14,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901828,2025-11-14,2025-11-14T06:56:38.070000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,93029,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.710911497798784,45.18171783112938]","Rue Docteur Hermite, 38000 Grenoble",FRM38E38185025,GRENOBLE - Rue Docteur Hermite,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRM38E381850251,2025-11-14,2025-11-14T06:56:38.070000+00:00
1334,93030,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.710911497798784,45.18171783112938]","Rue Docteur Hermite, 38000 Grenoble",FRM38E38185025,GRENOBLE - Rue Docteur Hermite,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRM38E381850252,2025-11-14,2025-11-14T06:56:38.070000+00:00
1335,93031,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.7332931,45.1718768]","4 Rue Paul Claudel, 38100 GRENOBLE",FRM38E38185025,GRENOBLE - MC2,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRM38E381850253,2025-11-14,2025-11-14T06:56:38.070000+00:00
1336,93032,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.7332931,45.1718768]","4 Rue Paul Claudel, 38100 GRENOBLE",FRM38E38185025,GRENOBLE - MC2,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRM38E381850254,2025-11-14,2025-11-14T06:56:38.070000+00:00
1337,93041,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.704423457201063,45.202193745525555]","Avenue des Martyrs, 38000 Grenoble",FRM38E38185031,GRENOBLE - CEA Cambridge Avenue des Martyrs,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRM38E381850311,2025-11-14,2025-11-14T06:56:38.070000+00:00

In [37]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'support@alizecharge.fr', relations].loc[~itinerance_4['adresse_station - coordonneesXY']][400:700]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3842,148470,support@alizecharge.fr,Ecocharge77,"[2.671611,48.965435]","Rue D'Olympie, 77410 GRESSY",FRS77E77214001,GRESSY - Rue D'Olympie,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E772140011,2025-11-14,2025-11-14T06:56:38.070000+00:00
3843,148472,support@alizecharge.fr,Ecocharge77,"[2.671611,48.965435]","Rue D'Olympie, 77410 GRESSY",FRS77E77214001,GRESSY - Rue D'Olympie,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E772140012,2025-11-14,2025-11-14T06:56:38.070000+00:00
3844,148474,support@alizecharge.fr,Ecocharge77,"[2.957987,48.822292]","Grande Rue, 77580 GUERARD",FRS77E77219001,GUERARD - Grande Rue,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E772190011,2025-11-14,2025-11-14T06:56:38.070000+00:00
3845,148476,support@alizecharge.fr,Ecocharge77,"[2.957987,48.822292]","Grande Rue, 77580 GUERARD",FRS77E77219001,GUERARD - Grande Rue,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E772190012,2025-11-14,2025-11-14T06:56:38.070000+00:00
3846,148482,support@alizecharge.fr,Ecocharge77,"[2.765274,48.448474]","Rue De L'Église, 77850 HERICY",FRS77E77226001,HERICY - Rue De L'Église,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E772260011,2025-11-14,2025-11-14T06:56:38.070000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4078,149172,support@alizecharge.fr,Ecocharge77,"[2.664648,48.571087]","Rue Des Écoles, 77950 VOISENON",FRS77E77528001,VOISENON - Rue Des Écoles,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E775280012,2025-11-14,2025-11-14T06:56:38.070000+00:00
4079,149174,support@alizecharge.fr,Ecocharge77,"[2.969121,48.282539]","Rue Grande, 77940 VOULX",FRS77E77531001,VOULX - Rue Grande,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E775310011,2025-11-14,2025-11-14T06:56:38.070000+00:00
4080,149176,support@alizecharge.fr,Ecocharge77,"[2.969121,48.282539]","Rue Grande, 77940 VOULX",FRS77E77531001,VOULX - Rue Grande,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E775310012,2025-11-14,2025-11-14T06:56:38.070000+00:00
4081,149178,support@alizecharge.fr,Ecocharge77,"[2.773878,48.637527]","Avenue de la Gare, 77390 YEBLES",FRS77E77534001,YEBLES - Avenue de la Gare,Voirie,4,Accès libre,Mo-Su 00:00-23:57,False,FRS77E775340011,2025-11-14,2025-11-14T06:56:38.070000+00:00
4082,149180,support@alizecharge.fr,Ecocharge77,"[2.773878,48.637527]","Avenue de la Gare, 77390 YEBLES",FRS77E77534001,YEBLES - Avenue de la Gare,Voirie,4,Accès libre,Mo-Su 00:00-23:57,False,FRS77E775340012,2025-11-14,2025-11-14T06:56:38.070000+00:00

In [38]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[2.969121,48.282539]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
4079,149174,support@alizecharge.fr,Ecocharge77,"[2.969121,48.282539]","Rue Grande, 77940 VOULX",FRS77E77531001,VOULX - Rue Grande,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E775310011,2025-11-14,2025-11-14T06:56:38.070000+00:00
4080,149176,support@alizecharge.fr,Ecocharge77,"[2.969121,48.282539]","Rue Grande, 77940 VOULX",FRS77E77531001,VOULX - Rue Grande,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E775310012,2025-11-14,2025-11-14T06:56:38.070000+00:00
4197,149326,a.buffler@bouygues-es.com,Ecocharge77,"[2.969121,48.282539]",Rue Grande,FRS77P77531A,Voulx - Grande rue,Voirie,2,Accès libre,24/7,false,FRS77EEC7716711,2025-10-02,2025-10-02T09:07:31.329000+00:00
4198,149327,a.buffler@bouygues-es.com,Ecocharge77,"[2.969121,48.282539]",Rue Grande,FRS77P77531A,Voulx - Grande rue,Voirie,2,Accès libre,24/7,false,FRS77EEC7716712,2025-10-02,2025-10-02T09:07:31.329000+00:00

### Defauts operateur IZIVIA
Les défauts au nombre de 280 sont liés à une incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Izivia en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance, ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur un parking [-0.530598, 47.398424], on trouve 17 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué entre 1 et 3.

In [39]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'sav@izivia.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
48,2601,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16EWIIZ10311,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10311,2025-11-17,2025-11-17T14:41:29.377000+00:00
49,2602,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16EWIIZ10312,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10312,2025-11-17,2025-11-17T14:41:29.377000+00:00
50,2603,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16EWIIZ10321,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10321,2025-11-17,2025-11-17T14:41:29.377000+00:00
51,2604,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16EWIIZ10322,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10322,2025-11-17,2025-11-17T14:41:29.377000+00:00
413,25583,sav@izivia.com,E.LECLERC SAINT MAUR NORD,"[1.669763, 46.820196]","211 Av. de Tours, 36250 Saint-Maur",FRE04POAZS103,E.LECLERC SAINT MAUR NORD,Voirie,1,Accès libre,24/7,False,FRE04EOAZS10321,2025-11-17,2025-11-17T18:06:37.032741+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5700,174261,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial d'Aéroville 95700 Roissy-en-...,FRURWEUNIB1622,Aeroville - Terminal Cook,Voirie,6,Accès libre,24/7,false,FRURWEUNIB1622,2025-11-17,2025-11-17T14:41:31.589000+00:00
5701,174262,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial d'Aéroville 95700 Roissy-en-...,FRURWEUNIB1631,Aeroville - Terminal Cook,Voirie,6,Accès libre,24/7,false,FRURWEUNIB1631,2025-11-17,2025-11-17T14:41:31.589000+00:00
5702,174263,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial d'Aéroville 95700 Roissy-en-...,FRURWEUNIB1632,Aeroville - Terminal Cook,Voirie,6,Accès libre,24/7,false,FRURWEUNIB1632,2025-11-17,2025-11-17T14:41:31.589000+00:00
5703,174264,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial Aéroville 95700 Roissy-en-Fr...,FRURWEUNIB1711,Aeroville - Tokyo,Voirie,2,Accès libre,24/7,false,FRURWEUNIB1711,2025-11-17,2025-11-17T14:41:31.589000+00:00
5704,174265,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial Aéroville 95700 Roissy-en-Fr...,FRURWEUNIB1712,Aeroville - Tokyo,Voirie,2,Accès libre,24/7,false,FRURWEUNIB1712,2025-11-17,2025-11-17T14:41:31.589000+00:00

In [40]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-0.530598, 47.398424]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
478,25768,sav@izivia.com,HYPER U - MURS-ERIGNÉ,"[-0.530598, 47.398424]","26 Rue Valentin des Ormeaux, 49610 Mûrs-Erigné",FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,4,Accès libre,24/7,False,FRE04EOAZS24711,2025-11-17,2025-11-17T18:06:37.032741+00:00
479,25770,sav@izivia.com,HYPER U - MURS-ERIGNÉ,"[-0.530598, 47.398424]","26 Rue Valentin des Ormeaux, 49610 Mûrs-Erigné",FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,4,Accès libre,24/7,False,FRE04EOAZS24712,2025-11-17,2025-11-17T18:06:37.032741+00:00
480,25771,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04EOAZS24721,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,false,FRE04EOAZS24721,2025-11-17,2025-11-17T14:41:36.477000+00:00
481,25773,sav@izivia.com,HYPER U - MURS-ERIGNÉ,"[-0.530598, 47.398424]","26 Rue Valentin des Ormeaux, 49610 Mûrs-Erigné",FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,4,Accès libre,24/7,False,FRE04EOAZS24722,2025-11-17,2025-11-17T18:06:37.032741+00:00
482,25775,sav@izivia.com,HYPER U - MURS-ERIGNÉ,"[-0.530598, 47.398424]","26 Rue Valentin des Ormeaux, 49610 Mûrs-Erigné",FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,4,Accès libre,24/7,False,FRE04EOAZS24723,2025-11-17,2025-11-17T18:06:37.032741+00:00
2409,102186,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372101,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372101,2025-09-30,2025-09-30T08:35:00.909000+00:00
2410,102187,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37211,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37211,2025-09-30,2025-09-30T08:35:00.909000+00:00
2411,102188,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372111,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372111,2025-09-30,2025-09-30T08:35:00.909000+00:00
2412,102189,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372121,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372121,2025-09-30,2025-09-30T08:35:00.909000+00:00
2413,102190,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37221,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37221,2025-09-30,2025-09-30T08:35:00.909000+00:00
2414,102191,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37231,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37231,2025-09-30,2025-09-30T08:35:00.909000+00:00
2415,102192,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37241,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37241,2025-09-30,2025-09-30T08:35:00.909000+00:00
2416,102193,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37251,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37251,2025-09-30,2025-09-30T08:35:00.909000+00:00
2417,102194,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37261,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37261,2025-09-30,2025-09-30T08:35:00.909000+00:00
2418,102195,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37271,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37271,2025-09-30,2025-09-30T08:35:00.909000+00:00
2419,102196,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37281,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37281,2025-09-30,2025-09-30T08:35:00.909000+00:00
2420,102197,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37291,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37291,2025-09-30,2025-09-30T08:35:00.909000+00:00

### Defauts operateur CITEOS
Les défauts (230 points de recharge) sont liés à une incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié principalement à des doublons de pdc entre Citeos et Izivia, ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, à Soulac sur mer, à la coordonnée [-1.122837, 45.515089], on trouve 1 station Citeos Mobive avec 3 points de recharge et également 1 station Izivia Mobive avec 3 points de recharge.

In [41]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'cpo@citeos.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1370,93284,cpo@citeos.com,CPO CITEOS Mobive,"[1.570625, 45.442994]",31 Av. de la Gare 19140 UZERCHE,FRMBIPVAEKR,MOBIVE | Uzerche | Av. de la Gare,Voirie,2,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVAEKR1,2025-11-15,2025-11-17T10:54:25.629000+00:00
1371,93285,cpo@citeos.com,CPO CITEOS Mobive,"[1.570625, 45.442994]",31 Av. de la Gare 19140 UZERCHE,FRMBIPVAEKR,MOBIVE | Uzerche | Av. de la Gare,Voirie,2,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVAEKR2,2025-11-15,2025-11-17T10:54:25.629000+00:00
1372,93296,cpo@citeos.com,CPO CITEOS Mobive,"[1.406172, 45.953075]",Rue de la Gare 87240 AMBAZAC,FRMBIPVAEUM,MOBIVE | Ambazac | Gare,Voirie,2,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVAEUM1,2025-11-16,2025-11-17T10:54:25.629000+00:00
1373,93297,cpo@citeos.com,CPO CITEOS Mobive,"[1.406172, 45.953075]",Rue de la Gare 87240 AMBAZAC,FRMBIPVAEUM,MOBIVE | Ambazac | Gare,Voirie,2,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVAEUM2,2025-11-16,2025-11-17T10:54:25.629000+00:00
1374,93348,cpo@citeos.com,CPO CITEOS Mobive,"[0.028132, 45.894077]",15 Route Des Cagouilles 16140 AIGRE,FRMBIPVAFXA,MOBIVE | Aigre | Villejésus | Place de L'Glise,Voirie,2,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVAFXA1,2025-11-15,2025-11-17T10:54:25.629000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1517,95379,cpo@citeos.com,CPO CITEOS Mobive,"[-0.3265, 43.325056]",1 Rue Thomas Edison 64000 PAU,FRMBIPVCBKF,MOBIVE | Pau | Rue Thomas Edison,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCBKF3,2025-11-17,2025-11-17T10:54:25.629000+00:00
1518,95434,cpo@citeos.com,CPO CITEOS Mobive,"[-1.122837, 45.515089]",3 Rue de L'Hôtel de Ville 33780 SOULAC-SUR-MER,FRMBIPVCCRR,MOBIVE | Soulac-Sur-Mer | Parking de la Mairie,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCRR2,2025-11-16,2025-11-17T10:54:25.629000+00:00
1519,95435,cpo@citeos.com,CPO CITEOS Mobive,"[-1.122837, 45.515089]",3 Rue de L'Hôtel de Ville 33780 SOULAC-SUR-MER,FRMBIPVCCRR,MOBIVE | Soulac-Sur-Mer | Parking de la Mairie,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCRR3,2025-11-16,2025-11-17T10:54:25.629000+00:00
1520,95442,cpo@citeos.com,CPO CITEOS Mobive,"[-0.826756, 44.664279]",3 Avenue ZAC 2000 33380 MIOS,FRMBIPVCCXF,MOBIVE | MIOS - Echangeur Pelouneyres,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCXF2,2025-11-17,2025-11-17T10:54:25.629000+00:00
1521,95443,cpo@citeos.com,CPO CITEOS Mobive,"[-0.826756, 44.664279]",3 Avenue ZAC 2000 33380 MIOS,FRMBIPVCCXF,MOBIVE | MIOS - Echangeur Pelouneyres,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCXF3,2025-11-17,2025-11-17T10:54:25.629000+00:00

In [42]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[1.570625, 45.442994]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1370,93284,cpo@citeos.com,CPO CITEOS Mobive,"[1.570625, 45.442994]",31 Av. de la Gare 19140 UZERCHE,FRMBIPVAEKR,MOBIVE | Uzerche | Av. de la Gare,Voirie,2,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVAEKR1,2025-11-15,2025-11-17T10:54:25.629000+00:00
1371,93285,cpo@citeos.com,CPO CITEOS Mobive,"[1.570625, 45.442994]",31 Av. de la Gare 19140 UZERCHE,FRMBIPVAEKR,MOBIVE | Uzerche | Av. de la Gare,Voirie,2,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVAEKR2,2025-11-15,2025-11-17T10:54:25.629000+00:00
3218,138962,sav@izivia.com,MOBIVE - FDEE 19,"[1.570625, 45.442994]",AVENUE DE LA GARE 19140 UZERCHE,FRS19PMB193111,UZERCHE - AVENUE DE LA GARE,Voirie,2,Accès libre,24/7,false,FRS19EMB193111,2024-05-15,2024-05-15T08:30:02.806000+00:00
3219,138963,sav@izivia.com,MOBIVE - FDEE 19,"[1.570625, 45.442994]",AVENUE DE LA GARE 19140 UZERCHE,FRS19PMB193112,UZERCHE - AVENUE DE LA GARE,Voirie,2,Accès libre,24/7,false,FRS19EMB193112,2024-05-15,2024-05-15T08:30:02.806000+00:00

In [43]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-1.122837, 45.515089]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1518,95434,cpo@citeos.com,CPO CITEOS Mobive,"[-1.122837, 45.515089]",3 Rue de L'Hôtel de Ville 33780 SOULAC-SUR-MER,FRMBIPVCCRR,MOBIVE | Soulac-Sur-Mer | Parking de la Mairie,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCRR2,2025-11-16,2025-11-17T10:54:25.629000+00:00
1519,95435,cpo@citeos.com,CPO CITEOS Mobive,"[-1.122837, 45.515089]",3 Rue de L'Hôtel de Ville 33780 SOULAC-SUR-MER,FRMBIPVCCRR,MOBIVE | Soulac-Sur-Mer | Parking de la Mairie,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCRR3,2025-11-16,2025-11-17T10:54:25.629000+00:00
3375,141054,sav@izivia.com,MOBIVE - SDEEG 33,"[-1.122837, 45.515089]",2 RUE DE LHOTEL DE VILLE 33780 SOULAC-SUR-MER,FRS33PMB3317621,SOULAC-SUR-MER - PARKING DE LA MAIRIE,Voirie,3,Accès libre,24/7,false,FRS33EMB3317621,2024-05-15,2024-05-15T08:30:10.714000+00:00
3376,141055,sav@izivia.com,MOBIVE - SDEEG 33,"[-1.122837, 45.515089]",2 RUE DE LHOTEL DE VILLE 33780 SOULAC-SUR-MER,FRS33PMB3317622,SOULAC-SUR-MER - PARKING DE LA MAIRIE,Voirie,3,Accès libre,24/7,false,FRS33EMB3317622,2024-05-15,2024-05-15T08:30:10.714000+00:00
3377,141056,sav@izivia.com,MOBIVE - SDEEG 33,"[-1.122837, 45.515089]",2 RUE DE LHOTEL DE VILLE 33780 SOULAC-SUR-MER,FRS33PMB3317623,SOULAC-SUR-MER - PARKING DE LA MAIRIE,Voirie,3,Accès libre,24/7,false,FRS33EMB3317623,2024-05-15,2024-05-15T08:30:10.714000+00:00

In [44]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-0.826756, 44.664279]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1520,95442,cpo@citeos.com,CPO CITEOS Mobive,"[-0.826756, 44.664279]",3 Avenue ZAC 2000 33380 MIOS,FRMBIPVCCXF,MOBIVE | MIOS - Echangeur Pelouneyres,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCXF2,2025-11-17,2025-11-17T10:54:25.629000+00:00
1521,95443,cpo@citeos.com,CPO CITEOS Mobive,"[-0.826756, 44.664279]",3 Avenue ZAC 2000 33380 MIOS,FRMBIPVCCXF,MOBIVE | MIOS - Echangeur Pelouneyres,Voirie,3,Accès libre,Mo-Su 00:00-24:00,false,FRMBIEVCCXF3,2025-11-17,2025-11-17T10:54:25.629000+00:00
3355,141029,sav@izivia.com,MOBIVE - SDEEG 33,"[-0.826756, 44.664279]",ECHANGEUR PELOUNEYRES 33380 MIOS,FRS33PMB3315511,MIOS - ECHANGEUR PELOUNEYRES,Voirie,4,Accès libre,24/7,false,FRS33EMB3315511,2024-05-15,2024-05-15T08:30:10.714000+00:00
3356,141030,sav@izivia.com,MOBIVE - SDEEG 33,"[-0.826756, 44.664279]",ECHANGEUR PELOUNEYRES 33380 MIOS,FRS33PMB3315512,MIOS - ECHANGEUR PELOUNEYRES,Voirie,4,Accès libre,24/7,false,FRS33EMB3315512,2024-05-15,2024-05-15T08:30:10.714000+00:00
3357,141031,sav@izivia.com,MOBIVE - SDEEG 33,"[-0.826756, 44.664279]",ECHANGEUR PELOUNEYRES 33380 MIOS,FRS33PMB3315513,MIOS - ECHANGEUR PELOUNEYRES,Voirie,4,Accès libre,24/7,false,FRS33EMB3315513,2024-05-15,2024-05-15T08:30:10.714000+00:00
3358,141032,sav@izivia.com,MOBIVE - SDEEG 33,"[-0.826756, 44.664279]",ECHANGEUR PELOUNEYRES 33380 MIOS,FRS33PMB3315514,MIOS - ECHANGEUR PELOUNEYRES,Voirie,4,Accès libre,24/7,false,FRS33EMB3315514,2024-05-15,2024-05-15T08:30:10.714000+00:00

### Defauts operateur ENIplenitude
Les défauts (200 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Ionity en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance ainsi qu'un ancien pdc de regroupement par station avec un nom d'enseigne différent (IONITY GMBH), ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur l'aire de Mornas [4.732409, 44.194832], on trouve 26 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué de 23 pour chaque station.

In [83]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'support@service.emob.eniplenitude.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
2896,126897,support@service.emob.eniplenitude.com,Aire de Haut Forez Sud,"[3.81239414,45.85502495]","Aire de Haut Forez Sud, 42440 Les Salles",FRPLNEH000249,Aire de Haut Forez Sud,Station dédiée à la recharge rapide,9,Accès réservé,24/7,false,FRPLNEH0002491,2025-11-16,2025-11-17T20:00:32.420000+00:00
2897,126898,support@service.emob.eniplenitude.com,Aire de Haut Forez Sud,"[3.81239414,45.85502495]","Aire de Haut Forez Sud, 42440 Les Salles",FRPLNEH000249,Aire de Haut Forez Sud,Station dédiée à la recharge rapide,9,Accès réservé,24/7,false,FRPLNEH0002492,2025-11-16,2025-11-17T20:00:32.420000+00:00
2898,126899,support@service.emob.eniplenitude.com,Aire de Haut Forez Sud,"[3.81239414,45.85502495]","Aire de Haut Forez Sud, 42440 Les Salles",FRPLNEH000249,Aire de Haut Forez Sud,Voirie,9,Accès réservé,24/7,false,FRPLNEH0002493,2025-11-16,2025-11-17T20:00:32.420000+00:00
2899,126900,support@service.emob.eniplenitude.com,Eni Station - 22 AVENUE DU CLOS MOUZON,"[4.90481800,46.57255600]","22 AVENUE DU CLOS MOUZON, 71700 Tournus",FRPLNEH000531,Eni Station - 22 AVENUE DU CLOS MOUZON,Station dédiée à la recharge rapide,3,Accès réservé,24/7,false,FRPLNEH0005311,2025-11-17,2025-11-17T20:00:32.420000+00:00
2900,126901,support@service.emob.eniplenitude.com,Eni Station - 22 AVENUE DU CLOS MOUZON,"[4.90481800,46.57255600]","22 AVENUE DU CLOS MOUZON, 71700 Tournus",FRPLNEH000531,Eni Station - 22 AVENUE DU CLOS MOUZON,Station dédiée à la recharge rapide,3,Accès réservé,24/7,false,FRPLNEH0005312,2025-11-17,2025-11-17T20:00:32.420000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3091,127186,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,24/7,false,FRPLNEH0021313,2025-11-17,2025-11-17T20:00:32.420000+00:00
3092,127187,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Voirie,32,Accès réservé,24/7,false,FRPLNEH0021314,2025-11-17,2025-11-17T20:00:32.420000+00:00
3093,127281,support@service.emob.eniplenitude.com,Eni Station - 19 BIS AVE BERTHELOT,"[4.55132000,45.49025100]","19 BIS AVE BERTHELOT, 42152 L'HORME",FRPLNEH003099,Eni Station - 19 BIS AVE BERTHELOT,Station dédiée à la recharge rapide,3,Accès réservé,24/7,false,FRPLNEH0030991,2025-11-16,2025-11-17T20:00:32.420000+00:00
3094,127282,support@service.emob.eniplenitude.com,Eni Station - 19 BIS AVE BERTHELOT,"[4.55132000,45.49025100]","19 BIS AVE BERTHELOT, 42152 L'HORME",FRPLNEH003099,Eni Station - 19 BIS AVE BERTHELOT,Voirie,3,Accès réservé,24/7,false,FRPLNEH0030992,2025-11-16,2025-11-17T20:00:32.420000+00:00
3095,127283,support@service.emob.eniplenitude.com,Eni Station - 19 BIS AVE BERTHELOT,"[4.55132000,45.49025100]","19 BIS AVE BERTHELOT, 42152 L'HORME",FRPLNEH003099,Eni Station - 19 BIS AVE BERTHELOT,Station dédiée à la recharge rapide,3,Accès réservé,24/7,false,FRPLNEH0030993,2025-11-16,2025-11-17T20:00:32.420000+00:00

In [84]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRPLNEH002131', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3089,127184,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,24/7,false,FRPLNEH0021311,2025-11-17,2025-11-17T20:00:32.420000+00:00
3090,127185,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,24/7,false,FRPLNEH0021312,2025-11-17,2025-11-17T20:00:32.420000+00:00
3091,127186,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,24/7,false,FRPLNEH0021313,2025-11-17,2025-11-17T20:00:32.420000+00:00
3092,127187,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Voirie,32,Accès réservé,24/7,false,FRPLNEH0021314,2025-11-17,2025-11-17T20:00:32.420000+00:00

### Defauts operateur MOBILIZE
Les défauts (320 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Ionity en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance ainsi qu'un ancien pdc de regroupement par station avec un nom d'enseigne différent (IONITY GMBH), ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur l'aire de Mornas [4.732409, 44.194832], on trouve 26 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué de 23 pour chaque station.

In [81]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'fastcharge.exploitation@mobilize.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1626,96391,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE1,2025-11-17,2025-11-17T20:00:32.420000+00:00
1627,96393,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE2,2025-11-17,2025-11-17T20:00:32.420000+00:00
1628,96395,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE3,2025-11-17,2025-11-17T20:00:32.420000+00:00
1629,96397,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE4,2025-11-17,2025-11-17T20:00:32.420000+00:00
1630,96399,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE5,2025-11-17,2025-11-17T20:00:32.420000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942,97087,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Léonard Cimetière,"[4.73105000,45.97956400]","Rue Léonard Cimetière, 69400 Villefranche-sur-...",FRMFCEVILLEFRANCHE,Mobilize Fast Charge Rue Léonard Cimetière,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEVILLEFRANCHE3,2025-11-17,2025-11-17T20:00:32.420000+00:00
1943,97089,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Léonard Cimetière,"[4.73105000,45.97956400]","Rue Léonard Cimetière, 69400 Villefranche-sur-...",FRMFCEVILLEFRANCHE,Mobilize Fast Charge Rue Léonard Cimetière,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEVILLEFRANCHE4,2025-11-17,2025-11-17T20:00:32.420000+00:00
1944,97091,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Léonard Cimetière,"[4.73105000,45.97956400]","Rue Léonard Cimetière, 69400 Villefranche-sur-...",FRMFCEVILLEFRANCHE,Mobilize Fast Charge Rue Léonard Cimetière,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEVILLEFRANCHE5,2025-11-17,2025-11-17T20:00:32.420000+00:00
1945,97093,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Léonard Cimetière,"[4.73105000,45.97956400]","Rue Léonard Cimetière, 69400 Villefranche-sur-...",FRMFCEVILLEFRANCHE,Mobilize Fast Charge Rue Léonard Cimetière,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEVILLEFRANCHE6,2025-11-17,2025-11-17T20:00:32.420000+00:00
1946,97095,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Léonard Cimetière,"[4.73105000,45.97956400]","Rue Léonard Cimetière, 69400 Villefranche-sur-...",FRMFCEVILLEFRANCHE,Mobilize Fast Charge Rue Léonard Cimetière,Voirie,7,Accès réservé,24/7,false,FRMFCEVILLEFRANCHE7,2025-11-17,2025-11-17T20:00:32.420000+00:00

In [82]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRMFCEALBERTVILLE', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1626,96391,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE1,2025-11-17,2025-11-17T20:00:32.420000+00:00
1627,96393,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE2,2025-11-17,2025-11-17T20:00:32.420000+00:00
1628,96395,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE3,2025-11-17,2025-11-17T20:00:32.420000+00:00
1629,96397,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE4,2025-11-17,2025-11-17T20:00:32.420000+00:00
1630,96399,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE5,2025-11-17,2025-11-17T20:00:32.420000+00:00
1631,96401,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE6,2025-11-17,2025-11-17T20:00:32.420000+00:00
1632,96403,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Voirie,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE7,2025-11-17,2025-11-17T20:00:32.420000+00:00

### Defauts operateur BOUYGUES
Les défauts (286 points de recharge) sont liés à une incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes).

Les défauts sont majoritairement associés à l'enseigne Ecocharge77 pour laquelle on trouve des stations en doublon entre Bouygues et AlizeCharge. Ce défaut semble être lié à un transfert de bornes d'un opérateur à un autre sans que les anciennes stations aient été supprimées.

Par exemple, pour la coordonnées [3.438183,48.694653], on trouve quatre points de recharge associés à deux stations (une est opérée par Bouygues et l'autre par AlizeCharge).

In [49]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'a.buffler@bouygues-es.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
4083,149182,a.buffler@bouygues-es.com,Ecocharge77,"[3.438183,48.694653]",route de Brangis,FRS77P77301A,Montceaux-les-Provins,Voirie,2,Accès libre,24/7,false,FRS77EEC7710011,2025-10-02,2025-10-02T09:07:31.329000+00:00
4084,149183,a.buffler@bouygues-es.com,Ecocharge77,"[3.438183,48.694653]",route de Brangis,FRS77P77301A,Montceaux-les-Provins,Voirie,2,Accès libre,24/7,false,FRS77EEC7710012,2025-10-02,2025-10-02T09:07:31.329000+00:00
4085,149184,a.buffler@bouygues-es.com,Ecocharge77,"[2.938246,48.675091]",Avenue du général Leclerc,FRS77P77031A,Bernay-Vilbert - Salle des fêtes,Voirie,2,Accès libre,24/7,false,FRS77EEC771011,2025-10-02,2025-10-02T09:07:31.329000+00:00
4086,149187,a.buffler@bouygues-es.com,Ecocharge77,"[2.938246,48.675091]",Avenue du général Leclerc,FRS77P77031A,Bernay-Vilbert - Salle des fêtes,Voirie,2,Accès libre,24/7,false,FRS77EEC771012,2025-10-02,2025-10-02T09:07:31.329000+00:00
4087,149188,a.buffler@bouygues-es.com,Ecocharge77,"[3.427434,48.851772]",rue Brulée,FRS77P77303A,Montdauphin,Voirie,2,Accès libre,24/7,false,FRS77EEC7710211,2025-10-02,2025-10-02T09:07:31.329000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4477,149760,a.buffler@bouygues-es.com,Ecocharge77,"[2.859685,48.926731]",Place Jean Jaurès,FRS77P77276A,Mareuil-les-Meaux,Voirie,2,Accès libre,24/7,false,FRS77EEC779412,2025-10-02,2025-10-02T09:07:31.329000+00:00
4478,149767,a.buffler@bouygues-es.com,Ecocharge77,"[2.850102,48.349255]",Rue Grande,FRS77P77299A,Morêt-Loing-et-Orvanne - Montarlot,Voirie,2,Accès libre,24/7,false,FRS77EEC779811,2025-10-02,2025-10-02T09:07:31.329000+00:00
4479,149768,a.buffler@bouygues-es.com,Ecocharge77,"[2.850102,48.349255]",Rue Grande,FRS77P77299A,Morêt-Loing-et-Orvanne - Montarlot,Voirie,2,Accès libre,24/7,false,FRS77EEC779812,2025-10-02,2025-10-02T09:07:31.329000+00:00
4480,149769,a.buffler@bouygues-es.com,Ecocharge77,"[2.985625,48.941795]",place de la mairie,FRS77P77300A,Montceaux-les-Meaux,Voirie,2,Accès libre,24/7,false,FRS77EEC779911,2025-10-02,2025-10-02T09:07:31.329000+00:00
4481,149770,a.buffler@bouygues-es.com,Ecocharge77,"[2.985625,48.941795]",place de la mairie,FRS77P77300A,Montceaux-les-Meaux,Voirie,2,Accès libre,24/7,false,FRS77EEC779912,2025-10-02,2025-10-02T09:07:31.329000+00:00

In [50]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[2.850102,48.349255]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3924,148736,support@alizecharge.fr,Ecocharge77,"[2.850102,48.349255]","Rue Grande, 77250 MORET-LOING-ORVANNE",FRS77E77316001,MORET-LOING-ORVANNE - Rue Grande,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E773160011,2025-11-14,2025-11-14T06:56:38.070000+00:00
3925,148738,support@alizecharge.fr,Ecocharge77,"[2.850102,48.349255]","Rue Grande, 77250 MORET-LOING-ORVANNE",FRS77E77316001,MORET-LOING-ORVANNE - Rue Grande,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E773160012,2025-11-14,2025-11-14T06:56:38.070000+00:00
4478,149767,a.buffler@bouygues-es.com,Ecocharge77,"[2.850102,48.349255]",Rue Grande,FRS77P77299A,Morêt-Loing-et-Orvanne - Montarlot,Voirie,2,Accès libre,24/7,false,FRS77EEC779811,2025-10-02,2025-10-02T09:07:31.329000+00:00
4479,149768,a.buffler@bouygues-es.com,Ecocharge77,"[2.850102,48.349255]",Rue Grande,FRS77P77299A,Morêt-Loing-et-Orvanne - Montarlot,Voirie,2,Accès libre,24/7,false,FRS77EEC779812,2025-10-02,2025-10-02T09:07:31.329000+00:00

In [51]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[3.438183,48.694653]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3907,148694,support@alizecharge.fr,Ecocharge77,"[3.438183,48.694653]","Route De Brangis, 77151 MONTCEAUX-LES-PROVINS",FRS77E77301001,MONTCEAUX-LES-PROVINS - Route De Brangis,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E773010011,2025-11-14,2025-11-14T06:56:38.070000+00:00
3908,148696,support@alizecharge.fr,Ecocharge77,"[3.438183,48.694653]","Route De Brangis, 77151 MONTCEAUX-LES-PROVINS",FRS77E77301001,MONTCEAUX-LES-PROVINS - Route De Brangis,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRS77E773010012,2025-11-14,2025-11-14T06:56:38.070000+00:00
4083,149182,a.buffler@bouygues-es.com,Ecocharge77,"[3.438183,48.694653]",route de Brangis,FRS77P77301A,Montceaux-les-Provins,Voirie,2,Accès libre,24/7,false,FRS77EEC7710011,2025-10-02,2025-10-02T09:07:31.329000+00:00
4084,149183,a.buffler@bouygues-es.com,Ecocharge77,"[3.438183,48.694653]",route de Brangis,FRS77P77301A,Montceaux-les-Provins,Voirie,2,Accès libre,24/7,false,FRS77EEC7710012,2025-10-02,2025-10-02T09:07:31.329000+00:00

### Cohérence implantation_station - id_station
- 107 pdc sont liés à une erreur de choix d'implantation (couplé à d'autres erreurs)

In [52]:
itinerance_4.loc[~itinerance_4['implantation_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
79,3595,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","Rue de Berlin, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Voirie,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE914790151,2025-11-14,2025-11-14T06:56:38.070000+00:00
80,3596,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","Rue de Berlin, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Parking public,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901510,2025-11-14,2025-11-14T06:56:38.070000+00:00
81,3597,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","Rue de Berlin, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Parking public,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901511,2025-11-14,2025-11-14T06:56:38.070000+00:00
82,3598,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","Rue de Berlin, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Parking public,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901512,2025-11-14,2025-11-14T06:56:38.070000+00:00
83,3599,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","Rue de Berlin, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Voirie,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE914790152,2025-11-14,2025-11-14T06:56:38.070000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4793,157094,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE94,Shell Fenioux Est,Voirie,8,Accès réservé,24/7,false,FRSHEE944,2025-11-17,2025-11-17T20:00:32.420000+00:00
4794,157096,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Station dédiée à la recharge rapide,8,Accès réservé,24/7,false,FRSHEE951,2025-11-17,2025-11-17T20:00:32.420000+00:00
4795,157098,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Station dédiée à la recharge rapide,8,Accès réservé,24/7,false,FRSHEE952,2025-11-17,2025-11-17T20:00:32.420000+00:00
4796,157100,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Station dédiée à la recharge rapide,8,Accès réservé,24/7,false,FRSHEE953,2025-11-17,2025-11-17T20:00:32.420000+00:00
4797,157102,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Voirie,8,Accès réservé,24/7,false,FRSHEE954,2025-11-17,2025-11-17T20:00:32.420000+00:00

### Cohérence nom_station - id_station
- 210 pdc sont associés à une station avec un nom non cohérent

In [53]:
itinerance_4.loc[~itinerance_4['nom_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
18,411,contact@nexteneo.com,Ville d'Annecy,"[6.12983, 45.902285]",[Rue Guillaume Fichet][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Parking de Bonlieu,Parking public,11,Accès réservé,24/7,FALSE,FR0NXEVSE8BD3L,2024-12-23,2025-09-30T07:48:19.920000+00:00
19,423,contact@nexteneo.com,Ville d'Annecy,"[6.12983, 45.902285]",[Rue Guillaume Fichet][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Parking de Bonlieu,Parking public,11,Accès réservé,24/7,FALSE,FR0NXEVSE99XBN,2024-12-23,2025-09-30T07:48:19.920000+00:00
20,453,contact@nexteneo.com,Ville d'Annecy,"[6.128716, 45.9]",[1 Esplanade de l'hôtel de ville][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Hôtel de ville,Parking public,6,Accès réservé,24/7,FALSE,FR0NXEVSEBYTEK,2024-12-23,2025-09-30T07:48:19.920000+00:00
21,462,contact@nexteneo.com,Ville d'Annecy,"[6.128716, 45.9]",[1 Esplanade de l'hôtel de ville][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Hôtel de ville,Parking public,6,Accès réservé,24/7,FALSE,FR0NXEVSECTDM6,2024-12-23,2025-09-30T07:48:19.920000+00:00
22,464,contact@nexteneo.com,Ville d'Annecy,"[6.12983, 45.902285]",[Rue Guillaume Fichet][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Parking de Bonlieu,Parking public,11,Accès réservé,24/7,FALSE,FR0NXEVSED4T64,2024-12-23,2025-09-30T07:48:19.920000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5844,188877,support@alizecharge.fr,Seymaborne,"[1.877203,48.5760925]","Rue André Thome, 78120 SONCHAMP",FRY03E78601001,SONCHAMP - MAIRIE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786010014,2025-11-14,2025-11-14T06:56:38.070000+00:00
5845,188878,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150011,2025-11-14,2025-11-14T06:56:38.070000+00:00
5846,188879,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150012,2025-11-14,2025-11-14T06:56:38.070000+00:00
5847,188880,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150013,2025-11-14,2025-11-14T06:56:38.070000+00:00
5848,188881,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150014,2025-11-14,2025-11-14T06:56:38.070000+00:00

### Coherence adresse - coordonnees
- 2337 pdc ont une adresse non cohérente avec les coordonnées géographiques

In [54]:
itinerance_4.loc[~itinerance_4['adresse_station - coordonneesXY'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
48,2601,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16EWIIZ10311,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10311,2025-11-17,2025-11-17T14:41:29.377000+00:00
49,2602,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16EWIIZ10312,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10312,2025-11-17,2025-11-17T14:41:29.377000+00:00
50,2603,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16EWIIZ10321,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10321,2025-11-17,2025-11-17T14:41:29.377000+00:00
51,2604,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16EWIIZ10322,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10322,2025-11-17,2025-11-17T14:41:29.377000+00:00
91,3615,support@alizecharge.fr,ADP Groupe,"[2.362554,48.728787]","2 Rue des Transporteurs, 94390 Paray-Vieille-P...",FRADPE91479018,ORY EP - Parking P3 SILO - Niveau 2,Parking public,10,Accès libre,Mo-Su 00:00-23:57,False,FRADPE914790181,2025-11-14,2025-11-14T06:56:38.070000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5929,189731,advenir@zeborne.com,GARAGE NELLO CHELLI - DIJON,"[5.065799, 47.354481]",23 RUE DES ARDENNES 21000 Dijon,FRZTLE22AC55087,Toyota - Dijon - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 07:45-12:00,Mo-Fr 13:45-19:00,Sat 09:00-...",false,FRZTLE22AC55087,2021-02-19,2024-12-06T06:45:00.153000+00:00
5930,189742,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.419000+00:00
5931,189743,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.419000+00:00
5932,189744,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.419000+00:00
5933,189745,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.419000+00:00

In [55]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[5.2592028, 46.1746523]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5930,189742,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.419000+00:00
5931,189743,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.419000+00:00
5932,189744,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.419000+00:00
5933,189745,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.419000+00:00

In [56]:
itinerance_4.loc[itinerance_4.adresse_station == 'RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5930,189742,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.419000+00:00
5932,189744,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.419000+00:00

In [57]:
itinerance_4.loc[itinerance_4.adresse_station == ' RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5931,189743,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.419000+00:00
5933,189745,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.419000+00:00

### Cohérence station - coordonnées
- 218 pdc sont associés à des stations avec plusieurs coordonnées (majorité AlizeCharge)

In [58]:
itinerance_4.loc[~itinerance_4['coordonneesXY - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
0,330,acelec@acelec-france.com,Camaïeu France,"[3.207306,50.684918]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E0HKH51125,2022-07-21,2024-12-06T06:46:31.269000+00:00
1,331,acelec@acelec-france.com,Camaïeu France,"[3.207246,50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E8OV45243,2022-07-21,2024-12-06T06:46:31.269000+00:00
2,332,acelec@acelec-france.com,Camaïeu France,"[3.207124,50.684984]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EBEQA5957,2022-07-21,2024-12-06T06:46:31.269000+00:00
3,333,acelec@acelec-france.com,Camaïeu France,"[3.20737,50.684898]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ECC1C5530,2022-07-21,2024-12-06T06:46:31.269000+00:00
4,334,acelec@acelec-france.com,HOTEL KYRIAD PARIS BEZONS,"[2.212336,48.931356]",80 Av. Gabriel Péri 95870 BEZONS,FR073PKYRIADBEZONS,HOTEL KYRIAD PARIS BEZONS,Parking privé à usage public,1,Accès libre,Mo-Fr 08:00-19:01,false,FR073EJJYD51230,2022-07-21,2024-12-06T06:46:31.269000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5844,188877,support@alizecharge.fr,Seymaborne,"[1.877203,48.5760925]","Rue André Thome, 78120 SONCHAMP",FRY03E78601001,SONCHAMP - MAIRIE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786010014,2025-11-14,2025-11-14T06:56:38.070000+00:00
5845,188878,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150011,2025-11-14,2025-11-14T06:56:38.070000+00:00
5846,188879,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150012,2025-11-14,2025-11-14T06:56:38.070000+00:00
5847,188880,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150013,2025-11-14,2025-11-14T06:56:38.070000+00:00
5848,188881,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150014,2025-11-14,2025-11-14T06:56:38.070000+00:00

In [59]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRTLSE31555040', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
4520,166476,support@alizecharge.fr,CPO Alizé Liberté Public,"[1.4503666,43.6039735]","61 Bd Lazare Carnot, 31000 TOULOUSE",FRTLSE31555040,TOULOUSE - Bd Lazare Carnot,Voirie,1,Accès libre,Mo-Su 00:00-23:57,False,FRTLSE315550401,2025-11-14,2025-11-14T06:56:38.070000+00:00
4521,166477,support@alizecharge.fr,CPO Alizé Liberté Public,"[1.4503666,43.6039735]","61 Bd Lazare Carnot, 31000 TOULOUSE",FRTLSE31555040,TOULOUSE - Bd Lazare Carnot,Voirie,1,Accès libre,Mo-Su 00:00-23:57,False,FRTLSE3155504021,2025-11-14,2025-11-14T06:56:38.070000+00:00
4522,166478,support@alizecharge.fr,CPO Alizé Liberté Public,"[1.4503666,43.6039735]","61 Bd Lazare Carnot, 31000 TOULOUSE",FRTLSE31555040,TOULOUSE - Bd Lazare Carnot,Voirie,1,Accès libre,Mo-Su 00:00-23:57,False,FRTLSE3155504022,2025-11-14,2025-11-14T06:56:38.070000+00:00
4523,166479,support@alizecharge.fr,CPO Alizé Liberté Public,"[1.45026,43.6040701]","63 Bd Lazare Carnot, 31000 TOULOUSE",FRTLSE31555040,TOULOUSE – Station Deux-Roues Lazare Carnot,Voirie,3,Accès libre,Mo-Su 00:00-23:57,False,FRTLSE315550403,2025-11-14,2025-11-14T06:56:38.070000+00:00
4524,166480,support@alizecharge.fr,CPO Alizé Liberté Public,"[1.45026,43.6040701]","63 Bd Lazare Carnot, 31000 TOULOUSE",FRTLSE31555040,TOULOUSE – Station Deux-Roues Lazare Carnot,Voirie,3,Accès libre,Mo-Su 00:00-23:57,False,FRTLSE315550404,2025-11-14,2025-11-14T06:56:38.070000+00:00
4525,166481,support@alizecharge.fr,CPO Alizé Liberté Public,"[1.45026,43.6040701]","63 Bd Lazare Carnot, 31000 TOULOUSE",FRTLSE31555040,TOULOUSE – Station Deux-Roues Lazare Carnot,Voirie,3,Accès libre,Mo-Su 00:00-23:57,False,FRTLSE315550405,2025-11-14,2025-11-14T06:56:38.070000+00:00

In [60]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRFR1PEHNKRRPQNR', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : une station avec plusieurs coordonnées -> incompréhension distinction station / pdc

In [61]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR073PCAMAIEUFR', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
0,330,acelec@acelec-france.com,Camaïeu France,"[3.207306,50.684918]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E0HKH51125,2022-07-21,2024-12-06T06:46:31.269000+00:00
1,331,acelec@acelec-france.com,Camaïeu France,"[3.207246,50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E8OV45243,2022-07-21,2024-12-06T06:46:31.269000+00:00
2,332,acelec@acelec-france.com,Camaïeu France,"[3.207124,50.684984]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EBEQA5957,2022-07-21,2024-12-06T06:46:31.269000+00:00
3,333,acelec@acelec-france.com,Camaïeu France,"[3.20737,50.684898]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ECC1C5530,2022-07-21,2024-12-06T06:46:31.269000+00:00
5,335,acelec@acelec-france.com,Camaïeu France,"[3.207306,50.684918]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EK0BJ522,2022-07-21,2024-12-06T06:46:31.269000+00:00
6,336,acelec@acelec-france.com,Camaïeu France,"[3.207047,50.685013]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EMZLV5283,2022-07-21,2024-12-06T06:46:31.269000+00:00
7,337,acelec@acelec-france.com,Camaïeu France,"[3.20737,50.684898]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EO0AV51091,2022-07-21,2024-12-06T06:46:31.269000+00:00
8,338,acelec@acelec-france.com,Camaïeu France,"[3.207187,50.684964]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP7QU5233,2022-07-21,2024-12-06T06:46:31.269000+00:00
9,339,acelec@acelec-france.com,Camaïeu France,"[3.206962,50.685049]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP9LD51287,2022-07-21,2024-12-06T06:46:31.269000+00:00
10,340,acelec@acelec-france.com,Camaïeu France,"[3.207433,50.684876]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EQ1GI51176,2022-07-21,2024-12-06T06:46:31.269000+00:00
11,341,acelec@acelec-france.com,Camaïeu France,"[3.207433,50.684876]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EREUO5946,2022-07-21,2024-12-06T06:46:31.269000+00:00
13,345,acelec@acelec-france.com,Camaïeu France,"[3.207187,50.684964]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ETCIX5105,2022-07-21,2024-12-06T06:46:31.269000+00:00
14,346,acelec@acelec-france.com,Camaïeu France,"[3.207124,50.684984]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EU6RQ5270,2022-07-21,2024-12-06T06:46:31.269000+00:00
15,347,acelec@acelec-france.com,Camaïeu France,"[3.207047,50.685013]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EUHNJ5886,2022-07-21,2024-12-06T06:46:31.269000+00:00
16,348,acelec@acelec-france.com,Camaïeu France,"[3.206962,50.685049]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EXINB5826,2022-07-21,2024-12-06T06:46:31.269000+00:00
17,349,acelec@acelec-france.com,Camaïeu France,"[3.207246,50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EYLF65474,2022-07-21,2024-12-06T06:46:31.269000+00:00

- exemple : une station avec plusieurs coordonnées -> regroupement de stations ?

In [62]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR55CPBP514', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : plusieurs stations d'opérateurs différents avec les mêmes coordonnées -> suppression non effectuée lors d'un changement d'opérateur ?

In [63]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[0.08745032, 48.40887156]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [64]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-4.374469, 48.471878]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : quatre stations avec une localisation identique mais deux adresses différentes + id identique entre station et pdc -> erreur d'adresse et erreur d'id_station ?

In [65]:
itinerance_5.loc[itinerance_5.coordonneesXY	 == '[-0.366184, 43.332508]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Incoherence nbre_pdc
- 583 pdc ont un champ 'nbre_pdc' mal documenté

In [66]:
itinerance_4.loc[~itinerance_4['nbre_pdc - id_station_itinerance'], relations][200:215]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
361,22673,support@dream-energy.fr,Hôtel Kyriad Enzo Hôtel Pont A Mousson,"[6.06469, 48.900576]",210 Allée de l'Espace Saint-Martin - 54700 Pon...,FRDREP90106271,PONT A MOUSSON,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714743,2025-04-23,2025-10-30T21:38:38.412000+00:00
362,22674,support@dream-energy.fr,Hôtel Kyriad Enzo Hôtel Pont A Mousson,"[6.06469, 48.900576]",210 Allée de l'Espace Saint-Martin - 54700 Pon...,FRDREP90106271,PONT A MOUSSON,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714751,2025-04-23,2025-10-30T21:38:38.412000+00:00
363,22675,support@dream-energy.fr,Hôtel Kyriad Enzo Hôtel Pont A Mousson,"[6.06469, 48.900576]",210 Allée de l'Espace Saint-Martin - 54700 Pon...,FRDREP90106271,PONT A MOUSSON,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714752,2025-04-23,2025-10-30T21:38:38.412000+00:00
364,22676,support@dream-energy.fr,Hôtel Kyriad Enzo Hôtel Pont A Mousson,"[6.06469, 48.900576]",210 Allée de l'Espace Saint-Martin - 54700 Pon...,FRDREP90106271,PONT A MOUSSON,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714761,2025-04-23,2025-10-30T21:38:38.412000+00:00
365,22677,support@dream-energy.fr,Hôtel Kyriad Enzo Hôtel Pont A Mousson,"[6.06469, 48.900576]",210 Allée de l'Espace Saint-Martin - 54700 Pon...,FRDREP90106271,PONT A MOUSSON,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714762,2025-04-23,2025-10-30T21:38:38.412000+00:00
366,22678,support@dream-energy.fr,F1 EPINAL CHAVELOT,"[6.432452, 48.222682]",Rue de la Malboué - Chavelot 88150,FRDREP90106268,CHAVELOT,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714801,2025-04-23,2025-10-30T21:38:38.412000+00:00
367,22679,support@dream-energy.fr,F1 EPINAL CHAVELOT,"[6.432452, 48.222682]",Rue de la Malboué - Chavelot 88150,FRDREP90106268,CHAVELOT,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714802,2025-04-23,2025-10-30T21:38:38.412000+00:00
368,22680,support@dream-energy.fr,F1 EPINAL CHAVELOT,"[6.432452, 48.222682]",Rue de la Malboué - Chavelot 88150,FRDREP90106268,CHAVELOT,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714803,2025-04-23,2025-10-30T21:38:38.412000+00:00
369,22681,support@dream-energy.fr,F1 EPINAL CHAVELOT,"[6.432452, 48.222682]",Rue de la Malboué - Chavelot 88150,FRDREP90106268,CHAVELOT,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714811,2025-04-23,2025-10-30T21:38:38.412000+00:00
370,22682,support@dream-energy.fr,F1 EPINAL CHAVELOT,"[6.432452, 48.222682]",Rue de la Malboué - Chavelot 88150,FRDREP90106268,CHAVELOT,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714812,2025-04-23,2025-10-30T21:38:38.412000+00:00
371,22683,support@dream-energy.fr,F1 EPINAL CHAVELOT,"[6.432452, 48.222682]",Rue de la Malboué - Chavelot 88150,FRDREP90106268,CHAVELOT,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714821,2025-04-23,2025-10-30T21:38:38.412000+00:00
372,22684,support@dream-energy.fr,F1 EPINAL CHAVELOT,"[6.432452, 48.222682]",Rue de la Malboué - Chavelot 88150,FRDREP90106268,CHAVELOT,Parking public,2,Accès libre,24/7,FALSE,FRDREE12345714822,2025-04-23,2025-10-30T21:38:38.412000+00:00
373,22685,support@dream-energy.fr,Ibis Styles Nancy Ouest Laxou,"[6.131646, 48.696645]",10 rue de la Saône - 54520 Laxou,FRDREP90106250,LAXOU,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714861,2025-04-23,2025-10-30T21:38:38.412000+00:00
374,22686,support@dream-energy.fr,Ibis Styles Nancy Ouest Laxou,"[6.131646, 48.696645]",10 rue de la Saône - 54520 Laxou,FRDREP90106250,LAXOU,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714862,2025-04-23,2025-10-30T21:38:38.412000+00:00
375,22687,support@dream-energy.fr,Ibis Styles Nancy Ouest Laxou,"[6.131646, 48.696645]",10 rue de la Saône - 54520 Laxou,FRDREP90106250,LAXOU,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714863,2025-04-23,2025-10-30T21:38:38.412000+00:00

### coherence station - enseigne
- 5 stations ont plusieurs noms d'enseigne

In [67]:
itinerance_4.loc[~itinerance_4['nom_enseigne - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
340,22648,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534911,2025-04-23,2025-10-30T21:38:38.412000+00:00
341,22649,support@dream-energy.fr,ENZO HOTEL FROUARD,"[6.150969, 48.742738]",15 rue Ferdinand Braun - Ostwald 67540,FRDREP90106270,OSTWALD - STRASBOURG LA VIGIE,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534912,2025-04-23,2025-10-30T21:38:38.412000+00:00
342,22650,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534913,2025-04-23,2025-10-30T21:38:38.412000+00:00
343,22651,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534921,2025-04-23,2025-10-30T21:38:38.412000+00:00
344,22652,support@dream-energy.fr,B&B HOTEL Nancy Frouard,"[6.150969, 48.742738]",3 Rue de Nerbevaux - Frouard 54390,FRDREP90106270,NANCY FROUARD,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534922,2025-04-23,2025-10-30T21:38:38.412000+00:00
899,53335,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.999000+00:00
900,53336,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.999000+00:00
901,53337,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS3,2022-12-09,2024-12-06T06:49:25.999000+00:00
906,57033,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.527000+00:00
907,57034,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.527000+00:00
908,57035,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS3,2022-10-04,2024-12-06T06:49:29.527000+00:00
1008,62648,support@alizecharge.fr,pass pass électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090011,2025-11-14,2025-11-14T06:56:38.070000+00:00
1009,62649,support@alizecharge.fr,pass pass électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090012,2025-11-14,2025-11-14T06:56:38.070000+00:00
1010,62650,support@alizecharge.fr,Pass Pass Électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090013,2025-11-14,2025-11-14T06:56:38.070000+00:00
1011,62651,support@alizecharge.fr,pass pass électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090014,2025-11-14,2025-11-14T06:56:38.070000+00:00
1012,62652,support@alizecharge.fr,pass pass électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090015,2025-11-14,2025-11-14T06:56:38.070000+00:00
1013,62653,support@alizecharge.fr,pass pass électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090016,2025-11-14,2025-11-14T06:56:38.070000+00:00
1014,62654,support@alizecharge.fr,Pass Pass Électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090017,2025-11-14,2025-11-14T06:56:38.070000+00:00
1015,62655,support@alizecharge.fr,Pass Pass Électrique,"[3.125616,50.650287]","Rue du Moulin Delmar, 59491 VILLENEUVE D'ASCQ",FRH01E59009001,VILLENEUVE D'ASCQ - Rue du Moulin Delmar - Par...,Voirie,8,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590090018,2025-11-14,2025-11-14T06:56:38.070000+00:00
1016,62760,support@alizecharge.fr,Pass Pass Électrique,"[2.460441,50.78763]","Pole Gare, 59670 BAVINCHOVE",FRH01E59054001,BAVINCHOVE - Pole Gare,Voirie,5,Accès libre,Mo-Su 00:00-23:57,False,FRH01E5905400111,2025-11-14,2025-11-14T06:56:38.070000+00:00
1017,62761,support@alizecharge.fr,Pass Pass Électrique,"[2.460441,50.78763]","Pole Gare, 59670 BAVINCHOVE",FRH01E59054001,BAVINCHOVE - Pole Gare,Voirie,5,Accès libre,Mo-Su 00:00-23:57,False,FRH01E5905400112,2025-11-14,2025-11-14T06:56:38.070000+00:00
1018,62762,support@alizecharge.fr,Pass Pass Électrique,"[2.460441,50.78763]","Pole Gare, 59670 BAVINCHOVE",FRH01E59054001,BAVINCHOVE - Pole Gare,Voirie,5,Accès libre,Mo-Su 00:00-23:57,False,FRH01E5905400121,2025-11-14,2025-11-14T06:56:38.070000+00:00
1019,62763,support@alizecharge.fr,Pass Pass Électrique,"[2.460441,50.78763]","Pole Gare, 59670 BAVINCHOVE",FRH01E59054001,BAVINCHOVE - Pole Gare,Voirie,5,Accès libre,Mo-Su 00:00-23:57,False,FRH01E5905400122,2025-11-14,2025-11-14T06:56:38.070000+00:00
1020,62764,support@alizecharge.fr,pass pass électrique,"[2.460441,50.78763]","Pole Gare, 59670 BAVINCHOVE",FRH01E59054001,BAVINCHOVE - Pole Gare,Voirie,5,Accès libre,Mo-Su 00:00-23:57,False,FRH01E590540013,2025-11-14,2025-11-14T06:56:38.070000+00:00
1021,62819,support@alizecharge.fr,pass pass électrique,"[3.227063,50.172734]","Place Eugène Thomas, 59400 CAMBRAI",FRH01E59122006,CAMBRAI - Place Eugène Thomas,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRH01E591220061,2025-11-14,2025-11-14T06:56:38.070000+00:00
1022,62820,support@alizecharge.fr,Pass Pass Électrique,"[3.227063,50.172734]","Place Eugène Thomas, 59400 CAMBRAI",FRH01E59122006,CAMBRAI - Place Eugène Thomas,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRH01E591220062,2025-11-14,2025-11-14T06:56:38.070000+00:00
1023,63457,support@alizecharge.fr,pass pass électrique,"[2.59498,49.2182]","Rue du Poteau, 60300 CHAMANT",FRH01E60138002,CHAMANT - Avenue du Poteau,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRH01E601380021,2025-11-14,2025-11-14T06:56:38.070000+00:00
1024,63458,support@alizecharge.fr,Pass Pass Électrique,"[2.59498,49.2182]","Rue du Poteau, 60300 CHAMANT",FRH01E60138002,CHAMANT - Avenue du Poteau,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRH01E601380022,2025-11-14,2025-11-14T06:56:38.070000+00:00
1025,63681,support@alizecharge.fr,pass pass électrique,"[2.44539,49.2216]","4 Rue du 8 Mai 1945, 60740 SAINT-MAXIMIN",FRH01E60589001,SAINT-MAXIMIN - Rue du 8 Mai 1945,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRH01E605890011,2025-11-14,2025-11-14T06:56:38.070000+00:00
1026,63682,support@alizecharge.fr,Pass Pass Électrique,"[2.44539,49.2216]","4 Rue du 8 Mai 1945, 60740 SAINT-MAXIMIN",FRH01E60589001,SAINT-MAXIMIN - Rue du 8 Mai 1945,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRH01E605890012,2025-11-14,2025-11-14T06:56:38.070000+00:00
1027,63830,support@alizecharge.fr,pass pass électrique,"[2.639003,50.522021]","Avenue du Maréchal juin, 62400 BETHUNE",FRH01E62119001,BETHUNE - Avenue du Maréchal juin,Voirie,6,Accès libre,Mo-Su 00:00-23:57,False,FRH01E621190011,2025-11-14,2025-11-14T06:56:38.070000+00:00
1028,63831,support@alizecharge.fr,pass pass électrique,"[2.639003,50.522021]","Avenue du Maréchal juin, 62400 BETHUNE",FRH01E62119001,BETHUNE - Avenue du Maréchal juin,Voirie,6,Accès libre,Mo-Su 00:00-23:57,False,FRH01E621190012,2025-11-14,2025-11-14T06:56:38.070000+00:00
1029,63832,support@alizecharge.fr,pass pass électrique,"[2.639003,50.522021]","Avenue du Maréchal juin, 62400 BETHUNE",FRH01E62119001,BETHUNE - Avenue du Maréchal juin,Voirie,6,Accès libre,Mo-Su 00:00-23:57,False,FRH01E621190013,2025-11-14,2025-11-14T06:56:38.070000+00:00
1030,63833,support@alizecharge.fr,pass pass électrique,"[2.639003,50.522021]","Avenue du Maréchal juin, 62400 BETHUNE",FRH01E62119001,BETHUNE - Avenue du Maréchal juin,Voirie,6,Accès libre,Mo-Su 00:00-23:57,False,FRH01E621190014,2025-11-14,2025-11-14T06:56:38.070000+00:00
1031,63834,support@alizecharge.fr,Pass Pass Électrique,"[2.639003,50.522021]","Avenue du Maréchal juin, 62400 BETHUNE",FRH01E62119001,BETHUNE - Avenue du Maréchal juin,Voirie,6,Accès libre,Mo-Su 00:00-23:57,False,FRH01E621190015,2025-11-14,2025-11-14T06:56:38.070000+00:00
1032,63835,support@alizecharge.fr,Pass Pass Électrique,"[2.639003,50.522021]","Avenue du Maréchal juin, 62400 BETHUNE",FRH01E62119001,BETHUNE - Avenue du Maréchal juin,Voirie,6,Accès libre,Mo-Su 00:00-23:57,False,FRH01E621190016,2025-11-14,2025-11-14T06:56:38.070000+00:00
1033,63954,support@alizecharge.fr,Pass Pass Électrique,"[2.95,50.417]","Parking de le Gare SNCF, 62110 HENIN BEAUMONT",FRH01E62427002,HENIN BEAUMONT - Parking de le Gare SNCF,Voirie,4,Accès libre,Mo-Su 00:00-23:57,False,FRH01E624270021,2025-11-14,2025-11-14T06:56:38.070000+00:00
1034,63955,support@alizecharge.fr,Pass Pass Électrique,"[2.95,50.417]","Parking de le Gare SNCF, 62110 HENIN BEAUMONT",FRH01E62427002,HENIN BEAUMONT - Parking de le Gare SNCF,Voirie,4,Accès libre,Mo-Su 00:00-23:57,False,FRH01E624270022,2025-11-14,2025-11-14T06:56:38.070000+00:00
1035,63956,support@alizecharge.fr,pass pass électrique,"[2.95,50.417]","Parking de le Gare SNCF, 62110 HENIN BEAUMONT",FRH01E62427002,HENIN BEAUMONT - Parking de le Gare SNCF,Voirie,4,Accès libre,Mo-Su 00:00-23:57,False,FRH01E624270023,2025-11-14,2025-11-14T06:56:38.070000+00:00
1036,63957,support@alizecharge.fr,pass pass électrique,"[2.95,50.417]","Parking de le Gare SNCF, 62110 HENIN BEAUMONT",FRH01E62427002,HENIN BEAUMONT - Parking de le Gare SNCF,Voirie,4,Accès libre,Mo-Su 00:00-23:57,False,FRH01E624270024,2025-11-14,2025-11-14T06:56:38.070000+00:00
1305,91960,contact@rirodo.fr,LAST MILES SOLUTIONS,"[5.39, 43.27]",20 Rue Negresko,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRLMSE1897228,2023-09-06,2024-12-06T06:47:15.989000+00:00
1550,96015,support@mobilize-ps.fr,BODEMER BAYEUX,"[-0.700226002831211, 49.27084281571326]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,BODEMER Bayeux,Parking privé à usage public,1,Accès libre,24/7,False,FRMBZESMYCQ1,2024-06-03,2025-10-28T15:28:31.144000+00:00
1551,96016,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[-0.700259, 49.270901]","\t16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,\t\tScauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",False,FRMBZESMYQC1,2024-06-03,2025-10-28T15:28:31.144000+00:00
3106,132898,contact@rirodo.fr,MONTA,"[5.39, 43.27]",20 Rue NEGRESKO,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRRIRE2804856,2023-09-06,2024-12-06T06:47:15.989000+00:00

In [68]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRFR1EAYRU', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
52270,52291,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.213000+00:00
52272,52293,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.213000+00:00
52274,52295,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU3,2022-08-25,2024-12-06T06:49:41.213000+00:00
53314,53335,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.999000+00:00
53315,53336,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.999000+00:00
53316,53337,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS3,2022-12-09,2024-12-06T06:49:25.999000+00:00

In [69]:
itinerance_init.loc[itinerance_init.nom_enseigne == 'RME Loos (FR-FR1)', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
52270,52291,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.213000+00:00
52272,52293,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.213000+00:00
53314,53335,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.999000+00:00
53315,53336,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.999000+00:00
57012,57033,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.527000+00:00
57013,57034,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.527000+00:00

### cohérence station - horaires
- exemple de station avec plusieurs types d'horaire (15)

In [70]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRS23D2302001', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
139263,139436,contact@mobive.fr,Réseau MOBIVE,"[2.297630254367735, 45.98220366857867]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:01,False,FRS23P230200101,2023-03-09,2025-09-11T07:22:20.875000+00:00
139264,139437,contact@mobive.fr,Réseau MOBIVE,"[2.297630254367735, 45.98220366857867]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:02,False,FRS23P230200102,2023-03-09,2025-09-11T07:22:20.875000+00:00

### cohérence station - deux-roues
- exemple de station avec plusieurs indications d'accessibilité deux-roues (583)

In [71]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRV75PPX1716', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
177938,178112,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17161,2025-06-30,2025-11-17T18:06:37.032741+00:00
177939,178113,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,TRUE,FRV75EPX17161,2023-07-06,2025-05-05T13:44:55.751000+00:00
177940,178114,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17162,2025-06-30,2025-11-17T18:06:37.032741+00:00
177941,178115,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,TRUE,FRV75EPX17162,2023-07-06,2025-05-05T13:44:55.751000+00:00
177942,178116,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17163,2025-06-30,2025-11-17T18:06:37.032741+00:00
177943,178117,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17163,2023-07-06,2025-05-05T13:44:55.751000+00:00
177944,178118,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17164,2025-06-30,2025-11-17T18:06:37.032741+00:00
177945,178119,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17164,2023-07-06,2025-05-05T13:44:55.751000+00:00
177946,178120,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17165,2025-06-30,2025-11-17T18:06:37.032741+00:00
177947,178121,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17165,2023-07-06,2025-05-05T13:44:55.751000+00:00
177948,178122,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17166,2025-06-30,2025-11-17T18:06:37.032741+00:00
177949,178123,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17166,2023-07-06,2025-05-05T13:44:55.751000+00:00
177950,178124,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17167,2025-06-30,2025-11-17T18:06:37.032741+00:00
177951,178125,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17167,2023-07-06,2025-05-05T13:44:55.751000+00:00

### stations avec pdc > 350 kW

- exemple de station avec une puissance de plus de 350 kW

In [72]:
data['p_nom'] = data['puissance_nominale'].str.replace(",", ".")

In [73]:
data['p_nom'] = data['p_nom'].astype('float')

In [75]:
from copy import copy
data350 = copy(data.loc[data["p_nom"] > 350, :])

In [76]:
data350['index'] = 0

In [77]:
data350.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
79,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP7436646854835046002,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER01,2025-07-10,2025-11-15T03:01:22+00:00
80,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP7436646854835046002,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER02,2025-07-10,2025-11-15T03:01:22+00:00
81,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP7436646854835046002,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER03,2025-07-10,2025-11-15T03:01:22+00:00
82,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP7436646854835046002,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER04,2025-07-10,2025-11-15T03:01:22+00:00
83,0,roaming@zunder.com,Zunder,"[2.240639 , 47.096021]","A71/E11, km200, Aire de Bourges-Marmagne, Mar...",ESZUNP5607534268681669145,Zunder/122319,Station dédiée à la recharge rapide,48,Accès libre,24/7,False,ESZUNEFR1801ER01,2025-10-27,2025-11-15T03:01:22+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190005,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER01,2025-10-15,2025-11-17T18:06:37.032741+00:00
190006,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER02,2025-10-15,2025-11-17T18:06:37.032741+00:00
190007,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER03,2025-10-15,2025-11-17T18:06:37.032741+00:00
190008,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER04,2025-10-15,2025-11-17T18:06:37.032741+00:00
190835,0,c.blanchot@enerjump.fr,Watt'up,"[1.4680245239967855, 45.15332621876889]",153 rue des levades,Non concerné,Watt'up Brive 19001,Station dédiée à la recharge rapide,4,Accès réservé,24/7,false,Non concerné,2024-09-23,2024-09-24T08:19:16.919000+00:00

In [78]:
data350['contact_operateur'].unique()

array(['roaming@zunder.com', 'c.blanchot@enerjump.fr',
       'info.allego.france@allego.eu', 'fabien.lepeytre@allego.eu',
       'bppulsefranceops@bp.com', 'evdriversupport@bp.com',
       'exploitation@yaway-recharge.eu', 'roaming-dev@road.io',
       'help@electra.com', 'help@go-electra.com', 'support@fastned.nl',
       'contact@enerjump.fr', 'supervision-ev.france@totalenergies.com',
       'support@iecharge.io', 'info@ionity.eu', 'bornes@lidl.fr',
       'kontakt@lidl.de', 'irve@soregies.fr', 'support@mobilize-ps.fr',
       'energy@milence.com', 'ops@obornes.fr',
       'exploitation.irve@picoty.fr', 'contact@sowattsolutions.com',
       'support@alizecharge.fr', 'charging-france@tesla.com',
       'support@voltalia-mobility.com', 'support@greenflux.com',
       'support.vianeo@engie.com', 'kg@lastmilesolutions.com'],
      dtype=object)