## *Jeu de données IRVE*
-------------------
# Analyse des relations entre champs (intégrité des données)
------------------------------
## Contexte
- clarification du rôle des modèles de données dans les jeux de données (cf mise à jour récente des [guides data.gouv](https://guides.etalab.gouv.fr/qualite/documenter-les-donnees/))
- intégration d'une propriété "relationship" dans les schémas de données ([issue TableSchema](https://github.com/frictionlessdata/specs/issues/803) en cours de validation)
- création d'outils de contrôle des relations entre champs des jeux de données tabulaires (cf usage ci-dessous)

## Objectifs
- valider sur un cas réel l'utilisation d'un modèle de données en complément d'un schéma de données
- identifier les apports que pourraient avoir les contrôles de validation des relations entre champs

## Résultats
- les principaux résultats sont regroupés sur un [tableau de bord](https://nbviewer.org/github/loco-philippe/Environmental-Sensing/blob/main/python/Validation/irve/Analyse/IRVE_indicateurs.ipynb) 
- la formalisation d'un modèle de données facilite la compréhension des données et des relations entre champs
- l'outil de contrôle permet d'améliorer significativement la qualité des données par l'identification d'incohérences de relations
- l'identification des incohérences permet de trouver des stratégies de réduction des écarts (dans l'exemple ci-dessous, on passe 36% d'écart à 3,8 %)  
- l'analyse des données permet de (re)construire le modèle de données qui minimise les incohérences
- les incohérences détectées sur le jeu de données IRVE restent faibles (inférieures à 5 % des point de charge documentés - voir chapitre 4)

## Suite à donner
- Mettre à jour, valider et publier le modèle de données IRVE
- Définir les contrôles supplémentaires à intégrer pour toutes nouvelles données ainsi que pour le jeu complet
- Mettre en oeuvre les outils de contrôle

## Evolutions possibles 
- Ajouter dans les guides d'Etalab un guide pour les modèles de données 
- Intégrer dans les schémas de données la propriété "relationship" en cours de validation,
- Définir un indicateur qui mesure l'écart (existant / attendu) des relations entre champs

## Sommaire
*(liens actifs sur jupyter Notebook ou Nbviewer)*
- [1 - modèle de données](#1---modèle-de-données)
- [2 - Initialisation](#2---Initialisation)
- [3 - Séparation des pdc itinerance et hors itinerance](#3---Séparation-des-pdc-itinerance-et-hors-itinerance)
- [4 - Bilan initial intégrité](#4---Bilan-initial-intégrité)
- [5 - Séparation doublons pdc - date de maj](#5---Séparation-doublons-pdc---date-de-maj)
- [6 - Séparation doublons station - date de maj](#6---Séparation-doublons-station---date-de-maj)
- [7 - Synthèse](#7---Synthèse)
- [8 - Exemples d'erreurs résiduelles](#8---Exemples-d\'erreurs-résiduelles)

Ce Notebook peut être consulté sur [nbviewer](http://nbviewer.org/github/loco-philippe/Environmental-Sensing/tree/main/python/Validation/irve/Analyse)

données utilisées : https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/    
fichier : "*consolidation-etalab-schema-irve-statique-v-2.2.0-2024xxxx.csv*"

-----------------------
# 1 - modèle de données

Le modèle de données proposé ci-dessous est construit sur la base du schéma de données mis à disposition et du contenu du jeu de données.    
Il est à consolider en fonction de l'expertise des concepteurs et réutilisateurs (voir [guide méthodologique](https://github.com/loco-philippe/Environmental-Sensing/blob/main/property_relationship/FR_methodology.ipynb)).

*Notation:*
- *M : Mandatory - documentation obligatoire*
- *PK : Primary Key - identifiant unique de l'entité*
- *Root : champ fictif associé à une ligne du tableau*

In [1]:
from base64 import b64encode
from IPython.display import Image, display
with open('IRVE_modele.txt', 'r', encoding="utf-8") as f:
    modele = f.read()
display(Image(url="https://mermaid.ink/img/" + b64encode(modele.encode("ascii")).decode("ascii")))

------
# 2 - Initialisation
## initialisation logicielle

In [2]:
from datetime import datetime
import json
from tab_dataset import Cdataset
import pandas as pd
import ntv_pandas as npd
import pathlib

def analyse_integrite(data, schema, affiche=True, indic=True):
    '''analyse les relations du DataFrame 'data' définies dans le schéma 'schema'.
    Le nombre de ligne en erreur par relation (dict) est retourné et optionnellement affiché (paramètre 'affiche=True') . 
    Les lignes en erreur sont optionnellement ajoutées (paramètre 'indic=True') à 'data' sous forme de champs booléens par relation.
    '''
    dic_errors = Cdataset(data).check_relationship(schema)
    dic_count = {name: len(errors) for name, errors in dic_errors.items()}
    if affiche:
        for name, total in dic_count.items():
            print('{:<50} {:>5}'.format(name, total))
    if indic:
        data['ok'] = True
        for name, errors in dic_errors.items():
            data[name] = True
            data.loc[errors, name] = False
            data['ok'] = data['ok'] & data[name] 
    return dic_count

def add_nbre_pdc(data, affiche=True):
    '''ajoute un champ avec le nombre de pdc calculés et le compare au champ 'nbre_pdc'
    Le nombre d'écarts est affiché optionnellement (paramètre 'affiche=True').
    '''
    data['nb_pdc_calc'] = data.groupby('id_station_itinerance')['index'].transform('count')
    nbre_pdc = data['nbre_pdc'].astype('int')
    data['nbre_pdc_ok'] = data['nb_pdc_calc'] == nbre_pdc
    data['calc-nbre'] = data['nb_pdc_calc'] - nbre_pdc
    if affiche:
        ecart_nbre = len(data) - data['nbre_pdc_ok'].sum()
        print('{:<20} {:>5}'.format('nbre_pdc_ko', ecart_nbre))
        print(round(ecart_nbre / len(data) * 100), ' %')

## initialisation des données
- lecture du fichier issu de l'api 190 000 lignes (120 000 fin 2024)

In [255]:
dates = ['2023-03-03', '2023-04-17', '2023-05-02', '2023-05-24', '2023-06-17', '2023-07-04', '2023-07-23', '2023-08-08',
         '2023-09-06', '2023-09-19', '2023-10-04', '2023-10-21', '2023-10-31', '2023-11-23', '2023-12-14', '2023-12-29',
         '2024-01-15', '2024-02-07', '2024-02-28', '2024-03-27', '2024-04-24', '2024-05-19', '2024-06-05', '2024-08-02',
         '2024-10-24', '2024-11-27', '2025-01-03', '2025-10-04', '2025-11-18', '2026-02-18', '2026-03-14', 
         '2026-11-01', # données brutes 14/03
         '2026-12-01'  # données dédoublonnées 14/03
        ]
file_dedoubl =  'consolidation_transport_irve_statique_14_03.csv'
file_brut = 'consolidation_transport_avec_doublons_irve_statique_14_03.csv'
chemin = str(pathlib.Path(npd.__file__).parent.parent.parent/"Environmental-Sensing"/"python"/"Validation"/"irve"/"Analyse")

date= dates[-3]
if date == dates[-1]:
    file = file_dedoubl
elif date == dates[-2]:
    file = file_brut
else:
    file = 'consolidation-etalab-schema-irve-statique-v-2.3.1-'+date[:4]+date[5:7]+date[8:]+'.csv' # après 2024-02-06
log = {'date_irve': date, 'file': file, 'chemin': chemin}
irve = pd.read_csv(log['chemin'] + '/' + log['file'], sep=',', low_memory=False, dtype='object')
log['len_irve'] = len(irve)
#print('nombre de lignes : ', log['len_irve']) 
print('nombre de lignes : {}, nombre de pdc : {} \n'.format(log['len_irve'], len(irve.groupby(['id_pdc_itinerance']).count())))

nombre de lignes : 213792, nombre de pdc : 152468

In [254]:
irve_brut = pd.read_csv(log['chemin'] + '/' + file_brut, sep=',', low_memory=False, dtype='object')

#print('nombre de lignes : ', len(irve_brut)) 
print('nombre de lignes : {}, nombre de pdc : {} \n'.format(len(irve_brut), len(irve_brut.groupby(['id_pdc_itinerance']).count())))

nombre de lignes : 386786, nombre de pdc : 150001

## données EVZEN

In [175]:
#irve.columns

In [176]:
#irve_zen = irve[irve['nom_operateur'] == 'EVzen']
#len(irve_zen), list(irve_zen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

In [177]:
#irve_zen = irve[irve['contact_operateur'] == 'support@evzen.com']
#len(irve_zen), list(irve_zen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

In [178]:
#itinerance_5_full.columns

In [179]:
#erreur_zen = itinerance_5_full[itinerance_5_full['contact_operateur'] ==  'support@evzen.com']

In [180]:
#cas_erreur = 'adresse_station - coordonneesXY'
#erreur_zen[~erreur_zen[cas_erreur]].sort_values(by=['coordonneesXY']) # [0:30]

In [181]:
#irve[irve['coordonneesXY'] == '[-0.03405, 48.75304]'][['nom_amenageur', 'siren_amenageur', 'contact_amenageur',
#       'nom_operateur', 'contact_operateur', 'telephone_operateur',
#       'nom_enseigne', 'id_station_itinerance', 'id_station_local',
#       'nom_station', 'implantation_station', 'adresse_station',
#       'code_insee_commune', 'coordonneesXY', 'nbre_pdc', 'id_pdc_itinerance',
#       'id_pdc_local', 'puissance_nominale', 'prise_type_ef', 'prise_type_2']]

In [182]:
#irve_brut_zen = irve_brut[irve_brut['nom_operateur'] == 'EVzen']
#len(irve_brut_zen), list(irve_brut_zen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

In [183]:
#station_evzen = pd.DataFrame({'id_station_itinerance': irve_brut_zen.drop_duplicates('id_station_itinerance')['id_station_itinerance']})
#irve_stations_evzen = irve.merge(station_evzen, how="inner", on="id_station_itinerance")
#len(irve_stations_evzen), list(irve_stations_evzen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

In [184]:
#irve[irve['id_station_itinerance'] == 'FREVZPE1ECBE2B195F42949F1DD8C53B022']

## schéma de données
Le schéma de données restreint à la propriété 'relationship' et construit à partir du modèle de données est le suivants :

In [185]:
# complément à inclure dans le schéma de données
schema = {
    'relationships': [
         # relation unicité des pdl
         {"fields": ["id_pdc_itinerance", "index"],                    "link" : "coupled" },   
         # relations inter entités
         {"fields": ["id_station_itinerance", "contact_operateur"],    "link" : "derived" },
         {"fields": ["id_station_itinerance", "nom_enseigne"],         "link" : "derived" },
         {"fields": ["id_station_itinerance", "coordonneesXY"],        "link" : "derived" },
         {"fields": ["id_pdc_itinerance", "id_station_itinerance"],    "link" : "derived" },
         # relations intra entité - station
         {"fields": ["id_station_itinerance", "nom_station"],          "link" : "derived" },
         {"fields": ["id_station_itinerance", "implantation_station"], "link" : "derived" },
         #{"fields": ["id_station_itinerance", "date_maj"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "nbre_pdc"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "condition_acces"],      "link" : "derived" },
         {"fields": ["id_station_itinerance", "horaires"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "station_deux_roues"],   "link" : "derived" },
         # relations intra entité - localisation
         {"fields": ["coordonneesXY", "adresse_station"],              "link" : "derived" }
    ]
}
fields_schema = set([field for relation in schema['relationships'] for field in relation['fields']])
# liste des champs liés à un controle (relations) et obligatoires (mandatory)
relations = ['index', 'contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 
             'nom_station', 'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 
             'id_pdc_itinerance', 'date_maj', 'last_modified']
mandatory = ['contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 'nom_station',
             'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 'id_pdc_itinerance', 
             'puissance_nominale', 'prise_type_ef', 'prise_type_2', 'prise_type_combo_ccs', 'prise_type_chademo', 
             'prise_type_autre', 'paiement_acte', 'paiement_autre', 'reservation',  'accessibilite_pmr', 'restriction_gabarit', 
             'date_maj', 'last_modified']
controles = ['index - id_pdc_itinerance', 'contact_operateur - id_station_itinerance', 'nom_enseigne - id_station_itinerance',
             'coordonneesXY - id_station_itinerance', 'id_station_itinerance - id_pdc_itinerance',
             'nom_station - id_station_itinerance', 'implantation_station - id_station_itinerance',
             'nbre_pdc - id_station_itinerance', 'condition_acces - id_station_itinerance', 'horaires - id_station_itinerance',
             'station_deux_roues - id_station_itinerance', 'adresse_station - coordonneesXY']

-----------------------
## 3 - Séparation des pdc itinerance et hors itinerance
- 0.14 % des points de recharge sont hors itinerance (1 % en 2024)

In [186]:
if file in [file_brut, file_dedoubl]:
    irve['last_modified'] = irve['datagouv_last_modified']

In [187]:
# séparation des données
data = irve
data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']] = data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']].astype('string')
#data[['last_modified','date_maj']] = data[['last_modified','date_maj']].astype('datetime64')
data['non_concerne'] = data['id_station_itinerance'].str.contains('oncern') | data['id_pdc_itinerance'].str.contains('oncern')

non_concerne = data[data['non_concerne']].reset_index()['index']
itinerance = data[~data['non_concerne']].reset_index()
itinerance_init = itinerance.loc[:, relations]
log['pdc_hors_itinerance'] = len(non_concerne)
log['pdc_en_itinerance'] = len(itinerance)
print('nombre de pdc hors itinerance : ', log['pdc_hors_itinerance'], 'soit : ', len(non_concerne)/(len(non_concerne)+len(itinerance)))
print('nombre de pdc en itinerance   : ', log['pdc_en_itinerance'])

nombre de pdc hors itinerance :  176 soit :  0.0011750802860252241
nombre de pdc en itinerance   :  149601

In [188]:
itinerance.groupby(['datagouv_organization_or_owner']).count()['index'].sort_values(ascending=False)[0:15]

datagouv_organization_or_owner
QualiCharge                                  61079
GIREVE                                       26135
Alizé                                        13847
IZIVIA                                       13009
Indigo Group                                  7273
Driveco                                       3919
Eco-Movement                                  3168
TotalEnergies Marketing France                1849
Engie Mobilités Electriques                   1729
Citeos Ingénierie IdF & Est (Cogelum IdF)     1481
Lidl                                          1344
Electric 55 Charging                          1300
Qovoltis                                      1200
e-Totem                                       1110
Rossini Energy                                 857
Name: index, dtype: int64

(Dans Qualicharge, on a 61 450 pdc, ici on en retrouve 45 910 . Il en manque 15 540 ??)

In [189]:
# arborescence des champs et nombre de valeurs différentes
print(itinerance_init.npd.analysis().tree())

-1: root-derived (149601)
   0 : index (0 - 149601)
   1 : contact_operateur (149366 - 235)
   2 : nom_enseigne (144427 - 5174)
   3 : coordonneesXY (115027 - 34574)
   4 : adresse_station (114791 - 34810)
   5 : id_station_itineranc (104301 - 45300)
   6 : nom_station (113856 - 35745)
   7 : implantation_station (149596 - 5)
   8 : nbre_pdc (149496 - 105)
   9 : condition_acces (149599 - 2)
   10: horaires (148507 - 1094)
   11: station_deux_roues (149599 - 2)
   12: id_pdc_itinerance (0 - 149601)
   13: date_maj (148674 - 927)
   14: last_modified (149173 - 428)

-----------------------
## 4 - Bilan initial intégrité
- 58 % des lignes présentent un défaut d'intégrité (moins de 20% en 2024)

In [190]:
# séparation données bonnes (itinerance_ok_1) et données résiduelles (itinerance_1)
res = analyse_integrite(itinerance_init, schema)
itinerance_ok_1 = itinerance_init.loc[itinerance_init.ok, relations].reset_index(drop=True)
itinerance_1 = itinerance_init.loc[~itinerance_init.ok, relations].reset_index(drop=True)
itinerance_init = itinerance_init.loc[:, relations]
log['init_ok'] = len(itinerance_ok_1)
log['init_ko'] = len(itinerance_1)
print("\nnombre d'enregistrements sans erreurs : ", log['init_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['init_ko'])
print("taux d'erreur : ", round(log['init_ko'] / log['pdc_en_itinerance'] * 100), ' %')

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance           1647
nom_enseigne - id_station_itinerance                3927
coordonneesXY - id_station_itinerance               5231
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 2175
implantation_station - id_station_itinerance        1965
nbre_pdc - id_station_itinerance                    5016
condition_acces - id_station_itinerance              104
horaires - id_station_itinerance                     920
station_deux_roues - id_station_itinerance            73
adresse_station - coordonneesXY                     8701

nombre d'enregistrements sans erreurs :  134731
nombre d'enregistrements avec au moins une erreur :  14870
taux d'erreur :  10  %

-----------------------
## 5 - Séparation doublons pdc - date de maj
- 51 % des pdc en erreur sont liées aux doublons de pdc (40 % fin 2024)
- la suppression des doublons permet de réduire de 94% le nombre de lignes erronnées (50 % fin 2024)

In [191]:
# séparation doublons pdc (doublons_pdc) et données résiduelles (itinerance_2)
itinerance_1['doublons_pdc'] = itinerance_1.sort_values(by=['date_maj', 'last_modified']).duplicated('id_pdc_itinerance', keep='last')

doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)['index']
#doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_2 = itinerance_1[~itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_1 = itinerance_1.loc[:, relations]
log['doublons_pdc'] = len(doublons_pdc)
log['sans_doublons_pdc'] = len(itinerance_2)
print('nombre de doublons pdc : ', log['doublons_pdc'], ' soit ', round(log['doublons_pdc']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_pdc'], ' soit ', round(log['sans_doublons_pdc']/log['init_ko'] * 100), ' %')

nombre de doublons pdc :  0  soit  0  %
nombre de pdc sans doublon   :  14870  soit  100  %

In [192]:
# séparation données bonnes (itinerance_ok_3) et données résiduelles (itinerance_3)
res = analyse_integrite(itinerance_2, schema)
itinerance_ok_3 = itinerance_2.loc[itinerance_2.ok, relations].reset_index(drop=True)
itinerance_3 = itinerance_2.loc[~itinerance_2.ok, relations].reset_index(drop=True)
itinerance_2 = itinerance_2.loc[:, relations]
log['etape3_ok'] = len(itinerance_ok_3)
log['etape3_ko'] = len(itinerance_3)
print("\nnombre d'enregistrements sans erreurs : ", log['etape3_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape3_ko'])

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance           1647
nom_enseigne - id_station_itinerance                3927
coordonneesXY - id_station_itinerance               5231
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 2175
implantation_station - id_station_itinerance        1965
nbre_pdc - id_station_itinerance                    5016
condition_acces - id_station_itinerance              104
horaires - id_station_itinerance                     920
station_deux_roues - id_station_itinerance            73
adresse_station - coordonneesXY                     8701

nombre d'enregistrements sans erreurs :  0
nombre d'enregistrements avec au moins une erreur :  14870

-----------------------
## 6 - Séparation doublons station - date de maj
- la suppression des anciens pdc permet de réduire de 13 % supplémentaire le nombre de lignes erronnées
- les dernières erreurs correspondent à des stations associées à 69 opérateurs et sont liées à des causes multiples

In [193]:
# séparation doublons stations (doublons_stat_maj) et données résiduelles (itinerance_4)
itinerance_3['stat_maj'] = itinerance_3.id_station_itinerance + itinerance_3.date_maj
stat_maj_unique = itinerance_3.sort_values(by='stat_maj').drop_duplicates('id_station_itinerance', keep='last')
itinerance_3['last_stat_maj'] = itinerance_3['stat_maj'].isin(stat_maj_unique['stat_maj'])

doublons_stat_maj = itinerance_3[~itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)['index']
itinerance_4 = itinerance_3[itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)
itinerance_3 = itinerance_3.loc[:, relations]
log['doublons_station'] = len(doublons_stat_maj)
log['sans_doublons_station'] = len(itinerance_4)
print('nombre de doublons stations : ', log['doublons_station'], ' soit ', 
      round(log['doublons_station']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_station'])

nombre de doublons stations :  2397  soit  16  %
nombre de pdc sans doublon   :  12473

In [194]:
# séparation données bonnes (itinerance_ok_5) et données résiduelles (itinerance_5 / itinerance_5_full)
res = analyse_integrite(itinerance_4, schema)
itinerance_ok_5 = itinerance_4.loc[itinerance_4.ok, relations].reset_index(drop=True)
itinerance_5_full = itinerance_4.loc[~itinerance_4.ok].reset_index(drop=True)
itinerance_5 = itinerance_5_full.loc[:, relations]
#itinerance_4 = itinerance_4.loc[:, relations]
log['etape5_ok'] = len(itinerance_ok_5)
log['etape5_ko'] = len(itinerance_5)
print("\nnombre d'enregistrements sans erreurs : ", log['etape5_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape5_ko'], ' soit ', 
      round(log['etape5_ko']/log['etape3_ko'] * 100), ' %')

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              2
nom_enseigne - id_station_itinerance                   7
coordonneesXY - id_station_itinerance                987
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 1255
implantation_station - id_station_itinerance          71
nbre_pdc - id_station_itinerance                    1118
condition_acces - id_station_itinerance               23
horaires - id_station_itinerance                     102
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     8391

nombre d'enregistrements sans erreurs :  2216
nombre d'enregistrements avec au moins une erreur :  10257  soit  69  %

In [195]:
# structure des données présentant une erreur et nombre de valeurs
print(itinerance_5.npd.analysis().tree())

-1: root-derived (10257)
   0 : index (0 - 10257)
   1 : contact_operateur (10179 - 78)
   2 : nom_enseigne (9955 - 302)
   3 : coordonneesXY (8670 - 1587)
   4 : adresse_station (7564 - 2693)
      11: station_deux_roues (2691 - 2)
   5 : id_station_itineranc (7155 - 3102)
      13: date_maj (2801 - 301)
      14: last_modified (2999 - 103)
   6 : nom_station (7618 - 2639)
   7 : implantation_station (10252 - 5)
   8 : nbre_pdc (10213 - 44)
   9 : condition_acces (10255 - 2)
   10: horaires (10108 - 149)
   12: id_pdc_itinerance (0 - 10257)

In [196]:
# nb maxi d'erreurs
itinerance_4['somme'] = 0
for name in res.keys():
    itinerance_4['somme'] += 1 - itinerance_4[name]
erreurs = max(itinerance_4['somme'])
maxi = itinerance_4[itinerance_4.somme >= erreurs]
print("nombre d'enregistrements avec ", erreurs, " erreurs : ", len(maxi))

nombre d'enregistrements avec  4  erreurs :  37

In [197]:
# principaux opérateurs contributeur de défauts
operateurs = list(itinerance_5.drop_duplicates('contact_operateur')['contact_operateur'])
erreurs_op = [len(itinerance_5.loc[itinerance_5.contact_operateur == operateur]) for operateur in operateurs]
err_op_5, oper_5 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:5]))
err_op_10, oper_10 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:10]))

print(len(err_op_5), ' opérateurs représentent : ', round(sum(err_op_5) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_5, oper_5):
    print(err, op)

5  opérateurs représentent :  64  % des écarts

2626 support@evzen.com
1926 support@alizecharge.fr
790 info@ionity.eu
726 territoires@syaden.fr
489 bornes@lidl.fr

In [198]:
print(len(err_op_10), ' opérateurs représentent : ', round(sum(err_op_10) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_10, oper_10):
    print(err, op)

10  opérateurs représentent :  81  % des écarts

2626 support@evzen.com
1926 support@alizecharge.fr
790 info@ionity.eu
726 territoires@syaden.fr
489 bornes@lidl.fr
437 roaming@freshmile.com
382 roaming@zunder.com
356 sav@izivia.com
355 kg@lastmilesolutions.com
222 irve@soregies.fr

-----------------------
## 7 - Synthèse

### fichiers
Génération des fichiers intégrant les défauts d'intégrité :
- fichier csv des lignes résiduelles à traiter (IRVE_itinerance_residuel)
- fichier csv des données itinerance avec indicateur des données à corriger ou à ignorer (IRVE_itinerance_complet)
- fichier csv des données itinerance valides (IRVE_itinerance_valide)
- fichier csv des doublons (IRVE_itinerance_doublons)

In [199]:
# consolidation des données
itinerance['doublons_stat_maj'] = itinerance['index'].isin(doublons_stat_maj)
itinerance['doublons_pdc'] = itinerance['index'].isin(doublons_pdc)
itinerance['lignes_a_corriger'] = itinerance['index'].isin(itinerance_5['index'])
itinerance['doublons_a_supprimer'] = itinerance['doublons_stat_maj'] | itinerance['doublons_pdc']
itinerance['lignes_ko'] = itinerance['doublons_a_supprimer'] | itinerance['lignes_a_corriger']
print('total des lignes à corriger : ', itinerance['lignes_a_corriger'].sum())
itinerance_doublons = itinerance[itinerance['doublons_a_supprimer']].reset_index(drop=True)
print('total des doublons à supprimer : ', len(itinerance_doublons))
itinerance_ok = itinerance[~itinerance['lignes_ko']].reset_index(drop=True)
print('nombre de pdc avec controles ok : ', len(itinerance_ok))

total des lignes à corriger :  10257
total des doublons à supprimer :  2397
nombre de pdc avec controles ok :  136947

In [200]:
# génération des fichiers
extension = log['date_irve'] +'.csv'
itinerance_5_full.to_csv('IRVE_itinerance_residuel' + extension)
itinerance.to_csv('IRVE_itinerance_complet' + extension)
itinerance_ok.to_csv('IRVE_itinerance_valide' + extension)
itinerance_doublons.to_csv('IRVE_itinerance_doublons' + extension)
log['IRVE_itinerance_residuel' + extension] = len(itinerance_5_full)
log['IRVE_itinerance_complet' + extension] = len(itinerance)
log['IRVE_itinerance_valide' + extension] = len(itinerance_ok)
log['IRVE_itinerance_valide_stat' + extension] = len(itinerance_ok.drop_duplicates('id_station_itinerance', keep='last'))
log['IRVE_itinerance_doublons' + extension] = len(itinerance_doublons)

In [201]:
l_prefix = list(pd.read_csv(log['chemin'] + '/' + 'Operations_Recharge_16-07-2024.csv', sep=';', low_memory=False, dtype='object')['Identifiant'])
l_prefix[0]

'FR073'

In [202]:
for op in oper_5:
    print('IRVE_itinerance_residuel' + '_' + op + '_' + extension)
    itinerance_5_full.loc[itinerance_5_full.contact_operateur == op].to_csv('IRVE_itinerance_residuel' + '_' + op + '_' + extension)

IRVE_itinerance_residuel_support@evzen.com_2026-12-01.csv
IRVE_itinerance_residuel_support@alizecharge.fr_2026-12-01.csv
IRVE_itinerance_residuel_info@ionity.eu_2026-12-01.csv
IRVE_itinerance_residuel_territoires@syaden.fr_2026-12-01.csv
IRVE_itinerance_residuel_bornes@lidl.fr_2026-12-01.csv

### vérification de l'intégrité

In [203]:
# vérification de l'absence d'erreurs
res = analyse_integrite(itinerance_ok.loc[:, relations], schema, affiche=False)
log['bilan_erreurs'] = sum(res.values())
log['date'] = datetime.now().isoformat()
print('bilan intégrité :')
print('    erreurs : ', log['bilan_erreurs'])

bilan intégrité :
    erreurs :  0

In [204]:
# structure des données bonnes
#print(Cdataset(itinerance_ok.loc[:, mandatory]).tree())
print(itinerance_ok.loc[:, mandatory].npd.analysis().tree())

-1: root-derived (136947)
   4 : id_station_itineranc (94749 - 42198)
      0 : contact_operateur (41973 - 225)
      1 : nom_enseigne (37767 - 4431)
      2 : coordonneesXY (10042 - 32156)
         3 : adresse_station (768 - 31388)
      5 : nom_station (9188 - 33010)
      6 : implantation_station (42193 - 5)
      7 : nbre_pdc (42098 - 100)
      8 : condition_acces (42196 - 2)
      9 : horaires (41220 - 978)
      10: station_deux_roues (42196 - 2)
   11: id_pdc_itinerance (0 - 136947)
   12: puissance_nominale (136751 - 196)
   13: prise_type_ef (136945 - 2)
   14: prise_type_2 (136945 - 2)
   15: prise_type_combo_ccs (136945 - 2)
   16: prise_type_chademo (136945 - 2)
   17: prise_type_autre (136945 - 2)
   18: paiement_acte (136945 - 2)
   19: paiement_autre (136944 - 3)
   20: reservation (136945 - 2)
   21: accessibilite_pmr (136943 - 4)
   22: restriction_gabarit (136797 - 150)
   23: date_maj (136072 - 875)
   24: last_modified (136562 - 385)

### Indicateurs

In [205]:
# génération des indicateurs liés aux règles
regles = ['Pdc non unique', 'Station multi-operateurs', 'Station multi-enseignes', 'Station multi-localisations', 
          'Pdc multi-stations', 'station avec plusieurs noms', 'station multi-implantations', 
          'nombre de pdc par station incoherent', 'station multi-acces', 'station multi-horaires', 
          'acces deux-roues incoherent', 'localisation multi-adresses']
principal = [16, 17, 18, 19, 20]
secondaire = [21, 22, 23, 24, 25, 26, 27]
irve = itinerance_5_full # residuel
total = len(irve)
indic = {}

irve['principal'] = True
for ind in principal:
    irve['principal'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] = True
for ind in secondaire:
    irve['secondaire'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] |= (~irve['principal'] & ~irve['secondaire'])
irve['verif'] = irve['principal'] & irve['secondaire']
indic['principal pdc'] = int(total - irve['principal'].sum())
indic['secondaire pdc'] = int(total - irve['secondaire'].sum())

irve_p = irve[~irve['principal']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
irve_s = irve[~irve['secondaire']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
indic['principal stat'] = len(irve_p)
indic['secondaire stat'] = len(irve_s)

In [206]:
# ajout des principaux opérateurs contributeur de défauts
indic['operateurs'] = list(oper_5)
indic['erreurs_operateurs'] = list(err_op_5)

In [207]:
# ajout de l'indicateur d'écart entre nombre de pdc calculés et saisis
add_nbre_pdc(irve, affiche=True)
indic['nb_pdc_calc-nbre_pdc'] = int(irve['calc-nbre'].sum())

nbre_pdc_ko           2507
24  %

In [208]:
# indicateur d'écart entre nombre de pdc calculés et saisis sur les données sans doublon
itinerance_sans_doublons = itinerance[~itinerance['doublons_a_supprimer']].reset_index(drop=True)
add_nbre_pdc(itinerance_sans_doublons, affiche=True)

nbre_pdc_ko          32439
22  %

In [209]:
len(itinerance_4)

12473

In [210]:
# stockage des indicateurs
log |= indic
log_file = log['chemin'] + '/' + 'logfile.txt'
#with open('logfile.txt', 'a', encoding="utf-8") as f:
with open(log_file, 'a', encoding="utf-8") as f:
    f.write(json.dumps(log) + '\n')

In [211]:
itinerance_5_full.columns[16:28]

Index(['index - id_pdc_itinerance',
       'contact_operateur - id_station_itinerance',
       'nom_enseigne - id_station_itinerance',
       'coordonneesXY - id_station_itinerance',
       'id_station_itinerance - id_pdc_itinerance',
       'nom_station - id_station_itinerance',
       'implantation_station - id_station_itinerance',
       'nbre_pdc - id_station_itinerance',
       'condition_acces - id_station_itinerance',
       'horaires - id_station_itinerance',
       'station_deux_roues - id_station_itinerance',
       'adresse_station - coordonneesXY'],
      dtype='object')

-----------------------
## 8 - Exemples d'erreurs résiduelles 

### Erreurs multiples 
- exemple avec le nombre maximal d'erreurs (4) (35 pdc)
- exemple station 'FRS35P35093001B1' avec 25 pdc : coordonnées XY, nom_station, implantation station, condition accès)

In [212]:
maxi.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1462,13433,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003929,2025-12-11,2025-12-17T09:36:45.000000+0000
1463,13434,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003930,2025-12-11,2025-12-17T09:36:45.000000+0000
1464,13435,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003931,2025-12-11,2025-12-17T09:36:45.000000+0000
1465,13436,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003932,2025-12-11,2025-12-17T09:36:45.000000+0000
1466,13437,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003963,2025-12-11,2025-12-17T09:36:45.000000+0000
1467,13438,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003964,2025-12-11,2025-12-17T09:36:45.000000+0000
1468,13439,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003965,2025-12-11,2025-12-17T09:36:45.000000+0000
1469,13440,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003966,2025-12-11,2025-12-17T09:36:45.000000+0000
1677,13879,bornes@lidl.fr,LIDL,"[2.33427, 48.63166]",21 RUE DU PLESSIS,FRLDLPLFR4256EVCP,SAINTE GENEVIEVE DES BOIS,Parking privé à usage public,2,Accès libre,"Mo-Sa 08:30-20:30,Su 08:30-12:15",false,FRLDLE00007414,2025-12-11,2025-12-17T09:36:45.000000+0000
1678,13880,bornes@lidl.fr,LIDL,"[2.33427, 48.63166]",21 RUE DU PLESSIS,FRLDLPLFR4256EVCP,SAINTE GENEVIEVE DES BOIS,Parking privé à usage public,2,Accès libre,"Mo-Sa 08:30-20:30,Su 08:30-12:15",false,FRLDLE00007415,2025-12-11,2025-12-17T09:36:45.000000+0000
2221,20506,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.000000+0000
2222,20507,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.000000+0000
2223,20510,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,false,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.000000+0000
2224,20511,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,false,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.000000+0000
2225,20512,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,false,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.000000+0000
2226,20513,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,false,FRS35E3509300411,2024-09-18,2025-12-15T16:13:43.000000+0000
2227,20514,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,false,FRS35E3509300421,2024-09-18,2025-12-15T16:13:43.000000+0000
2228,20515,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,false,FRS35E3509300420,2024-09-18,2025-12-15T16:13:43.000000+0000
2229,20516,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,false,FRS35E350930041,2024-09-18,2025-12-15T16:13:43.000000+0000
2230,20517,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,false,FRS35E3509300412,2024-09-18,2025-12-15T16:13:43.000000+0000
2231,20518,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,false,FRS35E350930042,2024-09-18,2025-12-15T16:13:43.000000+0000
2232,20519,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,false,FRS35E3509300413,2024-09-18,2025-12-15T16:13:43.000000+0000
2233,20520,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,false,FRS35E3509300414,2024-09-18,2025-12-15T16:13:43.000000+0000
2234,20521,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,false,FRS35E3509300415,2024-09-18,2025-12-15T16:13:43.000000+0000
2235,20522,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,false,FRS35E3509300416,2024-09-18,2025-12-15T16:13:43.000000+0000
2236,20523,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,false,FRS35E3509300417,2024-09-18,2025-12-15T16:13:43.000000+0000
2237,20524,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,false,FRS35E3509300418,2024-09-18,2025-12-15T16:13:43.000000+0000
2238,20525,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,false,FRS35E3509300419,2024-09-18,2025-12-15T16:13:43.000000+0000
2239,20526,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,false,FRS35E350930043,2024-09-18,2025-12-15T16:13:43.000000+0000
2240,20527,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,false,FRS35E350930044,2024-09-18,2025-12-15T16:13:43.000000+0000
2241,20528,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,false,FRS35E350930045,2024-09-18,2025-12-15T16:13:43.000000+0000
2242,20529,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,false,FRS35E350930046,2024-09-18,2025-12-15T16:13:43.000000+0000
2243,20530,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,false,FRS35E350930047,2024-09-18,2025-12-15T16:13:43.000000+0000
5333,50125,support@alizecharge.fr,Le Plein Tarnais,"[2.49632, 43.63097]","Place De Castelnau, 81260 BRASSAC",FRS81E81037001,BRASSAC - Place De Castelnau,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRS81E810370012,2026-03-09,2026-03-09T15:02:55.000000+0000
6275,54698,support@alizecharge.fr,Le Plein Tarnais,"[2.49632, 43.63097]","Place De Castelnau, 81260 BRASSAC",FRS81E81037001,BRASSAC - Place De Castelnau,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRS81E810370011,2026-03-09,2026-03-09T15:02:55.000000+0000
7176,69195,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[49.27090, -0.70025]","\t16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,\t\tScauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",false,FRMBZESMYQC1,2024-06-03,2026-03-13T17:35:48.000000+0000
7177,69197,support@mobilize-ps.fr,BODEMER BAYEUX,"[49.27084, -0.70022]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,BODEMER Bayeux,Parking privé à usage public,1,Accès libre,24/7,false,FRMBZESMYCQ1,2024-06-03,2026-03-13T17:35:48.000000+0000

In [213]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRS35P35093001B1', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
2221,20506,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.000000+0000
2222,20507,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.000000+0000
2223,20510,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,false,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.000000+0000
2224,20511,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,false,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.000000+0000
2225,20512,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,false,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.000000+0000
2226,20513,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,false,FRS35E3509300411,2024-09-18,2025-12-15T16:13:43.000000+0000
2227,20514,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,false,FRS35E3509300421,2024-09-18,2025-12-15T16:13:43.000000+0000
2228,20515,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,false,FRS35E3509300420,2024-09-18,2025-12-15T16:13:43.000000+0000
2229,20516,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,false,FRS35E350930041,2024-09-18,2025-12-15T16:13:43.000000+0000
2230,20517,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,false,FRS35E3509300412,2024-09-18,2025-12-15T16:13:43.000000+0000
2231,20518,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,false,FRS35E350930042,2024-09-18,2025-12-15T16:13:43.000000+0000
2232,20519,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,false,FRS35E3509300413,2024-09-18,2025-12-15T16:13:43.000000+0000
2233,20520,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,false,FRS35E3509300414,2024-09-18,2025-12-15T16:13:43.000000+0000
2234,20521,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,false,FRS35E3509300415,2024-09-18,2025-12-15T16:13:43.000000+0000
2235,20522,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,false,FRS35E3509300416,2024-09-18,2025-12-15T16:13:43.000000+0000
2236,20523,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,false,FRS35E3509300417,2024-09-18,2025-12-15T16:13:43.000000+0000
2237,20524,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,false,FRS35E3509300418,2024-09-18,2025-12-15T16:13:43.000000+0000
2238,20525,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,false,FRS35E3509300419,2024-09-18,2025-12-15T16:13:43.000000+0000
2239,20526,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,false,FRS35E350930043,2024-09-18,2025-12-15T16:13:43.000000+0000
2240,20527,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,false,FRS35E350930044,2024-09-18,2025-12-15T16:13:43.000000+0000
2241,20528,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,false,FRS35E350930045,2024-09-18,2025-12-15T16:13:43.000000+0000
2242,20529,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,false,FRS35E350930046,2024-09-18,2025-12-15T16:13:43.000000+0000
2243,20530,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,false,FRS35E350930047,2024-09-18,2025-12-15T16:13:43.000000+0000

### Repartition des defauts par operateur
Répartition pour les 10 opérateurs présentant le plus de défauts

In [214]:
print('PdC avec une incohérence : ')
for operateur in oper_10:
    print('\n', sum(itinerance_5.contact_operateur == operateur))
    print('Répartition des incohérences ', operateur, ' :')
    for cont in controles:
        #print(cont, sum((itinerance_4['contact_operateur'] == 'supervision-ev.france@totalenergies.com') & ~(itinerance_4[cont])))
        print('{:<50} {:>5}'.format(cont, sum((itinerance_4['contact_operateur'] == operateur) & ~(itinerance_4[cont]))))

PdC avec une incohérence :

 2626
Répartition des incohérences  support@evzen.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  4
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     2622

 1926
Répartition des incohérences  support@alizecharge.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                213
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  855
implantation_station - id_station_itinerance          32
nbre_pdc - id_station_itinerance                     766
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     1103

 790
Répartition des incohérences  info@ionity.eu  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      790

 726
Répartition des incohérences  territoires@syaden.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      726

 489
Répartition des incohérences  bornes@lidl.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                468
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  154
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                     114
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                      24
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 437
Répartition des incohérences  roaming@freshmile.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      437

 382
Répartition des incohérences  roaming@zunder.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      382

 356
Répartition des incohérences  sav@izivia.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                 23
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   27
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                      23
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      333

 355
Répartition des incohérences  kg@lastmilesolutions.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      355

 222
Répartition des incohérences  irve@soregies.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance          12
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      210

### Defauts operateur ALIZECHARGE
Les défauts identifiés concernent des stations utilisant un même identifiant. Par exemple, la station 'FRADPE77294001' contient 40 points de recharge avec plusieurs adresses, plusieurs localisations, plusieurs noms de station et un nombre de points de rechage variable.

In [215]:
itinerance_4.loc[(~itinerance_4['nom_station - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'support@alizecharge.fr'), relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5144,48862,support@alizecharge.fr,Saemes,"[2.32420, 48.87113]","21 Place de la Madeleine, 75008 PARIS",FRSAEE75108003,SAEMES - Parking Madeleine-Tronchet - Niveau 3,Voirie,104,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE75108003275,2026-03-09,2026-03-09T15:02:55.000000+0000
5145,48873,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.70442, 45.20219]","0 Avenue des Martyrs, 38000 Grenoble",FRM38E38185031,GRENOBLE - CEA Cambridge Avenue des Martyrs,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRM38E381850312,2026-03-09,2026-03-09T15:02:55.000000+0000
5149,48894,support@alizecharge.fr,Saemes,"[2.32420, 48.87113]","21 Place de la Madeleine, 75008 PARIS",FRSAEE75108003,SAEMES - Parking Madeleine-Tronchet - Niveau 2,Voirie,30,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE75108003165,2026-03-09,2026-03-09T15:02:55.000000+0000
5151,48905,support@alizecharge.fr,Saemes,"[2.32420, 48.87113]","21 Place de la Madeleine, 75008 PARIS",FRSAEE75108003,SAEMES - Parking Madeleine-Tronchet - Niveau 3,Voirie,104,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE75108003285,2026-03-09,2026-03-09T15:02:55.000000+0000
5156,48925,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","0 Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SEYSSINS - Parking Le Prisme,Voirie,5,Accès libre,Mo-Su 00:00-23:57,false,FRM38E384860012,2026-03-09,2026-03-09T15:02:55.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7061,62463,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001201,2026-03-09,2026-03-09T15:02:55.000000+0000
7062,62577,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600212,2026-03-09,2026-03-09T15:02:55.000000+0000
7063,62578,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600211,2026-03-09,2026-03-09T15:02:55.000000+0000
7064,62579,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600222,2026-03-09,2026-03-09T15:02:55.000000+0000
7065,62580,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600221,2026-03-09,2026-03-09T15:02:55.000000+0000

In [216]:
itinerance_4.loc[(~itinerance_4['nbre_pdc - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'support@alizecharge.fr'), relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5144,48862,support@alizecharge.fr,Saemes,"[2.32420, 48.87113]","21 Place de la Madeleine, 75008 PARIS",FRSAEE75108003,SAEMES - Parking Madeleine-Tronchet - Niveau 3,Voirie,104,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE75108003275,2026-03-09,2026-03-09T15:02:55.000000+0000
5149,48894,support@alizecharge.fr,Saemes,"[2.32420, 48.87113]","21 Place de la Madeleine, 75008 PARIS",FRSAEE75108003,SAEMES - Parking Madeleine-Tronchet - Niveau 2,Voirie,30,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE75108003165,2026-03-09,2026-03-09T15:02:55.000000+0000
5151,48905,support@alizecharge.fr,Saemes,"[2.32420, 48.87113]","21 Place de la Madeleine, 75008 PARIS",FRSAEE75108003,SAEMES - Parking Madeleine-Tronchet - Niveau 3,Voirie,104,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE75108003285,2026-03-09,2026-03-09T15:02:55.000000+0000
5156,48925,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","0 Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SEYSSINS - Parking Le Prisme,Voirie,5,Accès libre,Mo-Su 00:00-23:57,false,FRM38E384860012,2026-03-09,2026-03-09T15:02:55.000000+0000
5157,48927,support@alizecharge.fr,EFFIA France,"[5.71289, 45.19235]","2 avenue Doyen Louis Weil, 38000 GRENOBLE",FRP01E38185011,Parking Grenoble Gares Europole - PARK GRENOBL...,Parking public,19,Accès libre,Mo-Su 00:00-23:57,false,FRP01E38185011111,2026-03-09,2026-03-09T15:02:55.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7061,62463,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001201,2026-03-09,2026-03-09T15:02:55.000000+0000
7062,62577,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600212,2026-03-09,2026-03-09T15:02:55.000000+0000
7063,62578,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600211,2026-03-09,2026-03-09T15:02:55.000000+0000
7064,62579,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600222,2026-03-09,2026-03-09T15:02:55.000000+0000
7065,62580,support@alizecharge.fr,Territoire de Energie TE53,"[-0.93954, 48.29696]","PLACE DE L'HÔTEL DE VILLE, 53500 ERNEE",FRS53E53096002,ERNEE - Place De L'Hôtel De Ville,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRS53E5309600221,2026-03-09,2026-03-09T15:02:55.000000+0000

In [217]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRADPE77294001', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
6958,61447,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001193,2026-03-09,2026-03-09T15:02:55.000000+0000
6959,61448,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001191,2026-03-09,2026-03-09T15:02:55.000000+0000
6960,61449,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001192,2026-03-09,2026-03-09T15:02:55.000000+0000
6961,61455,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001243,2026-03-09,2026-03-09T15:02:55.000000+0000
6962,61456,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001242,2026-03-09,2026-03-09T15:02:55.000000+0000
6963,61457,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001241,2026-03-09,2026-03-09T15:02:55.000000+0000
6966,61460,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001262,2026-03-09,2026-03-09T15:02:55.000000+0000
6967,61461,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001261,2026-03-09,2026-03-09T15:02:55.000000+0000
6968,61462,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001263,2026-03-09,2026-03-09T15:02:55.000000+0000
6976,61773,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001253,2026-03-09,2026-03-09T15:02:55.000000+0000
6977,61774,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001252,2026-03-09,2026-03-09T15:02:55.000000+0000
6978,61775,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001251,2026-03-09,2026-03-09T15:02:55.000000+0000
7010,62158,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001312,2026-03-09,2026-03-09T15:02:55.000000+0000
7011,62159,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001311,2026-03-09,2026-03-09T15:02:55.000000+0000
7012,62164,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001301,2026-03-09,2026-03-09T15:02:55.000000+0000
7013,62165,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001302,2026-03-09,2026-03-09T15:02:55.000000+0000
7014,62166,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001322,2026-03-09,2026-03-09T15:02:55.000000+0000
7015,62167,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001321,2026-03-09,2026-03-09T15:02:55.000000+0000
7027,62262,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001212,2026-03-09,2026-03-09T15:02:55.000000+0000
7028,62263,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001213,2026-03-09,2026-03-09T15:02:55.000000+0000
7029,62264,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001211,2026-03-09,2026-03-09T15:02:55.000000+0000
7038,62318,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001332,2026-03-09,2026-03-09T15:02:55.000000+0000
7039,62319,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001331,2026-03-09,2026-03-09T15:02:55.000000+0000
7040,62322,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001342,2026-03-09,2026-03-09T15:02:55.000000+0000
7041,62323,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001341,2026-03-09,2026-03-09T15:02:55.000000+0000
7044,62340,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001232,2026-03-09,2026-03-09T15:02:55.000000+0000
7045,62341,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001231,2026-03-09,2026-03-09T15:02:55.000000+0000
7046,62342,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001233,2026-03-09,2026-03-09T15:02:55.000000+0000
7047,62343,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001272,2026-03-09,2026-03-09T15:02:55.000000+0000
7048,62344,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001271,2026-03-09,2026-03-09T15:02:55.000000+0000
7049,62345,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001273,2026-03-09,2026-03-09T15:02:55.000000+0000
7050,62370,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001221,2026-03-09,2026-03-09T15:02:55.000000+0000
7051,62371,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001223,2026-03-09,2026-03-09T15:02:55.000000+0000
7052,62372,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001222,2026-03-09,2026-03-09T15:02:55.000000+0000
7053,62375,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001282,2026-03-09,2026-03-09T15:02:55.000000+0000
7054,62376,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001283,2026-03-09,2026-03-09T15:02:55.000000+0000
7055,62377,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001281,2026-03-09,2026-03-09T15:02:55.000000+0000
7059,62461,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001202,2026-03-09,2026-03-09T15:02:55.000000+0000
7060,62462,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001203,2026-03-09,2026-03-09T15:02:55.000000+0000
7061,62463,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001201,2026-03-09,2026-03-09T15:02:55.000000+0000

In [218]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[2.969121,48.282539]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Defauts operateur LIDL
Les défauts identifiés concernent principalement l'affectation de coordonnées au point de recharge et non à la station. Par exemple, pour une station composée de quatre bornes de deux points de recharge, on trouve une coordonnée différente pour chacune des bornes.

In [219]:
itinerance_4.loc[(~itinerance_4['coordonneesXY - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'bornes@lidl.fr') , relations].sort_values(by=["id_station_itinerance"])[0:50]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1317,12940,bornes@lidl.fr,LIDL,"[7.33667, 48.06137]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006684,2025-12-11,2025-12-17T09:36:45.000000+0000
1314,12937,bornes@lidl.fr,LIDL,"[7.33663, 48.06132]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006681,2025-12-11,2025-12-17T09:36:45.000000+0000
1318,12941,bornes@lidl.fr,LIDL,"[7.33670, 48.06141]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006685,2025-12-11,2025-12-17T09:36:45.000000+0000
1319,12942,bornes@lidl.fr,LIDL,"[7.33670, 48.06141]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006686,2025-12-11,2025-12-17T09:36:45.000000+0000
1316,12939,bornes@lidl.fr,LIDL,"[7.33667, 48.06137]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006683,2025-12-11,2025-12-17T09:36:45.000000+0000
1315,12938,bornes@lidl.fr,LIDL,"[7.33663, 48.06132]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006682,2025-12-11,2025-12-17T09:36:45.000000+0000
1503,13504,bornes@lidl.fr,LIDL,"[3.46612, 46.83519]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006060,2025-12-11,2025-12-17T09:36:45.000000+0000
1502,13503,bornes@lidl.fr,LIDL,"[3.46612, 46.83519]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006059,2025-12-11,2025-12-17T09:36:45.000000+0000
1501,13502,bornes@lidl.fr,LIDL,"[3.46613, 46.83523]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006058,2025-12-11,2025-12-17T09:36:45.000000+0000
1500,13501,bornes@lidl.fr,LIDL,"[3.46613, 46.83523]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006057,2025-12-11,2025-12-17T09:36:45.000000+0000
1499,13500,bornes@lidl.fr,LIDL,"[3.46613, 46.83527]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006056,2025-12-11,2025-12-17T09:36:45.000000+0000
1498,13499,bornes@lidl.fr,LIDL,"[3.46613, 46.83527]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006055,2025-12-11,2025-12-17T09:36:45.000000+0000
1476,13447,bornes@lidl.fr,LIDL,"[2.37828, 48.98769]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004323,2025-12-11,2025-12-17T09:36:45.000000+0000
1477,13448,bornes@lidl.fr,LIDL,"[2.37828, 48.98769]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004324,2025-12-11,2025-12-17T09:36:45.000000+0000
1478,13449,bornes@lidl.fr,LIDL,"[2.37814, 48.98761]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004325,2025-12-11,2025-12-17T09:36:45.000000+0000
1479,13450,bornes@lidl.fr,LIDL,"[2.37814, 48.98761]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004326,2025-12-11,2025-12-17T09:36:45.000000+0000
1481,13452,bornes@lidl.fr,LIDL,"[2.37797, 48.98752]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004328,2025-12-11,2025-12-17T09:36:45.000000+0000
1474,13445,bornes@lidl.fr,LIDL,"[2.37841, 48.98776]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004321,2025-12-11,2025-12-17T09:36:45.000000+0000
1475,13446,bornes@lidl.fr,LIDL,"[2.37841, 48.98776]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004322,2025-12-11,2025-12-17T09:36:45.000000+0000
1480,13451,bornes@lidl.fr,LIDL,"[2.37797, 48.98752]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004327,2025-12-11,2025-12-17T09:36:45.000000+0000
1504,13513,bornes@lidl.fr,LIDL,"[2.46814, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006917,2025-12-11,2025-12-17T09:36:45.000000+0000
1505,13514,bornes@lidl.fr,LIDL,"[2.46814, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006918,2025-12-11,2025-12-17T09:36:45.000000+0000
1507,13516,bornes@lidl.fr,LIDL,"[2.46821, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006920,2025-12-11,2025-12-17T09:36:45.000000+0000
1506,13515,bornes@lidl.fr,LIDL,"[2.46821, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006919,2025-12-11,2025-12-17T09:36:45.000000+0000
1376,13117,bornes@lidl.fr,LIDL,"[-3.43993, 48.73374]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005309,2025-12-11,2025-12-17T09:36:45.000000+0000
1378,13119,bornes@lidl.fr,LIDL,"[-3.43984, 48.73356]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005298,2025-12-11,2025-12-17T09:36:45.000000+0000
1379,13120,bornes@lidl.fr,LIDL,"[-3.43984, 48.73356]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005297,2025-12-11,2025-12-17T09:36:45.000000+0000
1377,13118,bornes@lidl.fr,LIDL,"[-3.43981, 48.73351]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005310,2025-12-11,2025-12-17T09:36:45.000000+0000
1313,12936,bornes@lidl.fr,LIDL,"[6.53238, 43.25534]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006712,2025-12-11,2025-12-17T09:36:45.000000+0000
1312,12935,bornes@lidl.fr,LIDL,"[6.53238, 43.25534]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006711,2025-12-11,2025-12-17T09:36:45.000000+0000
1311,12934,bornes@lidl.fr,LIDL,"[6.53232, 43.25531]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006710,2025-12-11,2025-12-17T09:36:45.000000+0000
1310,12933,bornes@lidl.fr,LIDL,"[6.53232, 43.25531]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006709,2025-12-11,2025-12-17T09:36:45.000000+0000
1309,12932,bornes@lidl.fr,LIDL,"[6.53243, 43.25578]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00005173,2025-12-11,2025-12-17T09:36:45.000000+0000
1308,12931,bornes@lidl.fr,LIDL,"[6.53243, 43.25578]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00005186,2025-12-11,2025-12-17T09:36:45.000000+0000
1320,12951,bornes@lidl.fr,LIDL,"[0.67401, 46.00272]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006611,2025-12-11,2025-12-17T09:36:45.000000+0000
1321,12952,bornes@lidl.fr,LIDL,"[0.67401, 46.00272]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006612,2025-12-11,2025-12-17T09:36:45.000000+0000
1322,12953,bornes@lidl.fr,LIDL,"[0.67403, 46.00277]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006613,2025-12-11,2025-12-17T09:36:45.000000+0000
1324,12955,bornes@lidl.fr,LIDL,"[0.67403, 46.00283]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006615,2025-12-11,2025-12-17T09:36:45.000000+0000
1325,12956,bornes@lidl.fr,LIDL,"[0.67403, 46.00283]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006616,2025-12-11,2025-12-17T09:36:45.000000+0000
1323,12954,bornes@lidl.fr,LIDL,"[0.67403, 46.00277]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006614,2025-12-11,2025-12-17T09:36:45.000000+0000
1514,13536,bornes@lidl.fr,LIDL,"[1.32590, 45.12886]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006617,2025-12-11,2025-12-17T09:36:45.000000+0000
1518,13540,bornes@lidl.fr,LIDL,"[1.32591, 45.12877]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006621,2025-12-11,2025-12-17T09:36:45.000000+0000
1517,13539,bornes@lidl.fr,LIDL,"[1.32590, 45.12882]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006620,2025-12-11,2025-12-17T09:36:45.000000+0000
1519,13541,bornes@lidl.fr,LIDL,"[1.32591, 45.12877]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006622,2025-12-11,2025-12-17T09:36:45.000000+0000
1516,13538,bornes@lidl.fr,LIDL,"[1.32590, 45.12882]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006619,2025-12-11,2025-12-17T09:36:45.000000+0000
1515,13537,bornes@lidl.fr,LIDL,"[1.32590, 45.12886]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006618,2025-12-11,2025-12-17T09:36:45.000000+0000
1403,13166,bornes@lidl.fr,LIDL,"[-0.21413, 44.90003]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006950,2025-12-11,2025-12-17T09:36:45.000000+0000
1404,13167,bornes@lidl.fr,LIDL,"[-0.21411, 44.90036]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006951,2025-12-11,2025-12-17T09:36:45.000000+0000
1405,13168,bornes@lidl.fr,LIDL,"[-0.21411, 44.90036]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006952,2025-12-11,2025-12-17T09:36:45.000000+0000
1402,13165,bornes@lidl.fr,LIDL,"[-0.21413, 44.90003]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006949,2025-12-11,2025-12-17T09:36:45.000000+0000

### Defauts operateur IZIVIA
Les défauts au nombre de 330 sont liés à une incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Izivia en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance, ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur un parking [-0.530598, 47.398424], on trouve 17 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué entre 1 et 3.

In [220]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'sav@izivia.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1856,16698,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11111,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11111,2025-09-30,2025-09-30T08:35:00.000000+0000
1857,16699,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG111101,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG111101,2025-09-30,2025-09-30T08:35:00.000000+0000
1858,16700,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11221,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11221,2025-09-30,2025-09-30T08:35:00.000000+0000
1859,16701,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11331,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11331,2025-09-30,2025-09-30T08:35:00.000000+0000
1860,16702,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11441,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11441,2025-09-30,2025-09-30T08:35:00.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7998,76498,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8211,2026-03-14,2026-03-14T07:00:49.000000+0000
7999,76499,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8221,2026-03-14,2026-03-14T07:00:49.000000+0000
8000,76500,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8231,2026-03-14,2026-03-14T07:00:49.000000+0000
8001,76501,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8241,2026-03-14,2026-03-14T07:00:49.000000+0000
8002,76856,sav@izivia.com,FLEX-E,"[44.96627, 4.88831]",Aire de covoiturage Vinci Autoroutes Valence N...,FRE04POAZS223,IZIVIA | AIRE DE COVOITURAGE DE VALENCE NORD,Voirie,4,Accès libre,24/7,false,FRE04EOAZS22332,2026-03-14,2026-03-14T07:01:30.000000+0000

In [221]:
itinerance_4.loc[(~itinerance_4['adresse_station - coordonneesXY']) & (itinerance_4['contact_operateur'] == 'sav@izivia.com') , relations].sort_values(by=["coordonneesXY"])[0:50]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
7066,62740,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10311,2026-03-14,2026-03-14T07:01:14.000000+0000
7067,62741,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10312,2026-03-14,2026-03-14T07:01:14.000000+0000
7068,62742,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10321,2026-03-14,2026-03-14T07:01:14.000000+0000
7069,62743,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10322,2026-03-14,2026-03-14T07:01:14.000000+0000
1856,16698,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11111,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11111,2025-09-30,2025-09-30T08:35:00.000000+0000
1881,17097,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2831,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2831,2025-09-30,2025-09-30T08:35:00.000000+0000
1882,17098,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2841,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2841,2025-09-30,2025-09-30T08:35:00.000000+0000
1883,17099,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2851,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2851,2025-09-30,2025-09-30T08:35:00.000000+0000
1884,17100,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2861,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2861,2025-09-30,2025-09-30T08:35:00.000000+0000
1885,17101,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2871,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2871,2025-09-30,2025-09-30T08:35:00.000000+0000
1886,17102,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2881,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2881,2025-09-30,2025-09-30T08:35:00.000000+0000
1887,17103,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2891,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2891,2025-09-30,2025-09-30T08:35:00.000000+0000
2057,17716,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4681,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4681,2025-09-30,2025-09-30T08:35:00.000000+0000
2055,17714,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4661,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4661,2025-09-30,2025-09-30T08:35:00.000000+0000
1880,17096,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2821,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2821,2025-09-30,2025-09-30T08:35:00.000000+0000
2054,17713,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4651,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4651,2025-09-30,2025-09-30T08:35:00.000000+0000
2053,17712,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4641,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4641,2025-09-30,2025-09-30T08:35:00.000000+0000
2052,17711,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4631,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4631,2025-09-30,2025-09-30T08:35:00.000000+0000
2051,17710,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4621,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4621,2025-09-30,2025-09-30T08:35:00.000000+0000
2050,17709,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG46101,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG46101,2025-09-30,2025-09-30T08:35:00.000000+0000
2049,17708,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4611,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4611,2025-09-30,2025-09-30T08:35:00.000000+0000
2056,17715,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4671,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4671,2025-09-30,2025-09-30T08:35:00.000000+0000
1879,17095,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG28121,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG28121,2025-09-30,2025-09-30T08:35:00.000000+0000
2058,17717,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4691,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4691,2025-09-30,2025-09-30T08:35:00.000000+0000
1877,17093,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG28101,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG28101,2025-09-30,2025-09-30T08:35:00.000000+0000
1859,16701,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11331,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11331,2025-09-30,2025-09-30T08:35:00.000000+0000
1858,16700,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11221,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11221,2025-09-30,2025-09-30T08:35:00.000000+0000
1857,16699,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG111101,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG111101,2025-09-30,2025-09-30T08:35:00.000000+0000
1878,17094,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG28111,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG28111,2025-09-30,2025-09-30T08:35:00.000000+0000
1861,16703,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11551,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11551,2025-09-30,2025-09-30T08:35:00.000000+0000
1862,16704,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11661,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11661,2025-09-30,2025-09-30T08:35:00.000000+0000
1863,16705,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11771,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11771,2025-09-30,2025-09-30T08:35:00.000000+0000
1864,16706,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11881,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11881,2025-09-30,2025-09-30T08:35:00.000000+0000
1865,16707,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11991,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11991,2025-09-30,2025-09-30T08:35:00.000000+0000
1866,17077,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2711,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2711,2025-09-30,2025-09-30T08:35:00.000000+0000
1867,17078,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG27101,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG27101,2025-09-30,2025-09-30T08:35:00.000000+0000
1868,17079,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2721,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2721,2025-09-30,2025-09-30T08:35:00.000000+0000
1860,16702,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11441,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11441,2025-09-30,2025-09-30T08:35:00.000000+0000
1869,17080,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2731,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2731,2025-09-30,2025-09-30T08:35:00.000000+0000
1871,17082,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2751,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2751,2025-09-30,2025-09-30T08:35:00.000000+0000
1876,17092,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2811,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2811,2025-09-30,2025-09-30T08:35:00.000000+0000
1875,17086,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2791,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2791,2025-09-30,2025-09-30T08:35:00.000000+0000
1874,17085,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2781,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2781,2025-09-30,2025-09-30T08:35:00.000000+0000
1873,17084,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2771,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2771,2025-09-30,2025-09-30T08:35:00.000000+0000
1870,17081,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2741,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2741,2025-09-30,2025-09-30T08:35:00.000000+0000
1872,17083,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2761,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2761,2025-09-30,2025-09-30T08:35:00.000000+0000
2135,19869,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37291,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37291,2025-09-30,2025-09-30T08:35:00.000000+0000
2134,19868,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37281,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37281,2025-09-30,2025-09-30T08:35:00.000000+0000
2133,19867,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37271,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37271,2025-09-30,2025-09-30T08:35:00.000000+0000
2126,19860,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372111,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372111,2025-09-30,2025-09-30T08:35:00.000000+0000

In [222]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-0.530598, 47.398424]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Defauts operateur ENIplenitude
Les défauts (200 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Ionity en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance ainsi qu'un ancien pdc de regroupement par station avec un nom d'enseigne différent (IONITY GMBH), ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur l'aire de Mornas [4.732409, 44.194832], on trouve 26 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué de 23 pour chaque station.

In [223]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'support@service.emob.eniplenitude.com', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [224]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRPLNEH002131', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Defauts operateur MOBILIZE
Les défauts (350 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

In [225]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'fastcharge.exploitation@mobilize.com', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [226]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRMFCEALBERTVILLE', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Cohérence implantation_station - id_station
- 107 pdc sont liés à une erreur de choix d'implantation (couplé à d'autres erreurs)

In [227]:
itinerance_4.loc[~itinerance_4['implantation_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
724,9870,irve@soregies.fr,SOREGIES MOBILITES,"[0.35768, 46.51348]",Rue des Quatres Assiettes,FRLMSE1234705061,SMARVES_QUATRE ASSIETTES,Station dédiée à la recharge rapide,1,Accès libre,24/7,false,FRLMSE12347050611,2025-05-06,2026-01-16T15:33:12.000000+0000
725,9871,irve@soregies.fr,SOREGIES MOBILITES,"[0.35768, 46.51348]",Rue des Quatres Assiettes,FRLMSE1234705061,SMARVES_QUATRE ASSIETTES,Station dédiée à la recharge rapide,1,Accès libre,24/7,false,FRLMSE12347050612,2025-05-06,2026-01-16T15:33:12.000000+0000
726,9872,irve@soregies.fr,SOREGIES MOBILITES,"[0.35768, 46.51348]",Rue des Quatres Assiettes,FRLMSE1234705061,SMARVES_QUATRE ASSIETTES,Voirie,1,Accès libre,24/7,false,FRLMSE12347050613,2025-05-06,2026-01-16T15:33:12.000000+0000
765,10242,irve@soregies.fr,SOREGIES MOBILITES,"[0.36708, 46.45444]",D741,FRLMSE1234708249,LA VILLEDIEU DU CLAIN_D741,Station dédiée à la recharge rapide,1,Accès libre,24/7,false,FRLMSE12347082491,2025-06-13,2026-01-16T15:33:12.000000+0000
766,10243,irve@soregies.fr,SOREGIES MOBILITES,"[0.36708, 46.45444]",D741,FRLMSE1234708249,LA VILLEDIEU DU CLAIN_D741,Station dédiée à la recharge rapide,1,Accès libre,24/7,false,FRLMSE12347082492,2025-06-13,2026-01-16T15:33:12.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5843,52337,support@alizecharge.fr,ADP Groupe,"[2.36698, 48.72946]","P4b Parking, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Voirie,12,Accès libre,Mo-Su 00:00-23:57,false,FRADPE914790152,2026-03-09,2026-03-09T15:02:55.000000+0000
5844,52344,support@alizecharge.fr,Saemes,"[2.34587, 48.87677]","1 Rue Mayran, 75009 PARIS",FRSAEE75109002,SAEMES - Parking Montholon,Voirie,17,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE7510900215,2026-03-09,2026-03-09T15:02:55.000000+0000
5846,52352,support@alizecharge.fr,Saemes,"[2.34587, 48.87677]","1 Rue Mayran, 75009 PARIS",FRSAEE75109002,SAEMES - Parking Montholon,Voirie,17,Accès libre,Mo-Su 00:00-23:57,false,FRSAEE7510900218,2026-03-09,2026-03-09T15:02:55.000000+0000
6657,56555,support@alizecharge.fr,Alizé Liberté 2,"[4.35704, 48.95777]","Rue des Viviers, 51000 CHÂLONS-EN-CHAMPAGNE",FRBE3E51108001,CHÂLONS - GHV,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRBE3E511080012,2026-03-09,2026-03-09T15:02:55.000000+0000
6818,60083,support@alizecharge.fr,Alizé Liberté 2,"[4.35704, 48.95777]","Rue des Viviers, 51000 CHÂLONS-EN-CHAMPAGNE",FRBE3E51108001,CHÂLONS - GHV,Parking public,3,Accès libre,Mo-Su 00:00-23:57,false,FRBE3E511080013,2026-03-09,2026-03-09T15:02:55.000000+0000

### Cohérence nom_station - id_station
- 210 pdc sont associés à une station avec un nom non cohérent

In [228]:
itinerance_4.loc[~itinerance_4['nom_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
26,271,contact@gmob.fr,GMOB,"[-61.51535, 16.25467]","Crédit agricole Mutuel de Guadeloupe, Petit-Pé...",FRGOBPCAMGPETITPEROU,SIEGE SOCIAL DU CREDIT AGRICOLE MUTUEL DE GUA...,Parking privé à usage public,16,Accès libre,Mo-Sa 06:00-20:00,false,FRGOBEE622321,2024-11-29,2024-06-14T07:23:10.000000+0000
27,272,contact@gmob.fr,GMOB,"[-61.51535, 16.25467]","Crédit agricole Mutuel de Guadeloupe, Petit-Pé...",FRGOBPCAMGPETITPEROU,SIEGE SOCIAL DU CREDIT AGRICOLE MUTUEL DE GUAD...,Parking privé à usage public,16,Accès libre,Mo-Sa 06:00-20:00,false,FRGOBEE622322,2024-11-29,2024-06-14T07:23:10.000000+0000
28,273,contact@gmob.fr,GMOB,"[-61.51535, 16.25467]","Crédit agricole Mutuel de Guadeloupe, Petit-Pé...",FRGOBPCAMGPETITPEROU,SIEGE SOCIAL DU CREDIT AGRICOLE MUTUEL DE GUA...,Parking privé à usage public,16,Accès libre,Mo-Sa 06:00-20:00,false,FRGOBEE62231,2024-11-29,2024-06-14T07:23:10.000000+0000
29,274,contact@gmob.fr,GMOB,"[-61.51535, 16.25467]","Crédit agricole Mutuel de Guadeloupe, Petit-Pé...",FRGOBPCAMGPETITPEROU,SIEGE SOCIAL DU CREDIT AGRICOLE MUTUEL DE GUAD...,Parking privé à usage public,16,Accès libre,Mo-Sa 06:00-20:00,false,FRGOBEE622332,2024-11-29,2024-06-14T07:23:10.000000+0000
30,275,contact@gmob.fr,GMOB,"[-61.51535, 16.25467]","Crédit agricole Mutuel de Guadeloupe, Petit-Pé...",FRGOBPCAMGPETITPEROU,SIEGE SOCIAL DU CREDIT AGRICOLE MUTUEL DE GUA...,Parking privé à usage public,16,Accès libre,Mo-Sa 06:00-20:00,false,FRGOBEE622341,2024-11-29,2024-06-14T07:23:10.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7997,76480,sav@izivia.com,QPARK,"[48.88984, 2.39401]",221 Avenue Jean Jaurès 75019 Paris,FRQPKPQPRK82,QPARK - 75040 PARIS - VILLETTE MUSIQUE,Voirie,20,Accès libre,24/7,false,FRQPKEQPRK8201,2026-03-14,2026-03-14T07:00:49.000000+0000
7998,76498,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8211,2026-03-14,2026-03-14T07:00:49.000000+0000
7999,76499,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8221,2026-03-14,2026-03-14T07:00:49.000000+0000
8000,76500,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8231,2026-03-14,2026-03-14T07:00:49.000000+0000
8001,76501,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8241,2026-03-14,2026-03-14T07:00:49.000000+0000

### Coherence adresse - coordonnees
- 2337 pdc ont une adresse non cohérente avec les coordonnées géographiques

In [229]:
itinerance_4.loc[~itinerance_4['adresse_station - coordonneesXY'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
0,52,contact@sevdec.com,Réseau de recharge DIFFUSION PLUS,"[49.13723, 1.31336]","Zac des, 1 Les Champs Chouette 27600 Saint Aub...",FRSEVP1M2050,M2050,Parking privé à usage public,3,Accès libre,Lun-Ven : 08:00-18:00,false,FRSEVE1M205001,2022-02-18,2025-10-09T13:08:46.000000+0000
1,53,contact@sevdec.com,Réseau de recharge DIFFUSION PLUS,"[49.13723, 1.31336]","Zac des, 1 Les Champs Chouette 27600 Saint Aub...",FRSEVP1M2050,M2050,Parking privé à usage public,3,Accès libre,Lun-Ven : 08:00-18:00,false,FRSEVE1M205002,2022-02-18,2025-10-09T13:08:46.000000+0000
2,54,contact@sevdec.com,Réseau de recharge DIFFUSION PLUS,"[49.13723, 1.31336]","Zac des, 1 Les Champs Chouette 27600 Saint Aub...",FRSEVP1M2050,M2050,Parking privé à usage public,3,Accès libre,Lun-Ven : 08:00-18:00,false,FRSEVE1M205003,2022-02-18,2025-10-09T13:08:46.000000+0000
3,55,contact@sevdec.com,Réseau de recharge DIFFUSION PLUS,"[49.13723, 1.31336]","Zac des, 1 Les Champs Chouette 27600 Saint Aub...",FRSEVP1M2051,M2051,Parking privé à usage public,3,Accès libre,Lun-Ven : 08:00-18:00,false,FRSEVE1M205101,2022-02-18,2025-10-09T13:08:46.000000+0000
4,56,contact@sevdec.com,Réseau de recharge DIFFUSION PLUS,"[49.13723, 1.31336]","Zac des, 1 Les Champs Chouette 27600 Saint Aub...",FRSEVP1M2051,M2051,Parking privé à usage public,3,Accès libre,Lun-Ven : 08:00-18:00,false,FRSEVE1M205102,2022-02-18,2025-10-09T13:08:46.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12468,148670,info@chargeguru.com,AUDI Volkswagen Skoda Trignac - 44570 - 2,"[-2.18555, 47.32332]","4 Route de Lonce, 44570 Trignac",FRCG0E003128,AUDI Volkswagen Skoda Trignac - 44570 - 2,Station dédiée à la recharge rapide,6,Accès réservé,24/7,false,FRCG0E003128,2026-03-13,2026-03-13T20:00:21.000000+0000
12469,148671,info@chargeguru.com,AUDI Volkswagen Skoda Trignac - 44570 - 2,"[-2.18555, 47.32332]","4 Route de Lonce, 44570 Trignac",FRCG0E003129,AUDI Volkswagen Skoda Trignac - 44570 - 2,Station dédiée à la recharge rapide,6,Accès réservé,24/7,false,FRCG0E003129,2026-03-13,2026-03-13T20:00:21.000000+0000
12470,148672,info@chargeguru.com,AUDI Volkswagen Skoda Trignac - 44570 - 2,"[-2.18555, 47.32332]","4 Route de Lonce, 44570 Trignac",FRCG0E003130,AUDI Volkswagen Skoda Trignac - 44570 - 2,Station dédiée à la recharge rapide,6,Accès réservé,24/7,false,FRCG0E003130,2026-03-13,2026-03-13T20:00:21.000000+0000
12471,148673,info@chargeguru.com,AUDI Volkswagen Skoda Trignac - 44570 - 2,"[-2.18555, 47.32332]","4 Route de Lonce, 44570 Trignac",FRCG0EE003131,AUDI Volkswagen Skoda Trignac - 44570 - 2,Voirie,6,Accès réservé,24/7,false,FRCG0EE003131,2026-03-13,2026-03-13T20:00:21.000000+0000
12472,149283,dsa@porsche.de,Porsche Sales & Marketplace Centre Porsche Rei...,"[4.08208, 49.23697]","Rue Léna Bernstein 12, 51100 Reims",FR911EFR00045100000010000001,Porsche Sales & Marketplace Centre Porsche Rei...,Station dédiée à la recharge rapide,1,Accès réservé,"We 08:30-18:30,Mo 08:30-18:30,Th 08:30-18:30,S...",false,FR911EFR00045100000010000001,2026-03-13,2026-03-13T20:00:21.000000+0000

In [230]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[5.2592028, 46.1746523]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [231]:
itinerance_4.loc[itinerance_4.adresse_station == 'RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
704,9811,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.000000+0000
707,9814,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.000000+0000

In [232]:
itinerance_4.loc[itinerance_4.adresse_station == ' RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
705,9812,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.000000+0000
706,9813,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.000000+0000

### Cohérence station - coordonnées
- 218 pdc sont associés à des stations avec plusieurs coordonnées (majorité AlizeCharge)

In [233]:
itinerance_4.loc[~itinerance_4['coordonneesXY - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
24,176,contact@sevdec.com,Réseau de recharge SEVDEC,"[49.46669, 1.13870]",296 Av. des Hauts Grigneux 76420 Bihorel,FRSEVP1MCB2035,MCB2035,Parking privé à usage public,3,Accès libre,Lun-Ven : 07:30-18:00;Sam : 09:00-18:00,false,FRSEVE1MCB2035,2024-01-01,2025-10-09T13:08:46.000000+0000
25,181,contact@sevdec.com,Réseau de recharge SEVDEC,"[49.33108, 1.10177]",1 Rue Parc en Seine 76410 Tourville-la-Rivière,FRSEVP1MCB2035,MCB2035,Parking privé à usage public,3,Accès libre,24/7,false,FRSEVE1MCB2033,2024-01-01,2025-10-09T13:08:46.000000+0000
64,1317,support@evzen.com,Simone,"[4.42714, 43.45753]",Rue Des Artisans - Borne 1 13460 SAINTES-MARIE...,FRS13PHT2TOP3OOS,"Stes-Maries-De-La-Mer, Rue Des Artisans",Voirie,4,Accès libre,24/7,false,FRS13EEKLK1,2023-05-01,2024-12-06T06:46:18.000000+0000
65,1318,support@evzen.com,Simone,"[4.42714, 43.45753]",Rue Des Artisans - Borne 1 13460 SAINTES-MARIE...,FRS13PHT2TOP3OOS,"Stes-Maries-De-La-Mer, Rue Des Artisans",Voirie,4,Accès libre,24/7,false,FRS13EEKLK2,2023-05-01,2024-12-06T06:46:18.000000+0000
66,1319,support@evzen.com,Simone,"[4.42708, 43.45751]",Rue Des Artisans - Borne 2 13460 SAINTES-MARIE...,FRS13PHT2TOP3OOS,"Stes-Maries-De-La-Mer, Rue Des Artisans",Voirie,4,Accès libre,24/7,false,FRS13EFMWB1,2023-05-01,2024-12-06T06:46:18.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7997,76480,sav@izivia.com,QPARK,"[48.88984, 2.39401]",221 Avenue Jean Jaurès 75019 Paris,FRQPKPQPRK82,QPARK - 75040 PARIS - VILLETTE MUSIQUE,Voirie,20,Accès libre,24/7,false,FRQPKEQPRK8201,2026-03-14,2026-03-14T07:00:49.000000+0000
7998,76498,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8211,2026-03-14,2026-03-14T07:00:49.000000+0000
7999,76499,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8221,2026-03-14,2026-03-14T07:00:49.000000+0000
8000,76500,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8231,2026-03-14,2026-03-14T07:00:49.000000+0000
8001,76501,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8241,2026-03-14,2026-03-14T07:00:49.000000+0000

In [234]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRTLSE31555040', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [235]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRFR1PEHNKRRPQNR', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : une station avec plusieurs coordonnées -> incompréhension distinction station / pdc

In [236]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR073PCAMAIEUFR', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
549,8390,acelec@acelec-france.com,Camaïeu France,"[3.20743, 50.68487]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EREUO5946,2022-07-21,2024-12-06T06:46:31.000000+0000
550,8391,acelec@acelec-france.com,Camaïeu France,"[3.20743, 50.68487]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EQ1GI51176,2022-07-21,2024-12-06T06:46:31.000000+0000
551,8392,acelec@acelec-france.com,Camaïeu France,"[3.20737, 50.68489]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ECC1C5530,2022-07-21,2024-12-06T06:46:31.000000+0000
552,8393,acelec@acelec-france.com,Camaïeu France,"[3.20737, 50.68489]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EO0AV51091,2022-07-21,2024-12-06T06:46:31.000000+0000
553,8394,acelec@acelec-france.com,Camaïeu France,"[3.20730, 50.68491]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EK0BJ522,2022-07-21,2024-12-06T06:46:31.000000+0000
554,8395,acelec@acelec-france.com,Camaïeu France,"[3.20730, 50.68491]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E0HKH51125,2022-07-21,2024-12-06T06:46:31.000000+0000
555,8396,acelec@acelec-france.com,Camaïeu France,"[3.20724, 50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E8OV45243,2022-07-21,2024-12-06T06:46:31.000000+0000
556,8397,acelec@acelec-france.com,Camaïeu France,"[3.20724, 50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EYLF65474,2022-07-21,2024-12-06T06:46:31.000000+0000
557,8398,acelec@acelec-france.com,Camaïeu France,"[3.20718, 50.68496]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ETCIX5105,2022-07-21,2024-12-06T06:46:31.000000+0000
558,8399,acelec@acelec-france.com,Camaïeu France,"[3.20718, 50.68496]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP7QU5233,2022-07-21,2024-12-06T06:46:31.000000+0000
559,8400,acelec@acelec-france.com,Camaïeu France,"[3.20712, 50.68498]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EU6RQ5270,2022-07-21,2024-12-06T06:46:31.000000+0000
560,8401,acelec@acelec-france.com,Camaïeu France,"[3.20712, 50.68498]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EBEQA5957,2022-07-21,2024-12-06T06:46:31.000000+0000
561,8402,acelec@acelec-france.com,Camaïeu France,"[3.20704, 50.68501]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EMZLV5283,2022-07-21,2024-12-06T06:46:31.000000+0000
562,8403,acelec@acelec-france.com,Camaïeu France,"[3.20704, 50.68501]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EUHNJ5886,2022-07-21,2024-12-06T06:46:31.000000+0000
563,8404,acelec@acelec-france.com,Camaïeu France,"[3.20696, 50.68504]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP9LD51287,2022-07-21,2024-12-06T06:46:31.000000+0000
564,8405,acelec@acelec-france.com,Camaïeu France,"[3.20696, 50.68504]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EXINB5826,2022-07-21,2024-12-06T06:46:31.000000+0000

- exemple : une station avec plusieurs coordonnées -> regroupement de stations ?

In [237]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR55CPBP514', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : plusieurs stations d'opérateurs différents avec les mêmes coordonnées -> suppression non effectuée lors d'un changement d'opérateur ?

In [238]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[0.08745032, 48.40887156]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [239]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-4.374469, 48.471878]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : quatre stations avec une localisation identique mais deux adresses différentes + id identique entre station et pdc -> erreur d'adresse et erreur d'id_station ?

In [240]:
itinerance_5.loc[itinerance_5.coordonneesXY	 == '[-0.366184, 43.332508]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Incoherence nbre_pdc
- 583 pdc ont un champ 'nbre_pdc' mal documenté

In [241]:
itinerance_4.loc[~itinerance_4['nbre_pdc - id_station_itinerance'], relations][200:215]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1265,12777,bornes@lidl.fr,LIDL,"[-0.67043, 44.83881]",8 Avenue Jean Perrin,FRLDLPLFR2826EVCP,BDX Merignac,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003568,2025-12-11,2025-12-17T09:36:45.000000+0000
1282,12828,bornes@lidl.fr,LIDL,"[1.50877, 45.15328]",39 avenue Abbé Jean Alvitre,FRLDLPLFR3436EVCP,BRIVE ALVITRE,Parking privé à usage public,2,Accès libre,24/7,false,FRLDLE00006633,2025-12-11,2025-12-17T09:36:45.000000+0000
1283,12829,bornes@lidl.fr,LIDL,"[1.50877, 45.15328]",39 avenue Abbé Jean Alvitre,FRLDLPLFR3436EVCP,BRIVE ALVITRE,Parking privé à usage public,2,Accès libre,24/7,false,FRLDLE00006634,2025-12-11,2025-12-17T09:36:45.000000+0000
1292,12861,bornes@lidl.fr,LIDL,"[3.39327, 46.15674]",12 route de Saint Pourçain,FRLDLPLFR2970EVCP,CHARMEIL Pourçain,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00003131,2025-12-11,2025-12-17T09:36:45.000000+0000
1293,12862,bornes@lidl.fr,LIDL,"[3.39327, 46.15674]",12 route de Saint Pourçain,FRLDLPLFR2970EVCP,CHARMEIL Pourçain,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00003232,2025-12-11,2025-12-17T09:36:45.000000+0000
1294,12863,bornes@lidl.fr,LIDL,"[3.39327, 46.15674]",12 route de Saint Pourçain,FRLDLPLFR2970EVCP,CHARMEIL Pourçain,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00003233,2025-12-11,2025-12-17T09:36:45.000000+0000
1295,12864,bornes@lidl.fr,LIDL,"[3.39327, 46.15674]",12 route de Saint Pourçain,FRLDLPLFR2970EVCP,CHARMEIL Pourçain,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00003234,2025-12-11,2025-12-17T09:36:45.000000+0000
1296,12865,bornes@lidl.fr,LIDL,"[3.39327, 46.15674]",12 route de Saint Pourçain,FRLDLPLFR2970EVCP,CHARMEIL Pourçain,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00003235,2025-12-11,2025-12-17T09:36:45.000000+0000
1297,12866,bornes@lidl.fr,LIDL,"[3.39327, 46.15674]",12 route de Saint Pourçain,FRLDLPLFR2970EVCP,CHARMEIL Pourçain,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00003236,2025-12-11,2025-12-17T09:36:45.000000+0000
1350,13054,bornes@lidl.fr,LIDL,"[2.18627, 49.00163]",4 René Coty,FRLDLPLFR3959EVCP,HERBLAY - Coty,Parking privé à usage public,10,Accès libre,24/7,false,FRLDLE00002105,2025-12-11,2025-12-17T09:36:45.000000+0000
1351,13055,bornes@lidl.fr,LIDL,"[2.18627, 49.00163]",4 René Coty,FRLDLPLFR3959EVCP,HERBLAY - Coty,Parking privé à usage public,10,Accès libre,24/7,false,FRLDLE00002106,2025-12-11,2025-12-17T09:36:45.000000+0000
1352,13056,bornes@lidl.fr,LIDL,"[2.18627, 49.00163]",4 René Coty,FRLDLPLFR3959EVCP,HERBLAY - Coty,Parking privé à usage public,10,Accès libre,24/7,false,FRLDLE00002107,2025-12-11,2025-12-17T09:36:45.000000+0000
1353,13057,bornes@lidl.fr,LIDL,"[2.18627, 49.00163]",4 René Coty,FRLDLPLFR3959EVCP,HERBLAY - Coty,Parking privé à usage public,10,Accès libre,24/7,false,FRLDLE00002108,2025-12-11,2025-12-17T09:36:45.000000+0000
1354,13058,bornes@lidl.fr,LIDL,"[2.18627, 49.00163]",4 René Coty,FRLDLPLFR3959EVCP,HERBLAY - Coty,Parking privé à usage public,10,Accès libre,24/7,false,FRLDLE00002109,2025-12-11,2025-12-17T09:36:45.000000+0000
1355,13059,bornes@lidl.fr,LIDL,"[2.18627, 49.00163]",4 René Coty,FRLDLPLFR3959EVCP,HERBLAY - Coty,Parking privé à usage public,10,Accès libre,24/7,false,FRLDLE00002110,2025-12-11,2025-12-17T09:36:45.000000+0000

### coherence station - enseigne
- 5 stations ont plusieurs noms d'enseigne

In [242]:
itinerance_4.loc[~itinerance_4['nom_enseigne - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
689,9208,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.000000+0000
690,9209,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.000000+0000
691,9210,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS3,2022-10-04,2024-12-06T06:49:29.000000+0000
1765,15099,contact@rirodo.fr,LAST MILES SOLUTIONS,"[43.27000, 5.39000]",20 Rue Negresko,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRLMSE1897228,2023-09-06,2024-12-06T06:47:15.000000+0000
1766,15100,contact@rirodo.fr,MONTA,"[43.27000, 5.39000]",20 Rue NEGRESKO,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRRIRE2804856,2023-09-06,2024-12-06T06:47:15.000000+0000
7176,69195,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[49.27090, -0.70025]","\t16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,\t\tScauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",false,FRMBZESMYQC1,2024-06-03,2026-03-13T17:35:48.000000+0000
7177,69197,support@mobilize-ps.fr,BODEMER BAYEUX,"[49.27084, -0.70022]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,BODEMER Bayeux,Parking privé à usage public,1,Accès libre,24/7,false,FRMBZESMYCQ1,2024-06-03,2026-03-13T17:35:48.000000+0000

In [243]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRFR1EAYRU', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
9173,9186,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.000000+0000
9174,9187,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.000000+0000
9175,9188,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS3,2022-12-09,2024-12-06T06:49:25.000000+0000
9306,9319,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.000000+0000
9307,9320,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.000000+0000
9308,9321,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU3,2022-08-25,2024-12-06T06:49:41.000000+0000

In [244]:
itinerance_init.loc[itinerance_init.nom_enseigne == 'RME Loos (FR-FR1)', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
9173,9186,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.000000+0000
9174,9187,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.000000+0000
9195,9208,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.000000+0000
9196,9209,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.000000+0000
9306,9319,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.000000+0000
9307,9320,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.000000+0000

### cohérence station - horaires
- exemple de station avec plusieurs types d'horaire (15)

In [245]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRS23D2302001', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3786,3794,contact@mobive.fr,Réseau MOBIVE,"[45.98220, 2.29763]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:01,false,FRS23P230200101,2023-03-09,2025-09-11T07:22:20.000000+0000
3787,3795,contact@mobive.fr,Réseau MOBIVE,"[45.98220, 2.29763]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:02,false,FRS23P230200102,2023-03-09,2025-09-11T07:22:20.000000+0000

### cohérence station - deux-roues
- exemple de station avec plusieurs indications d'accessibilité deux-roues (583)

In [246]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRV75PPX1716', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
108339,108515,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17165,2025-06-30,2026-03-13T23:59:49.000000+0000
108341,108517,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17167,2025-06-30,2026-03-13T23:59:49.000000+0000
110098,110274,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17162,2025-06-30,2026-03-13T23:59:49.000000+0000
110101,110277,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17163,2025-06-30,2026-03-13T23:59:49.000000+0000
114786,114962,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17164,2025-06-30,2026-03-13T23:59:49.000000+0000
135521,135697,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17161,2025-06-30,2026-03-13T23:59:49.000000+0000
144011,144187,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17166,2025-06-30,2026-03-13T23:59:49.000000+0000

### stations avec pdc > 350 kW

- exemple de station avec une puissance de plus de 350 kW

In [247]:
data['p_nom'] = data['puissance_nominale'].str.replace(",", ".")

In [248]:
data['p_nom'] = data['p_nom'].astype('float')

In [249]:
from copy import copy
data350 = copy(data.loc[data["p_nom"] > 350, :])

In [250]:
data350['index'] = 0

In [251]:
data350.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5891,0,contact@sowattsolutions.com,SOWATT SOLUTIONS,"[6.07734, 45.88929]",268 Route des Creuses 74600 Seynod,FRSWSE1000149991,ABB T360 VW Seynod 1,Station dédiée à la recharge rapide,2,Accès libre,24/7,false,FRSWSE10001499913,2025-11-12,2025-11-12T14:07:06.000000+0000
8384,0,support@greenflux.com,ENGIE Vianeo,"[4.76994, 45.80439]",Aire de Dardilly Energies PL - 69570 Dardilly,FRVIAP152004,ENGIE Vianeo - Station multi-énergies Dardilly PL,Station dédiée à la recharge rapide,1,Accès libre,24/7,false,FRVIAE20152003061,2026-01-05,2026-01-22T13:17:52.000000+0000
8385,0,support@greenflux.com,ENGIE Vianeo,"[4.76994, 45.80439]",Aire de Dardilly Energies PL - 69570 Dardilly,FRVIAP152004,ENGIE Vianeo - Station multi-énergies Dardilly PL,Station dédiée à la recharge rapide,1,Accès libre,24/7,false,FRVIAE20152003062,2026-01-05,2026-01-22T13:17:52.000000+0000
8512,0,energy@milence.com,Milence,"[49.19453, 1.22521]",Rte de Louviers 2 Heudebouville,FRMILP000003,Milence Charging Hub Heudebouville,Parking privé à usage public,2,Accès réservé,24/7,false,FRMILE000003,2025-04-18,2025-04-21T03:46:17.000000+0000
8513,0,energy@milence.com,Milence,"[49.19453, 1.22521]",Rte de Louviers 2 Heudebouville,FRMILP000004,Milence Charging Hub Heudebouville,Parking privé à usage public,2,Accès réservé,24/7,false,FRMILE000004,2025-04-18,2025-04-21T03:46:17.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149298,0,contact@enerjump.fr,Watt up by Enerjump - Brive 19-01,"[1.46804, 45.15317]","Rue des Levades 153, 19600 Saint-Pantaléon-de-...",FR190E190001SPE24ABB36012,Watt up by Enerjump - Brive 19-01,Station dédiée à la recharge rapide,4,Accès réservé,24/7,false,FR190E190001SPE24ABB360122,2026-03-13,2026-03-13T20:00:21.000000+0000
149299,0,contact@enerjump.fr,Watt up by Enerjump - Brive 19-01,"[1.46804, 45.15317]","Rue des Levades 153, 19600 Saint-Pantaléon-de-...",FR190E190001SPE24ABB36034,Watt up by Enerjump - Brive 19-01,Station dédiée à la recharge rapide,4,Accès réservé,24/7,false,FR190E190001SPE24ABB360341,2026-03-13,2026-03-13T20:00:21.000000+0000
149300,0,contact@enerjump.fr,Watt up by Enerjump - Brive 19-01,"[1.46804, 45.15317]","Rue des Levades 153, 19600 Saint-Pantaléon-de-...",FR190E190001SPE24ABB36034,Watt up by Enerjump - Brive 19-01,Station dédiée à la recharge rapide,4,Accès réservé,24/7,false,FR190E190001SPE24ABB360342,2026-03-13,2026-03-13T20:00:21.000000+0000
149303,0,contact@enerjump.fr,Watt up by Enerjump - Compans 77-01,"[2.64826, 48.99121]","rue elisabeth bosseli Département 9, 77290 Com...",FR190E770001SPE24ALP40012,Watt up by Enerjump - Compans 77-01,Station dédiée à la recharge rapide,4,Accès réservé,24/7,false,FR190E770001SPE24ALP400121,2026-03-13,2026-03-13T20:00:21.000000+0000
149304,0,contact@enerjump.fr,Watt up by Enerjump - Compans 77-01,"[2.64826, 48.99121]","rue elisabeth bosseli Département 9, 77290 Com...",FR190E770001SPE24ALP40012,Watt up by Enerjump - Compans 77-01,Station dédiée à la recharge rapide,4,Accès réservé,24/7,false,FR190E770001SPE24ALP400122,2026-03-13,2026-03-13T20:00:21.000000+0000

In [252]:
data350['contact_operateur'].unique()

array(['contact@sowattsolutions.com', 'support@greenflux.com',
       'energy@milence.com', 'irve@soregies.fr', 'roaming@zunder.com',
       'support@voltalia-mobility.com', 'exploitation.irve@picoty.fr',
       'roaming-dev@road.io', 'support@mobilize-ps.fr',
       'contact@ze-watt.com', 'info@ionity.eu', 'contact@lidl.fr',
       'bppulsefranceops@bp.com', 'support.vianeo@engie.com',
       'malek@autorecharge.fr', 'kg@lastmilesolutions.com',
       'help@go-electra.com', 'support@alizecharge.fr',
       'support@oreve.com', 'support@iecharge.io',
       'supervision-ev.france@totalenergies.com',
       'fabien.lepeytre@allego.eu', 'support.france@atlante.energy',
       'support@fastned.nl', 'noc@milence.com',
       'support@service.emob.eniplenitude.com',
       'charging-france@tesla.com', 'contact@enerjump.fr'], dtype=object)