## *Jeu de données IRVE*
-------------------
# Analyse des relations entre champs (intégrité des données)
------------------------------
## Contexte
- clarification du rôle des modèles de données dans les jeux de données (cf mise à jour récente des [guides data.gouv](https://guides.etalab.gouv.fr/qualite/documenter-les-donnees/))
- intégration d'une propriété "relationship" dans les schémas de données ([issue TableSchema](https://github.com/frictionlessdata/specs/issues/803) en cours de validation)
- création d'outils de contrôle des relations entre champs des jeux de données tabulaires (cf usage ci-dessous)

## Objectifs
- valider sur un cas réel l'utilisation d'un modèle de données en complément d'un schéma de données
- identifier les apports que pourraient avoir les contrôles de validation des relations entre champs

## Résultats
- les principaux résultats sont regroupés sur un [tableau de bord](https://nbviewer.org/github/loco-philippe/Environmental-Sensing/blob/main/python/Validation/irve/Analyse/IRVE_indicateurs.ipynb) 
- la formalisation d'un modèle de données facilite la compréhension des données et des relations entre champs
- l'outil de contrôle permet d'améliorer significativement la qualité des données par l'identification d'incohérences de relations
- l'identification des incohérences permet de trouver des stratégies de réduction des écarts (dans l'exemple ci-dessous, on passe 36% d'écart à 3,8 %)  
- l'analyse des données permet de (re)construire le modèle de données qui minimise les incohérences
- les incohérences détectées sur le jeu de données IRVE restent faibles (inférieures à 5 % des point de charge documentés - voir chapitre 4)

## Suite à donner
- Mettre à jour, valider et publier le modèle de données IRVE
- Définir les contrôles supplémentaires à intégrer pour toutes nouvelles données ainsi que pour le jeu complet
- Mettre en oeuvre les outils de contrôle

## Evolutions possibles 
- Ajouter dans les guides d'Etalab un guide pour les modèles de données 
- Intégrer dans les schémas de données la propriété "relationship" en cours de validation,
- Définir un indicateur qui mesure l'écart (existant / attendu) des relations entre champs

## Sommaire
*(liens actifs sur jupyter Notebook ou Nbviewer)*
- [1 - modèle de données](#1---modèle-de-données)
- [2 - Initialisation](#2---Initialisation)
- [3 - Séparation des pdc itinerance et hors itinerance](#3---Séparation-des-pdc-itinerance-et-hors-itinerance)
- [4 - Bilan initial intégrité](#4---Bilan-initial-intégrité)
- [5 - Séparation doublons pdc - date de maj](#5---Séparation-doublons-pdc---date-de-maj)
- [6 - Séparation doublons station - date de maj](#6---Séparation-doublons-station---date-de-maj)
- [7 - Synthèse](#7---Synthèse)
- [8 - Exemples d'erreurs résiduelles](#8---Exemples-d\'erreurs-résiduelles)

Ce Notebook peut être consulté sur [nbviewer](http://nbviewer.org/github/loco-philippe/Environmental-Sensing/tree/main/python/Validation/irve/Analyse)

données utilisées : https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/    
fichier : "*consolidation-etalab-schema-irve-statique-v-2.2.0-2024xxxx.csv*"

-----------------------
# 1 - modèle de données

Le modèle de données proposé ci-dessous est construit sur la base du schéma de données mis à disposition et du contenu du jeu de données.    
Il est à consolider en fonction de l'expertise des concepteurs et réutilisateurs (voir [guide méthodologique](https://github.com/loco-philippe/Environmental-Sensing/blob/main/property_relationship/FR_methodology.ipynb)).

*Notation:*
- *M : Mandatory - documentation obligatoire*
- *PK : Primary Key - identifiant unique de l'entité*
- *Root : champ fictif associé à une ligne du tableau*

In [1]:
from base64 import b64encode
from IPython.display import Image, display
with open('IRVE_modele.txt', 'r', encoding="utf-8") as f:
    modele = f.read()
display(Image(url="https://mermaid.ink/img/" + b64encode(modele.encode("ascii")).decode("ascii")))

------
# 2 - Initialisation
## initialisation logicielle

In [2]:
from datetime import datetime
import json
from tab_dataset import Cdataset
import pandas as pd
import ntv_pandas as npd
import pathlib

def analyse_integrite(data, schema, affiche=True, indic=True):
    '''analyse les relations du DataFrame 'data' définies dans le schéma 'schema'.
    Le nombre de ligne en erreur par relation (dict) est retourné et optionnellement affiché (paramètre 'affiche=True') . 
    Les lignes en erreur sont optionnellement ajoutées (paramètre 'indic=True') à 'data' sous forme de champs booléens par relation.
    '''
    dic_errors = Cdataset(data).check_relationship(schema)
    dic_count = {name: len(errors) for name, errors in dic_errors.items()}
    if affiche:
        for name, total in dic_count.items():
            print('{:<50} {:>5}'.format(name, total))
    if indic:
        data['ok'] = True
        for name, errors in dic_errors.items():
            data[name] = True
            data.loc[errors, name] = False
            data['ok'] = data['ok'] & data[name] 
    return dic_count

def add_nbre_pdc(data, affiche=True):
    '''ajoute un champ avec le nombre de pdc calculés et le compare au champ 'nbre_pdc'
    Le nombre d'écarts est affiché optionnellement (paramètre 'affiche=True').
    '''
    data['nb_pdc_calc'] = data.groupby('id_station_itinerance')['index'].transform('count')
    nbre_pdc = data['nbre_pdc'].astype('int')
    data['nbre_pdc_ok'] = data['nb_pdc_calc'] == nbre_pdc
    data['calc-nbre'] = data['nb_pdc_calc'] - nbre_pdc
    if affiche:
        ecart_nbre = len(data) - data['nbre_pdc_ok'].sum()
        print('{:<20} {:>5}'.format('nbre_pdc_ko', ecart_nbre))
        print(round(ecart_nbre / len(data) * 100), ' %')

## initialisation des données
- lecture du fichier issu de l'api 190 000 lignes (120 000 fin 2024)

In [303]:
dates = ['2023-03-03', '2023-04-17', '2023-05-02', '2023-05-24', '2023-06-17', '2023-07-04', '2023-07-23', '2023-08-08',
         '2023-09-06', '2023-09-19', '2023-10-04', '2023-10-21', '2023-10-31', '2023-11-23', '2023-12-14', '2023-12-29',
         '2024-01-15', '2024-02-07', '2024-02-28', '2024-03-27', '2024-04-24', '2024-05-19', '2024-06-05', '2024-08-02',
         '2024-10-24', '2024-11-27', '2025-01-03', '2025-10-04', '2025-11-18', '2026-02-18', 
         '2026-03-01', # données brutes 28/02
         '2026-04-01'  # données dédoublonnées 28/02
        ]
date= dates[-1]
chemin = str(pathlib.Path(npd.__file__).parent.parent.parent/"Environmental-Sensing"/"python"/"Validation"/"irve"/"Analyse")
log = {'date_irve': date, 
    'file': 'consolidation-etalab-schema-irve-statique-v-2.3.1-'+date[:4]+date[5:7]+date[8:]+'.csv', # après 2024-02-06
    'chemin': chemin
      }
irve = pd.read_csv(log['chemin'] + '/' + log['file'], sep=',', low_memory=False, dtype='object')
log['len_irve'] = len(irve)
print('nombre de lignes : ', log['len_irve'])

nombre de lignes :  148286

In [267]:
file = 'consolidation-etalab-schema-irve-statique-v-2.3.1-'+dates[-2][:4]+dates[-2][5:7]+dates[-2][8:]+'.csv'
irve_brut = pd.read_csv(log['chemin'] + '/' + file, sep=',', low_memory=False, dtype='object')

print('nombre de lignes : ', len(irve_brut))

nombre de lignes :  379946

## données EVZEN

In [304]:
irve.columns

Index(['nom_amenageur', 'siren_amenageur', 'contact_amenageur',
       'nom_operateur', 'contact_operateur', 'telephone_operateur',
       'nom_enseigne', 'id_station_itinerance', 'id_station_local',
       'nom_station', 'implantation_station', 'adresse_station',
       'code_insee_commune', 'coordonneesXY', 'nbre_pdc', 'id_pdc_itinerance',
       'id_pdc_local', 'puissance_nominale', 'prise_type_ef', 'prise_type_2',
       'prise_type_combo_ccs', 'prise_type_chademo', 'prise_type_autre',
       'gratuit', 'paiement_acte', 'paiement_cb', 'paiement_autre',
       'tarification', 'condition_acces', 'reservation', 'horaires',
       'accessibilite_pmr', 'restriction_gabarit', 'station_deux_roues',
       'raccordement', 'num_pdl', 'date_mise_en_service', 'observations',
       'date_maj', 'cable_t2_attache', 'consolidated_longitude',
       'consolidated_latitude', 'datagouv_dataset_id', 'datagouv_resource_id',
       'dataset_title', 'datagouv_organization_or_owner',
       'datagouv_last_modified', 'deduplication_status'],
      dtype='object')

In [268]:
irve_zen = irve[irve['nom_operateur'] == 'EVzen']
len(irve_zen), list(irve_zen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

(1316, ['QualiCharge'])

In [278]:
irve_zen = irve[irve['contact_operateur'] == 'support@evzen.com']
len(irve_zen), list(irve_zen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

(3334, ['evzen (SMEG Développement)', 'GIREVE', 'QualiCharge'])

In [280]:
itinerance_5_full.columns

Index(['index', 'contact_operateur', 'nom_enseigne', 'coordonneesXY',
       'adresse_station', 'id_station_itinerance', 'nom_station',
       'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires',
       'station_deux_roues', 'id_pdc_itinerance', 'date_maj', 'last_modified',
       'ok', 'index - id_pdc_itinerance',
       'contact_operateur - id_station_itinerance',
       'nom_enseigne - id_station_itinerance',
       'coordonneesXY - id_station_itinerance',
       'id_station_itinerance - id_pdc_itinerance',
       'nom_station - id_station_itinerance',
       'implantation_station - id_station_itinerance',
       'nbre_pdc - id_station_itinerance',
       'condition_acces - id_station_itinerance',
       'horaires - id_station_itinerance',
       'station_deux_roues - id_station_itinerance',
       'adresse_station - coordonneesXY', 'principal', 'secondaire', 'verif',
       'nb_pdc_calc', 'nbre_pdc_ok', 'calc-nbre'],
      dtype='object')

In [281]:
erreur_zen = itinerance_5_full[itinerance_5_full['contact_operateur'] ==  'support@evzen.com']

In [301]:
cas_erreur = 'adresse_station - coordonneesXY'
erreur_zen[~erreur_zen[cas_erreur]].sort_values(by=['coordonneesXY'])[0:30]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,...,condition_acces - id_station_itinerance,horaires - id_station_itinerance,station_deux_roues - id_station_itinerance,adresse_station - coordonneesXY,principal,secondaire,verif,nb_pdc_calc,nbre_pdc_ok,calc-nbre
4970,50342,support@evzen.com,EVzen,"[-0.03405, 48.75304]","Rue Maurice Ravel, Argentan 61200 France",FREVZP8717086625871458482,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
4969,50341,support@evzen.com,EVzen,"[-0.03405, 48.75304]","Rue Maurice Ravel, Argentan 61200 France",FREVZP8717086625871458482,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
4968,50340,support@evzen.com,EVzen,"[-0.03405, 48.75304]","Rue Maurice Ravel, Argentan 61200 France",FREVZP8717086625871458482,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
8974,128217,support@evzen.com,EVzen,"[-0.03405, 48.75304]",Rue Maurice Ravel 61200 Argentan,FREVZP3B222B60EC8D4077AB1F1C6D169CB,"EVzen - Argentan, PRIX MIAM Argentan",Station dédiée à la recharge rapide,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
8939,127576,support@evzen.com,EVzen,"[-0.03405, 48.75304]",Rue Maurice Ravel 61200 Argentan,FREVZP3B222B60EC8D4077AB1F1C6D169CB,"EVzen - Argentan, PRIX MIAM Argentan",Station dédiée à la recharge rapide,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
7845,101884,support@evzen.com,EVzen,"[-0.03405, 48.75304]",Rue Maurice Ravel 61200 Argentan,FREVZP3B222B60EC8D4077AB1F1C6D169CB,"EVzen - Argentan, PRIX MIAM Argentan",Station dédiée à la recharge rapide,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
8243,115997,support@evzen.com,EVzen,"[-0.03910, 43.10761]",Avenue Alexandre Marqui 65100 Lourdes,FREVZP5083A7E2A38F4A728AC1E063E1AB7,"EVzen - Lourdes, Feu Vert Lourdes",Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
8022,105363,support@evzen.com,EVzen,"[-0.03910, 43.10761]",Avenue Alexandre Marqui 65100 Lourdes,FREVZP5083A7E2A38F4A728AC1E063E1AB7,"EVzen - Lourdes, Feu Vert Lourdes",Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
7974,103798,support@evzen.com,EVzen,"[-0.03910, 43.10761]",Avenue Alexandre Marqui 65100 Lourdes,FREVZP5083A7E2A38F4A728AC1E063E1AB7,"EVzen - Lourdes, Feu Vert Lourdes",Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
5740,57073,support@evzen.com,EVzen,"[-0.03910, 43.10761]","Avenue Alexandre Marqui, Lourdes 65100 France",FREVZP1293885263679903663,EVzen/5083A7E2-A38F-4A72-8AC1-E063E1AB708E,Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
5742,57075,support@evzen.com,EVzen,"[-0.03910, 43.10761]","Avenue Alexandre Marqui, Lourdes 65100 France",FREVZP1293885263679903663,EVzen/5083A7E2-A38F-4A72-8AC1-E063E1AB708E,Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
5743,57076,support@evzen.com,EVzen,"[-0.03910, 43.10761]","Avenue Alexandre Marqui, Lourdes 65100 France",FREVZP1293885263679903663,EVzen/5083A7E2-A38F-4A72-8AC1-E063E1AB708E,Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
5744,57077,support@evzen.com,EVzen,"[-0.03910, 43.10761]","Avenue Alexandre Marqui, Lourdes 65100 France",FREVZP1293885263679903663,EVzen/5083A7E2-A38F-4A72-8AC1-E063E1AB708E,Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
8000,104664,support@evzen.com,EVzen,"[-0.03910, 43.10761]",Avenue Alexandre Marqui 65100 Lourdes,FREVZP5083A7E2A38F4A728AC1E063E1AB7,"EVzen - Lourdes, Feu Vert Lourdes",Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
5741,57074,support@evzen.com,EVzen,"[-0.03910, 43.10761]","Avenue Alexandre Marqui, Lourdes 65100 France",FREVZP1293885263679903663,EVzen/5083A7E2-A38F-4A72-8AC1-E063E1AB708E,Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
8065,107545,support@evzen.com,EVzen,"[-0.03910, 43.10761]",Avenue Alexandre Marqui 65100 Lourdes,FREVZP5083A7E2A38F4A728AC1E063E1AB7,"EVzen - Lourdes, Feu Vert Lourdes",Parking privé à usage public,5,Accès libre,...,True,True,True,False,True,False,False,5,True,0
4910,50278,support@evzen.com,EVzen,"[-0.09590, 43.00029]","4 Avenue Pierre de Coubertin, Argelès-Gazost 6...",FREVZP7990943664499928953,EVzen/10508f61-0c35-4b1b-bc5e-e72c54de927d,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
7849,101930,support@evzen.com,EVzen,"[-0.09590, 43.00029]",Avenue Pierre de Coubertin 4 65400 Argelès-Gazost,FREVZP10508F610C354B1BBC5EE72C54DE9,"EVzen - Argelès-Gazost, NETTO Argelès-Gazost",Station dédiée à la recharge rapide,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
8005,104818,support@evzen.com,EVzen,"[-0.09590, 43.00029]",Avenue Pierre de Coubertin 4 65400 Argelès-Gazost,FREVZP10508F610C354B1BBC5EE72C54DE9,"EVzen - Argelès-Gazost, NETTO Argelès-Gazost",Station dédiée à la recharge rapide,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
4908,50276,support@evzen.com,EVzen,"[-0.09590, 43.00029]","4 Avenue Pierre de Coubertin, Argelès-Gazost 6...",FREVZP7990943664499928953,EVzen/10508f61-0c35-4b1b-bc5e-e72c54de927d,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
4909,50277,support@evzen.com,EVzen,"[-0.09590, 43.00029]","4 Avenue Pierre de Coubertin, Argelès-Gazost 6...",FREVZP7990943664499928953,EVzen/10508f61-0c35-4b1b-bc5e-e72c54de927d,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
7837,101795,support@evzen.com,EVzen,"[-0.09590, 43.00029]",Avenue Pierre de Coubertin 4 65400 Argelès-Gazost,FREVZP10508F610C354B1BBC5EE72C54DE9,"EVzen - Argelès-Gazost, NETTO Argelès-Gazost",Station dédiée à la recharge rapide,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
4926,50297,support@evzen.com,EVzen,"[-0.12279, 47.23045]","24 Rue du Pavé du Riou, Distré 49400 France",FREVZP1182614901070403361,EVzen/1D9154A5-48C4-4309-9CC6-8CB074D62029,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
4927,50298,support@evzen.com,EVzen,"[-0.12279, 47.23045]","24 Rue du Pavé du Riou, Distré 49400 France",FREVZP1182614901070403361,EVzen/1D9154A5-48C4-4309-9CC6-8CB074D62029,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
4928,50299,support@evzen.com,EVzen,"[-0.12279, 47.23045]","24 Rue du Pavé du Riou, Distré 49400 France",FREVZP1182614901070403361,EVzen/1D9154A5-48C4-4309-9CC6-8CB074D62029,Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
8140,111897,support@evzen.com,EVzen,"[-0.12279, 47.23045]",Rue Du Pavé 24 49400 Distre,FREVZP1D9154A548C443099CC68CB074D62,"EVzen - Distre, BUT Distre",Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
8718,123057,support@evzen.com,EVzen,"[-0.12279, 47.23045]",Rue Du Pavé 24 49400 Distre,FREVZP1D9154A548C443099CC68CB074D62,"EVzen - Distre, BUT Distre",Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
8918,127312,support@evzen.com,EVzen,"[-0.12279, 47.23045]",Rue Du Pavé 24 49400 Distre,FREVZP1D9154A548C443099CC68CB074D62,"EVzen - Distre, BUT Distre",Parking privé à usage public,3,Accès libre,...,True,True,True,False,True,False,False,3,True,0
6258,60000,support@evzen.com,EVzen,"[-0.26598, 49.14980]","Rue du Grand Chemin, Cagny 14630 France",FREVZP3959835251169921994,EVzen/7B938667-9236-449E-9823-D2321551F3B9,Parking privé à usage public,7,Accès libre,...,True,True,True,False,True,False,False,7,True,0
6259,60001,support@evzen.com,EVzen,"[-0.26598, 49.14980]","Rue du Grand Chemin, Cagny 14630 France",FREVZP3959835251169921994,EVzen/7B938667-9236-449E-9823-D2321551F3B9,Parking privé à usage public,7,Accès libre,...,True,True,True,False,True,False,False,7,True,0

In [312]:
irve[irve['coordonneesXY'] == '[-0.03405, 48.75304]'][['nom_amenageur', 'siren_amenageur', 'contact_amenageur',
       'nom_operateur', 'contact_operateur', 'telephone_operateur',
       'nom_enseigne', 'id_station_itinerance', 'id_station_local',
       'nom_station', 'implantation_station', 'adresse_station',
       'code_insee_commune', 'coordonneesXY', 'nbre_pdc', 'id_pdc_itinerance',
       'id_pdc_local', 'puissance_nominale', 'prise_type_ef', 'prise_type_2']]

,nom_amenageur,siren_amenageur,contact_amenageur,nom_operateur,contact_operateur,telephone_operateur,nom_enseigne,id_station_itinerance,id_station_local,nom_station,implantation_station,adresse_station,code_insee_commune,coordonneesXY,nbre_pdc,id_pdc_itinerance,id_pdc_local,puissance_nominale,prise_type_ef,prise_type_2
50340,SMEG Développement,NaN,NaN,GreenFlux Assets B.V. | FR*EVZ,support@evzen.com,NaN,EVzen,FREVZP8717086625871458482,1435792,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,Parking privé à usage public,"Rue Maurice Ravel, Argentan 61200 France",NaN,"[-0.03405, 48.75304]",3,FREVZEKIEU1,3912367,120.000000000000000,false,false
50341,SMEG Développement,NaN,NaN,GreenFlux Assets B.V. | FR*EVZ,support@evzen.com,NaN,EVzen,FREVZP8717086625871458482,1435792,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,Parking privé à usage public,"Rue Maurice Ravel, Argentan 61200 France",NaN,"[-0.03405, 48.75304]",3,FREVZEKIEU2,3912364,120.000000000000000,false,false
50342,SMEG Développement,NaN,NaN,GreenFlux Assets B.V. | FR*EVZ,support@evzen.com,NaN,EVzen,FREVZP8717086625871458482,1435792,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,Parking privé à usage public,"Rue Maurice Ravel, Argentan 61200 France",NaN,"[-0.03405, 48.75304]",3,FREVZELOMA1,3912361,22.000000000000000,false,true
101884,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,"EVzen - Argentan, PRIX MIAM Argentan",Station dédiée à la recharge rapide,Rue Maurice Ravel 61200 Argentan,61006,"[-0.03405, 48.75304]",3,FREVZEFREVZELOMA1,NaN,22.000000000000000,false,true
127576,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,"EVzen - Argentan, PRIX MIAM Argentan",Station dédiée à la recharge rapide,Rue Maurice Ravel 61200 Argentan,61006,"[-0.03405, 48.75304]",3,FREVZEFREVZEKIEU1,NaN,120.000000000000000,false,false
128217,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,"EVzen - Argentan, PRIX MIAM Argentan",Station dédiée à la recharge rapide,Rue Maurice Ravel 61200 Argentan,61006,"[-0.03405, 48.75304]",3,FREVZEFREVZEKIEU2,NaN,120.000000000000000,false,false

In [307]:
irve[irve['coordonneesXY'] == '[-0.03405, 48.75304]'][['nom_amenageur', 'siren_amenageur', 'contact_amenageur',
       'nom_operateur', 'contact_operateur', 'telephone_operateur',
       'nom_enseigne', 'id_station_itinerance', 'id_station_local',
       'nom_station', 'implantation_station', 'adresse_station',
       'code_insee_commune', 'coordonneesXY', 'nbre_pdc', 'id_pdc_itinerance',
       'id_pdc_local', 'puissance_nominale', 'prise_type_ef', 'prise_type_2',
       'prise_type_combo_ccs', 'prise_type_chademo', 'prise_type_autre']]

,nom_amenageur,siren_amenageur,contact_amenageur,nom_operateur,contact_operateur,telephone_operateur,nom_enseigne,id_station_itinerance,id_station_local,nom_station,...,coordonneesXY,nbre_pdc,id_pdc_itinerance,id_pdc_local,puissance_nominale,prise_type_ef,prise_type_2,prise_type_combo_ccs,prise_type_chademo,prise_type_autre
50340,SMEG Développement,NaN,NaN,GreenFlux Assets B.V. | FR*EVZ,support@evzen.com,NaN,EVzen,FREVZP8717086625871458482,1435792,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,...,"[-0.03405, 48.75304]",3,FREVZEKIEU1,3912367,120.000000000000000,false,false,true,false,false
50341,SMEG Développement,NaN,NaN,GreenFlux Assets B.V. | FR*EVZ,support@evzen.com,NaN,EVzen,FREVZP8717086625871458482,1435792,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,...,"[-0.03405, 48.75304]",3,FREVZEKIEU2,3912364,120.000000000000000,false,false,true,false,false
50342,SMEG Développement,NaN,NaN,GreenFlux Assets B.V. | FR*EVZ,support@evzen.com,NaN,EVzen,FREVZP8717086625871458482,1435792,EVzen/3B222B60-EC8D-4077-AB1F-1C6D169CB4B1,...,"[-0.03405, 48.75304]",3,FREVZELOMA1,3912361,22.000000000000000,false,true,false,false,false
101884,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,"EVzen - Argentan, PRIX MIAM Argentan",...,"[-0.03405, 48.75304]",3,FREVZEFREVZELOMA1,NaN,22.000000000000000,false,true,false,false,false
127576,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,"EVzen - Argentan, PRIX MIAM Argentan",...,"[-0.03405, 48.75304]",3,FREVZEFREVZEKIEU1,NaN,120.000000000000000,false,false,true,false,false
128217,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,"EVzen - Argentan, PRIX MIAM Argentan",...,"[-0.03405, 48.75304]",3,FREVZEFREVZEKIEU2,NaN,120.000000000000000,false,false,true,false,false

In [311]:
irve[irve['coordonneesXY'] == '[-0.03405, 48.75304]'][['id_station_itinerance', 'gratuit', 'paiement_acte', 'paiement_cb', 'paiement_autre',
       'tarification', 'condition_acces', 'reservation', 'horaires',
       'accessibilite_pmr', 'restriction_gabarit', 'station_deux_roues',
       'raccordement', 'num_pdl', 'date_mise_en_service', 'observations',
       'date_maj', 'cable_t2_attache', 'consolidated_longitude',
       'consolidated_latitude']]

,id_station_itinerance,gratuit,paiement_acte,paiement_cb,paiement_autre,tarification,condition_acces,reservation,horaires,accessibilite_pmr,restriction_gabarit,station_deux_roues,raccordement,num_pdl,date_mise_en_service,observations,date_maj,cable_t2_attache,consolidated_longitude,consolidated_latitude
50340,FREVZP8717086625871458482,false,true,true,true,NaN,Accès libre,false,24/7,Accessibilité inconnue,Restriction de gabarit non précisée,false,NaN,NaN,NaN,NaN,2025-09-24,NaN,-0.03405,48.75304
50341,FREVZP8717086625871458482,false,true,true,true,NaN,Accès libre,false,24/7,Accessibilité inconnue,Restriction de gabarit non précisée,false,NaN,NaN,NaN,NaN,2025-09-24,NaN,-0.03405,48.75304
50342,FREVZP8717086625871458482,false,true,true,true,NaN,Accès libre,false,24/7,Accessibilité inconnue,Restriction de gabarit non précisée,false,NaN,NaN,NaN,NaN,2025-09-24,NaN,-0.03405,48.75304
101884,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,true,NaN,NaN,NaN,Accès libre,false,24/7,Accessible mais non réservé PMR,Aucune,false,NaN,50078366067890,NaN,NaN,2026-02-27,NaN,-0.03405,48.75304
127576,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,true,NaN,NaN,NaN,Accès libre,false,24/7,Accessible mais non réservé PMR,Aucune,false,NaN,50078366067890,NaN,NaN,2026-02-27,NaN,-0.03405,48.75304
128217,FREVZP3B222B60EC8D4077AB1F1C6D169CB,NaN,true,NaN,NaN,NaN,Accès libre,false,24/7,Accessible mais non réservé PMR,Aucune,false,NaN,50078366067890,NaN,NaN,2026-02-27,NaN,-0.03405,48.75304

In [269]:
irve_brut_zen = irve_brut[irve_brut['nom_operateur'] == 'EVzen']
len(irve_brut_zen), list(irve_brut_zen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

(1316, ['QualiCharge'])

In [277]:
station_evzen = pd.DataFrame({'id_station_itinerance': irve_brut_zen.drop_duplicates('id_station_itinerance')['id_station_itinerance']})
irve_stations_evzen = irve.merge(station_evzen, how="inner", on="id_station_itinerance")
len(irve_stations_evzen), list(irve_stations_evzen.drop_duplicates('datagouv_organization_or_owner')['datagouv_organization_or_owner'])

(1316, ['QualiCharge'])

In [273]:
irve[irve['id_station_itinerance'] == 'FREVZPE1ECBE2B195F42949F1DD8C53B022']

,nom_amenageur,siren_amenageur,contact_amenageur,nom_operateur,contact_operateur,telephone_operateur,nom_enseigne,id_station_itinerance,id_station_local,nom_station,...,date_maj,cable_t2_attache,consolidated_longitude,consolidated_latitude,datagouv_dataset_id,datagouv_resource_id,dataset_title,datagouv_organization_or_owner,datagouv_last_modified,deduplication_status
101987,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZPE1ECBE2B195F42949F1DD8C53B022,NaN,"EVzen - Toutry, Bi1 Toutry",...,2026-02-21,NaN,4.12541,47.49931,6818bce2d9af175f6e01a1b2,8bb0a6e2-1016-42ba-aaee-f72f55c82e9f,Infrastructures de recharge pour véhicules éle...,QualiCharge,2026-02-28T00:40:31.000000+0000,unique
103544,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZPE1ECBE2B195F42949F1DD8C53B022,NaN,"EVzen - Toutry, Bi1 Toutry",...,2026-02-21,NaN,4.12541,47.49931,6818bce2d9af175f6e01a1b2,8bb0a6e2-1016-42ba-aaee-f72f55c82e9f,Infrastructures de recharge pour véhicules éle...,QualiCharge,2026-02-28T00:40:31.000000+0000,unique
103920,SMEG DEVELOPPEMENT,940861826,contact@evzen.com,EVzen,support@evzen.com,tel:+33-9-69-39-09-03,EVzen,FREVZPE1ECBE2B195F42949F1DD8C53B022,NaN,"EVzen - Toutry, Bi1 Toutry",...,2026-02-21,NaN,4.12541,47.49931,6818bce2d9af175f6e01a1b2,8bb0a6e2-1016-42ba-aaee-f72f55c82e9f,Infrastructures de recharge pour véhicules éle...,QualiCharge,2026-02-28T00:40:31.000000+0000,unique

## schéma de données
Le schéma de données restreint à la propriété 'relationship' et construit à partir du modèle de données est le suivants :

In [184]:
# complément à inclure dans le schéma de données
schema = {
    'relationships': [
         # relation unicité des pdl
         {"fields": ["id_pdc_itinerance", "index"],                    "link" : "coupled" },   
         # relations inter entités
         {"fields": ["id_station_itinerance", "contact_operateur"],    "link" : "derived" },
         {"fields": ["id_station_itinerance", "nom_enseigne"],         "link" : "derived" },
         {"fields": ["id_station_itinerance", "coordonneesXY"],        "link" : "derived" },
         {"fields": ["id_pdc_itinerance", "id_station_itinerance"],    "link" : "derived" },
         # relations intra entité - station
         {"fields": ["id_station_itinerance", "nom_station"],          "link" : "derived" },
         {"fields": ["id_station_itinerance", "implantation_station"], "link" : "derived" },
         #{"fields": ["id_station_itinerance", "date_maj"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "nbre_pdc"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "condition_acces"],      "link" : "derived" },
         {"fields": ["id_station_itinerance", "horaires"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "station_deux_roues"],   "link" : "derived" },
         # relations intra entité - localisation
         {"fields": ["coordonneesXY", "adresse_station"],              "link" : "derived" }
    ]
}
fields_schema = set([field for relation in schema['relationships'] for field in relation['fields']])
# liste des champs liés à un controle (relations) et obligatoires (mandatory)
relations = ['index', 'contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 
             'nom_station', 'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 
             'id_pdc_itinerance', 'date_maj', 'last_modified']
mandatory = ['contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 'nom_station',
             'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 'id_pdc_itinerance', 
             'puissance_nominale', 'prise_type_ef', 'prise_type_2', 'prise_type_combo_ccs', 'prise_type_chademo', 
             'prise_type_autre', 'paiement_acte', 'paiement_autre', 'reservation',  'accessibilite_pmr', 'restriction_gabarit', 
             'date_maj', 'last_modified']
controles = ['index - id_pdc_itinerance', 'contact_operateur - id_station_itinerance', 'nom_enseigne - id_station_itinerance',
             'coordonneesXY - id_station_itinerance', 'id_station_itinerance - id_pdc_itinerance',
             'nom_station - id_station_itinerance', 'implantation_station - id_station_itinerance',
             'nbre_pdc - id_station_itinerance', 'condition_acces - id_station_itinerance', 'horaires - id_station_itinerance',
             'station_deux_roues - id_station_itinerance', 'adresse_station - coordonneesXY']

-----------------------
## 3 - Séparation des pdc itinerance et hors itinerance
- 0.14 % des points de recharge sont hors itinerance (1 % en 2024)

In [185]:
irve['last_modified'] = irve['datagouv_last_modified']

In [186]:
# séparation des données
data = irve
data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']] = data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']].astype('string')
#data[['last_modified','date_maj']] = data[['last_modified','date_maj']].astype('datetime64')
data['non_concerne'] = data['id_station_itinerance'].str.contains('oncern') | data['id_pdc_itinerance'].str.contains('oncern')

non_concerne = data[data['non_concerne']].reset_index()['index']
itinerance = data[~data['non_concerne']].reset_index()
itinerance_init = itinerance.loc[:, relations]
log['pdc_hors_itinerance'] = len(non_concerne)
log['pdc_en_itinerance'] = len(itinerance)
print('nombre de pdc hors itinerance : ', log['pdc_hors_itinerance'], 'soit : ', len(non_concerne)/(len(non_concerne)+len(itinerance)))
print('nombre de pdc en itinerance   : ', log['pdc_en_itinerance'])

nombre de pdc hors itinerance :  176 soit :  0.0011868955936501085
nombre de pdc en itinerance   :  148110

In [187]:
itinerance.groupby(['datagouv_organization_or_owner']).count()['index'].sort_values(ascending=False)[0:15]

datagouv_organization_or_owner
QualiCharge                                  46503
GIREVE                                       31714
Alizé                                        13624
IZIVIA                                       12958
Eco-Movement                                 10806
Indigo Group                                  6907
Driveco                                       3935
TotalEnergies Marketing France                1849
Engie Mobilités Electriques                   1827
Citeos Ingénierie IdF & Est (Cogelum IdF)     1468
Lidl                                          1344
Electric 55 Charging                          1291
Qovoltis                                      1220
e-Totem                                       1111
Rossini Energy                                 897
Name: index, dtype: int64

Dans Qualicharge, on a 61 450 pdc, ici on en retrouve 45 910 . Il en manque 15 540 ??

In [188]:
# arborescence des champs et nombre de valeurs différentes
print(itinerance_init.npd.analysis().tree())

-1: root-derived (148110)
   0 : index (0 - 148110)
   2 : nom_enseigne (143101 - 5009)
   3 : coordonneesXY (113625 - 34485)
   4 : adresse_station (113570 - 34540)
   5 : id_station_itineranc (98461 - 49649)
   6 : nom_station (112753 - 35357)
   7 : implantation_station (148105 - 5)
   8 : nbre_pdc (148007 - 103)
   10: horaires (146931 - 1179)
   12: id_pdc_itinerance (461 - 147649)
      1 : contact_operateur (147408 - 241)
      9 : condition_acces (147647 - 2)
      11: station_deux_roues (147647 - 2)
      13: date_maj (146719 - 930)
      14: last_modified (147210 - 439)

-----------------------
## 4 - Bilan initial intégrité
- 58 % des lignes présentent un défaut d'intégrité (moins de 20% en 2024)

In [189]:
# séparation données bonnes (itinerance_ok_1) et données résiduelles (itinerance_1)
res = analyse_integrite(itinerance_init, schema)
itinerance_ok_1 = itinerance_init.loc[itinerance_init.ok, relations].reset_index(drop=True)
itinerance_1 = itinerance_init.loc[~itinerance_init.ok, relations].reset_index(drop=True)
itinerance_init = itinerance_init.loc[:, relations]
log['init_ok'] = len(itinerance_ok_1)
log['init_ko'] = len(itinerance_1)
print("\nnombre d'enregistrements sans erreurs : ", log['init_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['init_ko'])
print("taux d'erreur : ", round(log['init_ko'] / log['pdc_en_itinerance'] * 100), ' %')

index - id_pdc_itinerance                            816
contact_operateur - id_station_itinerance           1601
nom_enseigne - id_station_itinerance                3888
coordonneesXY - id_station_itinerance               5226
id_station_itinerance - id_pdc_itinerance             28
nom_station - id_station_itinerance                 2260
implantation_station - id_station_itinerance        2232
nbre_pdc - id_station_itinerance                    4990
condition_acces - id_station_itinerance              104
horaires - id_station_itinerance                     903
station_deux_roues - id_station_itinerance            73
adresse_station - coordonneesXY                     8203

nombre d'enregistrements sans erreurs :  132857
nombre d'enregistrements avec au moins une erreur :  15253
taux d'erreur :  10  %

In [190]:
itinerance_quali = itinerance[itinerance['datagouv_organization_or_owner'] == 'QualiCharge'].reset_index().loc[:, relations]
print(len(itinerance_quali))
res = analyse_integrite(itinerance_quali, schema)

46503
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      148

In [191]:
itinerance_quali = itinerance[itinerance['datagouv_organization_or_owner'] == 'GIREVE'].reset_index().loc[:, relations]
print(len(itinerance_quali))
res = analyse_integrite(itinerance_quali, schema)

31714
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      368

In [192]:
itinerance_quali = itinerance[itinerance['datagouv_organization_or_owner'] == 'Eco-Movement'].reset_index().loc[:, relations]
print(len(itinerance_quali))
res = analyse_integrite(itinerance_quali, schema)

10806
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance         323
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        9

In [193]:
itinerance_quali[~itinerance_quali['adresse_station - coordonneesXY']].sort_values(['adresse_station'])[0:50]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,...,nom_enseigne - id_station_itinerance,coordonneesXY - id_station_itinerance,id_station_itinerance - id_pdc_itinerance,nom_station - id_station_itinerance,implantation_station - id_station_itinerance,nbre_pdc - id_station_itinerance,condition_acces - id_station_itinerance,horaires - id_station_itinerance,station_deux_roues - id_station_itinerance,adresse_station - coordonneesXY
2760,91304,support@virta.global,Installation pilote - Hervé Thermique,"[0.65425, 47.35397]","12 Rue Denis PAPIN, 37300 Joué Les Tours",FRVIRE209668,Installation pilote - Hervé Thermique,Voirie,1,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
5177,93721,support@modulo-energies.fr,MODULO - JOUE LES TOURS - Agence HT - Rue Deni...,"[0.65425, 47.35397]","12 Rue Denis Papin, 37300 JOUE LES TOURS",FRS37E209631,MODULO - JOUE LES TOURS - Agence HT - Rue Deni...,Voirie,2,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
5178,93722,support@modulo-energies.fr,MODULO - JOUE LES TOURS - Agence HT - Rue Deni...,"[0.65425, 47.35397]","12 Rue Denis Papin, 37300 JOUE LES TOURS",FRS37E209663,MODULO - JOUE LES TOURS - Agence HT - Rue Deni...,Voirie,2,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
4752,93296,charge@ubitricity.com,Ubitricity 443 Avenue du Bois au Coq,"[0.11958, 49.51633]","443 Avenue du Bois au Coq, 76610 Le Havre",FRUBIE10030869,Ubitricity 443 Avenue du Bois au Coq,Voirie,2,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
4753,93297,charge@ubitricity.com,Ubitricity 443 Avenue du Bois au Coq,"[0.11958, 49.51633]","443 Avenue du Bois au Coq, 76610 Le Havre",FRUBIE10086518,Ubitricity 443 Avenue du Bois au Coq,Voirie,2,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
4744,93288,charge@ubitricity.com,Ubitricity Rue Henri Cayeux / boulevard Bois a...,"[0.11958, 49.51633]","Rue Henri Cayeux / boulevard Bois au Coq (Par,...",FRUBIE10025553,Ubitricity Rue Henri Cayeux / boulevard Bois a...,Voirie,4,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
4745,93289,charge@ubitricity.com,Ubitricity Rue Henri Cayeux / boulevard Bois a...,"[0.11958, 49.51633]","Rue Henri Cayeux / boulevard Bois au Coq (Par,...",FRUBIE10075904,Ubitricity Rue Henri Cayeux / boulevard Bois a...,Voirie,4,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
4746,93290,charge@ubitricity.com,Ubitricity Rue Henri Cayeux / boulevard Bois a...,"[0.11958, 49.51633]","Rue Henri Cayeux / boulevard Bois au Coq (Par,...",FRUBIE10078611,Ubitricity Rue Henri Cayeux / boulevard Bois a...,Voirie,4,Accès réservé,...,True,True,True,True,True,True,True,True,True,False
4747,93291,charge@ubitricity.com,Ubitricity Rue Henri Cayeux / boulevard Bois a...,"[0.11958, 49.51633]","Rue Henri Cayeux / boulevard Bois au Coq (Par,...",FRUBIE10081681,Ubitricity Rue Henri Cayeux / boulevard Bois a...,Voirie,4,Accès réservé,...,True,True,True,True,True,True,True,True,True,False

In [194]:
#itinerance_quali[itinerance_quali['adresse_station']=='10 Rue des precurseurs']
itinerance_quali[itinerance_quali['coordonneesXY']=='[3.11985, 50.65196]']

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified, ok, index - id_pdc_itinerance, contact_operateur - id_station_itinerance, nom_enseigne - id_station_itinerance, coordonneesXY - id_station_itinerance, id_station_itinerance - id_pdc_itinerance, nom_station - id_station_itinerance, implantation_station - id_station_itinerance, nbre_pdc - id_station_itinerance, condition_acces - id_station_itinerance, horaires - id_station_itinerance, station_deux_roues - id_station_itinerance, adresse_station - coordonneesXY]
Index: []

[0 rows x 28 columns]

-----------------------
## 5 - Séparation doublons pdc - date de maj
- 51 % des pdc en erreur sont liées aux doublons de pdc (40 % fin 2024)
- la suppression des doublons permet de réduire de 94% le nombre de lignes erronnées (50 % fin 2024)

In [195]:
# séparation doublons pdc (doublons_pdc) et données résiduelles (itinerance_2)
itinerance_1['doublons_pdc'] = itinerance_1.sort_values(by=['date_maj', 'last_modified']).duplicated('id_pdc_itinerance', keep='last')

doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)['index']
#doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_2 = itinerance_1[~itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_1 = itinerance_1.loc[:, relations]
log['doublons_pdc'] = len(doublons_pdc)
log['sans_doublons_pdc'] = len(itinerance_2)
print('nombre de doublons pdc : ', log['doublons_pdc'], ' soit ', round(log['doublons_pdc']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_pdc'], ' soit ', round(log['sans_doublons_pdc']/log['init_ko'] * 100), ' %')

nombre de doublons pdc :  461  soit  3  %
nombre de pdc sans doublon   :  14792  soit  97  %

In [196]:
# séparation données bonnes (itinerance_ok_3) et données résiduelles (itinerance_3)
res = analyse_integrite(itinerance_2, schema)
itinerance_ok_3 = itinerance_2.loc[itinerance_2.ok, relations].reset_index(drop=True)
itinerance_3 = itinerance_2.loc[~itinerance_2.ok, relations].reset_index(drop=True)
itinerance_2 = itinerance_2.loc[:, relations]
log['etape3_ok'] = len(itinerance_ok_3)
log['etape3_ko'] = len(itinerance_3)
print("\nnombre d'enregistrements sans erreurs : ", log['etape3_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape3_ko'])

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance           1601
nom_enseigne - id_station_itinerance                3859
coordonneesXY - id_station_itinerance               5141
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 2162
implantation_station - id_station_itinerance        2231
nbre_pdc - id_station_itinerance                    4966
condition_acces - id_station_itinerance              104
horaires - id_station_itinerance                     881
station_deux_roues - id_station_itinerance            73
adresse_station - coordonneesXY                     8128

nombre d'enregistrements sans erreurs :  268
nombre d'enregistrements avec au moins une erreur :  14524

-----------------------
## 6 - Séparation doublons station - date de maj
- la suppression des anciens pdc permet de réduire de 13 % supplémentaire le nombre de lignes erronnées
- les dernières erreurs correspondent à des stations associées à 69 opérateurs et sont liées à des causes multiples

In [197]:
# séparation doublons stations (doublons_stat_maj) et données résiduelles (itinerance_4)
itinerance_3['stat_maj'] = itinerance_3.id_station_itinerance + itinerance_3.date_maj
stat_maj_unique = itinerance_3.sort_values(by='stat_maj').drop_duplicates('id_station_itinerance', keep='last')
itinerance_3['last_stat_maj'] = itinerance_3['stat_maj'].isin(stat_maj_unique['stat_maj'])

doublons_stat_maj = itinerance_3[~itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)['index']
itinerance_4 = itinerance_3[itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)
itinerance_3 = itinerance_3.loc[:, relations]
log['doublons_station'] = len(doublons_stat_maj)
log['sans_doublons_station'] = len(itinerance_4)
print('nombre de doublons stations : ', log['doublons_station'], ' soit ', 
      round(log['doublons_station']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_station'])

nombre de doublons stations :  1574  soit  10  %
nombre de pdc sans doublon   :  12950

In [198]:
# séparation données bonnes (itinerance_ok_5) et données résiduelles (itinerance_5 / itinerance_5_full)
res = analyse_integrite(itinerance_4, schema)
itinerance_ok_5 = itinerance_4.loc[itinerance_4.ok, relations].reset_index(drop=True)
itinerance_5_full = itinerance_4.loc[~itinerance_4.ok].reset_index(drop=True)
itinerance_5 = itinerance_5_full.loc[:, relations]
#itinerance_4 = itinerance_4.loc[:, relations]
log['etape5_ok'] = len(itinerance_ok_5)
log['etape5_ko'] = len(itinerance_5)
print("\nnombre d'enregistrements sans erreurs : ", log['etape5_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape5_ko'], ' soit ', 
      round(log['etape5_ko']/log['etape3_ko'] * 100), ' %')

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              2
nom_enseigne - id_station_itinerance                 388
coordonneesXY - id_station_itinerance               1344
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 1249
implantation_station - id_station_itinerance         377
nbre_pdc - id_station_itinerance                    1525
condition_acces - id_station_itinerance               23
horaires - id_station_itinerance                     103
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     7819

nombre d'enregistrements sans erreurs :  2592
nombre d'enregistrements avec au moins une erreur :  10358  soit  71  %

In [199]:
# structure des données présentant une erreur et nombre de valeurs
print(itinerance_5.npd.analysis().tree())

-1: root-derived (10358)
   0 : index (0 - 10358)
   1 : contact_operateur (10270 - 88)
   2 : nom_enseigne (9928 - 430)
   3 : coordonneesXY (8611 - 1747)
   4 : adresse_station (7617 - 2741)
      11: station_deux_roues (2739 - 2)
   5 : id_station_itineranc (6799 - 3559)
      13: date_maj (3264 - 295)
   6 : nom_station (7775 - 2583)
   7 : implantation_station (10353 - 5)
   8 : nbre_pdc (10312 - 46)
   9 : condition_acces (10356 - 2)
   10: horaires (10207 - 151)
   12: id_pdc_itinerance (0 - 10358)
   14: last_modified (10246 - 112)

In [200]:
# nb maxi d'erreurs
itinerance_4['somme'] = 0
for name in res.keys():
    itinerance_4['somme'] += 1 - itinerance_4[name]
erreurs = max(itinerance_4['somme'])
maxi = itinerance_4[itinerance_4.somme >= erreurs]
print("nombre d'enregistrements avec ", erreurs, " erreurs : ", len(maxi))

nombre d'enregistrements avec  4  erreurs :  41

In [201]:
# principaux opérateurs contributeur de défauts
operateurs = list(itinerance_5.drop_duplicates('contact_operateur')['contact_operateur'])
erreurs_op = [len(itinerance_5.loc[itinerance_5.contact_operateur == operateur]) for operateur in operateurs]
err_op_5, oper_5 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:5]))
err_op_10, oper_10 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:10]))

print(len(err_op_5), ' opérateurs représentent : ', round(sum(err_op_5) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_5, oper_5):
    print(err, op)

5  opérateurs représentent :  60  % des écarts

2623 support@evzen.com
1736 support@alizecharge.fr
753 sav@izivia.com
579 territoires@syaden.fr
489 bornes@lidl.fr

In [202]:
print(len(err_op_10), ' opérateurs représentent : ', round(sum(err_op_10) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_10, oper_10):
    print(err, op)

10  opérateurs représentent :  75  % des écarts

2623 support@evzen.com
1736 support@alizecharge.fr
753 sav@izivia.com
579 territoires@syaden.fr
489 bornes@lidl.fr
382 info@ionity.eu
363 kg@lastmilesolutions.com
358 roaming@zunder.com
226 roaming@freshmile.com
226 irve@soregies.fr

-----------------------
## 7 - Synthèse

### fichiers
Génération des fichiers intégrant les défauts d'intégrité :
- fichier csv des lignes résiduelles à traiter (IRVE_itinerance_residuel)
- fichier csv des données itinerance avec indicateur des données à corriger ou à ignorer (IRVE_itinerance_complet)
- fichier csv des données itinerance valides (IRVE_itinerance_valide)
- fichier csv des doublons (IRVE_itinerance_doublons)

In [203]:
# consolidation des données
itinerance['doublons_stat_maj'] = itinerance['index'].isin(doublons_stat_maj)
itinerance['doublons_pdc'] = itinerance['index'].isin(doublons_pdc)
itinerance['lignes_a_corriger'] = itinerance['index'].isin(itinerance_5['index'])
itinerance['doublons_a_supprimer'] = itinerance['doublons_stat_maj'] | itinerance['doublons_pdc']
itinerance['lignes_ko'] = itinerance['doublons_a_supprimer'] | itinerance['lignes_a_corriger']
print('total des lignes à corriger : ', itinerance['lignes_a_corriger'].sum())
itinerance_doublons = itinerance[itinerance['doublons_a_supprimer']].reset_index(drop=True)
print('total des doublons à supprimer : ', len(itinerance_doublons))
itinerance_ok = itinerance[~itinerance['lignes_ko']].reset_index(drop=True)
print('nombre de pdc avec controles ok : ', len(itinerance_ok))

total des lignes à corriger :  10358
total des doublons à supprimer :  2035
nombre de pdc avec controles ok :  135717

In [204]:
# génération des fichiers
extension = log['date_irve'] +'.csv'
itinerance_5_full.to_csv('IRVE_itinerance_residuel' + extension)
itinerance.to_csv('IRVE_itinerance_complet' + extension)
itinerance_ok.to_csv('IRVE_itinerance_valide' + extension)
itinerance_doublons.to_csv('IRVE_itinerance_doublons' + extension)
log['IRVE_itinerance_residuel' + extension] = len(itinerance_5_full)
log['IRVE_itinerance_complet' + extension] = len(itinerance)
log['IRVE_itinerance_valide' + extension] = len(itinerance_ok)
log['IRVE_itinerance_valide_stat' + extension] = len(itinerance_ok.drop_duplicates('id_station_itinerance', keep='last'))
log['IRVE_itinerance_doublons' + extension] = len(itinerance_doublons)

In [205]:
l_prefix = list(pd.read_csv(log['chemin'] + '/' + 'Operations_Recharge_16-07-2024.csv', sep=';', low_memory=False, dtype='object')['Identifiant'])
l_prefix[0]

'FR073'

In [206]:
for op in oper_5:
    print('IRVE_itinerance_residuel' + '_' + op + '_' + extension)
    itinerance_5_full.loc[itinerance_5_full.contact_operateur == op].to_csv('IRVE_itinerance_residuel' + '_' + op + '_' + extension)

IRVE_itinerance_residuel_support@evzen.com_2026-04-01.csv
IRVE_itinerance_residuel_support@alizecharge.fr_2026-04-01.csv
IRVE_itinerance_residuel_sav@izivia.com_2026-04-01.csv
IRVE_itinerance_residuel_territoires@syaden.fr_2026-04-01.csv
IRVE_itinerance_residuel_bornes@lidl.fr_2026-04-01.csv

### vérification de l'intégrité

In [207]:
# vérification de l'absence d'erreurs
res = analyse_integrite(itinerance_ok.loc[:, relations], schema, affiche=False)
log['bilan_erreurs'] = sum(res.values())
log['date'] = datetime.now().isoformat()
print('bilan intégrité :')
print('    erreurs : ', log['bilan_erreurs'])

bilan intégrité :
    erreurs :  0

In [208]:
# structure des données bonnes
#print(Cdataset(itinerance_ok.loc[:, mandatory]).tree())
print(itinerance_ok.loc[:, mandatory].npd.analysis().tree())

-1: root-derived (135717)
   4 : id_station_itineranc (89632 - 46085)
      0 : contact_operateur (45855 - 230)
      1 : nom_enseigne (41396 - 4689)
      2 : coordonneesXY (14046 - 32039)
         3 : adresse_station (842 - 31197)
      5 : nom_station (13387 - 32698)
      6 : implantation_station (46080 - 5)
      7 : nbre_pdc (45987 - 98)
      8 : condition_acces (46083 - 2)
      9 : horaires (45022 - 1063)
      10: station_deux_roues (46083 - 2)
   11: id_pdc_itinerance (0 - 135717)
   12: puissance_nominale (135530 - 187)
   13: prise_type_ef (135715 - 2)
   14: prise_type_2 (135715 - 2)
   15: prise_type_combo_ccs (135715 - 2)
   16: prise_type_chademo (135715 - 2)
   17: prise_type_autre (135715 - 2)
   18: paiement_acte (135715 - 2)
   19: paiement_autre (135714 - 3)
   20: reservation (135715 - 2)
   21: accessibilite_pmr (135713 - 4)
   22: restriction_gabarit (135573 - 144)
   23: date_maj (134839 - 878)
   24: last_modified (135322 - 395)

### Indicateurs

In [209]:
# génération des indicateurs liés aux règles
regles = ['Pdc non unique', 'Station multi-operateurs', 'Station multi-enseignes', 'Station multi-localisations', 
          'Pdc multi-stations', 'station avec plusieurs noms', 'station multi-implantations', 
          'nombre de pdc par station incoherent', 'station multi-acces', 'station multi-horaires', 
          'acces deux-roues incoherent', 'localisation multi-adresses']
principal = [16, 17, 18, 19, 20]
secondaire = [21, 22, 23, 24, 25, 26, 27]
irve = itinerance_5_full # residuel
total = len(irve)
indic = {}

irve['principal'] = True
for ind in principal:
    irve['principal'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] = True
for ind in secondaire:
    irve['secondaire'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] |= (~irve['principal'] & ~irve['secondaire'])
irve['verif'] = irve['principal'] & irve['secondaire']
indic['principal pdc'] = int(total - irve['principal'].sum())
indic['secondaire pdc'] = int(total - irve['secondaire'].sum())

irve_p = irve[~irve['principal']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
irve_s = irve[~irve['secondaire']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
indic['principal stat'] = len(irve_p)
indic['secondaire stat'] = len(irve_s)

In [210]:
# ajout des principaux opérateurs contributeur de défauts
indic['operateurs'] = list(oper_5)
indic['erreurs_operateurs'] = list(err_op_5)

In [211]:
# ajout de l'indicateur d'écart entre nombre de pdc calculés et saisis
add_nbre_pdc(irve, affiche=True)
indic['nb_pdc_calc-nbre_pdc'] = int(irve['calc-nbre'].sum())

nbre_pdc_ko           3489
34  %

In [212]:
# indicateur d'écart entre nombre de pdc calculés et saisis sur les données sans doublon
itinerance_sans_doublons = itinerance[~itinerance['doublons_a_supprimer']].reset_index(drop=True)
add_nbre_pdc(itinerance_sans_doublons, affiche=True)

nbre_pdc_ko          35392
24  %

In [213]:
len(itinerance_4)

12950

In [214]:
# stockage des indicateurs
log |= indic
log_file = log['chemin'] + '/' + 'logfile.txt'
#with open('logfile.txt', 'a', encoding="utf-8") as f:
with open(log_file, 'a', encoding="utf-8") as f:
    f.write(json.dumps(log) + '\n')

In [215]:
itinerance_5_full.columns[16:28]

Index(['index - id_pdc_itinerance',
       'contact_operateur - id_station_itinerance',
       'nom_enseigne - id_station_itinerance',
       'coordonneesXY - id_station_itinerance',
       'id_station_itinerance - id_pdc_itinerance',
       'nom_station - id_station_itinerance',
       'implantation_station - id_station_itinerance',
       'nbre_pdc - id_station_itinerance',
       'condition_acces - id_station_itinerance',
       'horaires - id_station_itinerance',
       'station_deux_roues - id_station_itinerance',
       'adresse_station - coordonneesXY'],
      dtype='object')

-----------------------
## 8 - Exemples d'erreurs résiduelles 

### Erreurs multiples 
- exemple avec le nombre maximal d'erreurs (4) (35 pdc)
- exemple station 'FRS35P35093001B1' avec 25 pdc : coordonnées XY, nom_station, implantation station, condition accès)

In [216]:
maxi.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
39,207,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.000000+0000
40,208,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.000000+0000
41,211,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,false,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.000000+0000
42,212,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,false,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.000000+0000
43,213,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,false,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.000000+0000
44,214,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,false,FRS35E3509300411,2024-09-18,2025-12-15T16:13:43.000000+0000
45,215,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,false,FRS35E3509300421,2024-09-18,2025-12-15T16:13:43.000000+0000
46,216,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,false,FRS35E3509300420,2024-09-18,2025-12-15T16:13:43.000000+0000
47,217,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,false,FRS35E350930041,2024-09-18,2025-12-15T16:13:43.000000+0000
48,218,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,false,FRS35E3509300412,2024-09-18,2025-12-15T16:13:43.000000+0000
49,219,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,false,FRS35E350930042,2024-09-18,2025-12-15T16:13:43.000000+0000
50,220,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,false,FRS35E3509300413,2024-09-18,2025-12-15T16:13:43.000000+0000
51,221,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,false,FRS35E3509300414,2024-09-18,2025-12-15T16:13:43.000000+0000
52,222,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,false,FRS35E3509300415,2024-09-18,2025-12-15T16:13:43.000000+0000
53,223,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,false,FRS35E3509300416,2024-09-18,2025-12-15T16:13:43.000000+0000
54,224,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,false,FRS35E3509300417,2024-09-18,2025-12-15T16:13:43.000000+0000
55,225,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,false,FRS35E3509300418,2024-09-18,2025-12-15T16:13:43.000000+0000
56,226,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,false,FRS35E3509300419,2024-09-18,2025-12-15T16:13:43.000000+0000
57,227,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,false,FRS35E350930043,2024-09-18,2025-12-15T16:13:43.000000+0000
58,228,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,false,FRS35E350930044,2024-09-18,2025-12-15T16:13:43.000000+0000
59,229,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,false,FRS35E350930045,2024-09-18,2025-12-15T16:13:43.000000+0000
60,230,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,false,FRS35E350930046,2024-09-18,2025-12-15T16:13:43.000000+0000
61,231,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,false,FRS35E350930047,2024-09-18,2025-12-15T16:13:43.000000+0000
1180,15802,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003929,2025-12-11,2025-12-17T09:36:45.000000+0000
1181,15803,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003930,2025-12-11,2025-12-17T09:36:45.000000+0000
1182,15804,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003931,2025-12-11,2025-12-17T09:36:45.000000+0000
1183,15805,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003932,2025-12-11,2025-12-17T09:36:45.000000+0000
1184,15806,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003963,2025-12-11,2025-12-17T09:36:45.000000+0000
1185,15807,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003964,2025-12-11,2025-12-17T09:36:45.000000+0000
1186,15808,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003965,2025-12-11,2025-12-17T09:36:45.000000+0000
1187,15809,bornes@lidl.fr,LIDL,"[2.33401, 48.63200]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003966,2025-12-11,2025-12-17T09:36:45.000000+0000
1395,16248,bornes@lidl.fr,LIDL,"[2.33427, 48.63166]",21 RUE DU PLESSIS,FRLDLPLFR4256EVCP,SAINTE GENEVIEVE DES BOIS,Parking privé à usage public,2,Accès libre,"Mo-Sa 08:30-20:30,Su 08:30-12:15",false,FRLDLE00007414,2025-12-11,2025-12-17T09:36:45.000000+0000
1396,16249,bornes@lidl.fr,LIDL,"[2.33427, 48.63166]",21 RUE DU PLESSIS,FRLDLPLFR4256EVCP,SAINTE GENEVIEVE DES BOIS,Parking privé à usage public,2,Accès libre,"Mo-Sa 08:30-20:30,Su 08:30-12:15",false,FRLDLE00007415,2025-12-11,2025-12-17T09:36:45.000000+0000
2906,25384,support@alizecharge.fr,Le Plein Tarnais,"[2.49632, 43.63097]","Place De Castelnau, 81260 BRASSAC",FRS81E81037001,BRASSAC - Place De Castelnau,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRS81E810370011,2026-02-12,2026-02-12T13:33:57.000000+0000
3707,30379,support@alizecharge.fr,Le Plein Tarnais,"[2.49632, 43.63097]","Place De Castelnau, 81260 BRASSAC",FRS81E81037001,BRASSAC - Place De Castelnau,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRS81E810370012,2026-02-12,2026-02-12T13:33:57.000000+0000
6755,73462,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[49.27090, -0.70025]","\t16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,\t\tScauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",false,FRMBZESMYQC1,2024-06-03,2026-02-25T07:35:03.000000+0000
6756,73469,support@mobilize-ps.fr,BODEMER BAYEUX,"[49.27084, -0.70022]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,BODEMER Bayeux,Parking privé à usage public,1,Accès libre,24/7,false,FRMBZESMYCQ1,2024-06-03,2026-02-25T07:35:03.000000+0000
6907,85622,sav@izivia.com,SIGEIF,"[48.83370, 2.25867]",6 Avenue la Voie Lactée 92100 Boulogne-Billanc...,FRSIGPSIGE529,"SIGEIF - Boulogne Billancourt, Avenue de la Vo...",Voirie,3,Accès libre,24/7,false,FRSIGESIGE52912,2026-02-27,2026-02-27T07:34:21.000000+0000
6965,87461,sav@izivia.com,Izivia Express,"[47.39842, -0.53059]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,false,FRE04EOAZS24721,2026-02-27,2026-02-27T07:36:36.000000+0000
9202,119118,sav@izivia.com,GPSO,"[2.25867, 48.83370]","6 Avenue la Voie Lactée, 92100 Boulogne-Billan...",FRSIGPSIGE529,"SIGEIF - Boulogne Billancourt, Avenue de la Vo...",Voirie,2,Accès libre,24/7,false,FRSIGESIGE52913,2026-02-27,2026-02-28T00:40:31.000000+0000
10076,122246,sav@izivia.com,GPSO,"[2.25867, 48.83370]","6 Avenue la Voie Lactée, 92100 Boulogne-Billan...",FRSIGPSIGE529,"SIGEIF - Boulogne Billancourt, Avenue de la Vo...",Voirie,2,Accès libre,24/7,false,FRSIGESIGE52911,2026-02-27,2026-02-28T00:40:31.000000+0000

In [217]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRS35P35093001B1', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
39,207,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.000000+0000
40,208,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.000000+0000
41,211,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,false,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.000000+0000
42,212,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,false,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.000000+0000
43,213,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,false,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.000000+0000
44,214,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,false,FRS35E3509300411,2024-09-18,2025-12-15T16:13:43.000000+0000
45,215,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,false,FRS35E3509300421,2024-09-18,2025-12-15T16:13:43.000000+0000
46,216,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,false,FRS35E3509300420,2024-09-18,2025-12-15T16:13:43.000000+0000
47,217,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,false,FRS35E350930041,2024-09-18,2025-12-15T16:13:43.000000+0000
48,218,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,false,FRS35E3509300412,2024-09-18,2025-12-15T16:13:43.000000+0000
49,219,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,false,FRS35E350930042,2024-09-18,2025-12-15T16:13:43.000000+0000
50,220,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,false,FRS35E3509300413,2024-09-18,2025-12-15T16:13:43.000000+0000
51,221,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,false,FRS35E3509300414,2024-09-18,2025-12-15T16:13:43.000000+0000
52,222,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,false,FRS35E3509300415,2024-09-18,2025-12-15T16:13:43.000000+0000
53,223,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,false,FRS35E3509300416,2024-09-18,2025-12-15T16:13:43.000000+0000
54,224,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,false,FRS35E3509300417,2024-09-18,2025-12-15T16:13:43.000000+0000
55,225,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,false,FRS35E3509300418,2024-09-18,2025-12-15T16:13:43.000000+0000
56,226,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,false,FRS35E3509300419,2024-09-18,2025-12-15T16:13:43.000000+0000
57,227,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,false,FRS35E350930043,2024-09-18,2025-12-15T16:13:43.000000+0000
58,228,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,false,FRS35E350930044,2024-09-18,2025-12-15T16:13:43.000000+0000
59,229,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,false,FRS35E350930045,2024-09-18,2025-12-15T16:13:43.000000+0000
60,230,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,false,FRS35E350930046,2024-09-18,2025-12-15T16:13:43.000000+0000
61,231,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,false,FRS35E350930047,2024-09-18,2025-12-15T16:13:43.000000+0000

### Repartition des defauts par operateur
Répartition pour les 10 opérateurs présentant le plus de défauts

In [218]:
print('PdC avec une incohérence : ')
for operateur in oper_10:
    print('\n', sum(itinerance_5.contact_operateur == operateur))
    print('Répartition des incohérences ', operateur, ' :')
    for cont in controles:
        #print(cont, sum((itinerance_4['contact_operateur'] == 'supervision-ev.france@totalenergies.com') & ~(itinerance_4[cont])))
        print('{:<50} {:>5}'.format(cont, sum((itinerance_4['contact_operateur'] == operateur) & ~(itinerance_4[cont]))))

PdC avec une incohérence :

 2623
Répartition des incohérences  support@evzen.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  4
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     2619

 1736
Répartition des incohérences  support@alizecharge.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                174
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  831
implantation_station - id_station_itinerance          15
nbre_pdc - id_station_itinerance                     772
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      967

 753
Répartition des incohérences  sav@izivia.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                 381
coordonneesXY - id_station_itinerance                416
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   42
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                     416
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      338

 579
Répartition des incohérences  territoires@syaden.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      579

 489
Répartition des incohérences  bornes@lidl.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                468
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  154
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                     114
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                      24
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 382
Répartition des incohérences  info@ionity.eu  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      382

 363
Répartition des incohérences  kg@lastmilesolutions.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      363

 358
Répartition des incohérences  roaming@zunder.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      358

 226
Répartition des incohérences  roaming@freshmile.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      226

 226
Répartition des incohérences  irve@soregies.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance          12
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      214

### Defauts operateur ALIZECHARGE
Les défauts identifiés concernent des stations utilisant un même identifiant. Par exemple, la station 'FRADPE77294001' contient 40 points de recharge avec plusieurs adresses, plusieurs localisations, plusieurs noms de station et un nombre de points de rechage variable.

In [219]:
itinerance_4.loc[(~itinerance_4['nom_station - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'support@alizecharge.fr'), relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
2326,21942,support@alizecharge.fr,Seymaborne,"[1.84089, 48.61362]","Rue de la Droue 51, 78120 SONCHAMP",FRY03E78601001,SONCHAMP - CHAPELLE GREFFIERS,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRY03E786010011,2026-02-12,2026-02-12T13:33:57.000000+0000
2327,21951,support@alizecharge.fr,La borne bleue,"[2.41354, 48.83379]","Avenue Daumesnil, 94160 SAINT-MANDÉ",FRSIPE94067006,SAINT-MANDÉ - 11 TER Avenue Daumesnil - DC,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRSIPE940670064,2026-02-12,2026-02-12T13:33:57.000000+0000
2329,21968,support@alizecharge.fr,EFFIA France,"[5.71289, 45.19235]","2 avenue Doyen Louis Weil, 38000 GRENOBLE",FRP01E38185011,Parking Grenoble Gares Europole - PARK GRENOBL...,Parking public,19,Accès libre,Mo-Su 00:00-23:57,false,FRP01E3818501171,2026-02-12,2026-02-12T13:33:57.000000+0000
2330,21978,support@alizecharge.fr,Territoire de Energie TE53,"[-0.92914, 48.29732]","Avenue General De Gaulle, 53500 ERNEE",FRS53E53096002,ERNEE - Avenue General De Gaulle,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRS53E530960024,2026-02-12,2026-02-12T13:33:57.000000+0000
2333,22047,support@alizecharge.fr,Seymaborne,"[1.94170, 48.84361]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRY03E786150013,2026-02-12,2026-02-12T13:33:57.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4044,35210,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600122,2026-02-12,2026-02-12T13:33:57.000000+0000
4045,35211,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600121,2026-02-12,2026-02-12T13:33:57.000000+0000
4048,35369,support@alizecharge.fr,Pass pass électrique,"[2.79579, 50.29597]","Parking rue des Rosati, 62223 SAINT-LAURENT-B...",FRH01E62753003,SAINT-LAURENT-BLANGY - Parking rue des Rosati,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRH01E6275300311,2026-02-12,2026-02-12T13:33:57.000000+0000
4049,35402,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600141,2026-02-12,2026-02-12T13:33:57.000000+0000
4050,35403,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600142,2026-02-12,2026-02-12T13:33:57.000000+0000

In [220]:
itinerance_4.loc[(~itinerance_4['nbre_pdc - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'support@alizecharge.fr'), relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
2327,21951,support@alizecharge.fr,La borne bleue,"[2.41354, 48.83379]","Avenue Daumesnil, 94160 SAINT-MANDÉ",FRSIPE94067006,SAINT-MANDÉ - 11 TER Avenue Daumesnil - DC,Voirie,3,Accès libre,Mo-Su 00:00-23:57,false,FRSIPE940670064,2026-02-12,2026-02-12T13:33:57.000000+0000
2329,21968,support@alizecharge.fr,EFFIA France,"[5.71289, 45.19235]","2 avenue Doyen Louis Weil, 38000 GRENOBLE",FRP01E38185011,Parking Grenoble Gares Europole - PARK GRENOBL...,Parking public,19,Accès libre,Mo-Su 00:00-23:57,false,FRP01E3818501171,2026-02-12,2026-02-12T13:33:57.000000+0000
2330,21978,support@alizecharge.fr,Territoire de Energie TE53,"[-0.92914, 48.29732]","Avenue General De Gaulle, 53500 ERNEE",FRS53E53096002,ERNEE - Avenue General De Gaulle,Voirie,2,Accès libre,Mo-Su 00:00-23:57,false,FRS53E530960024,2026-02-12,2026-02-12T13:33:57.000000+0000
2336,22069,support@alizecharge.fr,EFFIA France,"[2.35368, 48.87988]","4 RUE DE COMPIÈGNE, 75010 PARIS",FRP01E75110002,Parking Paris Gare du Nord N-3 (Horaire) - EFFIA,Parking public,18,Accès libre,Mo-Su 00:00-23:57,false,FRP01E7511000211,2026-02-12,2026-02-12T13:33:57.000000+0000
2337,22110,support@alizecharge.fr,EFFIA France,"[5.71289, 45.19235]","2 avenue Doyen Louis Weil, 38000 GRENOBLE",FRP01E38185011,Parking Grenoble Gares Europole - PARK GRENOBL...,Parking public,19,Accès libre,Mo-Su 00:00-23:57,false,FRP01E38185011131,2026-02-12,2026-02-12T13:33:57.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4043,35194,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600162,2026-02-12,2026-02-12T13:33:57.000000+0000
4044,35210,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600122,2026-02-12,2026-02-12T13:33:57.000000+0000
4045,35211,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600121,2026-02-12,2026-02-12T13:33:57.000000+0000
4049,35402,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600141,2026-02-12,2026-02-12T13:33:57.000000+0000
4050,35403,support@alizecharge.fr,Grenoble-Alpes Métropole,"[5.69126, 45.16525]","Allée Roger Rahon, 38180 SEYSSINS",FRM38E38486001,SMMAG - SEYSSINS - Parking Le Prisme,Voirie,9,Accès libre,Mo-Su 00:00-23:57,false,FRM38E3848600142,2026-02-12,2026-02-12T13:33:57.000000+0000

In [221]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRADPE77294001', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3964,34489,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001193,2026-02-12,2026-02-12T13:33:57.000000+0000
3965,34490,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001191,2026-02-12,2026-02-12T13:33:57.000000+0000
3966,34491,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001192,2026-02-12,2026-02-12T13:33:57.000000+0000
3967,34494,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001202,2026-02-12,2026-02-12T13:33:57.000000+0000
3968,34495,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001203,2026-02-12,2026-02-12T13:33:57.000000+0000
3969,34496,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001201,2026-02-12,2026-02-12T13:33:57.000000+0000
3985,34616,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001301,2026-02-12,2026-02-12T13:33:57.000000+0000
3986,34617,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001302,2026-02-12,2026-02-12T13:33:57.000000+0000
3987,34618,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001322,2026-02-12,2026-02-12T13:33:57.000000+0000
3988,34619,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001321,2026-02-12,2026-02-12T13:33:57.000000+0000
3990,34780,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001312,2026-02-12,2026-02-12T13:33:57.000000+0000
3991,34781,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001311,2026-02-12,2026-02-12T13:33:57.000000+0000
4000,34963,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001232,2026-02-12,2026-02-12T13:33:57.000000+0000
4001,34964,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001231,2026-02-12,2026-02-12T13:33:57.000000+0000
4002,34965,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001233,2026-02-12,2026-02-12T13:33:57.000000+0000
4003,34972,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001272,2026-02-12,2026-02-12T13:33:57.000000+0000
4004,34973,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001271,2026-02-12,2026-02-12T13:33:57.000000+0000
4005,34974,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001273,2026-02-12,2026-02-12T13:33:57.000000+0000
4006,34975,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001253,2026-02-12,2026-02-12T13:33:57.000000+0000
4007,34976,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001252,2026-02-12,2026-02-12T13:33:57.000000+0000
4008,34977,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001251,2026-02-12,2026-02-12T13:33:57.000000+0000
4011,35046,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001332,2026-02-12,2026-02-12T13:33:57.000000+0000
4012,35047,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001331,2026-02-12,2026-02-12T13:33:57.000000+0000
4013,35048,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001342,2026-02-12,2026-02-12T13:33:57.000000+0000
4014,35049,support@alizecharge.fr,ADP Groupe,"[2.36375, 48.73349]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001341,2026-02-12,2026-02-12T13:33:57.000000+0000
4019,35084,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001243,2026-02-12,2026-02-12T13:33:57.000000+0000
4020,35085,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001242,2026-02-12,2026-02-12T13:33:57.000000+0000
4021,35086,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001241,2026-02-12,2026-02-12T13:33:57.000000+0000
4022,35095,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001262,2026-02-12,2026-02-12T13:33:57.000000+0000
4023,35096,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001261,2026-02-12,2026-02-12T13:33:57.000000+0000
4024,35097,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001263,2026-02-12,2026-02-12T13:33:57.000000+0000
4029,35143,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001221,2026-02-12,2026-02-12T13:33:57.000000+0000
4030,35144,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001223,2026-02-12,2026-02-12T13:33:57.000000+0000
4031,35145,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001222,2026-02-12,2026-02-12T13:33:57.000000+0000
4032,35152,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001282,2026-02-12,2026-02-12T13:33:57.000000+0000
4033,35153,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001283,2026-02-12,2026-02-12T13:33:57.000000+0000
4034,35154,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001281,2026-02-12,2026-02-12T13:33:57.000000+0000
4035,35155,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001212,2026-02-12,2026-02-12T13:33:57.000000+0000
4036,35156,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001213,2026-02-12,2026-02-12T13:33:57.000000+0000
4037,35157,support@alizecharge.fr,ADP Groupe,"[2.61094, 49.00764]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,false,FRADPE77294001211,2026-02-12,2026-02-12T13:33:57.000000+0000

In [222]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[2.969121,48.282539]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Defauts operateur LIDL
Les défauts identifiés concernent principalement l'affectation de coordonnées au point de recharge et non à la station. Par exemple, pour une station composée de quatre bornes de deux points de recharge, on trouve une coordonnée différente pour chacune des bornes.

In [223]:
itinerance_4.loc[(~itinerance_4['coordonneesXY - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'bornes@lidl.fr') , relations].sort_values(by=["id_station_itinerance"])[0:50]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1035,15309,bornes@lidl.fr,LIDL,"[7.33667, 48.06137]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006684,2025-12-11,2025-12-17T09:36:45.000000+0000
1032,15306,bornes@lidl.fr,LIDL,"[7.33663, 48.06132]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006681,2025-12-11,2025-12-17T09:36:45.000000+0000
1036,15310,bornes@lidl.fr,LIDL,"[7.33670, 48.06141]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006685,2025-12-11,2025-12-17T09:36:45.000000+0000
1037,15311,bornes@lidl.fr,LIDL,"[7.33670, 48.06141]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006686,2025-12-11,2025-12-17T09:36:45.000000+0000
1034,15308,bornes@lidl.fr,LIDL,"[7.33667, 48.06137]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006683,2025-12-11,2025-12-17T09:36:45.000000+0000
1033,15307,bornes@lidl.fr,LIDL,"[7.33663, 48.06132]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006682,2025-12-11,2025-12-17T09:36:45.000000+0000
1221,15873,bornes@lidl.fr,LIDL,"[3.46612, 46.83519]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006060,2025-12-11,2025-12-17T09:36:45.000000+0000
1220,15872,bornes@lidl.fr,LIDL,"[3.46612, 46.83519]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006059,2025-12-11,2025-12-17T09:36:45.000000+0000
1219,15871,bornes@lidl.fr,LIDL,"[3.46613, 46.83523]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006058,2025-12-11,2025-12-17T09:36:45.000000+0000
1218,15870,bornes@lidl.fr,LIDL,"[3.46613, 46.83523]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006057,2025-12-11,2025-12-17T09:36:45.000000+0000
1217,15869,bornes@lidl.fr,LIDL,"[3.46613, 46.83527]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006056,2025-12-11,2025-12-17T09:36:45.000000+0000
1216,15868,bornes@lidl.fr,LIDL,"[3.46613, 46.83527]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006055,2025-12-11,2025-12-17T09:36:45.000000+0000
1194,15816,bornes@lidl.fr,LIDL,"[2.37828, 48.98769]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004323,2025-12-11,2025-12-17T09:36:45.000000+0000
1195,15817,bornes@lidl.fr,LIDL,"[2.37828, 48.98769]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004324,2025-12-11,2025-12-17T09:36:45.000000+0000
1196,15818,bornes@lidl.fr,LIDL,"[2.37814, 48.98761]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004325,2025-12-11,2025-12-17T09:36:45.000000+0000
1197,15819,bornes@lidl.fr,LIDL,"[2.37814, 48.98761]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004326,2025-12-11,2025-12-17T09:36:45.000000+0000
1199,15821,bornes@lidl.fr,LIDL,"[2.37797, 48.98752]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004328,2025-12-11,2025-12-17T09:36:45.000000+0000
1192,15814,bornes@lidl.fr,LIDL,"[2.37841, 48.98776]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004321,2025-12-11,2025-12-17T09:36:45.000000+0000
1193,15815,bornes@lidl.fr,LIDL,"[2.37841, 48.98776]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004322,2025-12-11,2025-12-17T09:36:45.000000+0000
1198,15820,bornes@lidl.fr,LIDL,"[2.37797, 48.98752]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004327,2025-12-11,2025-12-17T09:36:45.000000+0000
1222,15882,bornes@lidl.fr,LIDL,"[2.46814, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006917,2025-12-11,2025-12-17T09:36:45.000000+0000
1223,15883,bornes@lidl.fr,LIDL,"[2.46814, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006918,2025-12-11,2025-12-17T09:36:45.000000+0000
1225,15885,bornes@lidl.fr,LIDL,"[2.46821, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006920,2025-12-11,2025-12-17T09:36:45.000000+0000
1224,15884,bornes@lidl.fr,LIDL,"[2.46821, 49.24073]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006919,2025-12-11,2025-12-17T09:36:45.000000+0000
1094,15486,bornes@lidl.fr,LIDL,"[-3.43993, 48.73374]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005309,2025-12-11,2025-12-17T09:36:45.000000+0000
1096,15488,bornes@lidl.fr,LIDL,"[-3.43984, 48.73356]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005298,2025-12-11,2025-12-17T09:36:45.000000+0000
1097,15489,bornes@lidl.fr,LIDL,"[-3.43984, 48.73356]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005297,2025-12-11,2025-12-17T09:36:45.000000+0000
1095,15487,bornes@lidl.fr,LIDL,"[-3.43981, 48.73351]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005310,2025-12-11,2025-12-17T09:36:45.000000+0000
1031,15305,bornes@lidl.fr,LIDL,"[6.53238, 43.25534]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006712,2025-12-11,2025-12-17T09:36:45.000000+0000
1030,15304,bornes@lidl.fr,LIDL,"[6.53238, 43.25534]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006711,2025-12-11,2025-12-17T09:36:45.000000+0000
1029,15303,bornes@lidl.fr,LIDL,"[6.53232, 43.25531]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006710,2025-12-11,2025-12-17T09:36:45.000000+0000
1028,15302,bornes@lidl.fr,LIDL,"[6.53232, 43.25531]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006709,2025-12-11,2025-12-17T09:36:45.000000+0000
1027,15301,bornes@lidl.fr,LIDL,"[6.53243, 43.25578]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00005173,2025-12-11,2025-12-17T09:36:45.000000+0000
1026,15300,bornes@lidl.fr,LIDL,"[6.53243, 43.25578]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00005186,2025-12-11,2025-12-17T09:36:45.000000+0000
1038,15320,bornes@lidl.fr,LIDL,"[0.67401, 46.00272]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006611,2025-12-11,2025-12-17T09:36:45.000000+0000
1039,15321,bornes@lidl.fr,LIDL,"[0.67401, 46.00272]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006612,2025-12-11,2025-12-17T09:36:45.000000+0000
1040,15322,bornes@lidl.fr,LIDL,"[0.67403, 46.00277]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006613,2025-12-11,2025-12-17T09:36:45.000000+0000
1042,15324,bornes@lidl.fr,LIDL,"[0.67403, 46.00283]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006615,2025-12-11,2025-12-17T09:36:45.000000+0000
1043,15325,bornes@lidl.fr,LIDL,"[0.67403, 46.00283]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006616,2025-12-11,2025-12-17T09:36:45.000000+0000
1041,15323,bornes@lidl.fr,LIDL,"[0.67403, 46.00277]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006614,2025-12-11,2025-12-17T09:36:45.000000+0000
1232,15905,bornes@lidl.fr,LIDL,"[1.32590, 45.12886]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006617,2025-12-11,2025-12-17T09:36:45.000000+0000
1236,15909,bornes@lidl.fr,LIDL,"[1.32591, 45.12877]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006621,2025-12-11,2025-12-17T09:36:45.000000+0000
1235,15908,bornes@lidl.fr,LIDL,"[1.32590, 45.12882]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006620,2025-12-11,2025-12-17T09:36:45.000000+0000
1237,15910,bornes@lidl.fr,LIDL,"[1.32591, 45.12877]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006622,2025-12-11,2025-12-17T09:36:45.000000+0000
1234,15907,bornes@lidl.fr,LIDL,"[1.32590, 45.12882]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006619,2025-12-11,2025-12-17T09:36:45.000000+0000
1233,15906,bornes@lidl.fr,LIDL,"[1.32590, 45.12886]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006618,2025-12-11,2025-12-17T09:36:45.000000+0000
1121,15535,bornes@lidl.fr,LIDL,"[-0.21413, 44.90003]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006950,2025-12-11,2025-12-17T09:36:45.000000+0000
1122,15536,bornes@lidl.fr,LIDL,"[-0.21411, 44.90036]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006951,2025-12-11,2025-12-17T09:36:45.000000+0000
1123,15537,bornes@lidl.fr,LIDL,"[-0.21411, 44.90036]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006952,2025-12-11,2025-12-17T09:36:45.000000+0000
1120,15534,bornes@lidl.fr,LIDL,"[-0.21413, 44.90003]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006949,2025-12-11,2025-12-17T09:36:45.000000+0000

### Defauts operateur IZIVIA
Les défauts au nombre de 330 sont liés à une incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Izivia en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance, ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur un parking [-0.530598, 47.398424], on trouve 17 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué entre 1 et 3.

In [224]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'sav@izivia.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
125,2280,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11111,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11111,2025-09-30,2025-09-30T08:35:00.000000+0000
126,2281,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG111101,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG111101,2025-09-30,2025-09-30T08:35:00.000000+0000
127,2282,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11221,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11221,2025-09-30,2025-09-30T08:35:00.000000+0000
128,2283,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11331,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11331,2025-09-30,2025-09-30T08:35:00.000000+0000
129,2284,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11441,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11441,2025-09-30,2025-09-30T08:35:00.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10723,127307,sav@izivia.com,McDonald's - SAINT JOUAN DES GUERETS,"[-1.97506, 48.60402]","Avenue des Français Libres, 35430 ST JOUAN DES...",FRIZFPFAST455,IZIVIA FAST - McDonald's - SAINT JOUAN DES GUE...,Voirie,2,Accès libre,24/7,false,FRIZFEFAST45511,2026-02-27,2026-02-28T00:40:31.000000+0000
10724,127308,sav@izivia.com,1414,"[3.98880, 47.85258]","Les Petits Jumeriaux, 89700 TONNERRE",FRIZFPFAST468,IZIVIA FAST - McDonald's - TONNERRE,Voirie,2,Accès libre,24/7,false,FRIZFEFAST46811,2026-02-27,2026-02-28T00:40:31.000000+0000
10725,127310,sav@izivia.com,1163,"[-4.21755, 47.88236]","7 Rue Hyacinthe Le Bleis, 29120 PONT L'ABBE",FRIZFPFAST469,IZIVIA FAST - McDonald's - PONT LABBE,Voirie,2,Accès libre,24/7,false,FRIZFEFAST46913,2026-02-27,2026-02-28T00:40:31.000000+0000
10734,127326,sav@izivia.com,695,"[-1.55260, 48.83804]","605 Rte de Villedieu, 50400 YQUELON",FRIZFPFAST470,IZIVIA FAST - McDonald's - GRANVILLE,Voirie,2,Accès libre,24/7,false,FRIZFEFAST47013,2026-02-27,2026-02-28T00:40:31.000000+0000
10735,127327,sav@izivia.com,McDonald's - SAINT ANDRE DE CUBZAC 1,"[-0.43724, 45.00601]","290 Rue nationale, 33240 ST ANDRE DE CUBZAC",FRIZFPFAST498,IZIVIA FAST - McDonald's - SAINT ANDRE DE CUBZ...,Voirie,2,Accès libre,24/7,false,FRIZFEFAST49813,2026-02-27,2026-02-28T00:40:31.000000+0000

In [225]:
itinerance_4.loc[(~itinerance_4['adresse_station - coordonneesXY']) & (itinerance_4['contact_operateur'] == 'sav@izivia.com') , relations].sort_values(by=["coordonneesXY"])[0:50]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
6932,86697,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10311,2026-02-27,2026-02-27T07:34:28.000000+0000
6933,86698,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10312,2026-02-27,2026-02-27T07:34:28.000000+0000
6934,86699,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10321,2026-02-27,2026-02-27T07:34:28.000000+0000
6935,86700,sav@izivia.com,Wiiiz,"[43.56724, 6.94806]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,false,FRA16EWIIZ10322,2026-02-27,2026-02-27T07:34:28.000000+0000
125,2280,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11111,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11111,2025-09-30,2025-09-30T08:35:00.000000+0000
150,2679,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2831,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2831,2025-09-30,2025-09-30T08:35:00.000000+0000
151,2680,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2841,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2841,2025-09-30,2025-09-30T08:35:00.000000+0000
152,2681,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2851,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2851,2025-09-30,2025-09-30T08:35:00.000000+0000
153,2682,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2861,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2861,2025-09-30,2025-09-30T08:35:00.000000+0000
154,2683,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2871,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2871,2025-09-30,2025-09-30T08:35:00.000000+0000
155,2684,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2881,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2881,2025-09-30,2025-09-30T08:35:00.000000+0000
156,2685,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2891,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2891,2025-09-30,2025-09-30T08:35:00.000000+0000
326,3306,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4681,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4681,2025-09-30,2025-09-30T08:35:00.000000+0000
324,3304,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4661,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4661,2025-09-30,2025-09-30T08:35:00.000000+0000
149,2678,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2821,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2821,2025-09-30,2025-09-30T08:35:00.000000+0000
323,3303,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4651,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4651,2025-09-30,2025-09-30T08:35:00.000000+0000
322,3302,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4641,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4641,2025-09-30,2025-09-30T08:35:00.000000+0000
321,3301,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4631,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4631,2025-09-30,2025-09-30T08:35:00.000000+0000
320,3300,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4621,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4621,2025-09-30,2025-09-30T08:35:00.000000+0000
319,3299,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG46101,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG46101,2025-09-30,2025-09-30T08:35:00.000000+0000
318,3298,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4611,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4611,2025-09-30,2025-09-30T08:35:00.000000+0000
325,3305,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4671,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4671,2025-09-30,2025-09-30T08:35:00.000000+0000
148,2677,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG28121,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG28121,2025-09-30,2025-09-30T08:35:00.000000+0000
327,3307,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG4691,CNPE BUGEY - UFPI - BORNES EXISTANTES,Voirie,1,Accès libre,24/7,false,FROTHEIZIG4691,2025-09-30,2025-09-30T08:35:00.000000+0000
146,2675,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG28101,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG28101,2025-09-30,2025-09-30T08:35:00.000000+0000
128,2283,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11331,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11331,2025-09-30,2025-09-30T08:35:00.000000+0000
127,2282,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11221,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11221,2025-09-30,2025-09-30T08:35:00.000000+0000
126,2281,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG111101,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG111101,2025-09-30,2025-09-30T08:35:00.000000+0000
147,2676,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG28111,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG28111,2025-09-30,2025-09-30T08:35:00.000000+0000
130,2285,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11551,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11551,2025-09-30,2025-09-30T08:35:00.000000+0000
131,2286,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11661,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11661,2025-09-30,2025-09-30T08:35:00.000000+0000
132,2287,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11771,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11771,2025-09-30,2025-09-30T08:35:00.000000+0000
133,2288,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11881,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11881,2025-09-30,2025-09-30T08:35:00.000000+0000
134,2289,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11991,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11991,2025-09-30,2025-09-30T08:35:00.000000+0000
135,2659,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2711,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2711,2025-09-30,2025-09-30T08:35:00.000000+0000
136,2660,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG27101,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG27101,2025-09-30,2025-09-30T08:35:00.000000+0000
137,2661,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2721,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2721,2025-09-30,2025-09-30T08:35:00.000000+0000
129,2284,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",400 AVENUE COTIER 01150 SAINT VULBAS,FROTHPIZIG11441,CNPE BUGEY - CAMPUS UFPI - REMPLACEMENT,Voirie,1,Accès libre,24/7,false,FROTHEIZIG11441,2025-09-30,2025-09-30T08:35:00.000000+0000
138,2662,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2731,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2731,2025-09-30,2025-09-30T08:35:00.000000+0000
140,2664,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2751,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2751,2025-09-30,2025-09-30T08:35:00.000000+0000
145,2674,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2811,CNPE BUGEY - SUD 2 UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2811,2025-09-30,2025-09-30T08:35:00.000000+0000
144,2668,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2791,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2791,2025-09-30,2025-09-30T08:35:00.000000+0000
143,2667,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2781,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2781,2025-09-30,2025-09-30T08:35:00.000000+0000
142,2666,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2771,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2771,2025-09-30,2025-09-30T08:35:00.000000+0000
139,2663,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2741,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2741,2025-09-30,2025-09-30T08:35:00.000000+0000
141,2665,sav@izivia.com,EDF-EV100,"[45.80226, 5.26600]",AVENUE COTIER 01150 SAINT-VULBAS,FROTHPIZIG2761,CNPE BUGEY - CAMPUS UFPI,Voirie,1,Accès libre,24/7,false,FROTHEIZIG2761,2025-09-30,2025-09-30T08:35:00.000000+0000
404,5469,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37291,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37291,2025-09-30,2025-09-30T08:35:00.000000+0000
403,5468,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37281,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37281,2025-09-30,2025-09-30T08:35:00.000000+0000
402,5467,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37271,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37271,2025-09-30,2025-09-30T08:35:00.000000+0000
395,5460,sav@izivia.com,SYSTEME U,"[47.39842, -0.53059]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372111,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372111,2025-09-30,2025-09-30T08:35:00.000000+0000

In [226]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-0.530598, 47.398424]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Defauts operateur ENIplenitude
Les défauts (200 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Ionity en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance ainsi qu'un ancien pdc de regroupement par station avec un nom d'enseigne différent (IONITY GMBH), ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur l'aire de Mornas [4.732409, 44.194832], on trouve 26 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué de 23 pour chaque station.

In [227]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'support@service.emob.eniplenitude.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
7651,95137,support@service.emob.eniplenitude.com,"154 Impasse de, La Grande Grange","[5.55677, 45.28749]","154 Impasse de, La Grande Grange, 38210 Saint-...",FRPLNEH000963,"154 Impasse de, La Grande Grange",Station dédiée à la recharge rapide,12,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0009631,2026-02-27,2026-02-27T20:00:20.000000+0000
7652,95138,support@service.emob.eniplenitude.com,"154 Impasse de, La Grande Grange","[5.55677, 45.28749]","154 Impasse de, La Grande Grange, 38210 Saint-...",FRPLNEH000963,"154 Impasse de, La Grande Grange",Station dédiée à la recharge rapide,12,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0009632,2026-02-27,2026-02-27T20:00:20.000000+0000
7653,95139,support@service.emob.eniplenitude.com,"154 Impasse de, La Grande Grange","[5.55677, 45.28749]","154 Impasse de, La Grande Grange, 38210 Saint-...",FRPLNEH000963,"154 Impasse de, La Grande Grange",Voirie,12,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0009633,2026-02-27,2026-02-27T20:00:20.000000+0000
7654,95140,support@service.emob.eniplenitude.com,"154 Impasse de, La Grande Grange","[5.55677, 45.28749]","154 Impasse de, La Grande Grange, 38210 Saint-...",FRPLNEH001123,"154 Impasse de, La Grande Grange",Station dédiée à la recharge rapide,12,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0011231,2026-02-27,2026-02-27T20:00:20.000000+0000
7655,95141,support@service.emob.eniplenitude.com,"154 Impasse de, La Grande Grange","[5.55677, 45.28749]","154 Impasse de, La Grande Grange, 38210 Saint-...",FRPLNEH001123,"154 Impasse de, La Grande Grange",Station dédiée à la recharge rapide,12,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0011232,2026-02-27,2026-02-27T20:00:20.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7854,95655,support@service.emob.eniplenitude.com,Eni Station - 32 Av. Rhin et Danube,"[5.70518, 45.17892]","32 Av. Rhin et Danube, 38185 Grenoble",FRPLNEH000740,Eni Station - 32 Av. Rhin et Danube,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0007401,2026-02-27,2026-02-27T20:00:20.000000+0000
7855,95656,support@service.emob.eniplenitude.com,Eni Station - 32 Av. Rhin et Danube,"[5.70518, 45.17892]","32 Av. Rhin et Danube, 38185 Grenoble",FRPLNEH000740,Eni Station - 32 Av. Rhin et Danube,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0007402,2026-02-27,2026-02-27T20:00:20.000000+0000
7856,95657,support@service.emob.eniplenitude.com,Eni Station - 32 Av. Rhin et Danube,"[5.70518, 45.17892]","32 Av. Rhin et Danube, 38185 Grenoble",FRPLNEH000740,Eni Station - 32 Av. Rhin et Danube,Voirie,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0007403,2026-02-27,2026-02-27T20:00:20.000000+0000
7857,95658,support@service.emob.eniplenitude.com,Eni Station - 4 ROUTE D'ALTENHEIM,"[7.76553, 48.54346]","4 ROUTE D'ALTENHEIM, 67073 Strasbourg",FRPLNEH000562,Eni Station - 4 ROUTE D'ALTENHEIM,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0005621,2026-02-27,2026-02-27T20:00:20.000000+0000
7858,95659,support@service.emob.eniplenitude.com,Eni Station - 4 ROUTE D'ALTENHEIM,"[7.76553, 48.54346]","4 ROUTE D'ALTENHEIM, 67073 Strasbourg",FRPLNEH000562,Eni Station - 4 ROUTE D'ALTENHEIM,Voirie,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0005623,2026-02-27,2026-02-27T20:00:20.000000+0000

In [228]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRPLNEH002131', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
7775,95408,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054, 45.85570]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021311,2026-02-27,2026-02-27T20:00:20.000000+0000
7776,95409,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054, 45.85570]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021312,2026-02-27,2026-02-27T20:00:20.000000+0000
7777,95410,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054, 45.85570]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021313,2026-02-27,2026-02-27T20:00:20.000000+0000
7778,95411,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054, 45.85570]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Voirie,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021314,2026-02-27,2026-02-27T20:00:20.000000+0000

### Defauts operateur MOBILIZE
Les défauts (350 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

In [229]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'fastcharge.exploitation@mobilize.com', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [230]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRMFCEALBERTVILLE', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Cohérence implantation_station - id_station
- 107 pdc sont liés à une erreur de choix d'implantation (couplé à d'autres erreurs)

In [231]:
itinerance_4.loc[~itinerance_4['implantation_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
39,207,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.000000+0000
40,208,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.000000+0000
41,211,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,false,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.000000+0000
42,212,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,false,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.000000+0000
43,213,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,false,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7869,98675,support@iecharge.io,Vezin-le-Coquet,"[-1.75494, 48.12518]","4001 Rue de la Belle-Epine, 35132 Vezin-le-Coquet",FRIENE35353A,Vezin-le-Coquet,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRIENE35353A1,2026-02-27,2026-02-27T20:00:20.000000+0000
7870,98676,support@iecharge.io,Vezin-le-Coquet,"[-1.75494, 48.12518]","4001 Rue de la Belle-Epine, 35132 Vezin-le-Coquet",FRIENE35353A,Vezin-le-Coquet,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRIENE35353A2,2026-02-27,2026-02-27T20:00:20.000000+0000
7871,98677,support@iecharge.io,Vezin-le-Coquet,"[-1.75494, 48.12518]","4001 Rue de la Belle-Epine, 35132 Vezin-le-Coquet",FRIENE35353A,Vezin-le-Coquet,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRIENE35353A3,2026-02-27,2026-02-27T20:00:20.000000+0000
7872,98678,support@iecharge.io,Vezin-le-Coquet,"[-1.75494, 48.12518]","4001 Rue de la Belle-Epine, 35132 Vezin-le-Coquet",FRIENE35353A,Vezin-le-Coquet,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRIENE35353A4,2026-02-27,2026-02-27T20:00:20.000000+0000
7873,98679,support@iecharge.io,Vezin-le-Coquet,"[-1.75494, 48.12518]","4001 Rue de la Belle-Epine, 35132 Vezin-le-Coquet",FRIENE35353A,Vezin-le-Coquet,Voirie,5,Accès réservé,24/7,false,FRIENE35353A5,2026-02-27,2026-02-27T20:00:20.000000+0000

### Cohérence nom_station - id_station
- 210 pdc sont associés à une station avec un nom non cohérent

In [232]:
itinerance_4.loc[~itinerance_4['nom_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
39,207,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.000000+0000
40,208,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.000000+0000
41,211,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,false,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.000000+0000
42,212,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,false,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.000000+0000
43,213,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,false,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7907,100785,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8221,2026-02-27,2026-02-27T07:32:06.000000+0000
7908,100786,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8231,2026-02-27,2026-02-27T07:32:06.000000+0000
7909,100787,sav@izivia.com,QPARK,"[48.68130, 6.18956]",10 Av. Dr Heydenreich 54000 Nancy,FRQPKPQPRK82,QPARK - NANCY CHRU MATERNITÉ - 10 Avenue du Do...,Voirie,4,Accès libre,24/7,false,FRQPKEQPRK8241,2026-02-27,2026-02-27T07:32:06.000000+0000
9202,119118,sav@izivia.com,GPSO,"[2.25867, 48.83370]","6 Avenue la Voie Lactée, 92100 Boulogne-Billan...",FRSIGPSIGE529,"SIGEIF - Boulogne Billancourt, Avenue de la Vo...",Voirie,2,Accès libre,24/7,false,FRSIGESIGE52913,2026-02-27,2026-02-28T00:40:31.000000+0000
10076,122246,sav@izivia.com,GPSO,"[2.25867, 48.83370]","6 Avenue la Voie Lactée, 92100 Boulogne-Billan...",FRSIGPSIGE529,"SIGEIF - Boulogne Billancourt, Avenue de la Vo...",Voirie,2,Accès libre,24/7,false,FRSIGESIGE52911,2026-02-27,2026-02-28T00:40:31.000000+0000

### Coherence adresse - coordonnees
- 2337 pdc ont une adresse non cohérente avec les coordonnées géographiques

In [233]:
itinerance_4.loc[~itinerance_4['adresse_station - coordonneesXY'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
0,12,info@ionity.eu,IONITY GMBH,"[0.60966, 44.17130]","ZA du, Impasse de Beauregard, 47520 Le Passage...",FRIONE432700,IONITY Agen,Station dédiée à la recharge rapide,4,Accès libre,24/7,false,FRIONE4327,2023-03-21,2024-12-06T06:46:06.000000+0000
1,13,info@ionity.eu,IONITY GMBH,"[6.15826, 45.54878]","A43 L'aire de L'Arclusaz, 73390 Chateauneuf, F...",FRIONE409900,IONITY Arclusaz,Station dédiée à la recharge rapide,5,Accès libre,24/7,false,FRIONE4099,2023-03-21,2024-12-06T06:46:06.000000+0000
2,17,info@ionity.eu,IONITY GMBH,"[1.38781, 47.66402]",Aire de Blois Ménars - A10 - 41000 VILLERBON,FRIONE407800,IONITY Blois Ménars,Station dédiée à la recharge rapide,5,Accès libre,24/7,false,FRIONE4078,2023-03-21,2024-12-06T06:46:06.000000+0000
3,18,info@ionity.eu,IONITY GMBH,"[1.38775, 47.66588]",Aire de Blois Villerbon - A10 - 41000 VILLERBON,FRIONE408000,IONITY Blois Villerbon,Station dédiée à la recharge rapide,5,Accès libre,24/7,false,FRIONE4080,2023-03-21,2024-12-06T06:46:06.000000+0000
4,19,info@ionity.eu,IONITY GMBH,"[5.10745, 47.03076]",Aire de Bois Guillerot - A36 - 21250 Glanon,FRIONE412300,IONITY Bois Guillerot,Station dédiée à la recharge rapide,5,Accès libre,24/7,false,FRIONE4123,2023-03-21,2024-12-06T06:46:06.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12945,148277,support@evzen.com,EVzen,"[1.38396, 44.03857]","Za Futuropole, 510 Rte du N 510 82000 Montauban",FREVZPE870D4C6060F43B6B69FE09612E36,"EVzen - Montauban, NORAUTO Montauban",Station dédiée à la recharge rapide,6,Accès libre,24/7,false,FREVZEFREVZEADER2,2026-02-27,2026-02-28T00:40:31.000000+0000
12946,148280,support@evzen.com,EVzen,"[3.12736, 45.75694]",Av. de la Margeride 66 63170 Aubière,FREVZP65A1A5C0CB9245B398161508E736A,"EVzen - Aubière, NORAUTO Clermont Ferrand Aubiere",Station dédiée à la recharge rapide,3,Accès libre,"Sa 08:00-19:30, Fr 08:00-19:30, Th 08:00-19:30...",false,FREVZEFREVZEARAS2,2026-02-27,2026-02-28T00:40:31.000000+0000
12947,148283,support@evzen.com,EVzen,"[2.00261, 46.95691]",Rue De La Limoise 36100 Issoudun,FREVZP931730135A254DAFA30C1E3860EA5,"EVzen - Issoudun, V and B Issoudun",Parking privé à usage public,3,Accès libre,24/7,false,FREVZEFREVZEREYA1,2026-02-27,2026-02-28T00:40:31.000000+0000
12948,148284,support@evzen.com,EVzen,"[2.00261, 46.95691]",Rue De La Limoise 36100 Issoudun,FREVZP931730135A254DAFA30C1E3860EA5,"EVzen - Issoudun, V and B Issoudun",Parking privé à usage public,3,Accès libre,24/7,false,FREVZEFREVZERYUU1,2026-02-27,2026-02-28T00:40:31.000000+0000
12949,148285,support@evzen.com,EVzen,"[7.37627, 48.10655]",Rue Denis Papin 68000 Colmar,FREVZP028141431E3B4F86B2982E7EF19D3,"EVzen - Colmar, Joker Courses",Station dédiée à la recharge rapide,7,Accès libre,24/7,false,FREVZEFREVZEMIAN1,2026-02-27,2026-02-28T00:40:31.000000+0000

In [234]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[5.2592028, 46.1746523]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [235]:
itinerance_4.loc[itinerance_4.adresse_station == 'RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
594,11136,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.000000+0000
597,11139,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.000000+0000

In [236]:
itinerance_4.loc[itinerance_4.adresse_station == ' RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
595,11137,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.000000+0000
596,11138,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[46.17465, 5.25920]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.000000+0000

### Cohérence station - coordonnées
- 218 pdc sont associés à des stations avec plusieurs coordonnées (majorité AlizeCharge)

In [237]:
itinerance_4.loc[~itinerance_4['coordonneesXY - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
39,207,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.000000+0000
40,208,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06618, 48.62376]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,false,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.000000+0000
41,211,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,false,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.000000+0000
42,212,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,false,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.000000+0000
43,213,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.06437, 48.62946]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,false,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10666,126953,sav@izivia.com,NORAUTO,"[2.43462, 48.71351]","4 Rue des GauloisCentre Commercial Valdoly, 91...",FRE04POAZS264,NORAUTO - VIGNEUX MONTGERON,Voirie,4,Accès libre,24/7,false,FRE04EOAZS26412,2026-02-27,2026-02-28T00:40:31.000000+0000
10667,126957,sav@izivia.com,NORAUTO,"[2.35252, 49.00702]","Rue Jean MonnetZAE Les Perruches, Centre Comme...",FRE04POAZS270,NORAUTO - SAINT BRICE,Voirie,4,Accès libre,24/7,false,FRE04EOAZS27012,2026-02-27,2026-02-28T00:40:31.000000+0000
10668,126958,sav@izivia.com,NORAUTO,"[2.43833, 48.78074]","6 Rue de la Font Saint-Christophe, 94000 Créteil",FRE04POAZS278,NORAUTO - CRÉTEIL,Voirie,4,Accès libre,24/7,false,FRE04EOAZS27811,2026-02-27,2026-02-28T00:40:31.000000+0000
10671,126979,sav@izivia.com,NORAUTO - SAINT-NAZAIRE,"[-2.21196, 47.30312]","Rue de la Fontaine au Brun, 44570 Trignac",FRE04POAZS280,NORAUTO - SAINT-NAZAIRE,Voirie,4,Accès libre,24/7,false,FRE04EOAZS28012,2026-02-27,2026-02-28T00:40:31.000000+0000
10683,127136,sav@izivia.com,BOURGUEIL,"[0.16741, 47.27248]","27 Avenue du Général de Gaulle, 37140 Bourgueil",FRE04POAZS283,HYPER U - BOURGUEIL,Voirie,4,Accès libre,24/7,false,FRE04EOAZS28322,2026-02-27,2026-02-28T00:40:31.000000+0000

In [238]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRTLSE31555040', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [239]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRFR1PEHNKRRPQNR', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : une station avec plusieurs coordonnées -> incompréhension distinction station / pdc

In [240]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR073PCAMAIEUFR', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
500,10352,acelec@acelec-france.com,Camaïeu France,"[3.20743, 50.68487]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EREUO5946,2022-07-21,2024-12-06T06:46:31.000000+0000
501,10353,acelec@acelec-france.com,Camaïeu France,"[3.20743, 50.68487]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EQ1GI51176,2022-07-21,2024-12-06T06:46:31.000000+0000
502,10354,acelec@acelec-france.com,Camaïeu France,"[3.20737, 50.68489]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ECC1C5530,2022-07-21,2024-12-06T06:46:31.000000+0000
503,10355,acelec@acelec-france.com,Camaïeu France,"[3.20737, 50.68489]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EO0AV51091,2022-07-21,2024-12-06T06:46:31.000000+0000
504,10356,acelec@acelec-france.com,Camaïeu France,"[3.20730, 50.68491]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EK0BJ522,2022-07-21,2024-12-06T06:46:31.000000+0000
505,10357,acelec@acelec-france.com,Camaïeu France,"[3.20730, 50.68491]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E0HKH51125,2022-07-21,2024-12-06T06:46:31.000000+0000
506,10358,acelec@acelec-france.com,Camaïeu France,"[3.20724, 50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E8OV45243,2022-07-21,2024-12-06T06:46:31.000000+0000
507,10359,acelec@acelec-france.com,Camaïeu France,"[3.20724, 50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EYLF65474,2022-07-21,2024-12-06T06:46:31.000000+0000
508,10360,acelec@acelec-france.com,Camaïeu France,"[3.20718, 50.68496]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ETCIX5105,2022-07-21,2024-12-06T06:46:31.000000+0000
509,10361,acelec@acelec-france.com,Camaïeu France,"[3.20718, 50.68496]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP7QU5233,2022-07-21,2024-12-06T06:46:31.000000+0000
510,10362,acelec@acelec-france.com,Camaïeu France,"[3.20712, 50.68498]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EU6RQ5270,2022-07-21,2024-12-06T06:46:31.000000+0000
511,10363,acelec@acelec-france.com,Camaïeu France,"[3.20712, 50.68498]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EBEQA5957,2022-07-21,2024-12-06T06:46:31.000000+0000
512,10364,acelec@acelec-france.com,Camaïeu France,"[3.20704, 50.68501]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EMZLV5283,2022-07-21,2024-12-06T06:46:31.000000+0000
513,10365,acelec@acelec-france.com,Camaïeu France,"[3.20704, 50.68501]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EUHNJ5886,2022-07-21,2024-12-06T06:46:31.000000+0000
514,10366,acelec@acelec-france.com,Camaïeu France,"[3.20696, 50.68504]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP9LD51287,2022-07-21,2024-12-06T06:46:31.000000+0000
515,10367,acelec@acelec-france.com,Camaïeu France,"[3.20696, 50.68504]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EXINB5826,2022-07-21,2024-12-06T06:46:31.000000+0000

- exemple : une station avec plusieurs coordonnées -> regroupement de stations ?

In [241]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR55CPBP514', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : plusieurs stations d'opérateurs différents avec les mêmes coordonnées -> suppression non effectuée lors d'un changement d'opérateur ?

In [242]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[0.08745032, 48.40887156]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [243]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-4.374469, 48.471878]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : quatre stations avec une localisation identique mais deux adresses différentes + id identique entre station et pdc -> erreur d'adresse et erreur d'id_station ?

In [244]:
itinerance_5.loc[itinerance_5.coordonneesXY	 == '[-0.366184, 43.332508]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Incoherence nbre_pdc
- 583 pdc ont un champ 'nbre_pdc' mal documenté

In [245]:
itinerance_4.loc[~itinerance_4['nbre_pdc - id_station_itinerance'], relations][200:215]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1892,18500,support@dream-energy.fr,ARTEPARC BIOT,"[43.62316, 7.06858]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,3,Accès libre,24/7,false,FRDREE10001534971,2025-04-23,2026-01-08T20:43:20.000000+0000
1893,18501,support@dream-energy.fr,ARTEPARC BIOT,"[43.62316, 7.06858]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,3,Accès libre,24/7,false,FRDREE10001534972,2025-04-23,2026-01-08T20:43:20.000000+0000
1894,18502,support@dream-energy.fr,ARTEPARC BIOT,"[43.62316, 7.06858]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,3,Accès libre,24/7,false,FRDREE10001534973,2025-04-23,2026-01-08T20:43:20.000000+0000
1895,18503,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440041,2025-04-23,2026-01-08T20:43:20.000000+0000
1896,18504,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440042,2025-04-23,2026-01-08T20:43:20.000000+0000
1897,18505,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,3,Accès libre,24/7,false,FRDREE10001440051,2025-04-23,2026-01-08T20:43:20.000000+0000
1898,18506,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,3,Accès libre,24/7,false,FRDREE10001440052,2025-04-23,2026-01-08T20:43:20.000000+0000
1899,18507,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,3,Accès libre,24/7,false,FRDREE10001440053,2025-04-23,2026-01-08T20:43:20.000000+0000
1900,18508,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440061,2025-04-23,2026-01-08T20:43:20.000000+0000
1901,18509,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440062,2025-04-23,2026-01-08T20:43:20.000000+0000
1902,18510,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440071,2025-04-23,2026-01-08T20:43:20.000000+0000
1904,18512,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440081,2025-04-23,2026-01-08T20:43:20.000000+0000
1905,18513,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440082,2025-04-23,2026-01-08T20:43:20.000000+0000
1906,18514,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440091,2025-04-23,2026-01-08T20:43:20.000000+0000
1907,18515,support@dream-energy.fr,ARTEPARC LESQUIN,"[50.59708, 3.13065]",97 Rue Marcel Sembat - LESQUIN 59810,FRDREP89899387,LESQUIN,Parking public,2,Accès libre,24/7,false,FRDREE10001440092,2025-04-23,2026-01-08T20:43:20.000000+0000

### coherence station - enseigne
- 5 stations ont plusieurs noms d'enseigne

In [246]:
itinerance_4.loc[~itinerance_4['nom_enseigne - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
634,11886,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.000000+0000
635,11887,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.000000+0000
636,11888,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS3,2022-10-04,2024-12-06T06:49:29.000000+0000
1428,16351,contact@rirodo.fr,LAST MILES SOLUTIONS,"[43.27000, 5.39000]",20 Rue Negresko,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRLMSE1897228,2023-09-06,2024-12-06T06:47:15.000000+0000
1429,16352,contact@rirodo.fr,MONTA,"[43.27000, 5.39000]",20 Rue NEGRESKO,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRRIRE2804856,2023-09-06,2024-12-06T06:47:15.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10666,126953,sav@izivia.com,NORAUTO,"[2.43462, 48.71351]","4 Rue des GauloisCentre Commercial Valdoly, 91...",FRE04POAZS264,NORAUTO - VIGNEUX MONTGERON,Voirie,4,Accès libre,24/7,false,FRE04EOAZS26412,2026-02-27,2026-02-28T00:40:31.000000+0000
10667,126957,sav@izivia.com,NORAUTO,"[2.35252, 49.00702]","Rue Jean MonnetZAE Les Perruches, Centre Comme...",FRE04POAZS270,NORAUTO - SAINT BRICE,Voirie,4,Accès libre,24/7,false,FRE04EOAZS27012,2026-02-27,2026-02-28T00:40:31.000000+0000
10668,126958,sav@izivia.com,NORAUTO,"[2.43833, 48.78074]","6 Rue de la Font Saint-Christophe, 94000 Créteil",FRE04POAZS278,NORAUTO - CRÉTEIL,Voirie,4,Accès libre,24/7,false,FRE04EOAZS27811,2026-02-27,2026-02-28T00:40:31.000000+0000
10671,126979,sav@izivia.com,NORAUTO - SAINT-NAZAIRE,"[-2.21196, 47.30312]","Rue de la Fontaine au Brun, 44570 Trignac",FRE04POAZS280,NORAUTO - SAINT-NAZAIRE,Voirie,4,Accès libre,24/7,false,FRE04EOAZS28012,2026-02-27,2026-02-28T00:40:31.000000+0000
10683,127136,sav@izivia.com,BOURGUEIL,"[0.16741, 47.27248]","27 Avenue du Général de Gaulle, 37140 Bourgueil",FRE04POAZS283,HYPER U - BOURGUEIL,Voirie,4,Accès libre,24/7,false,FRE04EOAZS28322,2026-02-27,2026-02-28T00:40:31.000000+0000

In [247]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRFR1EAYRU', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
11332,11346,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.000000+0000
11333,11347,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.000000+0000
11334,11348,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU3,2022-08-25,2024-12-06T06:49:41.000000+0000
12322,12336,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.000000+0000
12323,12337,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.000000+0000
12324,12338,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS3,2022-12-09,2024-12-06T06:49:25.000000+0000

In [248]:
itinerance_init.loc[itinerance_init.nom_enseigne == 'RME Loos (FR-FR1)', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
11332,11346,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.000000+0000
11333,11347,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02000, 50.61000]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.000000+0000
11872,11886,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.000000+0000
11873,11887,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61750, 3.00961]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,false,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.000000+0000
12322,12336,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.000000+0000
12323,12337,contact@electricite-loos.fr,RME Loos (FR-FR1),"[50.61544, 3.01427]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,false,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.000000+0000

### cohérence station - horaires
- exemple de station avec plusieurs types d'horaire (15)

In [249]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRS23D2302001', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
17940,18114,contact@mobive.fr,Réseau MOBIVE,"[45.98220, 2.29763]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:01,false,FRS23P230200101,2023-03-09,2025-09-11T07:22:20.000000+0000
17941,18115,contact@mobive.fr,Réseau MOBIVE,"[45.98220, 2.29763]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:02,false,FRS23P230200102,2023-03-09,2025-09-11T07:22:20.000000+0000

### cohérence station - deux-roues
- exemple de station avec plusieurs indications d'accessibilité deux-roues (583)

In [250]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRV75PPX1716', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
119150,119326,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17165,2025-06-30,2026-02-28T00:40:31.000000+0000
119219,119395,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17167,2025-06-30,2026-02-28T00:40:31.000000+0000
122128,122304,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17162,2025-06-30,2026-02-28T00:40:31.000000+0000
122139,122315,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17163,2025-06-30,2026-02-28T00:40:31.000000+0000
125819,125995,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17164,2025-06-30,2026-02-28T00:40:31.000000+0000
129392,129568,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17161,2025-06-30,2026-02-28T00:40:31.000000+0000
140471,140647,supervision-ev.france@totalenergies.com,Belib',"[2.32420, 48.89575]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,false,FRV75EPX17166,2025-06-30,2026-02-28T00:40:31.000000+0000

### stations avec pdc > 350 kW

- exemple de station avec une puissance de plus de 350 kW

In [251]:
data['p_nom'] = data['puissance_nominale'].str.replace(",", ".")

In [252]:
data['p_nom'] = data['p_nom'].astype('float')

In [253]:
from copy import copy
data350 = copy(data.loc[data["p_nom"] > 350, :])

In [254]:
data350['index'] = 0

In [255]:
data350.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
18169,0,contact@sowattsolutions.com,SOWATT SOLUTIONS,"[6.07734, 45.88929]",268 Route des Creuses 74600 Seynod,FRSWSE1000149991,ABB T360 VW Seynod 1,Station dédiée à la recharge rapide,2,Accès libre,24/7,false,FRSWSE10001499913,2025-11-12,2025-11-12T14:07:06.000000+0000
18333,0,c.blanchot@enerjump.fr,Watt'up,"[48.99178, 2.65176]",RUE ELISABETH BOSELLI 77290 COMPANS,FR190P770001SPE24,Compans Watt'up Truck,Station dédiée à la recharge rapide,4,Accès libre,24/7,false,FR190E770001SPE24ALP400121,2025-01-08,2025-01-17T06:30:12.000000+0000
18334,0,c.blanchot@enerjump.fr,Watt'up,"[48.99178, 2.65176]",RUE ELISABETH BOSELLI 77290 COMPANS,FR190P770001SPE24,Compans Watt'up Truck,Station dédiée à la recharge rapide,4,Accès libre,24/7,false,FR190E770001SPE24ALP400122,2025-01-08,2025-01-17T06:30:12.000000+0000
18458,0,energy@milence.com,Milence,"[49.19453, 1.22521]",Rte de Louviers 2 Heudebouville,FRMILP000003,Milence Charging Hub Heudebouville,Parking privé à usage public,2,Accès réservé,24/7,false,FRMILE000003,2025-04-18,2025-04-21T03:46:17.000000+0000
18459,0,energy@milence.com,Milence,"[49.19453, 1.22521]",Rte de Louviers 2 Heudebouville,FRMILP000004,Milence Charging Hub Heudebouville,Parking privé à usage public,2,Accès réservé,24/7,false,FRMILE000004,2025-04-18,2025-04-21T03:46:17.000000+0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147403,0,charging-france@tesla.com,Tesla,"[5.47956, 43.29468]",Route de la Sablière,FRTSLP30237,"Marseille La Valentine, France",Parking public,16,Accès libre,24/7,false,FRTSLE00LTE5,2026-02-24,2026-02-28T00:40:31.000000+0000
148204,0,contact@lidl.fr,Lidl France,"[3.06045, 50.62238]","Boulevard Victor Hugo 116, 59000, Lille",FRLDLPLFR1188EVCP,LFR1188EVCP02,Parking public,2,Accès libre,Ma-Di 00:00-23:59; Lu 00:00-23:59,false,FRLDLE00006733,2026-02-27,2026-02-28T00:40:31.000000+0000
148211,0,contact@lidl.fr,Lidl France,"[3.11910, 50.62475]","Rue Roger Salengro 383, 59800, Lille",FRLDLPLFR2009EVCP,LFR2009EVCP02,Parking public,2,Accès libre,Ma-Di 08:30-19:30,false,FRLDLE00006736,2026-02-27,2026-02-28T00:40:31.000000+0000
148251,0,contact@lidl.fr,Lidl France,"[3.09202, 50.34416]","Rue du Maréchal Joffre 10, 59552, Lambres-Lez-...",FRLDLPLFR2670EVCP,LFR2670EVCP03,Parking public,2,Accès libre,Ma-Di 08:30-19:30,false,FRLDLE00006739,2026-02-27,2026-02-28T00:40:31.000000+0000
148278,0,contact@lidl.fr,Lidl France,"[3.11910, 50.62475]","Rue Roger Salengro 383, 59800, Lille",FRLDLPLFR2009EVCP,LFR2009EVCP02,Parking public,2,Accès libre,Ma-Di 08:30-19:30,false,FRLDLE00006735,2026-02-27,2026-02-28T00:40:31.000000+0000

In [256]:
data350['contact_operateur'].unique()

array(['contact@sowattsolutions.com', 'c.blanchot@enerjump.fr',
       'energy@milence.com', 'irve@soregies.fr', 'support@greenflux.com',
       'ops@obornes.fr', 'support@voltalia-mobility.com',
       'roaming@zunder.com', 'exploitation.irve@picoty.fr',
       'roaming-dev@road.io', 'operations.france@atlante.energy',
       'support@mobilize-ps.fr', 'info@ionity.eu', 'support@fastned.nl',
       'noc@milence.com', 'contact@enerjump.fr',
       'bppulsefranceops@bp.com', 'support.vianeo@engie.com',
       'kg@lastmilesolutions.com', 'contact@lidl.fr',
       'malek@autorecharge.fr', 'support@alizecharge.fr',
       'support@oreve.com', 'charging-france@tesla.com',
       'supervision-ev.france@totalenergies.com'], dtype=object)