## *Jeu de données IRVE*
-------------------
# Analyse des relations entre champs (intégrité des données)
------------------------------
## Contexte
- clarification du rôle des modèles de données dans les jeux de données (cf mise à jour récente des [guides data.gouv](https://guides.etalab.gouv.fr/qualite/documenter-les-donnees/))
- intégration d'une propriété "relationship" dans les schémas de données ([issue TableSchema](https://github.com/frictionlessdata/specs/issues/803) en cours de validation)
- création d'outils de contrôle des relations entre champs des jeux de données tabulaires (cf usage ci-dessous)

## Objectifs
- valider sur un cas réel l'utilisation d'un modèle de données en complément d'un schéma de données
- identifier les apports que pourraient avoir les contrôles de validation des relations entre champs

## Résultats
- les principaux résultats sont regroupés sur un [tableau de bord](https://nbviewer.org/github/loco-philippe/Environmental-Sensing/blob/main/python/Validation/irve/Analyse/IRVE_indicateurs.ipynb) 
- la formalisation d'un modèle de données facilite la compréhension des données et des relations entre champs
- l'outil de contrôle permet d'améliorer significativement la qualité des données par l'identification d'incohérences de relations
- l'identification des incohérences permet de trouver des stratégies de réduction des écarts (dans l'exemple ci-dessous, on passe 36% d'écart à 3,8 %)  
- l'analyse des données permet de (re)construire le modèle de données qui minimise les incohérences
- les incohérences détectées sur le jeu de données IRVE restent faibles (inférieures à 5 % des point de charge documentés - voir chapitre 4)

## Suite à donner
- Mettre à jour, valider et publier le modèle de données IRVE
- Définir les contrôles supplémentaires à intégrer pour toutes nouvelles données ainsi que pour le jeu complet
- Mettre en oeuvre les outils de contrôle

## Evolutions possibles 
- Ajouter dans les guides d'Etalab un guide pour les modèles de données 
- Intégrer dans les schémas de données la propriété "relationship" en cours de validation,
- Définir un indicateur qui mesure l'écart (existant / attendu) des relations entre champs

## Sommaire
*(liens actifs sur jupyter Notebook ou Nbviewer)*
- [1 - modèle de données](#1---modèle-de-données)
- [2 - Initialisation](#2---Initialisation)
- [3 - Séparation des pdc itinerance et hors itinerance](#3---Séparation-des-pdc-itinerance-et-hors-itinerance)
- [4 - Bilan initial intégrité](#4---Bilan-initial-intégrité)
- [5 - Séparation doublons pdc - date de maj](#5---Séparation-doublons-pdc---date-de-maj)
- [6 - Séparation doublons station - date de maj](#6---Séparation-doublons-station---date-de-maj)
- [7 - Synthèse](#7---Synthèse)
- [8 - Exemples d'erreurs résiduelles](#8---Exemples-d\'erreurs-résiduelles)

Ce Notebook peut être consulté sur [nbviewer](http://nbviewer.org/github/loco-philippe/Environmental-Sensing/tree/main/python/Validation/irve/Analyse)

données utilisées : https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/    
fichier : "*consolidation-etalab-schema-irve-statique-v-2.2.0-2024xxxx.csv*"

-----------------------
# 1 - modèle de données

Le modèle de données proposé ci-dessous est construit sur la base du schéma de données mis à disposition et du contenu du jeu de données.    
Il est à consolider en fonction de l'expertise des concepteurs et réutilisateurs (voir [guide méthodologique](https://github.com/loco-philippe/Environmental-Sensing/blob/main/property_relationship/FR_methodology.ipynb)).

*Notation:*
- *M : Mandatory - documentation obligatoire*
- *PK : Primary Key - identifiant unique de l'entité*
- *Root : champ fictif associé à une ligne du tableau*

In [1]:
from base64 import b64encode
from IPython.display import Image, display
with open('IRVE_modele.txt', 'r', encoding="utf-8") as f:
    modele = f.read()
display(Image(url="https://mermaid.ink/img/" + b64encode(modele.encode("ascii")).decode("ascii")))

------
# 2 - Initialisation
## initialisation logicielle

In [2]:
from datetime import datetime
import json
from tab_dataset import Cdataset
import pandas as pd
import ntv_pandas as npd
import pathlib

def analyse_integrite(data, schema, affiche=True, indic=True):
    '''analyse les relations du DataFrame 'data' définies dans le schéma 'schema'.
    Le nombre de ligne en erreur par relation (dict) est retourné et optionnellement affiché (paramètre 'affiche=True') . 
    Les lignes en erreur sont optionnellement ajoutées (paramètre 'indic=True') à 'data' sous forme de champs booléens par relation.
    '''
    dic_errors = Cdataset(data).check_relationship(schema)
    dic_count = {name: len(errors) for name, errors in dic_errors.items()}
    if affiche:
        for name, total in dic_count.items():
            print('{:<50} {:>5}'.format(name, total))
    if indic:
        data['ok'] = True
        for name, errors in dic_errors.items():
            data[name] = True
            data.loc[errors, name] = False
            data['ok'] = data['ok'] & data[name] 
    return dic_count

def add_nbre_pdc(data, affiche=True):
    '''ajoute un champ avec le nombre de pdc calculés et le compare au champ 'nbre_pdc'
    Le nombre d'écarts est affiché optionnellement (paramètre 'affiche=True').
    '''
    data['nb_pdc_calc'] = data.groupby('id_station_itinerance')['index'].transform('count')
    nbre_pdc = data['nbre_pdc'].astype('int')
    data['nbre_pdc_ok'] = data['nb_pdc_calc'] == nbre_pdc
    data['calc-nbre'] = data['nb_pdc_calc'] - nbre_pdc
    if affiche:
        ecart_nbre = len(data) - data['nbre_pdc_ok'].sum()
        print('{:<20} {:>5}'.format('nbre_pdc_ko', ecart_nbre))
        print(round(ecart_nbre / len(data) * 100), ' %')

## initialisation des données
- lecture du fichier issu de l'api 190 000 lignes (120 000 fin 2024)

In [3]:
dates = ['2023-03-03', '2023-04-17', '2023-05-02', '2023-05-24', '2023-06-17', '2023-07-04', '2023-07-23', '2023-08-08',
         '2023-09-06', '2023-09-19', '2023-10-04', '2023-10-21', '2023-10-31', '2023-11-23', '2023-12-14', '2023-12-29',
         '2024-01-15', '2024-02-07', '2024-02-28', '2024-03-27', '2024-04-24', '2024-05-19', '2024-06-05', '2024-08-02',
         '2024-10-24', '2024-11-27', '2025-01-03', '2025-10-04', '2025-11-18', '2026-02-18']
date= dates[-1]
log = {'date_irve': date, 
    'file': 'consolidation-etalab-schema-irve-statique-v-2.3.1-'+date[:4]+date[5:7]+date[8:]+'.csv', # après 2024-02-06
    'chemin': str(pathlib.Path(npd.__file__).parent.parent.parent/"Environmental-Sensing"/"python"/"Validation"/"irve"/"Analyse")
      }
irve = pd.read_csv(log['chemin'] + '/' + log['file'], sep=',', low_memory=False, dtype='object')
log['len_irve'] = len(irve)
print('nombre de lignes : ', log['len_irve'])

nombre de lignes :  209637

## schéma de données
Le schéma de données restreint à la propriété 'relationship' et construit à partir du modèle de données est le suivants :

In [4]:
# complément à inclure dans le schéma de données
schema = {
    'relationships': [
         # relation unicité des pdl
         {"fields": ["id_pdc_itinerance", "index"],                    "link" : "coupled" },   
         # relations inter entités
         {"fields": ["id_station_itinerance", "contact_operateur"],    "link" : "derived" },
         {"fields": ["id_station_itinerance", "nom_enseigne"],         "link" : "derived" },
         {"fields": ["id_station_itinerance", "coordonneesXY"],        "link" : "derived" },
         {"fields": ["id_pdc_itinerance", "id_station_itinerance"],    "link" : "derived" },
         # relations intra entité - station
         {"fields": ["id_station_itinerance", "nom_station"],          "link" : "derived" },
         {"fields": ["id_station_itinerance", "implantation_station"], "link" : "derived" },
         #{"fields": ["id_station_itinerance", "date_maj"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "nbre_pdc"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "condition_acces"],      "link" : "derived" },
         {"fields": ["id_station_itinerance", "horaires"],             "link" : "derived" },
         {"fields": ["id_station_itinerance", "station_deux_roues"],   "link" : "derived" },
         # relations intra entité - localisation
         {"fields": ["coordonneesXY", "adresse_station"],              "link" : "derived" }
    ]
}
# liste des champs liés à un controle (relations) et obligatoires (mandatory)
relations = ['index', 'contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 
             'nom_station', 'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 
             'id_pdc_itinerance', 'date_maj', 'last_modified']
mandatory = ['contact_operateur', 'nom_enseigne', 'coordonneesXY', 'adresse_station', 'id_station_itinerance', 'nom_station',
             'implantation_station', 'nbre_pdc', 'condition_acces', 'horaires', 'station_deux_roues', 'id_pdc_itinerance', 
             'puissance_nominale', 'prise_type_ef', 'prise_type_2', 'prise_type_combo_ccs', 'prise_type_chademo', 
             'prise_type_autre', 'paiement_acte', 'paiement_autre', 'reservation',  'accessibilite_pmr', 'restriction_gabarit', 
             'date_maj', 'last_modified']
controles = ['index - id_pdc_itinerance', 'contact_operateur - id_station_itinerance', 'nom_enseigne - id_station_itinerance',
             'coordonneesXY - id_station_itinerance', 'id_station_itinerance - id_pdc_itinerance',
             'nom_station - id_station_itinerance', 'implantation_station - id_station_itinerance',
             'nbre_pdc - id_station_itinerance', 'condition_acces - id_station_itinerance', 'horaires - id_station_itinerance',
             'station_deux_roues - id_station_itinerance', 'adresse_station - coordonneesXY']

-----------------------
## 3 - Séparation des pdc itinerance et hors itinerance
- 0.14 % des points de recharge sont hors itinerance (1 % en 2024)

In [5]:
# séparation des données
data = irve
data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']] = data[['id_station_itinerance','id_pdc_itinerance','restriction_gabarit']].astype('string')
#data[['last_modified','date_maj']] = data[['last_modified','date_maj']].astype('datetime64')
data['non_concerne'] = data['id_station_itinerance'].str.contains('oncern') | data['id_pdc_itinerance'].str.contains('oncern')

non_concerne = data[data['non_concerne']].reset_index()['index']
itinerance = data[~data['non_concerne']].reset_index()
itinerance_init = itinerance.loc[:, relations]
log['pdc_hors_itinerance'] = len(non_concerne)
log['pdc_en_itinerance'] = len(itinerance)
print('nombre de pdc hors itinerance : ', log['pdc_hors_itinerance'], 'soit : ', len(non_concerne)/(len(non_concerne)+len(itinerance)))
print('nombre de pdc en itinerance   : ', log['pdc_en_itinerance'])

nombre de pdc hors itinerance :  299 soit :  0.00142627494192342
nombre de pdc en itinerance   :  209338

In [6]:
# arborescence des champs et nombre de valeurs différentes
print(itinerance_init.npd.analysis().tree())

-1: root-derived (209338)
   0 : index (0 - 209338)
   1 : contact_operateur (209089 - 249)
   2 : nom_enseigne (203837 - 5501)
   3 : coordonneesXY (164202 - 45136)
   4 : adresse_station (166401 - 42937)
   5 : id_station_itineranc (150168 - 59170)
   6 : nom_station (167676 - 41662)
   7 : implantation_station (209331 - 7)
   8 : nbre_pdc (209233 - 105)
   9 : condition_acces (209333 - 5)
   10: horaires (208124 - 1214)
   11: station_deux_roues (209331 - 7)
   12: id_pdc_itinerance (61479 - 147859)
   13: date_maj (208348 - 990)
   14: last_modified (208685 - 653)

-----------------------
## 4 - Bilan initial intégrité
- 58 % des lignes présentent un défaut d'intégrité (moins de 20% en 2024)

In [7]:
# séparation données bonnes (itinerance_ok_1) et données résiduelles (itinerance_1)
res = analyse_integrite(itinerance_init, schema)
itinerance_ok_1 = itinerance_init.loc[itinerance_init.ok, relations].reset_index(drop=True)
itinerance_1 = itinerance_init.loc[~itinerance_init.ok, relations].reset_index(drop=True)
itinerance_init = itinerance_init.loc[:, relations]
log['init_ok'] = len(itinerance_ok_1)
log['init_ko'] = len(itinerance_1)
print("\nnombre d'enregistrements sans erreurs : ", log['init_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['init_ko'])
print("taux d'erreur : ", round(log['init_ko'] / log['pdc_en_itinerance'] * 100), ' %')

index - id_pdc_itinerance                          115242
contact_operateur - id_station_itinerance          31472
nom_enseigne - id_station_itinerance               37178
coordonneesXY - id_station_itinerance              56387
id_station_itinerance - id_pdc_itinerance          57630
nom_station - id_station_itinerance                20255
implantation_station - id_station_itinerance       25943
nbre_pdc - id_station_itinerance                   26308
condition_acces - id_station_itinerance             7479
horaires - id_station_itinerance                   17329
station_deux_roues - id_station_itinerance         69344
adresse_station - coordonneesXY                    11620

nombre d'enregistrements sans erreurs :  87849
nombre d'enregistrements avec au moins une erreur :  121489
taux d'erreur :  58  %

-----------------------
## 5 - Séparation doublons pdc - date de maj
- 51 % des pdc en erreur sont liées aux doublons de pdc (40 % fin 2024)
- la suppression des doublons permet de réduire de 94% le nombre de lignes erronnées (50 % fin 2024)

In [8]:
# séparation doublons pdc (doublons_pdc) et données résiduelles (itinerance_2)
itinerance_1['doublons_pdc'] = itinerance_1.sort_values(by=['date_maj', 'last_modified']).duplicated('id_pdc_itinerance', keep='last')

doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)['index']
#doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_2 = itinerance_1[~itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_1 = itinerance_1.loc[:, relations]
log['doublons_pdc'] = len(doublons_pdc)
log['sans_doublons_pdc'] = len(itinerance_2)
print('nombre de doublons pdc : ', log['doublons_pdc'], ' soit ', round(log['doublons_pdc']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_pdc'], ' soit ', round(log['sans_doublons_pdc']/log['init_ko'] * 100), ' %')

nombre de doublons pdc :  61479  soit  51  %
nombre de pdc sans doublon   :  60010  soit  49  %

In [9]:
# séparation données bonnes (itinerance_ok_3) et données résiduelles (itinerance_3)
res = analyse_integrite(itinerance_2, schema)
itinerance_ok_3 = itinerance_2.loc[itinerance_2.ok, relations].reset_index(drop=True)
itinerance_3 = itinerance_2.loc[~itinerance_2.ok, relations].reset_index(drop=True)
itinerance_2 = itinerance_2.loc[:, relations]
log['etape3_ok'] = len(itinerance_ok_3)
log['etape3_ko'] = len(itinerance_3)
print("\nnombre d'enregistrements sans erreurs : ", log['etape3_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape3_ko'])

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance           1636
nom_enseigne - id_station_itinerance                1876
coordonneesXY - id_station_itinerance               3168
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 2171
implantation_station - id_station_itinerance        2566
nbre_pdc - id_station_itinerance                    2863
condition_acces - id_station_itinerance              141
horaires - id_station_itinerance                     909
station_deux_roues - id_station_itinerance          2544
adresse_station - coordonneesXY                     2052

nombre d'enregistrements sans erreurs :  53143
nombre d'enregistrements avec au moins une erreur :  6867

-----------------------
## 6 - Séparation doublons station - date de maj
- la suppression des anciens pdc permet de réduire de 13 % supplémentaire le nombre de lignes erronnées
- les dernières erreurs correspondent à des stations associées à 69 opérateurs et sont liées à des causes multiples

In [10]:
# séparation doublons stations (doublons_stat_maj) et données résiduelles (itinerance_4)
itinerance_3['stat_maj'] = itinerance_3.id_station_itinerance + itinerance_3.date_maj
stat_maj_unique = itinerance_3.sort_values(by='stat_maj').drop_duplicates('id_station_itinerance', keep='last')
itinerance_3['last_stat_maj'] = itinerance_3['stat_maj'].isin(stat_maj_unique['stat_maj'])

doublons_stat_maj = itinerance_3[~itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)['index']
itinerance_4 = itinerance_3[itinerance_3['last_stat_maj']].loc[:, relations].reset_index(drop=True)
itinerance_3 = itinerance_3.loc[:, relations]
log['doublons_station'] = len(doublons_stat_maj)
log['sans_doublons_station'] = len(itinerance_4)
print('nombre de doublons stations : ', log['doublons_station'], ' soit ', 
      round(log['doublons_station']/log['init_ko'] * 100), ' %')
print('nombre de pdc sans doublon   : ', log['sans_doublons_station'])

nombre de doublons stations :  992  soit  1  %
nombre de pdc sans doublon   :  5875

In [11]:
# séparation données bonnes (itinerance_ok_5) et données résiduelles (itinerance_5 / itinerance_5_full)
res = analyse_integrite(itinerance_4, schema)
itinerance_ok_5 = itinerance_4.loc[itinerance_4.ok, relations].reset_index(drop=True)
itinerance_5_full = itinerance_4.loc[~itinerance_4.ok].reset_index(drop=True)
itinerance_5 = itinerance_5_full.loc[:, relations]
#itinerance_4 = itinerance_4.loc[:, relations]
log['etape5_ok'] = len(itinerance_ok_5)
log['etape5_ko'] = len(itinerance_5)
print("\nnombre d'enregistrements sans erreurs : ", log['etape5_ok'])
print("nombre d'enregistrements avec au moins une erreur : ", log['etape5_ko'], ' soit ', 
      round(log['etape5_ko']/log['etape3_ko'] * 100), ' %')

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              2
nom_enseigne - id_station_itinerance                  15
coordonneesXY - id_station_itinerance               1029
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                 1297
implantation_station - id_station_itinerance         730
nbre_pdc - id_station_itinerance                    1172
condition_acces - id_station_itinerance               41
horaires - id_station_itinerance                     105
station_deux_roues - id_station_itinerance             9
adresse_station - coordonneesXY                     1706

nombre d'enregistrements sans erreurs :  1537
nombre d'enregistrements avec au moins une erreur :  4338  soit  63  %

In [12]:
# structure des données présentant une erreur et nombre de valeurs
print(itinerance_5.npd.analysis().tree())

-1: root-derived (4338)
   0 : index (0 - 4338)
   1 : contact_operateur (4269 - 69)
   2 : nom_enseigne (4026 - 312)
   3 : coordonneesXY (3534 - 804)
   4 : adresse_station (3399 - 939)
   5 : id_station_itineranc (3162 - 1176)
      13: date_maj (1002 - 174)
   6 : nom_station (3449 - 889)
   7 : implantation_station (4333 - 5)
   8 : nbre_pdc (4299 - 39)
   9 : condition_acces (4336 - 2)
   10: horaires (4228 - 110)
   11: station_deux_roues (4333 - 5)
   12: id_pdc_itinerance (0 - 4338)
   14: last_modified (4233 - 105)

In [13]:
# nb maxi d'erreurs
itinerance_4['somme'] = 0
for name in res.keys():
    itinerance_4['somme'] += 1 - itinerance_4[name]
erreurs = max(itinerance_4['somme'])
maxi = itinerance_4[itinerance_4.somme >= erreurs]
print("nombre d'enregistrements avec ", erreurs, " erreurs : ", len(maxi))

nombre d'enregistrements avec  4  erreurs :  40

In [14]:
# principaux opérateurs contributeur de défauts
operateurs = list(itinerance_5.drop_duplicates('contact_operateur')['contact_operateur'])
erreurs_op = [len(itinerance_5.loc[itinerance_5.contact_operateur == operateur]) for operateur in operateurs]
err_op_5, oper_5 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:5]))
err_op_10, oper_10 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:10]))

print(len(err_op_5), ' opérateurs représentent : ', round(sum(err_op_5) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_5, oper_5):
    print(err, op)

5  opérateurs représentent :  58  % des écarts

1136 support@alizecharge.fr
491 bornes@lidl.fr
353 fastcharge.exploitation@mobilize.com
348 sav@izivia.com
208 support@service.emob.eniplenitude.com

In [73]:
print(len(err_op_10), ' opérateurs représentent : ', round(sum(err_op_10) / sum(erreurs_op) * 100), ' % des écarts\n')
for err, op in zip(err_op_10, oper_10):
    print(err, op)

10  opérateurs représentent :  73  % des écarts

1136 support@alizecharge.fr
491 bornes@lidl.fr
353 fastcharge.exploitation@mobilize.com
348 sav@izivia.com
208 support@service.emob.eniplenitude.com
188 supervision-ev.france@totalenergies.com
141 support@dream-energy.fr
110 customerservice@shellrecharge.com
105 julien.humbert@amaranzero.com
102 support@greenflux.com

-----------------------
## 7 - Synthèse

### fichiers
Génération des fichiers intégrant les défauts d'intégrité :
- fichier csv des lignes résiduelles à traiter (IRVE_itinerance_residuel)
- fichier csv des données itinerance avec indicateur des données à corriger ou à ignorer (IRVE_itinerance_complet)
- fichier csv des données itinerance valides (IRVE_itinerance_valide)
- fichier csv des doublons (IRVE_itinerance_doublons)

In [15]:
# consolidation des données
itinerance['doublons_stat_maj'] = itinerance['index'].isin(doublons_stat_maj)
itinerance['doublons_pdc'] = itinerance['index'].isin(doublons_pdc)
itinerance['lignes_a_corriger'] = itinerance['index'].isin(itinerance_5['index'])
itinerance['doublons_a_supprimer'] = itinerance['doublons_stat_maj'] | itinerance['doublons_pdc']
itinerance['lignes_ko'] = itinerance['doublons_a_supprimer'] | itinerance['lignes_a_corriger']
print('total des lignes à corriger : ', itinerance['lignes_a_corriger'].sum())
itinerance_doublons = itinerance[itinerance['doublons_a_supprimer']].reset_index(drop=True)
print('total des doublons à supprimer : ', len(itinerance_doublons))
itinerance_ok = itinerance[~itinerance['lignes_ko']].reset_index(drop=True)
print('nombre de pdc avec controles ok : ', len(itinerance_ok))

total des lignes à corriger :  4338
total des doublons à supprimer :  62471
nombre de pdc avec controles ok :  142529

In [16]:
# génération des fichiers
extension = log['date_irve'] +'.csv'
itinerance_5_full.to_csv('IRVE_itinerance_residuel' + extension)
itinerance.to_csv('IRVE_itinerance_complet' + extension)
itinerance_ok.to_csv('IRVE_itinerance_valide' + extension)
itinerance_doublons.to_csv('IRVE_itinerance_doublons' + extension)
log['IRVE_itinerance_residuel' + extension] = len(itinerance_5_full)
log['IRVE_itinerance_complet' + extension] = len(itinerance)
log['IRVE_itinerance_valide' + extension] = len(itinerance_ok)
log['IRVE_itinerance_valide_stat' + extension] = len(itinerance_ok.drop_duplicates('id_station_itinerance', keep='last'))
log['IRVE_itinerance_doublons' + extension] = len(itinerance_doublons)

In [17]:
l_prefix = list(pd.read_csv(log['chemin'] + '/' + 'Operations_Recharge_16-07-2024.csv', sep=';', low_memory=False, dtype='object')['Identifiant'])
l_prefix[0]

'FR073'

In [18]:
for op in oper_5:
    print('IRVE_itinerance_residuel' + '_' + op + '_' + extension)
    itinerance_5_full.loc[itinerance_5_full.contact_operateur == op].to_csv('IRVE_itinerance_residuel' + '_' + op + '_' + extension)

IRVE_itinerance_residuel_support@alizecharge.fr_2026-02-18.csv
IRVE_itinerance_residuel_bornes@lidl.fr_2026-02-18.csv
IRVE_itinerance_residuel_fastcharge.exploitation@mobilize.com_2026-02-18.csv
IRVE_itinerance_residuel_sav@izivia.com_2026-02-18.csv
IRVE_itinerance_residuel_support@service.emob.eniplenitude.com_2026-02-18.csv

### vérification de l'intégrité

In [19]:
# vérification de l'absence d'erreurs
res = analyse_integrite(itinerance_ok.loc[:, relations], schema, affiche=False)
log['bilan_erreurs'] = sum(res.values())
log['date'] = datetime.now().isoformat()
print('bilan intégrité :')
print('    erreurs : ', log['bilan_erreurs'])

bilan intégrité :
    erreurs :  0

In [20]:
# structure des données bonnes
#print(Cdataset(itinerance_ok.loc[:, mandatory]).tree())
print(itinerance_ok.loc[:, mandatory].npd.analysis().tree())

-1: root-derived (142529)
   4 : id_station_itineranc (93236 - 49293)
      0 : contact_operateur (49062 - 231)
      1 : nom_enseigne (44585 - 4708)
      2 : coordonneesXY (15275 - 34018)
         3 : adresse_station (917 - 33101)
      5 : nom_station (14912 - 34381)
      6 : implantation_station (49288 - 5)
      7 : nbre_pdc (49197 - 96)
      8 : condition_acces (49288 - 5)
      9 : horaires (48221 - 1072)
      10: station_deux_roues (49286 - 7)
   11: id_pdc_itinerance (0 - 142529)
   12: puissance_nominale (142271 - 258)
   13: prise_type_ef (142521 - 8)
   14: prise_type_2 (142521 - 8)
   15: prise_type_combo_ccs (142521 - 8)
   16: prise_type_chademo (142521 - 8)
   17: prise_type_autre (142522 - 7)
   18: paiement_acte (142521 - 8)
   19: paiement_autre (142520 - 9)
   20: reservation (142522 - 7)
   21: accessibilite_pmr (142522 - 7)
   22: restriction_gabarit (142378 - 151)
   23: date_maj (141664 - 865)
   24: last_modified (142018 - 511)

### Indicateurs

In [21]:
# génération des indicateurs liés aux règles
regles = ['Pdc non unique', 'Station multi-operateurs', 'Station multi-enseignes', 'Station multi-localisations', 
          'Pdc multi-stations', 'station avec plusieurs noms', 'station multi-implantations', 
          'nombre de pdc par station incoherent', 'station multi-acces', 'station multi-horaires', 
          'acces deux-roues incoherent', 'localisation multi-adresses']
principal = [16, 17, 18, 19, 20]
secondaire = [21, 22, 23, 24, 25, 26, 27]
irve = itinerance_5_full # residuel
total = len(irve)
indic = {}

irve['principal'] = True
for ind in principal:
    irve['principal'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] = True
for ind in secondaire:
    irve['secondaire'] &= irve.iloc[:,ind]
    indic[regles[ind-16]] = int(total - irve.iloc[:,ind].sum())
irve['secondaire'] |= (~irve['principal'] & ~irve['secondaire'])
irve['verif'] = irve['principal'] & irve['secondaire']
indic['principal pdc'] = int(total - irve['principal'].sum())
indic['secondaire pdc'] = int(total - irve['secondaire'].sum())

irve_p = irve[~irve['principal']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
irve_s = irve[~irve['secondaire']].drop_duplicates('id_station_itinerance').reset_index(drop=True)
indic['principal stat'] = len(irve_p)
indic['secondaire stat'] = len(irve_s)

In [22]:
# ajout des principaux opérateurs contributeur de défauts
indic['operateurs'] = list(oper_5)
indic['erreurs_operateurs'] = list(err_op_5)

In [23]:
# ajout de l'indicateur d'écart entre nombre de pdc calculés et saisis
add_nbre_pdc(irve, affiche=True)
indic['nb_pdc_calc-nbre_pdc'] = int(irve['calc-nbre'].sum())

nbre_pdc_ko           2028
47  %

In [24]:
# indicateur d'écart entre nombre de pdc calculés et saisis sur les données sans doublon
itinerance_sans_doublons = itinerance[~itinerance['doublons_a_supprimer']].reset_index(drop=True)
add_nbre_pdc(itinerance_sans_doublons, affiche=True)

nbre_pdc_ko          38329
26  %

In [25]:
len(itinerance_4)

5875

In [26]:
# stockage des indicateurs
log |= indic
log_file = log['chemin'] + '/' + 'logfile.txt'
#with open('logfile.txt', 'a', encoding="utf-8") as f:
with open(log_file, 'a', encoding="utf-8") as f:
    f.write(json.dumps(log) + '\n')

In [27]:
itinerance_5_full.columns[16:28]

Index(['index - id_pdc_itinerance',
       'contact_operateur - id_station_itinerance',
       'nom_enseigne - id_station_itinerance',
       'coordonneesXY - id_station_itinerance',
       'id_station_itinerance - id_pdc_itinerance',
       'nom_station - id_station_itinerance',
       'implantation_station - id_station_itinerance',
       'nbre_pdc - id_station_itinerance',
       'condition_acces - id_station_itinerance',
       'horaires - id_station_itinerance',
       'station_deux_roues - id_station_itinerance',
       'adresse_station - coordonneesXY'],
      dtype='object')

-----------------------
## 8 - Exemples d'erreurs résiduelles 

### Erreurs multiples 
- exemple avec le nombre maximal d'erreurs (4) (35 pdc)
- exemple station 'FRS35P35093001B1' avec 25 pdc : coordonnées XY, nom_station, implantation station, condition accès)

In [28]:
maxi.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1421,93656,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003929,2025-12-11,2025-12-17T09:36:45.669000+00:00
1422,93657,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003930,2025-12-11,2025-12-17T09:36:45.669000+00:00
1423,93658,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003931,2025-12-11,2025-12-17T09:36:45.669000+00:00
1424,93659,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003932,2025-12-11,2025-12-17T09:36:45.669000+00:00
1429,93694,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003963,2025-12-11,2025-12-17T09:36:45.669000+00:00
1430,93695,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003964,2025-12-11,2025-12-17T09:36:45.669000+00:00
1431,93696,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003965,2025-12-11,2025-12-17T09:36:45.669000+00:00
1432,93697,bornes@lidl.fr,LIDL,"[2.334015,48.632005]",rue du Plessis,FRLDLPLFR4256EVCP,Saint-Geneviève-des-Bois - Plessis,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00003966,2025-12-11,2025-12-17T09:36:45.669000+00:00
1956,97950,bornes@lidl.fr,LIDL,"[2.3342784699172694,48.63166647558965]",21 RUE DU PLESSIS,FRLDLPLFR4256EVCP,SAINTE GENEVIEVE DES BOIS,Parking privé à usage public,2,Accès libre,"Mo-Sa 08:30-20:30,Su 08:30-12:15",false,FRLDLE00007414,2025-12-11,2025-12-17T09:36:45.669000+00:00
1957,97951,bornes@lidl.fr,LIDL,"[2.3342784699172694,48.63166647558965]",21 RUE DU PLESSIS,FRLDLPLFR4256EVCP,SAINTE GENEVIEVE DES BOIS,Parking privé à usage public,2,Accès libre,"Mo-Sa 08:30-20:30,Su 08:30-12:15",false,FRLDLE00007415,2025-12-11,2025-12-17T09:36:45.669000+00:00
2211,105182,support@mobilize-ps.fr,BODEMER BAYEUX,"[-0.700226002831211, 49.27084281571326]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,BODEMER Bayeux,Parking privé à usage public,1,Accès libre,24/7,False,FRMBZESMYCQ1,2024-06-03,2026-01-14T10:13:03.213000+00:00
2212,105183,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[-0.700259, 49.270901]","\t16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,\t\tScauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",False,FRMBZESMYQC1,2024-06-03,2026-01-14T10:13:03.213000+00:00
2241,105760,supervision-ev.france@totalenergies.com,MEL,"[3.036602, 50.647916]","Avenue Vauban, 59130 Lambersart",FRMELPRES5911202,LAMBERSART - Avenue Vauban,Voirie,4,Accès libre,24/7,FALSE,FRMELERES591300721,2025-10-09,2025-10-09T16:16:08.920000+00:00
2252,105820,supervision-ev.france@totalenergies.com,MEL,"[3.179727, 50.712572]","11 Rue Léo Lagrange, 59150 Wattrelos",FRMELPRES5911202,WATTRELOS - 11 Rue Léo Lagrange,Voirie,4,Accès libre,24/7,FALSE,FRMELERES591500521,2025-10-09,2025-10-09T16:16:08.920000+00:00
2258,105866,supervision-ev.france@totalenergies.com,MEL,"[3.154113, 50.679396]","Avenue des 2 Moulins, 59170 Croix",FRMELPRES5911202,CROIX - Avenue des 2 Moulins,Voirie,4,Accès libre,24/7,FALSE,FRMELERES591700521,2025-10-09,2025-10-09T16:16:08.920000+00:00
2274,106024,supervision-ev.france@totalenergies.com,MEL,"[3.134137, 50.710864]","230 Rue de Tourcoing, 59420 Mouvaux",FRMELPRES5911202,MOUVAUX - 230 Rue de Tourcoing,Voirie,4,Accès libre,24/7,FALSE,FRMELERES594200421,2025-10-09,2025-10-09T16:16:08.920000+00:00
2281,106084,supervision-ev.france@totalenergies.com,MEL,"[3.08578, 50.665872]","2 - 6 Rue Charles Gounod, 59700 Marcq-en-Barœul",FRMELPRES5911202,MARCQ-EN-BARŒUL - 2 - 6 Rue Charles Gounod,Voirie,4,Accès libre,24/7,FALSE,FRMELERES597000721,2025-10-09,2025-10-09T16:16:08.920000+00:00
3859,154552,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.419000+00:00
3860,154553,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.419000+00:00
3861,154558,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,False,FRS35E350930041,2024-09-18,2025-12-15T16:13:43.419000+00:00
3862,154559,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,False,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.419000+00:00
3863,154560,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,False,FRS35E3509300411,2024-09-18,2025-12-15T16:13:43.419000+00:00
3864,154561,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,False,FRS35E3509300412,2024-09-18,2025-12-15T16:13:43.419000+00:00
3865,154562,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,False,FRS35E3509300413,2024-09-18,2025-12-15T16:13:43.419000+00:00
3866,154563,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,False,FRS35E3509300414,2024-09-18,2025-12-15T16:13:43.419000+00:00
3867,154564,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,False,FRS35E3509300415,2024-09-18,2025-12-15T16:13:43.419000+00:00
3868,154565,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,False,FRS35E3509300416,2024-09-18,2025-12-15T16:13:43.419000+00:00
3869,154566,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,False,FRS35E3509300417,2024-09-18,2025-12-15T16:13:43.419000+00:00
3870,154567,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,False,FRS35E3509300418,2024-09-18,2025-12-15T16:13:43.419000+00:00
3871,154568,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,False,FRS35E3509300419,2024-09-18,2025-12-15T16:13:43.419000+00:00
3872,154569,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,False,FRS35E350930042,2024-09-18,2025-12-15T16:13:43.419000+00:00
3873,154570,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,False,FRS35E3509300420,2024-09-18,2025-12-15T16:13:43.419000+00:00
3874,154571,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,False,FRS35E3509300421,2024-09-18,2025-12-15T16:13:43.419000+00:00
3875,154572,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,False,FRS35E350930043,2024-09-18,2025-12-15T16:13:43.419000+00:00
3876,154573,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,False,FRS35E350930044,2024-09-18,2025-12-15T16:13:43.419000+00:00
3877,154574,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,False,FRS35E350930045,2024-09-18,2025-12-15T16:13:43.419000+00:00
3878,154575,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,False,FRS35E350930046,2024-09-18,2025-12-15T16:13:43.419000+00:00
3879,154576,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,False,FRS35E350930047,2024-09-18,2025-12-15T16:13:43.419000+00:00
3880,154577,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,False,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.419000+00:00
3881,154578,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,False,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.419000+00:00

In [29]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRS35P35093001B1', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3859,154552,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930011,2024-09-18,2025-12-15T16:13:43.419000+00:00
3860,154553,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.066189,48.623768]",15 rue Gouyon Matignon (Parking du Cosec) 3580...,FRS35P35093001B1,DINARD - 15 rue Gouyon Matignon (Parking du Co...,Voirie,1,Accès libre,24/7,False,FRS35E350930012,2024-09-18,2025-12-15T16:13:43.419000+00:00
3861,154558,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 3,Parking public,1,Accès réservé,24/7,False,FRS35E350930041,2024-09-18,2025-12-15T16:13:43.419000+00:00
3862,154559,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 1,Parking public,1,Accès réservé,24/7,False,FRS35E3509300410,2024-09-18,2025-12-15T16:13:43.419000+00:00
3863,154560,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 2,Parking public,1,Accès réservé,24/7,False,FRS35E3509300411,2024-09-18,2025-12-15T16:13:43.419000+00:00
3864,154561,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 39,Parking public,1,Accès réservé,24/7,False,FRS35E3509300412,2024-09-18,2025-12-15T16:13:43.419000+00:00
3865,154562,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 40,Parking public,1,Accès réservé,24/7,False,FRS35E3509300413,2024-09-18,2025-12-15T16:13:43.419000+00:00
3866,154563,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 41,Parking public,1,Accès réservé,24/7,False,FRS35E3509300414,2024-09-18,2025-12-15T16:13:43.419000+00:00
3867,154564,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 42,Parking public,1,Accès réservé,24/7,False,FRS35E3509300415,2024-09-18,2025-12-15T16:13:43.419000+00:00
3868,154565,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 43,Parking public,1,Accès réservé,24/7,False,FRS35E3509300416,2024-09-18,2025-12-15T16:13:43.419000+00:00
3869,154566,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 44,Parking public,1,Accès réservé,24/7,False,FRS35E3509300417,2024-09-18,2025-12-15T16:13:43.419000+00:00
3870,154567,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 45,Parking public,1,Accès réservé,24/7,False,FRS35E3509300418,2024-09-18,2025-12-15T16:13:43.419000+00:00
3871,154568,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 46,Parking public,1,Accès réservé,24/7,False,FRS35E3509300419,2024-09-18,2025-12-15T16:13:43.419000+00:00
3872,154569,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 4,Parking public,1,Accès réservé,24/7,False,FRS35E350930042,2024-09-18,2025-12-15T16:13:43.419000+00:00
3873,154570,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 26,Parking public,1,Accès réservé,24/7,False,FRS35E3509300420,2024-09-18,2025-12-15T16:13:43.419000+00:00
3874,154571,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 25,Parking public,1,Accès réservé,24/7,False,FRS35E3509300421,2024-09-18,2025-12-15T16:13:43.419000+00:00
3875,154572,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 5,Parking public,1,Accès réservé,24/7,False,FRS35E350930043,2024-09-18,2025-12-15T16:13:43.419000+00:00
3876,154573,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 6,Parking public,1,Accès réservé,24/7,False,FRS35E350930044,2024-09-18,2025-12-15T16:13:43.419000+00:00
3877,154574,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 7,Parking public,1,Accès réservé,24/7,False,FRS35E350930045,2024-09-18,2025-12-15T16:13:43.419000+00:00
3878,154575,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 8 (Réservée PM),Parking public,1,Accès réservé,24/7,False,FRS35E350930046,2024-09-18,2025-12-15T16:13:43.419000+00:00
3879,154576,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 9,Parking public,1,Accès réservé,24/7,False,FRS35E350930047,2024-09-18,2025-12-15T16:13:43.419000+00:00
3880,154577,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 10,Parking public,1,Accès réservé,24/7,False,FRS35E350930048,2024-09-18,2025-12-15T16:13:43.419000+00:00
3881,154578,serviceclient@ouestcharge.fr,OUEST CHARGE,"[-2.0643737,48.6294609]",Rue de la Corbinais 35800 DINARD,FRS35P35093001B1,DINARD - Parking Newquay - Place 11,Parking public,1,Accès réservé,24/7,False,FRS35E350930049,2024-09-18,2025-12-15T16:13:43.419000+00:00

### Repartition des defauts par operateur
Répartition pour les 10 opérateurs présentant le plus de défauts

In [30]:
print('PdC avec une incohérence : ')
for operateur in oper_10:
    print('\n', sum(itinerance_5.contact_operateur == operateur))
    print('Répartition des incohérences ', operateur, ' :')
    for cont in controles:
        #print(cont, sum((itinerance_4['contact_operateur'] == 'supervision-ev.france@totalenergies.com') & ~(itinerance_4[cont])))
        print('{:<50} {:>5}'.format(cont, sum((itinerance_4['contact_operateur'] == operateur) & ~(itinerance_4[cont]))))

PdC avec une incohérence :

 1136
Répartition des incohérences  support@alizecharge.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                179
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  831
implantation_station - id_station_itinerance          15
nbre_pdc - id_station_itinerance                     772
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      361

 491
Répartition des incohérences  bornes@lidl.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                470
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  154
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                     114
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                      24
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 353
Répartition des incohérences  fastcharge.exploitation@mobilize.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance         353
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 348
Répartition des incohérences  sav@izivia.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                 15
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   19
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                      15
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      333

 208
Répartition des incohérences  support@service.emob.eniplenitude.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance         208
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 188
Répartition des incohérences  supervision-ev.france@totalenergies.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                 65
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   65
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                      43
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                      10
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      120

 141
Répartition des incohérences  support@dream-energy.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  4
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                     136
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                       33

 110
Répartition des incohérences  customerservice@shellrecharge.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance         110
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

 105
Répartition des incohérences  julien.humbert@amaranzero.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      105

 102
Répartition des incohérences  support@greenflux.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                102
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  102
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

### Defauts operateur ALIZECHARGE
Les défauts identifiés concernent des stations utilisant un même identifiant. Par exemple, la station 'FRADPE77294001' contient 40 points de recharge avec plusieurs adresses, plusieurs localisations, plusieurs noms de station et un nombre de points de rechage variable.

In [76]:
itinerance_4.loc[(~itinerance_4['nom_station - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'support@alizecharge.fr'), relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
45,4331,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001191,2026-02-12,2026-02-12T13:33:57.539000+00:00
46,4332,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001192,2026-02-12,2026-02-12T13:33:57.539000+00:00
47,4333,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001193,2026-02-12,2026-02-12T13:33:57.539000+00:00
48,4334,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001201,2026-02-12,2026-02-12T13:33:57.539000+00:00
49,4335,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001202,2026-02-12,2026-02-12T13:33:57.539000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,206327,support@alizecharge.fr,Seymaborne,"[1.877203,48.5760925]","Rue André Thome, 78120 SONCHAMP",FRY03E78601001,SONCHAMP - MAIRIE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786010014,2026-02-12,2026-02-12T13:33:57.539000+00:00
5677,206328,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150011,2026-02-12,2026-02-12T13:33:57.539000+00:00
5678,206329,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150012,2026-02-12,2026-02-12T13:33:57.539000+00:00
5679,206330,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150013,2026-02-12,2026-02-12T13:33:57.539000+00:00
5680,206331,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150014,2026-02-12,2026-02-12T13:33:57.539000+00:00

In [77]:
itinerance_4.loc[(~itinerance_4['nbre_pdc - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'support@alizecharge.fr'), relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
45,4331,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001191,2026-02-12,2026-02-12T13:33:57.539000+00:00
46,4332,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001192,2026-02-12,2026-02-12T13:33:57.539000+00:00
47,4333,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001193,2026-02-12,2026-02-12T13:33:57.539000+00:00
48,4334,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001201,2026-02-12,2026-02-12T13:33:57.539000+00:00
49,4335,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001202,2026-02-12,2026-02-12T13:33:57.539000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4778,173323,support@alizecharge.fr,La borne bleue,"[2.413548857810981,48.83379329356487]","Avenue Daumesnil, 94160 SAINT-MANDÉ",FRSIPE94067006,SAINT-MANDÉ - 11 TER Avenue Daumesnil - AC,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRSIPE940670061,2026-02-12,2026-02-12T13:33:57.539000+00:00
4779,173324,support@alizecharge.fr,La borne bleue,"[2.413548857810981,48.83379329356487]","Avenue Daumesnil, 94160 SAINT-MANDÉ",FRSIPE94067006,SAINT-MANDÉ - 11 TER Avenue Daumesnil - AC,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRSIPE940670062,2026-02-12,2026-02-12T13:33:57.539000+00:00
4780,173325,support@alizecharge.fr,La borne bleue,"[2.41354815030137,48.833797152065976]","Avenue Daumesnil, 94160 SAINT-MANDÉ",FRSIPE94067006,SAINT-MANDÉ - 11 TER Avenue Daumesnil - DC,Voirie,3,Accès libre,Mo-Su 00:00-23:57,False,FRSIPE940670063,2026-02-12,2026-02-12T13:33:57.539000+00:00
4781,173326,support@alizecharge.fr,La borne bleue,"[2.41354815030137,48.833797152065976]","Avenue Daumesnil, 94160 SAINT-MANDÉ",FRSIPE94067006,SAINT-MANDÉ - 11 TER Avenue Daumesnil - DC,Voirie,3,Accès libre,Mo-Su 00:00-23:57,False,FRSIPE940670064,2026-02-12,2026-02-12T13:33:57.539000+00:00
4782,173327,support@alizecharge.fr,La borne bleue,"[2.41354815030137,48.833797152065976]","Avenue Daumesnil, 94160 SAINT-MANDÉ",FRSIPE94067006,SAINT-MANDÉ - 11 TER Avenue Daumesnil - DC,Voirie,3,Accès libre,Mo-Su 00:00-23:57,False,FRSIPE940670065,2026-02-12,2026-02-12T13:33:57.539000+00:00

In [82]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRADPE77294001', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
45,4331,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001191,2026-02-12,2026-02-12T13:33:57.539000+00:00
46,4332,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001192,2026-02-12,2026-02-12T13:33:57.539000+00:00
47,4333,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001193,2026-02-12,2026-02-12T13:33:57.539000+00:00
48,4334,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001201,2026-02-12,2026-02-12T13:33:57.539000+00:00
49,4335,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001202,2026-02-12,2026-02-12T13:33:57.539000+00:00
50,4336,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001203,2026-02-12,2026-02-12T13:33:57.539000+00:00
51,4337,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001211,2026-02-12,2026-02-12T13:33:57.539000+00:00
52,4338,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001212,2026-02-12,2026-02-12T13:33:57.539000+00:00
53,4339,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001213,2026-02-12,2026-02-12T13:33:57.539000+00:00
54,4340,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001221,2026-02-12,2026-02-12T13:33:57.539000+00:00
55,4341,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001222,2026-02-12,2026-02-12T13:33:57.539000+00:00
56,4342,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001223,2026-02-12,2026-02-12T13:33:57.539000+00:00
57,4343,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001231,2026-02-12,2026-02-12T13:33:57.539000+00:00
58,4344,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001232,2026-02-12,2026-02-12T13:33:57.539000+00:00
59,4345,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001233,2026-02-12,2026-02-12T13:33:57.539000+00:00
60,4346,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001241,2026-02-12,2026-02-12T13:33:57.539000+00:00
61,4347,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001242,2026-02-12,2026-02-12T13:33:57.539000+00:00
62,4348,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001243,2026-02-12,2026-02-12T13:33:57.539000+00:00
63,4349,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001251,2026-02-12,2026-02-12T13:33:57.539000+00:00
64,4350,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001252,2026-02-12,2026-02-12T13:33:57.539000+00:00
65,4351,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001253,2026-02-12,2026-02-12T13:33:57.539000+00:00
66,4352,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001261,2026-02-12,2026-02-12T13:33:57.539000+00:00
67,4353,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001262,2026-02-12,2026-02-12T13:33:57.539000+00:00
68,4354,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001263,2026-02-12,2026-02-12T13:33:57.539000+00:00
69,4355,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001271,2026-02-12,2026-02-12T13:33:57.539000+00:00
70,4356,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001272,2026-02-12,2026-02-12T13:33:57.539000+00:00
71,4357,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001273,2026-02-12,2026-02-12T13:33:57.539000+00:00
72,4358,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001281,2026-02-12,2026-02-12T13:33:57.539000+00:00
73,4359,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001282,2026-02-12,2026-02-12T13:33:57.539000+00:00
74,4360,support@alizecharge.fr,ADP Groupe,"[2.610949,49.0076438]","route du, Parking PW, 77290 Mitry-Mory",FRADPE77294001,CDGU - BAT (Réservé exclusivement aux taxis pa...,Parking public,30,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001283,2026-02-12,2026-02-12T13:33:57.539000+00:00
75,4361,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001301,2026-02-12,2026-02-12T13:33:57.539000+00:00
76,4362,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001302,2026-02-12,2026-02-12T13:33:57.539000+00:00
77,4363,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001311,2026-02-12,2026-02-12T13:33:57.539000+00:00
78,4364,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001312,2026-02-12,2026-02-12T13:33:57.539000+00:00
79,4365,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001321,2026-02-12,2026-02-12T13:33:57.539000+00:00
80,4366,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001322,2026-02-12,2026-02-12T13:33:57.539000+00:00
81,4367,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001331,2026-02-12,2026-02-12T13:33:57.539000+00:00
82,4368,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001332,2026-02-12,2026-02-12T13:33:57.539000+00:00
83,4369,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001341,2026-02-12,2026-02-12T13:33:57.539000+00:00
84,4370,support@alizecharge.fr,ADP Groupe,"[2.363758,48.733494]","P9M9+WR, 94390 Paray-Vieille-Poste",FRADPE77294001,ORY EX - BAT (Réservé exclusivement aux taxis ...,Parking public,36,Accès libre,Mo-Su 00:00-23:57,False,FRADPE77294001342,2026-02-12,2026-02-12T13:33:57.539000+00:00

In [33]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[2.969121,48.282539]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Defauts operateur LIDL
Les défauts identifiés concernent principalement l'affectation de coordonnées au point de recharge et non à la station. Par exemple, pour une station composée de quatre bornes de deux points de recharge, on trouve une coordonnée différente pour chacune des bornes.

In [85]:
itinerance_4.loc[(~itinerance_4['coordonneesXY - id_station_itinerance']) & (itinerance_4['contact_operateur'] == 'bornes@lidl.fr') , relations].sort_values(by=["id_station_itinerance"])[0:50]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
1748,96942,bornes@lidl.fr,LIDL,"[7.3367,48.06141]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006685,2025-12-11,2025-12-17T09:36:45.669000+00:00
1749,96943,bornes@lidl.fr,LIDL,"[7.3367,48.06141]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006686,2025-12-11,2025-12-17T09:36:45.669000+00:00
1747,96941,bornes@lidl.fr,LIDL,"[7.33667,48.06137]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006684,2025-12-11,2025-12-17T09:36:45.669000+00:00
1746,96940,bornes@lidl.fr,LIDL,"[7.33667,48.06137]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006683,2025-12-11,2025-12-17T09:36:45.669000+00:00
1745,96939,bornes@lidl.fr,LIDL,"[7.33663,48.06132]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006682,2025-12-11,2025-12-17T09:36:45.669000+00:00
1744,96938,bornes@lidl.fr,LIDL,"[7.33663,48.06132]",102. route de Rouffach,FRLDLPLFR0243EVCP,COLMAR,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006681,2025-12-11,2025-12-17T09:36:45.669000+00:00
1635,96138,bornes@lidl.fr,LIDL,"[3.466139,46.835271]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006056,2025-12-11,2025-12-17T09:36:45.669000+00:00
1636,96139,bornes@lidl.fr,LIDL,"[3.466131,46.835237]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006057,2025-12-11,2025-12-17T09:36:45.669000+00:00
1637,96140,bornes@lidl.fr,LIDL,"[3.466131,46.835237]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006058,2025-12-11,2025-12-17T09:36:45.669000+00:00
1638,96141,bornes@lidl.fr,LIDL,"[3.466129,46.835194]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006059,2025-12-11,2025-12-17T09:36:45.669000+00:00
1639,96142,bornes@lidl.fr,LIDL,"[3.466129,46.835194]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006060,2025-12-11,2025-12-17T09:36:45.669000+00:00
1634,96137,bornes@lidl.fr,LIDL,"[3.466139,46.835271]",383 Rue Roger Salengro,FRLDLPLFR1481EVCP,ST LEGER DES VIGNES,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006055,2025-12-11,2025-12-17T09:36:45.669000+00:00
1485,94255,bornes@lidl.fr,LIDL,"[2.377976775169,48.987525573284]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004328,2025-12-11,2025-12-17T09:36:45.669000+00:00
1478,94248,bornes@lidl.fr,LIDL,"[2.37841129303,48.987764950135]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004321,2025-12-11,2025-12-17T09:36:45.669000+00:00
1479,94249,bornes@lidl.fr,LIDL,"[2.37841129303,48.987764950135]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004322,2025-12-11,2025-12-17T09:36:45.669000+00:00
1480,94250,bornes@lidl.fr,LIDL,"[2.378287911415,48.987691025054]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004323,2025-12-11,2025-12-17T09:36:45.669000+00:00
1481,94251,bornes@lidl.fr,LIDL,"[2.378287911415,48.987691025054]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004324,2025-12-11,2025-12-17T09:36:45.669000+00:00
1482,94252,bornes@lidl.fr,LIDL,"[2.378148436546,48.987617099863]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004325,2025-12-11,2025-12-17T09:36:45.669000+00:00
1483,94253,bornes@lidl.fr,LIDL,"[2.378148436546,48.987617099863]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004326,2025-12-11,2025-12-17T09:36:45.669000+00:00
1484,94254,bornes@lidl.fr,LIDL,"[2.377976775169,48.987525573284]",ZAC du Cœur de Ville. Av. de la Division Leclerc,FRLDLPLFR1876EVCP,SARCELLES,Parking privé à usage public,8,Accès libre,24/7,false,FRLDLE00004327,2025-12-11,2025-12-17T09:36:45.669000+00:00
1795,97251,bornes@lidl.fr,LIDL,"[2.468212,49.240732]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006920,2025-12-11,2025-12-17T09:36:45.669000+00:00
1794,97250,bornes@lidl.fr,LIDL,"[2.468212,49.240732]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006919,2025-12-11,2025-12-17T09:36:45.669000+00:00
1793,97249,bornes@lidl.fr,LIDL,"[2.468145,49.240732]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006918,2025-12-11,2025-12-17T09:36:45.669000+00:00
1792,97248,bornes@lidl.fr,LIDL,"[2.468145,49.240732]",395 avenue Gabriel PERI,FRLDLPLFR1892EVCP,ST MAXIMIN,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006917,2025-12-11,2025-12-17T09:36:45.669000+00:00
1564,95050,bornes@lidl.fr,LIDL,"[-3.439811,48.733519]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005310,2025-12-11,2025-12-17T09:36:45.669000+00:00
1562,95048,bornes@lidl.fr,LIDL,"[-3.439845,48.733566]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005298,2025-12-11,2025-12-17T09:36:45.669000+00:00
1563,95049,bornes@lidl.fr,LIDL,"[-3.439931,48.733748]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005309,2025-12-11,2025-12-17T09:36:45.669000+00:00
1561,95047,bornes@lidl.fr,LIDL,"[-3.439845,48.733566]",27 Rue de la Madeleine,FRLDLPLFR1957EVCP,LANNION madeleine,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00005297,2025-12-11,2025-12-17T09:36:45.669000+00:00
1756,96960,bornes@lidl.fr,LIDL,"[6.532384,43.255349]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006711,2025-12-11,2025-12-17T09:36:45.669000+00:00
1754,96958,bornes@lidl.fr,LIDL,"[6.532326,43.255312]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006709,2025-12-11,2025-12-17T09:36:45.669000+00:00
1552,94916,bornes@lidl.fr,LIDL,"[6.532434,43.255782]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00005173,2025-12-11,2025-12-17T09:36:45.669000+00:00
1553,94935,bornes@lidl.fr,LIDL,"[6.532434,43.255782]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00005186,2025-12-11,2025-12-17T09:36:45.669000+00:00
1755,96959,bornes@lidl.fr,LIDL,"[6.532326,43.255312]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006710,2025-12-11,2025-12-17T09:36:45.669000+00:00
1757,96961,bornes@lidl.fr,LIDL,"[6.532384,43.255349]",91 Rue Carnot,FRLDLPLFR2217EVCP,COGOLIN Carnot,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006712,2025-12-11,2025-12-17T09:36:45.669000+00:00
1718,96842,bornes@lidl.fr,LIDL,"[0.6740331935603362,46.002775074594226]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006614,2025-12-11,2025-12-17T09:36:45.669000+00:00
1719,96843,bornes@lidl.fr,LIDL,"[0.6740365463212485,46.002837955042615]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006615,2025-12-11,2025-12-17T09:36:45.669000+00:00
1720,96844,bornes@lidl.fr,LIDL,"[0.6740365463212485,46.002837955042615]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006616,2025-12-11,2025-12-17T09:36:45.669000+00:00
1715,96839,bornes@lidl.fr,LIDL,"[0.674016429755774,46.00272756487474]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006611,2025-12-11,2025-12-17T09:36:45.669000+00:00
1716,96840,bornes@lidl.fr,LIDL,"[0.674016429755774,46.00272756487474]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006612,2025-12-11,2025-12-17T09:36:45.669000+00:00
1717,96841,bornes@lidl.fr,LIDL,"[0.6740331935603362,46.002775074594226]",Avenue du Général De Gaulle,FRLDLPLFR2285EVCP,CONFOLENS,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006613,2025-12-11,2025-12-17T09:36:45.669000+00:00
1726,96850,bornes@lidl.fr,LIDL,"[1.3259180139040503,45.12877270814785]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006622,2025-12-11,2025-12-17T09:36:45.669000+00:00
1725,96849,bornes@lidl.fr,LIDL,"[1.3259180139040503,45.12877270814785]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006621,2025-12-11,2025-12-17T09:36:45.669000+00:00
1724,96848,bornes@lidl.fr,LIDL,"[1.3259046028604002,45.12882285515484]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006620,2025-12-11,2025-12-17T09:36:45.669000+00:00
1721,96845,bornes@lidl.fr,LIDL,"[1.325901250099488,45.12886022883892]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006617,2025-12-11,2025-12-17T09:36:45.669000+00:00
1722,96846,bornes@lidl.fr,LIDL,"[1.325901250099488,45.12886022883892]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006618,2025-12-11,2025-12-17T09:36:45.669000+00:00
1723,96847,bornes@lidl.fr,LIDL,"[1.3259046028604002,45.12882285515484]",24 Rue Maurice Opinel,FRLDLPLFR2289EVCP,TERRASSON,Parking privé à usage public,6,Accès libre,24/7,false,FRLDLE00006619,2025-12-11,2025-12-17T09:36:45.669000+00:00
1805,97307,bornes@lidl.fr,LIDL,"[-0.214115,44.900367]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006952,2025-12-11,2025-12-17T09:36:45.669000+00:00
1804,97306,bornes@lidl.fr,LIDL,"[-0.214115,44.900367]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006951,2025-12-11,2025-12-17T09:36:45.669000+00:00
1803,97305,bornes@lidl.fr,LIDL,"[-0.214139,44.9000322]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006950,2025-12-11,2025-12-17T09:36:45.669000+00:00
1802,97304,bornes@lidl.fr,LIDL,"[-0.214139,44.9000322]",Avenue du Général de Gaulle,FRLDLPLFR2293EVCP,LIBOURNE,Parking privé à usage public,4,Accès libre,24/7,false,FRLDLE00006949,2025-12-11,2025-12-17T09:36:45.669000+00:00

### Defauts operateur IZIVIA
Les défauts au nombre de 330 sont liés à une incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Izivia en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance, ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur un parking [-0.530598, 47.398424], on trouve 17 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué entre 1 et 3.

In [34]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'sav@izivia.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
40,2748,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10311,2026-02-17,2026-02-17T07:01:22.360000+00:00
41,2749,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10312,2026-02-17,2026-02-17T07:01:22.360000+00:00
42,2751,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10321,2026-02-17,2026-02-17T07:01:22.360000+00:00
43,2752,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10322,2026-02-17,2026-02-17T07:01:22.360000+00:00
618,27781,sav@izivia.com,Izivia Express,"[2.495323, 48.77495]",19 Rte du Fief Cordelier 94380 Bonneuil-sur-Marne,FRE04POAZS227,BON - Station multi-énergie Bonneuil-Sur-Marne,Voirie,5,Accès libre,24/7,False,FRE04EOAZS22711,2026-02-17,2026-02-17T07:01:32.984000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5551,189701,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial d'Aéroville 95700 Roissy-en-...,FRURWPUNIB16,Aeroville - Terminal Cook,Voirie,6,Accès libre,24/7,False,FRURWEUNIB1622,2026-02-17,2026-02-17T07:01:46.588000+00:00
5552,189702,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial d'Aéroville 95700 Roissy-en-...,FRURWPUNIB16,Aeroville - Terminal Cook,Voirie,6,Accès libre,24/7,False,FRURWEUNIB1631,2026-02-17,2026-02-17T07:01:46.588000+00:00
5553,189703,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial d'Aéroville 95700 Roissy-en-...,FRURWPUNIB16,Aeroville - Terminal Cook,Voirie,6,Accès libre,24/7,False,FRURWEUNIB1632,2026-02-17,2026-02-17T07:01:46.588000+00:00
5554,189704,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial Aéroville 95700 Roissy-en-Fr...,FRURWPUNIB17,Aeroville - Tokyo,Voirie,2,Accès libre,24/7,False,FRURWEUNIB1711,2026-02-17,2026-02-17T07:01:46.588000+00:00
5555,189705,sav@izivia.com,UNIBAIL,"[2.523685, 48.9908]",Centre commercial Aéroville 95700 Roissy-en-Fr...,FRURWPUNIB17,Aeroville - Tokyo,Voirie,2,Accès libre,24/7,False,FRURWEUNIB1712,2026-02-17,2026-02-17T07:01:46.588000+00:00

In [87]:
itinerance_4.loc[(~itinerance_4['adresse_station - coordonneesXY']) & (itinerance_4['contact_operateur'] == 'sav@izivia.com') , relations].sort_values(by=["coordonneesXY"])[0:50]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3015,112315,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37231,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37231,2025-09-30,2025-09-30T08:35:00.909000+00:00
3010,112310,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372101,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372101,2025-09-30,2025-09-30T08:35:00.909000+00:00
3011,112311,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37211,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37211,2025-09-30,2025-09-30T08:35:00.909000+00:00
3017,112317,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37251,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37251,2025-09-30,2025-09-30T08:35:00.909000+00:00
3018,112318,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37261,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37261,2025-09-30,2025-09-30T08:35:00.909000+00:00
3014,112314,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37221,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37221,2025-09-30,2025-09-30T08:35:00.909000+00:00
3020,112320,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37281,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37281,2025-09-30,2025-09-30T08:35:00.909000+00:00
3021,112321,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37291,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37291,2025-09-30,2025-09-30T08:35:00.909000+00:00
3012,112312,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372111,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372111,2025-09-30,2025-09-30T08:35:00.909000+00:00
3013,112313,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372121,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372121,2025-09-30,2025-09-30T08:35:00.909000+00:00
3019,112319,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37271,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37271,2025-09-30,2025-09-30T08:35:00.909000+00:00
629,27871,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24723,2026-02-17,2026-02-17T07:01:32.984000+00:00
625,27864,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24711,2026-02-17,2026-02-17T07:01:32.984000+00:00
626,27866,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24712,2026-02-17,2026-02-17T07:01:32.984000+00:00
627,27868,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24721,2026-02-17,2026-02-17T07:01:32.984000+00:00
628,27869,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24722,2026-02-17,2026-02-17T07:01:32.984000+00:00
3016,112316,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37241,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37241,2025-09-30,2025-09-30T08:35:00.909000+00:00
2961,111165,sav@izivia.com,EDF-EV100,"[0.16392, 47.22969]",80 CENTRALE NUCLEAIRE 61150 AVOINE,FROTHPIZIG73131,CNPE CHINON - PARKING NORD 1,Voirie,1,Accès libre,24/7,false,FROTHEIZIG73131,2025-09-30,2025-09-30T08:35:00.909000+00:00
2958,111109,sav@izivia.com,EDF-EV100,"[0.16392, 47.22969]",80 CENTRALE NUCLEAIRECNPE DE CHINON 37420 AVOINE,FROTHPIZIG72211,CNPE CHINON - PARKING SUD 5,Voirie,1,Accès libre,24/7,false,FROTHEIZIG72211,2025-09-30,2025-09-30T08:35:00.909000+00:00
2960,111163,sav@izivia.com,EDF-EV100,"[0.16392, 47.22969]",80 CENTRALE NUCLEAIRE 61150 AVOINE,FROTHPIZIG73111,CNPE CHINON - PARKING NORD 1,Voirie,1,Accès libre,24/7,false,FROTHEIZIG73111,2025-09-30,2025-09-30T08:35:00.909000+00:00
2959,111110,sav@izivia.com,EDF-EV100,"[0.16392, 47.22969]",80 CENTRALE NUCLEAIRECNPE DE CHINON 37420 AVOINE,FROTHPIZIG72221,CNPE CHINON - PARKING SUD 5,Voirie,1,Accès libre,24/7,false,FROTHEIZIG72221,2025-09-30,2025-09-30T08:35:00.909000+00:00
2891,110762,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG46711,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG46711,2025-09-30,2025-09-30T08:35:00.909000+00:00
2892,110763,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467111,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467111,2025-09-30,2025-09-30T08:35:00.909000+00:00
2893,110764,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467121,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467121,2025-09-30,2025-09-30T08:35:00.909000+00:00
2894,110765,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467131,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467131,2025-09-30,2025-09-30T08:35:00.909000+00:00
2895,110766,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467141,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467141,2025-09-30,2025-09-30T08:35:00.909000+00:00
2896,110767,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467151,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467151,2025-09-30,2025-09-30T08:35:00.909000+00:00
2890,110761,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467101,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467101,2025-09-30,2025-09-30T08:35:00.909000+00:00
2870,110741,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466141,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466141,2025-09-30,2025-09-30T08:35:00.909000+00:00
2899,110770,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467181,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467181,2025-09-30,2025-09-30T08:35:00.909000+00:00
2900,110771,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467191,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467191,2025-09-30,2025-09-30T08:35:00.909000+00:00
2901,110772,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467201,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467201,2025-09-30,2025-09-30T08:35:00.909000+00:00
2902,110773,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG46721,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG46721,2025-09-30,2025-09-30T08:35:00.909000+00:00
2903,110774,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467211,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467211,2025-09-30,2025-09-30T08:35:00.909000+00:00
2904,110775,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467221,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467221,2025-09-30,2025-09-30T08:35:00.909000+00:00
2905,110776,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467231,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467231,2025-09-30,2025-09-30T08:35:00.909000+00:00
2906,110777,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467241,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467241,2025-09-30,2025-09-30T08:35:00.909000+00:00
2907,110778,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467251,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467251,2025-09-30,2025-09-30T08:35:00.909000+00:00
2898,110769,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467171,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467171,2025-09-30,2025-09-30T08:35:00.909000+00:00
2897,110768,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT-LAURENT DES EA...,FROTHPIZIG467161,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 4,Voirie,1,Accès libre,24/7,false,FROTHEIZIG467161,2025-09-30,2025-09-30T08:35:00.909000+00:00
2887,110758,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG46681,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG46681,2025-09-30,2025-09-30T08:35:00.909000+00:00
2869,110740,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466131,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466131,2025-09-30,2025-09-30T08:35:00.909000+00:00
2871,110742,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466151,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466151,2025-09-30,2025-09-30T08:35:00.909000+00:00
2872,110743,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466161,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466161,2025-09-30,2025-09-30T08:35:00.909000+00:00
2873,110744,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466171,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466171,2025-09-30,2025-09-30T08:35:00.909000+00:00
2874,110745,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466181,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466181,2025-09-30,2025-09-30T08:35:00.909000+00:00
2875,110746,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466191,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466191,2025-09-30,2025-09-30T08:35:00.909000+00:00
2876,110747,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466201,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466201,2025-09-30,2025-09-30T08:35:00.909000+00:00
2877,110748,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG46621,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG46621,2025-09-30,2025-09-30T08:35:00.909000+00:00
2878,110749,sav@izivia.com,EDF-EV100,"[1.5778, 47.72001]",LA CENTRALE NUCLEAIRECNPE SAINT LAURENT DES EA...,FROTHPIZIG466211,CNPE SAINT-LAURENT DES EAUX - E - RANGEE 3,Voirie,1,Accès libre,24/7,false,FROTHEIZIG466211,2025-09-30,2025-09-30T08:35:00.909000+00:00

In [35]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-0.530598, 47.398424]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
625,27864,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24711,2026-02-17,2026-02-17T07:01:32.984000+00:00
626,27866,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24712,2026-02-17,2026-02-17T07:01:32.984000+00:00
627,27868,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24721,2026-02-17,2026-02-17T07:01:32.984000+00:00
628,27869,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24722,2026-02-17,2026-02-17T07:01:32.984000+00:00
629,27871,sav@izivia.com,Izivia Express,"[-0.530598, 47.398424]",26 Rue Valentin des Ormeaux 49610 Mûrs-Erigné,FRE04POAZS247,HYPER U - MURS-ERIGNÉ,Voirie,5,Accès libre,24/7,False,FRE04EOAZS24723,2026-02-17,2026-02-17T07:01:32.984000+00:00
3010,112310,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372101,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372101,2025-09-30,2025-09-30T08:35:00.909000+00:00
3011,112311,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37211,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37211,2025-09-30,2025-09-30T08:35:00.909000+00:00
3012,112312,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372111,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372111,2025-09-30,2025-09-30T08:35:00.909000+00:00
3013,112313,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR372121,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR372121,2025-09-30,2025-09-30T08:35:00.909000+00:00
3014,112314,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37221,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37221,2025-09-30,2025-09-30T08:35:00.909000+00:00
3015,112315,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37231,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37231,2025-09-30,2025-09-30T08:35:00.909000+00:00
3016,112316,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37241,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37241,2025-09-30,2025-09-30T08:35:00.909000+00:00
3017,112317,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37251,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37251,2025-09-30,2025-09-30T08:35:00.909000+00:00
3018,112318,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37261,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37261,2025-09-30,2025-09-30T08:35:00.909000+00:00
3019,112319,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37271,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37271,2025-09-30,2025-09-30T08:35:00.909000+00:00
3020,112320,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37281,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37281,2025-09-30,2025-09-30T08:35:00.909000+00:00
3021,112321,sav@izivia.com,SYSTEME U,"[-0.530598, 47.398424]",RUE VALENTIN DES ORMEAUX 49610 MURS-ERIGNE,FROTHPOTHR37291,HYPER U - MURS-ERIGNE,Voirie,1,Accès libre,24/7,false,FROTHEOTHR37291,2025-09-30,2025-09-30T08:35:00.909000+00:00

### Defauts operateur ENIplenitude
Les défauts (200 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Ionity en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance ainsi qu'un ancien pdc de regroupement par station avec un nom d'enseigne différent (IONITY GMBH), ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur l'aire de Mornas [4.732409, 44.194832], on trouve 26 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué de 23 pour chaque station.

In [40]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'support@service.emob.eniplenitude.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3397,137270,support@service.emob.eniplenitude.com,Eni Station - 22 AVENUE DU CLOS MOUZON,"[4.90481800,46.57255600]","22 AVENUE DU CLOS MOUZON, 71700 Tournus",FRPLNEH000531,Eni Station - 22 AVENUE DU CLOS MOUZON,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0005311,2026-02-17,2026-02-17T20:00:19.819000+00:00
3398,137272,support@service.emob.eniplenitude.com,Eni Station - 22 AVENUE DU CLOS MOUZON,"[4.90481800,46.57255600]","22 AVENUE DU CLOS MOUZON, 71700 Tournus",FRPLNEH000531,Eni Station - 22 AVENUE DU CLOS MOUZON,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0005312,2026-02-17,2026-02-17T20:00:19.819000+00:00
3399,137274,support@service.emob.eniplenitude.com,Eni Station - 22 AVENUE DU CLOS MOUZON,"[4.90481800,46.57255600]","22 AVENUE DU CLOS MOUZON, 71700 Tournus",FRPLNEH000531,Eni Station - 22 AVENUE DU CLOS MOUZON,Voirie,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0005313,2026-02-17,2026-02-17T20:00:19.819000+00:00
3400,137276,support@service.emob.eniplenitude.com,Eni Station - BOULEVARD PONTIFFROY,"[6.17826100,49.12618100]","BOULEVARD PONTIFFROY, 57463 Metz",FRPLNEH000535,Eni Station - BOULEVARD PONTIFFROY,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0005351,2026-02-17,2026-02-17T20:00:19.819000+00:00
3401,137278,support@service.emob.eniplenitude.com,Eni Station - BOULEVARD PONTIFFROY,"[6.17826100,49.12618100]","BOULEVARD PONTIFFROY, 57463 Metz",FRPLNEH000535,Eni Station - BOULEVARD PONTIFFROY,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0005352,2026-02-17,2026-02-17T20:00:19.819000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3600,138199,support@service.emob.eniplenitude.com,Eni Station - 19 BIS AVE BERTHELOT,"[4.55132000,45.49025100]","19 BIS AVE BERTHELOT, 42152 L'Horme",FRPLNEH003099,Eni Station - 19 BIS AVE BERTHELOT,Station dédiée à la recharge rapide,3,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0030993,2026-02-17,2026-02-17T20:00:19.819000+00:00
3601,138231,support@service.emob.eniplenitude.com,Aire de Haut Forez Sud,"[3.81042700,45.85418600]","Aire de Haut Forez Sud, 42440 Les Salles",FRPLNEH003232,Aire de Haut Forez Sud,Station dédiée à la recharge rapide,35,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0032321,2026-02-17,2026-02-17T20:00:19.819000+00:00
3602,138233,support@service.emob.eniplenitude.com,Aire de Haut Forez Sud,"[3.81042700,45.85418600]","Aire de Haut Forez Sud, 42440 Les Salles",FRPLNEH003232,Aire de Haut Forez Sud,Station dédiée à la recharge rapide,35,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0032322,2026-02-17,2026-02-17T20:00:19.819000+00:00
3603,138235,support@service.emob.eniplenitude.com,Aire de Haut Forez Sud,"[3.81042700,45.85418600]","Aire de Haut Forez Sud, 42440 Les Salles",FRPLNEH003232,Aire de Haut Forez Sud,Station dédiée à la recharge rapide,35,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0032323,2026-02-17,2026-02-17T20:00:19.819000+00:00
3604,138237,support@service.emob.eniplenitude.com,Aire de Haut Forez Sud,"[3.81042700,45.85418600]","Aire de Haut Forez Sud, 42440 Les Salles",FRPLNEH003232,Aire de Haut Forez Sud,Voirie,35,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0032324,2026-02-17,2026-02-17T20:00:19.819000+00:00

In [41]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRPLNEH002131', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
3590,137883,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021311,2026-02-17,2026-02-17T20:00:19.819000+00:00
3591,137885,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021312,2026-02-17,2026-02-17T20:00:19.819000+00:00
3592,137887,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Station dédiée à la recharge rapide,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021313,2026-02-17,2026-02-17T20:00:19.819000+00:00
3593,137889,support@service.emob.eniplenitude.com,Haut Forez Nord - Autoroute A89,"[3.81054325,45.85570464]","Haut Forez Nord - Autoroute A89, 42440 Les Salles",FRPLNEH002131,Haut Forez Nord - Autoroute A89,Voirie,32,Accès réservé,"Mo 06:00-18:00,Tu 06:00-18:00,We 06:00-18:00,T...",false,FRPLNEH0021314,2026-02-17,2026-02-17T20:00:19.819000+00:00

### Defauts operateur MOBILIZE
Les défauts (350 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

In [42]:
itinerance_4.loc[itinerance_4['contact_operateur'] == 'fastcharge.exploitation@mobilize.com', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
2288,106129,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE1,2026-02-17,2026-02-17T20:00:19.819000+00:00
2289,106131,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE2,2026-02-17,2026-02-17T20:00:19.819000+00:00
2290,106133,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE3,2026-02-17,2026-02-17T20:00:19.819000+00:00
2291,106135,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE4,2026-02-17,2026-02-17T20:00:19.819000+00:00
2292,106137,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE5,2026-02-17,2026-02-17T20:00:19.819000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2636,106896,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Bd de Laval,"[-1.17667000,48.12059700]","Bd de Laval, 35500 Vitré",FRMFCEVITRE,Mobilize Fast Charge Bd de Laval,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRMFCEVITRE1,2026-02-17,2026-02-17T20:00:19.819000+00:00
2637,106898,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Bd de Laval,"[-1.17667000,48.12059700]","Bd de Laval, 35500 Vitré",FRMFCEVITRE,Mobilize Fast Charge Bd de Laval,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRMFCEVITRE2,2026-02-17,2026-02-17T20:00:19.819000+00:00
2638,106900,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Bd de Laval,"[-1.17667000,48.12059700]","Bd de Laval, 35500 Vitré",FRMFCEVITRE,Mobilize Fast Charge Bd de Laval,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRMFCEVITRE3,2026-02-17,2026-02-17T20:00:19.819000+00:00
2639,106902,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Bd de Laval,"[-1.17667000,48.12059700]","Bd de Laval, 35500 Vitré",FRMFCEVITRE,Mobilize Fast Charge Bd de Laval,Station dédiée à la recharge rapide,5,Accès réservé,24/7,false,FRMFCEVITRE4,2026-02-17,2026-02-17T20:00:19.819000+00:00
2640,106904,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Bd de Laval,"[-1.17667000,48.12059700]","Bd de Laval, 35500 Vitré",FRMFCEVITRE,Mobilize Fast Charge Bd de Laval,Voirie,5,Accès réservé,24/7,false,FRMFCEVITRE5,2026-02-17,2026-02-17T20:00:19.819000+00:00

In [43]:
itinerance_4.loc[itinerance_4.id_station_itinerance == 'FRMFCEALBERTVILLE', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
2288,106129,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE1,2026-02-17,2026-02-17T20:00:19.819000+00:00
2289,106131,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE2,2026-02-17,2026-02-17T20:00:19.819000+00:00
2290,106133,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE3,2026-02-17,2026-02-17T20:00:19.819000+00:00
2291,106135,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE4,2026-02-17,2026-02-17T20:00:19.819000+00:00
2292,106137,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE5,2026-02-17,2026-02-17T20:00:19.819000+00:00
2293,106139,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Station dédiée à la recharge rapide,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE6,2026-02-17,2026-02-17T20:00:19.819000+00:00
2294,106141,fastcharge.exploitation@mobilize.com,Mobilize Fast Charge Rue Raymond Bertrand,"[6.38337143,45.66105429]","Rue Raymond Bertrand, 73200 Albertville",FRMFCEALBERTVILLE,Mobilize Fast Charge Rue Raymond Bertrand,Voirie,7,Accès réservé,24/7,false,FRMFCEALBERTVILLE7,2026-02-17,2026-02-17T20:00:19.819000+00:00

### Cohérence implantation_station - id_station
- 107 pdc sont liés à une erreur de choix d'implantation (couplé à d'autres erreurs)

In [47]:
itinerance_4.loc[~itinerance_4['implantation_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
85,4452,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","P4b Parking, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Voirie,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE914790151,2026-02-12,2026-02-12T13:33:57.539000+00:00
86,4453,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","P4b Parking, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Parking public,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901510,2026-02-12,2026-02-12T13:33:57.539000+00:00
87,4454,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","P4b Parking, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Parking public,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901511,2026-02-12,2026-02-12T13:33:57.539000+00:00
88,4455,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","P4b Parking, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Parking public,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE9147901512,2026-02-12,2026-02-12T13:33:57.539000+00:00
89,4456,support@alizecharge.fr,ADP Groupe,"[2.366988,48.729465]","P4b Parking, 94390 Paray-Vieille-Poste",FRADPE91479015,ORY EP - Parking P4b Rouge - Niveau Terrasse,Voirie,12,Accès libre,Mo-Su 00:00-23:57,False,FRADPE914790152,2026-02-12,2026-02-12T13:33:57.539000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4765,171187,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE94,Shell Fenioux Est,Voirie,8,Accès réservé,24/7,false,FRSHEE944,2026-02-17,2026-02-17T20:00:19.819000+00:00
4766,171189,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Station dédiée à la recharge rapide,8,Accès réservé,24/7,false,FRSHEE951,2026-02-17,2026-02-17T20:00:19.819000+00:00
4767,171191,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Station dédiée à la recharge rapide,8,Accès réservé,24/7,false,FRSHEE952,2026-02-17,2026-02-17T20:00:19.819000+00:00
4768,171193,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Station dédiée à la recharge rapide,8,Accès réservé,24/7,false,FRSHEE953,2026-02-17,2026-02-17T20:00:19.819000+00:00
4769,171195,customerservice@shellrecharge.com,Shell Fenioux Est,"[-0.60280679,45.89253519]","A10 Aire de Fenioux Est, 17350 Fenioux",FRSHEE95,Shell Fenioux Est,Voirie,8,Accès réservé,24/7,false,FRSHEE954,2026-02-17,2026-02-17T20:00:19.819000+00:00

### Cohérence nom_station - id_station
- 210 pdc sont associés à une station avec un nom non cohérent

In [48]:
itinerance_4.loc[~itinerance_4['nom_station - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
18,452,contact@nexteneo.com,Ville d'Annecy,"[6.12983, 45.902285]",[Rue Guillaume Fichet][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Parking de Bonlieu,Parking public,11,Accès réservé,24/7,FALSE,FR0NXEVSE8BD3L,2024-12-23,2025-12-29T17:34:24.947000+00:00
19,468,contact@nexteneo.com,Ville d'Annecy,"[6.12983, 45.902285]",[Rue Guillaume Fichet][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Parking de Bonlieu,Parking public,11,Accès réservé,24/7,FALSE,FR0NXEVSE99XBN,2024-12-23,2025-12-29T17:34:24.947000+00:00
20,505,contact@nexteneo.com,Ville d'Annecy,"[6.128716, 45.9]",[1 Esplanade de l'hôtel de ville][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Hôtel de ville,Parking public,6,Accès réservé,24/7,FALSE,FR0NXEVSEBYTEK,2024-12-23,2025-12-29T17:34:24.947000+00:00
21,516,contact@nexteneo.com,Ville d'Annecy,"[6.128716, 45.9]",[1 Esplanade de l'hôtel de ville][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Hôtel de ville,Parking public,6,Accès réservé,24/7,FALSE,FR0NXEVSECTDM6,2024-12-23,2025-12-29T17:34:24.947000+00:00
22,518,contact@nexteneo.com,Ville d'Annecy,"[6.12983, 45.902285]",[Rue Guillaume Fichet][74000][Annecy],FR0NXPOOLHFX48,Ville d'Annecy - Parking de Bonlieu,Parking public,11,Accès réservé,24/7,FALSE,FR0NXEVSED4T64,2024-12-23,2025-12-29T17:34:24.947000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,206327,support@alizecharge.fr,Seymaborne,"[1.877203,48.5760925]","Rue André Thome, 78120 SONCHAMP",FRY03E78601001,SONCHAMP - MAIRIE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786010014,2026-02-12,2026-02-12T13:33:57.539000+00:00
5677,206328,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150011,2026-02-12,2026-02-12T13:33:57.539000+00:00
5678,206329,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150012,2026-02-12,2026-02-12T13:33:57.539000+00:00
5679,206330,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150013,2026-02-12,2026-02-12T13:33:57.539000+00:00
5680,206331,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150014,2026-02-12,2026-02-12T13:33:57.539000+00:00

### Coherence adresse - coordonnees
- 2337 pdc ont une adresse non cohérente avec les coordonnées géographiques

In [49]:
itinerance_4.loc[~itinerance_4['adresse_station - coordonneesXY'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
40,2748,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10311,2026-02-17,2026-02-17T07:01:22.360000+00:00
41,2749,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la-Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 1,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10312,2026-02-17,2026-02-17T07:01:22.360000+00:00
42,2751,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10321,2026-02-17,2026-02-17T07:01:22.360000+00:00
43,2752,sav@izivia.com,Wiiiz,"[6.948066, 43.567243]",Avenue Jean Mermoz 06210 Mandelieu-la Napoule,FRA16PWIIZ103,Mandelieu-la Napoule - Parking Mermoz 2,Voirie,2,Accès libre,24/7,False,FRA16EWIIZ10322,2026-02-17,2026-02-17T07:01:22.360000+00:00
97,4472,support@alizecharge.fr,ADP Groupe,"[2.362554,48.728787]","P3 Parking, 94390 Paray-Vieille-Poste",FRADPE91479018,ORY EP - Parking P3 SILO - Niveau 2,Parking public,10,Accès libre,Mo-Su 00:00-23:57,False,FRADPE914790181,2026-02-12,2026-02-12T13:33:57.539000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,208417,advenir@zeborne.com,GARAGE NELLO CHELLI - DIJON,"[5.065799, 47.354481]",23 RUE DES ARDENNES 21000 Dijon,FRZTLE22AC55087,Toyota - Dijon - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 07:45-12:00,Mo-Fr 13:45-19:00,Sat 09:00-...",false,FRZTLE22AC55087,2021-02-19,2024-12-06T06:45:00.153000+00:00
5871,208428,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.419000+00:00
5872,208429,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.419000+00:00
5873,208430,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.419000+00:00
5874,208431,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.419000+00:00

In [50]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[5.2592028, 46.1746523]', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5871,208428,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.419000+00:00
5872,208429,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.419000+00:00
5873,208430,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.419000+00:00
5874,208431,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.419000+00:00

In [51]:
itinerance_4.loc[itinerance_4.adresse_station == 'RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5871,208428,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57332,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57332,2021-04-08,2024-12-06T06:44:59.419000+00:00
5873,208430,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57334,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57334,2021-04-08,2024-12-06T06:44:59.419000+00:00

In [52]:
itinerance_4.loc[itinerance_4.adresse_station == ' RN 75 ZI DE NOIREFONTAINE 01250 Montagnat', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
5872,208429,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57333,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57333,2021-04-08,2024-12-06T06:44:59.419000+00:00
5874,208431,advenir@zeborne.com,TOYOTA MONTAGNAT - DJB BOURG,"[5.2592028, 46.1746523]",RN 75 ZI DE NOIREFONTAINE 01250 Montagnat,FRZTLE22AC57335,Toyota - Montagnat - 22kW AC,Parking public,1,Accès libre,"Mo-Fr 08:00–12:00,Mo-Fr 14:00–19:00,Sat 09:00-...",false,FRZTLE22AC57335,2021-04-08,2024-12-06T06:44:59.419000+00:00

### Cohérence station - coordonnées
- 218 pdc sont associés à des stations avec plusieurs coordonnées (majorité AlizeCharge)

In [53]:
itinerance_4.loc[~itinerance_4['coordonneesXY - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
0,352,acelec@acelec-france.com,Camaïeu France,"[3.207306,50.684918]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E0HKH51125,2022-07-21,2024-12-06T06:46:31.269000+00:00
1,353,acelec@acelec-france.com,Camaïeu France,"[3.207246,50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E8OV45243,2022-07-21,2024-12-06T06:46:31.269000+00:00
2,354,acelec@acelec-france.com,Camaïeu France,"[3.207124,50.684984]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EBEQA5957,2022-07-21,2024-12-06T06:46:31.269000+00:00
3,355,acelec@acelec-france.com,Camaïeu France,"[3.20737,50.684898]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ECC1C5530,2022-07-21,2024-12-06T06:46:31.269000+00:00
4,356,acelec@acelec-france.com,HOTEL KYRIAD PARIS BEZONS,"[2.212336,48.931356]",80 Av. Gabriel Péri 95870 BEZONS,FR073PKYRIADBEZONS,HOTEL KYRIAD PARIS BEZONS,Parking privé à usage public,1,Accès libre,Mo-Fr 08:00-19:01,false,FR073EJJYD51230,2022-07-21,2024-12-06T06:46:31.269000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,206327,support@alizecharge.fr,Seymaborne,"[1.877203,48.5760925]","Rue André Thome, 78120 SONCHAMP",FRY03E78601001,SONCHAMP - MAIRIE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786010014,2026-02-12,2026-02-12T13:33:57.539000+00:00
5677,206328,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150011,2026-02-12,2026-02-12T13:33:57.539000+00:00
5678,206329,support@alizecharge.fr,Seymaborne,"[1.934185,48.841843]","Parc De Folleville, 78850 THIVERVAL-GRIGNON",FRY03E78615001,THIVERVAL-GRIGNON - PARC DE FOLLEVILLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150012,2026-02-12,2026-02-12T13:33:57.539000+00:00
5679,206330,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150013,2026-02-12,2026-02-12T13:33:57.539000+00:00
5680,206331,support@alizecharge.fr,Seymaborne,"[1.9417047,48.8436144]","Résidence pièces des maisons, 78850 THIVERVAL...",FRY03E78615001,THIVERVAL-GRIGNON - ÉCOLE,Voirie,2,Accès libre,Mo-Su 00:00-23:57,False,FRY03E786150014,2026-02-12,2026-02-12T13:33:57.539000+00:00

In [54]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRTLSE31555040', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [55]:
itinerance_5.loc[itinerance_5.id_station_itinerance	 == 'FRFR1PEHNKRRPQNR', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : une station avec plusieurs coordonnées -> incompréhension distinction station / pdc

In [56]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR073PCAMAIEUFR', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
0,352,acelec@acelec-france.com,Camaïeu France,"[3.207306,50.684918]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E0HKH51125,2022-07-21,2024-12-06T06:46:31.269000+00:00
1,353,acelec@acelec-france.com,Camaïeu France,"[3.207246,50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073E8OV45243,2022-07-21,2024-12-06T06:46:31.269000+00:00
2,354,acelec@acelec-france.com,Camaïeu France,"[3.207124,50.684984]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EBEQA5957,2022-07-21,2024-12-06T06:46:31.269000+00:00
3,355,acelec@acelec-france.com,Camaïeu France,"[3.20737,50.684898]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ECC1C5530,2022-07-21,2024-12-06T06:46:31.269000+00:00
5,357,acelec@acelec-france.com,Camaïeu France,"[3.207306,50.684918]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EK0BJ522,2022-07-21,2024-12-06T06:46:31.269000+00:00
6,358,acelec@acelec-france.com,Camaïeu France,"[3.207047,50.685013]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EMZLV5283,2022-07-21,2024-12-06T06:46:31.269000+00:00
7,359,acelec@acelec-france.com,Camaïeu France,"[3.20737,50.684898]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EO0AV51091,2022-07-21,2024-12-06T06:46:31.269000+00:00
8,360,acelec@acelec-france.com,Camaïeu France,"[3.207187,50.684964]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP7QU5233,2022-07-21,2024-12-06T06:46:31.269000+00:00
9,361,acelec@acelec-france.com,Camaïeu France,"[3.206962,50.685049]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EP9LD51287,2022-07-21,2024-12-06T06:46:31.269000+00:00
10,362,acelec@acelec-france.com,Camaïeu France,"[3.207433,50.684876]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EQ1GI51176,2022-07-21,2024-12-06T06:46:31.269000+00:00
11,363,acelec@acelec-france.com,Camaïeu France,"[3.207433,50.684876]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EREUO5946,2022-07-21,2024-12-06T06:46:31.269000+00:00
13,367,acelec@acelec-france.com,Camaïeu France,"[3.207187,50.684964]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073ETCIX5105,2022-07-21,2024-12-06T06:46:31.269000+00:00
14,368,acelec@acelec-france.com,Camaïeu France,"[3.207124,50.684984]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EU6RQ5270,2022-07-21,2024-12-06T06:46:31.269000+00:00
15,369,acelec@acelec-france.com,Camaïeu France,"[3.207047,50.685013]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EUHNJ5886,2022-07-21,2024-12-06T06:46:31.269000+00:00
16,370,acelec@acelec-france.com,Camaïeu France,"[3.206962,50.685049]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EXINB5826,2022-07-21,2024-12-06T06:46:31.269000+00:00
17,371,acelec@acelec-france.com,Camaïeu France,"[3.207246,50.68494]",211 Av. Jules Brame 59100 Roubaix,FR073PCAMAIEUFR,CAMAÏEU FRANCE,Parking privé à usage public,1,Accès libre,Mo-Su 08:00-08:00,false,FR073EYLF65474,2022-07-21,2024-12-06T06:46:31.269000+00:00

- exemple : une station avec plusieurs coordonnées -> regroupement de stations ?

In [57]:
itinerance_5.loc[itinerance_5.id_station_itinerance == 'FR55CPBP514', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : plusieurs stations d'opérateurs différents avec les mêmes coordonnées -> suppression non effectuée lors d'un changement d'opérateur ?

In [58]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[0.08745032, 48.40887156]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

In [59]:
itinerance_4.loc[itinerance_4.coordonneesXY == '[-4.374469, 48.471878]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

- exemple : quatre stations avec une localisation identique mais deux adresses différentes + id identique entre station et pdc -> erreur d'adresse et erreur d'id_station ?

In [60]:
itinerance_5.loc[itinerance_5.coordonneesXY	 == '[-0.366184, 43.332508]', relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Incoherence nbre_pdc
- 583 pdc ont un champ 'nbre_pdc' mal documenté

In [61]:
itinerance_4.loc[~itinerance_4['nbre_pdc - id_station_itinerance'], relations][200:215]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
542,24199,support@dream-energy.fr,Ibis Budget Bar-Le-Duc,"[5.189233, 48.759043]",5 Rue des Valottes - 55000 Bar-le-Duc,FRDREP89959572,BAR-LE-DUC,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534931,2025-04-23,2026-01-08T20:43:20.260000+00:00
543,24200,support@dream-energy.fr,Ibis Budget Bar-Le-Duc,"[5.189233, 48.759043]",5 Rue des Valottes - 55000 Bar-le-Duc,FRDREP89959572,BAR-LE-DUC,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534932,2025-04-23,2026-01-08T20:43:20.260000+00:00
544,24201,support@dream-energy.fr,Ibis Budget Bar-Le-Duc,"[5.189233, 48.759043]",5 Rue des Valottes - 55000 Bar-le-Duc,FRDREP89959572,BAR-LE-DUC,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534933,2025-04-23,2026-01-08T20:43:20.260000+00:00
545,24202,support@dream-energy.fr,Ibis Budget Bar-Le-Duc,"[5.189233, 48.759043]",5 Rue des Valottes - 55000 Bar-le-Duc,FRDREP89959572,BAR-LE-DUC,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534941,2025-04-23,2026-01-08T20:43:20.260000+00:00
546,24203,support@dream-energy.fr,Ibis Budget Bar-Le-Duc,"[5.189233, 48.759043]",5 Rue des Valottes - 55000 Bar-le-Duc,FRDREP89959572,BAR-LE-DUC,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534942,2025-04-23,2026-01-08T20:43:20.260000+00:00
547,24204,support@dream-energy.fr,ARTEPARC MEYLAN,"[5.790741, 45.208687]",22 Chemin Du Vieux Chêne - 38240 Meylan,FRDREP89915112,MEYLAN,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534951,2025-04-23,2026-01-08T20:43:20.260000+00:00
548,24205,support@dream-energy.fr,ARTEPARC MEYLAN,"[5.790741, 45.208687]",22 Chemin Du Vieux Chêne - 38240 Meylan,FRDREP89915112,MEYLAN,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534952,2025-04-23,2026-01-08T20:43:20.260000+00:00
549,24206,support@dream-energy.fr,ARTEPARC MEYLAN,"[5.53111, 43.491344]",22 Chemin Du Vieux Chêne - 38240 Meylan,FRDREP89915112,MEYLAN,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534961,2025-04-23,2026-01-08T20:43:20.260000+00:00
550,24207,support@dream-energy.fr,ARTEPARC MEYLAN,"[5.53111, 43.491344]",22 Chemin Du Vieux Chêne - 38240 Meylan,FRDREP89915112,MEYLAN,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534962,2025-04-23,2026-01-08T20:43:20.260000+00:00
551,24208,support@dream-energy.fr,ARTEPARC BIOT,"[7.068587, 43.62316]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534971,2025-04-23,2026-01-08T20:43:20.260000+00:00
552,24209,support@dream-energy.fr,ARTEPARC BIOT,"[7.068587, 43.62316]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534972,2025-04-23,2026-01-08T20:43:20.260000+00:00
553,24210,support@dream-energy.fr,ARTEPARC BIOT,"[7.068587, 43.62316]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,3,Accès libre,24/7,FALSE,FRDREE10001534973,2025-04-23,2026-01-08T20:43:20.260000+00:00
554,24211,support@dream-energy.fr,ARTEPARC BIOT,"[7.068587, 43.62316]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534981,2025-04-23,2026-01-08T20:43:20.260000+00:00
555,24212,support@dream-energy.fr,ARTEPARC BIOT,"[7.068587, 43.62316]",965 route de Roumanille - 06410 Biot,FRDREP89915108,BIOT,Parking public,2,Accès libre,24/7,FALSE,FRDREE10001534982,2025-04-23,2026-01-08T20:43:20.260000+00:00
556,24217,support@dream-energy.fr,Hôtel Kyriad Enzo Hôtel Pont A Mousson,"[6.06469, 48.900576]",210 Allée de l'Espace Saint-Martin - 54700 Pon...,FRDREP90106271,PONT A MOUSSON,Parking public,3,Accès libre,24/7,FALSE,FRDREE12345714741,2025-04-23,2026-01-08T20:43:20.260000+00:00

### coherence station - enseigne
- 5 stations ont plusieurs noms d'enseigne

In [62]:
itinerance_4.loc[~itinerance_4['nom_enseigne - id_station_itinerance'], relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
378,15591,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72)),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830110,2026-01-06,2026-01-13T04:45:01.277000+00:00
379,15593,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830120,2026-01-06,2026-01-13T04:45:01.277000+00:00
380,15595,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830130,2026-01-06,2026-01-13T04:45:01.277000+00:00
381,15597,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830140,2026-01-06,2026-01-13T04:45:01.277000+00:00
382,15599,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830210,2026-01-06,2026-01-13T04:45:01.277000+00:00
383,15601,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830220,2026-01-06,2026-01-13T04:45:01.277000+00:00
384,15603,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830230,2026-01-06,2026-01-13T04:45:01.277000+00:00
385,15605,malek@autorecharge.fr,Etoile Routière LE BAILLEUL (72),"[-0.21463373160781, 47.7794811639259]",270 Rue D’Espagne 72200 Le Bailleul,FRAU1P00960000,Etoile Routière LE BAILLEUL (72),Parking privé à usage public,8,Accès réservé,24/7,false,FRAU1E00830240,2026-01-06,2026-01-13T04:45:01.277000+00:00
887,64659,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.527000+00:00
888,64660,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.527000+00:00
889,64661,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS3,2022-10-04,2024-12-06T06:49:29.527000+00:00
2094,102819,contact@rirodo.fr,LAST MILES SOLUTIONS,"[5.39, 43.27]",20 Rue Negresko,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRLMSE1897228,2023-09-06,2024-12-06T06:47:15.989000+00:00
2211,105182,support@mobilize-ps.fr,BODEMER BAYEUX,"[-0.700226002831211, 49.27084281571326]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,BODEMER Bayeux,Parking privé à usage public,1,Accès libre,24/7,False,FRMBZESMYCQ1,2024-06-03,2026-01-14T10:13:03.213000+00:00
2212,105183,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[-0.700259, 49.270901]","\t16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,\t\tScauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",False,FRMBZESMYQC1,2024-06-03,2026-01-14T10:13:03.213000+00:00
3654,144939,contact@rirodo.fr,MONTA,"[5.39, 43.27]",20 Rue NEGRESKO,FRRIRE2804856,PARKING NEGRESKO,Parking privé à usage public,2,Accès libre,24/7,false,FRRIRE2804856,2023-09-06,2024-12-06T06:47:15.989000+00:00

In [63]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRFR1EAYRU', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
59992,60016,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.213000+00:00
59993,60017,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.213000+00:00
59994,60018,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU3,2022-08-25,2024-12-06T06:49:41.213000+00:00
61036,61060,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.999000+00:00
61037,61061,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.999000+00:00
61038,61062,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS3,2022-12-09,2024-12-06T06:49:25.999000+00:00

In [64]:
itinerance_init.loc[itinerance_init.nom_enseigne == 'RME Loos (FR-FR1)', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
59992,60016,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel jean colonna d'ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU1,2022-12-25,2024-12-06T06:49:41.213000+00:00
59993,60017,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.02,50.61]",rue du colonnel ornano loos,FRFR1EAYRU,"Loos, Parking de la Gare",Parking public,3,Accès libre,24/7,false,FRFR1EAYRU2,2022-08-25,2024-12-06T06:49:41.213000+00:00
61036,61060,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS1,2022-12-09,2024-12-06T06:49:25.999000+00:00
61037,61061,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.014273, 50.615449]",12 Rue Salengro LOOS,FRFR1EAYRU,"Loos, Parking Salengro",Parking public,3,Accès libre,24/7,FALSE,FRFR1EDXS2,2022-12-09,2024-12-06T06:49:25.999000+00:00
64635,64659,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS1,2022-10-04,2024-12-06T06:49:29.527000+00:00
64636,64660,contact@electricite-loos.fr,RME Loos (FR-FR1),"[3.009613, 50.617509]",12 Rue Salengro LOOS,FRFR1EPJXS,"Loos, Parking CIL",Parking public,3,Accès libre,24/7,FALSE,FRFR1EPJXS2,2022-10-04,2024-12-06T06:49:29.527000+00:00

### cohérence station - horaires
- exemple de station avec plusieurs types d'horaire (15)

In [65]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRS23D2302001', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
151859,152035,contact@mobive.fr,Réseau MOBIVE,"[2.297630254367735, 45.98220366857867]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:01,False,FRS23P230200101,2023-03-09,2025-09-11T07:22:20.875000+00:00
151860,152036,contact@mobive.fr,Réseau MOBIVE,"[2.297630254367735, 45.98220366857867]",Place du Treix,FRS23D2302001,BELLEGARDE EN MARCHE - PLACE DE TREIX,Parking public,2,Accès libre,Mo-Su 00:00-00:02,False,FRS23P230200102,2023-03-09,2025-09-11T07:22:20.875000+00:00

### cohérence station - deux-roues
- exemple de station avec plusieurs indications d'accessibilité deux-roues (583)

In [66]:
itinerance_init.loc[itinerance_init.id_station_itinerance == 'FRV75PPX1716', relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
193588,193765,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17161,2025-06-30,2026-02-16T05:18:21.978547+00:00
193589,193766,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,TRUE,FRV75EPX17161,2023-07-06,2025-05-05T13:44:55.751000+00:00
193590,193767,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17162,2025-06-30,2026-02-16T05:18:21.978547+00:00
193591,193768,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,TRUE,FRV75EPX17162,2023-07-06,2025-05-05T13:44:55.751000+00:00
193592,193769,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17163,2025-06-30,2026-02-16T05:18:21.978547+00:00
193593,193770,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17163,2023-07-06,2025-05-05T13:44:55.751000+00:00
193594,193771,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17164,2025-06-30,2026-02-16T05:18:21.978547+00:00
193595,193772,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17164,2023-07-06,2025-05-05T13:44:55.751000+00:00
193596,193773,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17165,2025-06-30,2026-02-16T05:18:21.978547+00:00
193597,193774,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17165,2023-07-06,2025-05-05T13:44:55.751000+00:00
193598,193775,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17166,2025-06-30,2026-02-16T05:18:21.978547+00:00
193599,193776,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17166,2023-07-06,2025-05-05T13:44:55.751000+00:00
193600,193777,supervision-ev.france@totalenergies.com,Belib',"[2.324201, 48.895757]","47 Rue Navier, 75017 Paris",FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,False,FRV75EPX17167,2025-06-30,2026-02-16T05:18:21.978547+00:00
193601,193778,supervision-ev.france@totalenergies.com,Belib',"[2.3242009, 48.8957574]",47 Rue Navier 75017 Paris,FRV75PPX1716,Paris | Rue Navier 47,Voirie,7,Accès libre,24/7,FALSE,FRV75EPX17167,2023-07-06,2025-05-05T13:44:55.751000+00:00

### stations avec pdc > 350 kW

- exemple de station avec une puissance de plus de 350 kW

In [67]:
data['p_nom'] = data['puissance_nominale'].str.replace(",", ".")

In [68]:
data['p_nom'] = data['p_nom'].astype('float')

In [69]:
from copy import copy
data350 = copy(data.loc[data["p_nom"] > 350, :])

In [70]:
data350['index'] = 0

In [71]:
data350.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
97,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP665540345960790087,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER01,2025-07-10,2026-02-01T03:01:17+00:00
98,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP665540345960790087,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER02,2025-07-10,2026-02-01T03:01:17+00:00
99,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP665540345960790087,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER03,2025-07-10,2026-02-01T03:01:17+00:00
100,0,roaming@zunder.com,Zunder,"[4.053402 , 48.269709]","89 Route d'Auxerre, Saint-André-les-Vergers 10...",ESZUNP665540345960790087,Zunder/208656,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1001ER04,2025-07-10,2026-02-01T03:01:17+00:00
101,0,roaming@zunder.com,Zunder,"[0.192606 , 45.820336]","N10, Aussac-Vadalle 16560 France",ESZUNP7136222160008618048,Zunder/329883,Parking privé à usage public,4,Accès libre,24/7,False,ESZUNEFR1621ER01,2025-12-23,2026-02-01T03:01:17+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208691,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER01,2025-12-29,2026-02-16T05:18:21.978547+00:00
208692,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER02,2025-12-29,2026-02-16T05:18:21.978547+00:00
208693,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER03,2025-12-29,2026-02-16T05:18:21.978547+00:00
208694,0,roaming@zunder.com,Zunder,"[6.2772532, 48.36845975]","4 La Voivre, N57.",FRZUNP8813050087046756891,Zunder Charmes,Station dédiée à la recharge rapide,4,Accès libre,24/7,False,FRZUNEFR8801ER04,2025-12-29,2026-02-16T05:18:21.978547+00:00
209551,0,c.blanchot@enerjump.fr,Watt'up,"[1.4680245239967855, 45.15332621876889]",153 rue des levades,Non concerné,Watt'up Brive 19001,Station dédiée à la recharge rapide,4,Accès réservé,24/7,false,Non concerné,2024-09-23,2024-09-24T08:19:16.919000+00:00

In [72]:
data350['contact_operateur'].unique()

array(['roaming@zunder.com', 'contact@enerjump.fr',
       'c.blanchot@enerjump.fr', 'info.allego.france@allego.eu',
       'fabien.lepeytre@allego.eu', 'operations.france@atlante.energy',
       'support.france@atlante.energy', 'malek@autorecharge.fr',
       'bppulsefranceops@bp.com', 'exploitation@yaway-recharge.eu',
       'roaming-dev@road.io', 'help@electra.com', 'help@go-electra.com',
       'support@fastned.nl', 'supervision-ev.france@totalenergies.com',
       'support@iecharge.io', 'info@ionity.eu', 'contact@lidl.fr',
       'bornes@lidl.fr', 'irve@soregies.fr', 'support@mobilize-ps.fr',
       'energy@milence.com', 'noc@milence.com', 'ops@obornes.fr',
       'support@oreve.com', 'support@service.emob.eniplenitude.com',
       'exploitation.irve@picoty.fr', 'contact@sowattsolutions.com',
       'support@alizecharge.fr', 'charging-france@tesla.com',
       'support@voltalia-mobility.com', 'support@greenflux.com',
       'support.vianeo@engie.com', 'kg@lastmilesolutions.com'],
      dtype=object)